### ISSUE TITLE
textures mistake

### ISSUE THREAD

**Issue by JrantKing** [MJRLegends/ExtraPlanets#10]
applediamond.png
change-->
appleDiamond.png

**Comment by MJRLegends** [comment]
Yeah i know about this issue i will fix in the next version

**Comment by MJRLegends** [comment]
see commit #06a2a3c

**Comment by Cronosus** [comment]
another texture
assets\extraplanets\textures\entity\slime
iceslime.png
change-->
iceSlime.png

**Comment by MJRLegends** [comment]
Will be fixed in the next update, please open a new issue next time though :P

**Comment by MJRLegends** [comment]
Update v1.0 Pre-3.6.1 has been released, please give it a short while for curse/curseforge to do its processing and that and then it will be available
