### ISSUE TITLE
Mixed up planets

### ISSUE THREAD

**Issue by Srsam2401** [MJRLegends/ExtraPlanets#100]
### ---Going to a different planet when clicking on another planet on the map---

**Have you checked Closed Issues (if applicable):** [Yes]
### Description of Issue
[I try to go to the moon, but I keep going to Neptune; and when I go the Neptune, I go to Jupiter]

### Steps to Reproduce Issue
1. [Launch any rocket]
2. [Click a planet to go to]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Version of Mod using:** [ExtraPlanets-0.4.0-Beta-Build.jar]

### Additional Information
[None]

**Comment by MJRLegends** [comment]
Please post both Galacticraft config file and ExtraPlanets config file

**Comment by MJRLegends** [comment]
Ok, You need to delete the ExtraPlanets config file and you will be fine then, you might need to make a new world since the dimension id changes :D
