### ISSUE TITLE
Dimension -13 (A.K.A. Mercury) Crash with message including: java.lang.IllegalArgumentException: Could not get provider type for dimension -13, does not exist

### ISSUE THREAD

**Issue by CutlassPlayz** [MJRLegends/ExtraPlanets#101]
### ---Issue Report---
I load up the game and log in, I enter the world and about a minute later the world crashes. I have tried to change the dimension ID multiple times and none are working. I have even tried to completely disable the world but that gave me a java.lang.NullPointerException: Initializing game crash.
**Have you checked Closed Issues (if applicable):** [Yes or No]
### Description of Issue
[Description of the issue]
Dimension -13 A.K.A. on my config mercury, will not work no matter how many times I change the dimension ID. Crash with message including: java.lang.IllegalArgumentException: Could not get provider type for dimension -13, does not exist.
### Steps to Reproduce Issue
1. Have Galacticraft 1.7.10 494 and Extra Planets 1.7.10
2. Load up a world and wait about a minute (I also have many other mods so I don't know if this is an issue on my end)

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
https://pastebin.com/vPBkpCtv
**Version of Mod using:** [VERSION]
1.7.10
### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
When you get errors like this all you need to do is go to my add-ons config and change -13 dimension I'd to something else
