### ISSUE TITLE
New Updated Extra Planets gives issue of galacticraft not being up to the date of #493 or higher but it is and the game still crashes

### ISSUE THREAD

**Issue by CutlassPlayz** [MJRLegends/ExtraPlanets#102]
### ---Issue Report---
New Updated Extra Planets gives issue of galacticraft not being up to the date of #493 or higher but it is and the game still crashes
**Have you checked Closed Issues (if applicable):** [Yes or No]
yes
### Description of Issue
[Description of the issue]
Whenever I load up the game, once Extra Planets is initializing in Phase 3 5/7, an error pops up stating "ExtraPlanets has detected you are using a version below the required minimum version of build #493"
My Galacticraft version for planet,core, and micdoodle core are all 494 and I have no idea what is wrong. (P.S. the issue with the mercury dimension error is still not fixed and I cant find an ID that will work I have even installed an ID fixer and tried ID's from it, it still won't work. Also, I tried to get a higher galacticraft version but couldn't get the website to download it to work, it seems 494 is the highest working version for 1.7.10)
### Steps to Reproduce Issue
1. Have Extra Planets version 1.7.3
2. Have Galacticraft version 494(Core,Planets, and Micdoodle)

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
https://pastebin.com/n0HBvMHN
**Version of Mod using:** [VERSION]
1.7.3 (Newest updated 6 hours ago)
### Additional Information
[Any other information that may be able to help me with the problem]
If you need a list of my mods just ask.

**Comment by MJRLegends** [comment]
Your using 464 not 494 so the message saying "ExtraPlanets: has detected you are using a version below the required minimum version of build #493, You can find it here https://ci.micdoodle8.com/job/Galacticraft-1.7/" is correct
```
    UCHIJ   GalacticraftCore{3.0.12} [Galacticraft Core] (GalacticraftCore-1.7-3.0.12.464.jar)
    UCHIJ   GalacticraftMars{3.0.12} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.12.464.jar)
```

**Comment by CutlassPlayz** [comment]
Whenever I try to go to that website it never loads do you know why?

**Comment by MJRLegends** [comment]
@CutlassPlayz Nope works fine for me try https://micdoodle8.com/mods/galacticraft/downloads

**Comment by CutlassPlayz** [comment]
is there anyway you could give me the mods themselves in a firefox or something the download part wont work for me neither does the micdoodle forum

**Comment by MJRLegends** [comment]
Contact the Galacticraft developers via there support section on forums

**Comment by MJRLegends** [comment]
or take a look at this page https://forum.micdoodle8.com/index.php?threads/i-cant-download-galacticraft-what-to-do.3736/
