### ISSUE TITLE
I have tried everything to fix the dimension error A.K.A. Exception in server tick loop  java.lang.IllegalArgumentException: Could not get provider type for dimension x, does not exist and no matter what it will not work, I disabled one dimension that wasn't working and it just said a different dimension didn't work

### ISSUE THREAD

**Issue by CutlassPlayz** [MJRLegends/ExtraPlanets#103]
### ---Issue Report---
This is the 2nd time I have had this issue and it really sucks cause I wanna play this mod and it won't work for some reason.
**Have you checked Closed Issues (if applicable):** [Yes or No]
### Description of Issue
[Description of the issue]
Again, the error, Exception in server tick loop java.lang.IllegalArgumentException: Could not get provider type for dimension x, does not exist, continually crashes my game and will not allow me to use Extra Planets. I have updated Extra Planets to the newest version released roughly 7 hours ago and it still won't work. I have the newest version of Galacticraft 1.7.10 497 for core, planets, and micdoodle core. PLEASE HELP ME I DONT KNOW WHAT IS WRONG ANYMORE.
### Steps to Reproduce Issue
1. [First step]Have Extra Planets 1.7.3
2. [Second step]Have Galacticraft version 1.7.10 497 and run it.

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
(Multiple Paste Bins) https://pastebin.com/Sd8GCGT5  https://pastebin.com/XS3CPChz  https://pastebin.com/WGjcT6B1
**Version of Mod using:** [VERSION]
1.7.3
### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Change that dimension id in the config!

**Comment by CutlassPlayz** [comment]
I have changed them multiple times and non are working

**Comment by MJRLegends** [comment]
@CutlassPlayz Im unable to help you with loads of mods in your pack, im not here to help make a mod pack. You can change all dimension ids in my config apart from that you will need to find dimension ids else where in other config files for other mods

**Comment by CutlassPlayz** [comment]
Btw I found out the problem, Rftools isnt compatible because of how many dimensions it creates

**Comment by CutlassPlayz** [comment]
Scratch that its thaumcraft

**Comment by CutlassPlayz** [comment]
@MJRLegends

**Comment by CutlassPlayz** [comment]
Nevermind once again, it is zollern galaxy and rftools that does it

**Comment by MJRLegends** [comment]
@CutlassPlayz This isnt a mod issue on my side its part of minecraft and can be sorted with some config edits so im locking this issue as its not a bug. If you get any more 100% my mod bugs let me know
