### ISSUE TITLE
Ash Block breaking turns into a tier 4 rocket engine

### ISSUE THREAD

**Issue by MrEyeballs29** [MJRLegends/ExtraPlanets#107]
This is a cheaty mistake. When you break an ash block you get a tier 4 rocket engine instead of 4 ashes this sooo weird. weirder than ever!

**Comment by MJRLegends** [comment]
What mc version??

**Comment by MJRLegends** [comment]
@MrEyeballs29 Dont worry found out which version, Please put the mc version in future bug reports otherwise it makes it like 3x for me to find and test the bug

**Comment by MrEyeballs29** [comment]
Oh I will. I just forgot that I am only using 1.7.10 for you mod.

**Comment by MJRLegends** [comment]
@MrEyeballs29 Yeah a update will be out with the fix in a few days, you can use silk touch on the blocks to get the blocks to break down using a recipe, see nei for that recipe :D

**Comment by MrEyeballs29** [comment]
which tool I shall use to break it enchanted with silky without getting a weird item.

**Comment by MJRLegends** [comment]
Any tool with silk touch should hopefully work for you

**Comment by MrEyeballs29** [comment]
I am going to test it to make sure it works

**Comment by MrEyeballs29** [comment]
Wow It works?

**Comment by MJRLegends** [comment]
An update will be coming out today with this fix :D

**Comment by MJRLegends** [comment]
Fixed
