### ISSUE TITLE
Server crashes when loading some dimensions 1.11.2

### ISSUE THREAD

**Issue by ElSaam** [MJRLegends/ExtraPlanets#108]
### ---Issue Report---

**Have you checked Closed Issues (if applicable):** Yes
### Description of Issue
Server crashes when entering Jupiter or Venus. Kepler 22b works. Didn't try other planets.

### Steps to Reproduce Issue
1. https://youtu.be/VttMCmakZEs
2. [Second step]

**Crash log/Log (if applicable):** https://pastebin.com/rXJdZiTf

**Version of Mod using:** ExtraPlanets-0.1.1-Beta-Build.jar

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
I will take a look at Jupiter one but Venus isnt my planet its Galacticrafts

**Comment by MJRLegends** [comment]
Updates for 1.7.10, 1.10.2 and 1.11.2 have been submitted just waiting on curse to approve them and then they should show on curse to download
