### ISSUE TITLE
[1.11.2] Server&Client Crash: Exception in server tick loop

### ISSUE THREAD

**Issue by thedespo** [MJRLegends/ExtraPlanets#109]
### ---Issue Report---

**Have you checked Closed Issues (if applicable):** 
Yes
### Description of Issue
The Server crashed while using the NASA Workbench

### Steps to Reproduce Issue
1. open the NASA Workbench
2. add a schematic, in my case it was an Venus Rover Schematic
3. click on BACK/NEXT
4. Server and Client crashed

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

Crash Log: https://pastebin.com/KwujJJEm (Added by MJRLegends)

**Version of Mod using:** [ExtraPlanets-0.1.2-Beta-Build | GalacticraftCore-1.11.2-4.0.0.107 | Galacticraft-Planets-1.11.2-4.0.0.107 | MicdoodleCore-1.11.2-4.0.0.107 - also tested with Builds 106]

### Additional Information
Server + client crash log attached.
[crash-2017-06-14_20.56.51-server.txt](https://github.com/MJRLegends/ExtraPlanets/files/1075658/crash-2017-06-14_20.56.51-server.txt)
[crash-2017-06-14_20.52.42-client.txt](https://github.com/MJRLegends/ExtraPlanets/files/1075663/crash-2017-06-14_20.52.42-client.txt)
[crash-2017-06-14_20.56.54-client.txt](https://github.com/MJRLegends/ExtraPlanets/files/1075664/crash-2017-06-14_20.56.54-client.txt)

**Comment by MJRLegends** [comment]
Thanks i can fix this, also please use pastebin.com and not upload the files :D

**Comment by MJRLegends** [comment]
A New version will be out in the next few hours with the fix :D Let me know if you get any more issues

**Comment by thedespo** [comment]
wow, super fast response, thanks a lot 👍 regarding the logs, i will handle it that way next time :D

**Comment by MJRLegends** [comment]
@thedespo Change of plan from my above comment, Im going to upload a version now with the fix in :P Give me 20 mins and it will be on curse :D

**Comment by thedespo** [comment]
:D you are awesome !! super support

**Comment by MJRLegends** [comment]
No problem :D Any time :P

**Comment by MJRLegends** [comment]
Just waiting on Curse to approve the update and then it will be on Curse for you

**Comment by MJRLegends** [comment]
@thedespo Its been approved give this a test and let me know if anymore issues come about https://minecraft.curseforge.com/projects/extraplanets/files/2434183

**Comment by MJRLegends** [comment]
Im releasing another version has found more issues with what you reporting give me 20 mins for that one :D

**Comment by thedespo** [comment]
okay, i can confirm it. The same issue with mars rover and tier 4 rocket and above

**Comment by MJRLegends** [comment]
@thedespo yeah im releasing v0.1.4-Beta-Build now which will 100% fix this issue for you :D

**Comment by MJRLegends** [comment]
ok please try this one https://minecraft.curseforge.com/projects/extraplanets/files/2434192

**Comment by MJRLegends** [comment]
no i lied its broken still sorry 1.11.2 is a pain :( give me 10 :D

**Comment by thedespo** [comment]
okay :D, take your time, i´m happy about your support. just FYI >> https://pastebin.com/itM6XUwU

**Comment by MJRLegends** [comment]
Yeah its a number of things causing this issue, i keep fixing one and thinking thats it and then i find another haha

**Comment by MJRLegends** [comment]
Ok i think i have it all fixed now :D

**Comment by MJRLegends** [comment]
v0.1.5-Beta-Build is coming out :D

**Comment by MJRLegends** [comment]
let me know if v0.1.5-Beta-Build fixed it all :D
