### ISSUE TITLE
NEI rockets recipes

### ISSUE THREAD

**Issue by Cronosus** [MJRLegends/ExtraPlanets#11]
Tier7 rocket (maybe other too) still not showing recipe/s in NEI

1.0-Pre 3.5

**Comment by MJRLegends** [comment]
Can you test the others please

**Comment by MJRLegends** [comment]
Will be fixed in the next update/bug fix https://github.com/MJRLegends/ExtraPlanets/commit/574383db8971b86c64d768eda5408da94b17e6da

**Comment by MJRLegends** [comment]
v1.0-Pre 3.5.1 is out that contains this fix
