### ISSUE TITLE
[1.7.10] Incorrect Saplings

### ISSUE THREAD

**Issue by MrEyeballs29** [MJRLegends/ExtraPlanets#110]
## ---Issue Report---

**Have you checked Closed Issues (if applicable):** Yes
### Description of Issue
If you break a leaf it will sometimes be a wrong color

### Steps to Reproduce Issue
1. I chopped down the yellow tree in kepler 22b 
2. It gave me blue sapling I think

**Version of Mod using:** Extraplanets 1.7.6

### Additional Information
I also happened with red, green, and brown saplings too

**Comment by MJRLegends** [comment]
Thanks i can fix this

**Comment by MJRLegends** [comment]
I will be releasing updates tonight :D

**Comment by MJRLegends** [comment]
I think this is a 1.7.10 only bug which is good :D

**Comment by MrEyeballs29** [comment]
No problem 😃

**Comment by MJRLegends** [comment]
Found a few other bugs im going to fix with the trees too

**Comment by MJRLegends** [comment]
The leaves will be all removed and new leafs will generate in new chunks or new grown trees

**Comment by MrEyeballs29** [comment]
I don't have a world saved anyway. On the Side note there is work in progress blocks that have to get new chunks as well. But thanks anyway 👍 😄

**Comment by MJRLegends** [comment]
"work in progress blocks that have to get new chunks as wel" not sure what you mean there sorry.

And new updates are rolling out now

**Comment by MrEyeballs29** [comment]
you spelled "well" wrong. 😉 btw also it can be found in the description of [GalaxyWars](https://minecraft.curseforge.com/projects/galaxywars)

**Comment by MJRLegends** [comment]
@MrEyeballs29 Im not sure what issue your reporting here with the WIP blocks and items?

**Comment by MJRLegends** [comment]
![](https://i.gyazo.com/e89b58fd16bbb3a76021b17d82b11095.png)
