### ISSUE TITLE
[1.7.10] Ultimate and Hybrid solar panels do not consistently output their energy.

### ISSUE THREAD

**Issue by JaSpr** [MJRLegends/ExtraPlanets#111]
### ---Issue Report---

**Have you checked Closed Issues (if applicable):** YES
### Description of Issue
I have a basic, advanced, hybrid, and ultimate solar panels.  Both with IE2 wire, and with mekanism cables, the basic and advanced always output power.  The hybrid and ultimate only output power when they are first connected, but once they (quickly) fully drain, then they start filling back up again, outputting no power.

### Steps to Reproduce Issue
1. Let unconnected hybrid/ultimate solar panel fill up.
2. Connect (with wiring or cable) to some other energy storage that can accept the solar's stored energy.
2. Energy quickly drains into energy cell, but then stops outputting once the solar array is empty.  The solar array will then fill back up, and no longer output any of its power.

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Version of Mod using:** [VERSION]
Minecraft: 1.7.10
Modpack: Project Ozone 2 (2.2.9 EFU6)

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by JaSpr** [comment]
Update: It also appears that they dump their energy (into the system) once whenever their status changes (e.g. they seem to dump all their energy when morning hits, then immediately start storing again)

**Comment by MJRLegends** [comment]
Thanks i will look at this ASAP

**Comment by JaSpr** [comment]
Retesting, it seems that, when it suddenly stops, it's actually just dropping how quickly it is outputting power.  I tested with it connected directly to an energy cell, and the speed at which it is charging just suddenly drops.

Also, it's difficult to tell how much power it's actually generated.  In every other system, RF & J are equal, but the EP solars list them as different values, so I'm not sure what is correct.  The cables I am using can support 64kJ/t

**Comment by MJRLegends** [comment]
They seem to outputting fine for me with my testing

**Comment by MJRLegends** [comment]
I will do some more testing, i might redo some of the code for them too anyways

**Comment by MJRLegends** [comment]
@JaSpr Sorry for the delay, there will be a fix in todays update for MC 1.10.2 and 1.11.2 :D

**Comment by MJRLegends** [comment]
@JaSpr And MC 1.7.10 maybe today if not tomorrow :D

**Comment by MJRLegends** [comment]
and MC 1.8.9 soon haha

**Comment by MJRLegends** [comment]
MC 1.7.10 update is out fixing this issue
