### ISSUE TITLE
Missing dimention -34

### ISSUE THREAD

**Issue by MIGA2001** [MJRLegends/ExtraPlanets#112]
### ---Issue Report---

**Have you checked Closed Issues (if applicable): yes
### Description of Issue
As long as i have extra planets mod, I get this crash
### Steps to Reproduce Issue
I dunno, how you can reproduce it, but try downloading all mods I have)

**Crash log/Log (if applicable):** https://pastebin.com/mZubd6Cc
**Version of Mod using:** Latest for 1.7.10

**Comment by MJRLegends** [comment]
This means two or more mods are using this id for a dimension, you can change all dimension ids from my mods config and im sure you can from other mods configs too if they have dimensions

**Comment by MIGA2001** [comment]
Thanks, that helped
