### ISSUE TITLE
Could not get provider type for dimension -36, does not exist

### ISSUE THREAD

**Issue by AlphaMason** [MJRLegends/ExtraPlanets#113]
Game crashes when trying to get provider type for Extra Planets dimensions.

https://pastebin.com/n21mTDnn

version of mod 0.5.0 Beta
Minecraft 1.10.2

**Comment by MJRLegends** [comment]
This means two or more mods are using this id for a dimension, you can change all dimension ids from my mods config and im sure you can from other mods configs too if they have dimensions

**Comment by AlphaMason** [comment]
Thanks, but I was hoping you could tell me which mod was conflicting with Extra Planets?

**Comment by MJRLegends** [comment]
Im not sure, just change the ids in my config to another number

**Comment by MJRLegends** [comment]
Also when posting a issue next time please make sure to check known issues as this option in the issue template says "
**Have you checked Closed Issues (if applicable):** [Yes or No]"
as this has been posted 3 times in the last week

**Comment by pwnage-pineapple** [comment]
I'm having the same issue, but I tried four different ID numbers (-36, -99, -86, and -8160), and I get the same error, just with whichever ID I set. I'm reasonably certian that at least one of those should have worked. I am working with a large number of mods, but it is fairly unlikely that the error is an ID conflict

**Comment by MJRLegends** [comment]
that means you got more than one mod using that id then

**Comment by MJRLegends** [comment]
i use the 1.10.2 of my mod in my pack and it works fine so its to do with the mods you have with it so its must be a conflict

**Comment by MJRLegends** [comment]
You will need to start removing mods like AdvancedRocketry,etc to see if it fixes it

**Comment by pwnage-pineapple** [comment]
I collated all my config files together into one file using some Z-Shell work, used my text editor's search function to find any instance of the number -8160, and only found it within ExtraPlanets' config. I did the same with the other three IDs and get the same result. No other mod could possibly be using those IDs.

**Comment by MJRLegends** [comment]
Try GC and ExtraPlanets on there own

**Comment by pwnage-pineapple** [comment]
I cross-refrenced the lists of mods of my own and two other occurrences of this issue. Below is the list of all mods common to all three cases:

- BiomesOPlenty
- ChickenChunks
- CodeChickenCore
- Mekanism
- MekanismGenerators
- MekanismTools
- MineTweaker3
- Chisel
- Pam's Harvestcraft

Removing all of these mods was able to correct the issue. However, as far as I can tell, none of these mods add dimensions, thus making it very unlikely that this is caused by an ID conflict. I am currently re-adding the mods one by one to narrow the list down to a single mod. I will reply again when I have completed this

**Comment by pwnage-pineapple** [comment]
@covers1624 The error appears to be caused by ChickenChunks. I don't think it's possible that a chunkloader mod is causing a dimension ID conflict. I do, however, believe there is an interaction problem between the two mods, hence my bringing in covers1624.
