### ISSUE TITLE
ChickenChunks conflict (Could not get provider type for dimension -36, does not exist)

### ISSUE THREAD

**Issue by pwnage-pineapple** [MJRLegends/ExtraPlanets#114]
### ---Issue Report---

**Have you checked Closed Issues (if applicable):** Yes, see Additional Information
### Description of Issue
When this mod and ChickenChunks are used together, the game crashes a few minutes after loading a world with the error "Could not get provider type for dimension -36, does not exist"

### Steps to Reproduce Issue
1. Install Galacticraft, ExtraPlanets, and ChickenChunks
2. Start game and load a world
3. Wait a few minutes

**Version of Mod using:** Latest 1.10.2

### Additional Information
I cross-refrenced the lists of mods of my own and two other occurrences of this issue. Below is the list of all mods common to all three cases:

    BiomesOPlenty
    ChickenChunks
    CodeChickenCore
    Mekanism
    MekanismGenerators
    MekanismTools
    MineTweaker3
    Chisel
    Pam's Harvestcraft

Removing all of these mods was able to correct the issue. Having tested each mod one by one, The error appears to occur only when ChickenChunks is co-installed. I  believe there is an interaction problem between the two mods, hence my bringing in @covers1624.

**Comment by covers1624** [comment]
Chicken chunks has a dimension cached to chunk load, said dimension has been removed. I'll only be able to provide a fix for 1.11, you can mitigate this by deleting the chicken chunks folder inside your world. This will make all chunk loaders non functional untill first load.

**Comment by MJRLegends** [comment]
@covers1624 thanks for the message :) @pwnage-pineapple im closing this because its not a direct issue with my mod but with chicken chunks

**Comment by covers1624** [comment]
Yes, this is a topic for http://github.com/TheCBProject/ChickenChunks

**Comment by MJRLegends** [comment]
@covers1624 :) i appreciate the provided solution, its a shame a fix cant be integrated in to mc 1.10.2 but i understand why :P
