### ISSUE TITLE
[1.10.2] Shift-left click causes "disconnect-crash"

### ISSUE THREAD

**Issue by DeadSix27** [MJRLegends/ExtraPlanets#115]
(searched for left click, shift click, click, nothing seemingly relative found.)

### Description of Issue
Game disconnects you with error messages appearing on the server.

I reported this wrongly to silentgems first by accident, see here for more details:  https://github.com/SilentChaos512/SilentGems/issues/168

### Steps to Reproduce Issue
Go into creative mode give yourself supercharged katana then shift left click, causes disconnect with errors 

Stacktrace: https://gist.github.com/DeadSix27/aeea24a14c8bae8cf6d0b6baa27516b0

**Version:** ExtraPlanets-0.5.0-Beta-Build.jar

**Comment by MJRLegends** [comment]
A update for MC 1.10.2 and 1.11.2 will be out in a few hours :D Thanks for the bug report

**Comment by MJRLegends** [comment]
Update is out for MC 1.10.2, MC 1.11.2 update will be later @DeadSix27

**Comment by DeadSix27** [comment]
@MJRLegends thanks

**Comment by MJRLegends** [comment]
No problem :D Any more issues please let me know
