### ISSUE TITLE
[1.10.2] Client crashes upon entering planet dimension (kepler22b)

### ISSUE THREAD

**Issue by DeadSix27** [MJRLegends/ExtraPlanets#117]
**EDIT:** I remember trying another planet before with the same crash, I'll test that later, but kepler definitely crashes with this error.

### ---Issue Report---

Searched for "ArrayIndexOutOfBoundsException" in closed issues, no results.

### Description of Issue
I wanted to test flying to kepler in creative (:P) but the client crashes before even getting there, see linked stacktrace here: https://gist.github.com/DeadSix27/8b0e7d2f524e842d5ec2c1dd21433411

While I did that i also encountered another exception, which didn't cause a crash tho, that one is linked here: https://gist.github.com/DeadSix27/b9ff99c5454ac9a392b93ad7794d270b

### Steps to Reproduce Issue
Launch with tier 10 rocket towards kepler22b

**Version of Mod using:** ExtraPlanets-0.5.1-Beta-Build.jar

**Comment by MJRLegends** [comment]
theoneprobe and CustomColors are causes these crashes so im unable to fix sorry

**Comment by MJRLegends** [comment]
Please report this to them :D

**Comment by MJRLegends** [comment]
If they say its my fault get them to contact me and we can work it out :D

**Comment by DeadSix27** [comment]
@MJRLegends I just checked further, as I didn't even know there is a mod thats named CustomColors, turns out that CustomColors is part of OptiFine, I'll see if I can find their issue tracker and report it to them. (as well as report the other thing to TheOneProb.)

the CustomColors thing looked a lot like a forge error, thus I assumed its on extraplanets side. :P

**Comment by MJRLegends** [comment]
In that cause the crash issue with is from OptiFine is the main issue and sorry i dont support OptiFine due to the fact its a vanilla tool and has to many issues with modded

**Comment by MJRLegends** [comment]
The TheOneProb error isnt a major issue tbh so dont worry to much about it

**Comment by DeadSix27** [comment]
@MJRLegends Ye a lot of mods don't support OptiFine, helps a bit when you have a ton of mods installed tho, even on a beefy pc. I'll try it without tho for now. Think BetterFPS + foamfix + mipmaps on 0 gives a constant 120fps .. should be good enough.

 Also, should I still report this to OptiFine or can this only be solved on your end?

**Comment by MJRLegends** [comment]
i will see what i can do about that TheOneProb error leave it with me :D

**Comment by MJRLegends** [comment]
Put it this way OptiFine dont support modded and modded doesnt support OptiFine. and its a issue on there side but probably due to the lack of support for modded

**Comment by DeadSix27** [comment]
@MJRLegends Alright :p

**Comment by MJRLegends** [comment]
@DeadSix27 does the TheOneProb error happen in a new world?

**Comment by DeadSix27** [comment]
@MJRLegends Nope, It was my "filled" world, .. well a copy of it. I can try to reproduce it, give me a few minutes.

**Comment by MJRLegends** [comment]
ok we will call this fixed then and it was a optifine issue too :D
