### ISSUE TITLE
Galacticraft 4 missing and crash with Extra Planets

### ISSUE THREAD

**Issue by Superguz72** [MJRLegends/ExtraPlanets#118]
Galacticraft 4 on curse is missing and is impossible to launch with the original galacticraft of micdoodle 8 
The version of Extra Planets is 0.5.1 Beta 1.10.2
The crash is the following:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MalisisCorePlugin (malisiscore-1.10.2-4.2.9.jar)
  ForgelinPlugin (Forgelin-1.2.0.jar)
  LoadingPlugin (ResourceLoader-MC1.9.4-1.5.1.jar)
  AppEngCore (appliedenergistics2-rv4-alpha-9.jar)
  CoFH Loading Plugin (CoFHCore-1.10.2-4.1.7.11-universal.jar)
  BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.3.338.jar)
  ChiselCorePlugin (Chisel-MC1.10.2-0.0.7.7.jar)
  IC2core (industrialcraft-2-2.6.142-ex110.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.62-beta.jar)
  MicdoodlePlugin (MicdoodleCore-1.10.2-4.0.0.106.jar)
  RebornCoreASM (RebornCore-1.10.2-2.12.1.96-universal.jar)
  SFRCore (SolarFluxReborn_1.10.2-2.4r.jar)
  Brandon's Core (BrandonsCore-1.10.2-2.1.3.82-universal.jar)
  LoadingPlugin (Quark-r1.1-70.jar)
  ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.6.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.9.267-universal.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
Contact their authors BEFORE contacting forge

// Ooh. Shiny.

Time: 6/27/17 7:18 PM
Description: Rendering screen

java.lang.NoClassDefFoundError: bxl
	at net.minecraftforge.fml.common.versioning.Restriction.toStringFriendly(Restriction.java:224)
	at net.minecraftforge.fml.common.versioning.VersionRange.toStringFriendly(VersionRange.java:498)
	at net.minecraftforge.fml.client.GuiModsMissing.func_73863_a(GuiModsMissing.java:106)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.fml.common.versioning.Restriction.toStringFriendly(Restriction.java:224)
	at net.minecraftforge.fml.common.versioning.VersionRange.toStringFriendly(VersionRange.java:498)
	at net.minecraftforge.fml.client.GuiModsMissing.func_73863_a(GuiModsMissing.java:106)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)

-- Screen render details --
Details:
	Screen name: net.minecraftforge.fml.client.GuiModsMissing
	Mouse location: Scaled: (341, 155). Absolute: (1023, 301)
	Screen size: Scaled: (342, 256). Absolute: (1024, 768). Scale factor of 3
Stacktrace:
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Mac OS X (x86_64) version 10.12.5
	Java Version: 1.8.0_131, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1196906760 bytes (1141 MB) / 1797259264 bytes (1714 MB) up to 5726797824 bytes (5461 MB)
	JVM Flags: 3 total; -Xmx6144m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2202 147 mods loaded, 147 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	U	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	U	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2202.jar) 
	U	Forge{12.18.3.2202} [Minecraft Forge] (forge-1.10.2-12.18.3.2202.jar) 
	U	appliedenergistics2-core{rv4-alpha-9} [Applied Energistics 2 Core] (minecraft.jar) 
	U	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	U	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	U	cei{1.3} [Chunk Edge Indicator] (1.10-chunkedgeindicator-1.3.jar) 
	U	actuallyadditions{1.10.2-r97} [Actually Additions] (ActuallyAdditions-1.10.2-r97.jar) 
	U	aether_legacy{v1.0-1.9.4} [Aether Legacy] (aether_legacy-1.2.jar) 
	U	flyringbaublemod{0.2.1_1.10.2-45380c9} [AngelRing 2 Bauble] (angelRingToBauble-1.10.2-0.2.1.12+45380c9.jar) 
	U	appliedenergistics2{rv4-alpha-9} [Applied Energistics 2] (appliedenergistics2-rv4-alpha-9.jar) 
	U	AutoRegLib{1.0-2} [AutoRegLib] (AutoRegLib-1.0-2.jar) 
	U	avaritia{${mod_version}} [Avaritia] (Avaritia-1.10.2-2.2.4.-universal.jar) 
	U	Baubles{1.3.8} [Baubles] (Baubles-1.10.2-1.3.8.jar) 
	U	BBG{5.0.0} [BetterBedrockGen] (BBG-1.9.4-5.0.0.jar) 
	U	bdlib{1.12.2.17} [BD Lib] (bdlib-1.12.2.17-mc1.10.2.jar) 
	U	bedbugs{@VERSION@} [Bed Bugs] (BedBugs-1.10.2-1.1.4.jar) 
	U	BetterAchievements{0.3.2.39} [Better Achievements] (BetterAchievements-1.10.2-0.3.2.39.jar) 
	U	betterbuilderswands{0.10.2} [Better Builder's Wands] (BetterBuildersWands-1.10.2-0.10.2.209+115b204.jar) 
	U	BloodMagic{1.9.4-2.1.0-69} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.9.4-2.1.0-69.jar) 
	U	bookshelf{1.4.3.338} [Bookshelf] (Bookshelf-1.10.2-1.4.3.338.jar) 
	U	Botania{r1.9-339} [Botania] (Botania r1.9-339.jar) 
	U	brandonscore{2.1.3} [Brandon's Core] (BrandonsCore-1.10.2-2.1.3.82-universal.jar) 
	U	Chameleon{1.10-2.2.2} [Chameleon] (Chameleon-1.10-2.2.2.jar) 
	U	chancecubes{1.10.2-2.3.3.135} [Chance Cubes] (ChanceCubes-1.10.2-2.3.3.135.jar) 
	U	chickens{4.2.1} [Chickens] (chickens-4.3.jar) 
	U	chisel{MC1.10.2-0.0.7.7} [Chisel] (Chisel-MC1.10.2-0.0.7.7.jar) 
	U	chiselsandbits{12.10} [Chisels & Bits] (chiselsandbits-12.10.jar) 
	U	CodeChickenLib{2.5.9.267} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.5.9.267-universal.jar) 
	U	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.10.2-2.5.9.267-universal.jar) 
	U	cofhcore{4.1.7} [CoFH Core] (CoFHCore-1.10.2-4.1.7.11-universal.jar) 
	U	colossalchests{1.4.2} [Colossal Chests] (ColossalChests-1.10.2-1.4.2.jar) 
	U	commoncapabilities{1.2.2} [CommonCapabilities] (CommonCapabilities-1.9.4-1.2.2.jar) 
	U	controlling{1.0.3} [Controlling] (Controlling-1.0.3.jar) 
	U	counter_guns{1.0.1} [Counter Guns] (CounterGuns-1.10.2-1.0.1.jar) 
	U	ctgui{1.0.0} [CT-GUI] (CraftTweaker-1.10.2-3.0.26.jar) 
	U	MineTweaker3{3.0.26} [MineTweaker 3] (CraftTweaker-1.10.2-3.0.26.jar) 
	U	crafttweakerjei{1.0.1} [CraftTweaker JEI Support] (CraftTweaker-1.10.2-3.0.26.jar) 
	U	customnpcs{1.10.2} [CustomNPCs] (CustomNPCs_1.10.2(20nov16).jar) 
	U	cyclicmagic{1.9.13} [Cyclic] (Cyclic-1.10.2-1.9.13.jar) 
	U	cyclopscore{0.9.0} [Cyclops Core] (CyclopsCore-1.9.4-0.9.0.jar) 
	U	darkutils{1.1.6.103} [Dark Utilities] (DarkUtilities-1.10.2-1.1.6.103.jar) 
	U	PTRModelLib{1.0.0} [PTRModelLib] (Decocraft-2.3.6.1_1.10.2.jar) 
	U	props{2.3.6.1} [Decocraft] (Decocraft-2.3.6.1_1.10.2.jar) 
	U	deepresonance{1.4.2} [DeepResonance] (deepresonance-1.1x-1.4.2.jar) 
	U	draconicevolution{2.0.6} [Draconic Evolution] (Draconic-Evolution-1.10.2-2.0.6.157-universal.jar) 
	U	bitdrawers{0.35} [Drawers & Bits] (DrawersBits-1.10.2-0.35.jar) 
	U	dungeontactics{DT-0.11.1} [DungeonTactics] (DungeonTactics-1.10.2-0.11.1.jar) 
	U	eleccore{1.6.379} [ElecCore] (ElecCore-1.10.2-1.6.379.jar) 
	U	elevatorid{1.3.0} [Elevator Mod] (ElevatorMod[V.1.3.0][MC.1.10.2].jar) 
	U	endercore{1.10.2-0.4.1.62-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.62-beta.jar) 
	U	EnderIO{1.10.2-3.1.157} [Ender IO] (EnderIO-1.10.2-3.1.157.jar) 
	U	endertanks{1.4.9} [EnderTanks] (endertanks-1.10.0-1.4.9.jar) 
	U	energysynergy{1.1.1} [EnergySynergy] (EnergySynergy-1.10.2-1.1.1.jar) 
	U	environmentaltech{1.10.2-0.10.5h} [Environmental Tech] (environmentaltech-1.10.2-0.10.5h.jar) 
	U	extraplanets{0.5.1-Beta-Build} [Extra Planets] (ExtraPlanets-0.5.1-Beta-Build.jar) 
	U	ExtraUtils2{1.0} [ExtraUtils2] (extrautils2-1.10.2-1.1.3d.jar) 
	U	bigreactors{1.10.2-0.4.5.23} [Extreme Reactors] (ExtremeReactors-1.10.2-0.4.5.23.jar) 
	U	flatcoloredblocks{mc1.10-v4.4} [Flat Colored Blocks] (flatcoloredblocks-mc1.10-v4.4.jar) 
	U	fluxnetworks{1.1.0} [FluxNetworks] (FluxNetworks-1.10.2-1.1.0.jar) 
	U	forestry{5.2.16.348} [Forestry] (forestry_1.10.2-5.2.16.348.jar) 
	U	ftbl{0.0.0} [FTBLib] (FTBLib-1.10.2-3.2.3.jar) 
	U	ftbu{0.0.0} [FTBUtilities] (FTBUtilities-1.10.2-3.2.4.jar) 
	U	galacticraftplanets{4.0.0} [Galacticraft Planets] (Galacticraft-Planets-1.10.2-4.0.0.106.jar) 
	U	galacticraftcore{4.0.0} [Galacticraft Core] (GalacticraftCore-1.10.2-4.0.0.106.jar) 
	U	gendustry{1.6.5.27} [GenDustry] (gendustry-1.6.5.27-mc1.10.2.jar) 
	U	advgenerators{0.9.20.18} [Advanced Generators] (generators-0.9.20.18-mc1.10.2.jar) 
	U	gravestone{1.5.10} [Gravestone] (GraveStone Mod 1.5.10.jar) 
	U	guideapi{@VERSION@} [Guide-API] (Guide-API-1.10.2-2.0.2-45.jar) 
	U	hammercore{1.2.3} [Hammer Core] (HammerCore_1.10.2-1.2.3.jar) 
	U	immersiveengineering{0.10-54} [Immersive Engineering] (ImmersiveEngineering-0.10-54.jar) 
	U	IC2{2.6.142-ex110} [IndustrialCraft 2] (industrialcraft-2-2.6.142-ex110.jar) 
	U	inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks] (InventoryTweaks-1.61-58.jar) 
	U	ironchest{1.10.2-7.0.11.797} [Iron Chest] (ironchest-1.10.2-7.0.11.797.jar) 
	U	JEFB{1.0.4} [Just Enough Forestry Bees] (jefb_1.10.2-1.0.4.jar) 
	U	JEI{3.14.2.401} [Just Enough Items] (jei_1.10.2-3.14.2.401.jar) 
	U	jeibees{0.9.0.4} [JEI Bees] (jeibees-0.9.0.4-mc1.10.2.jar) 
	U	journeymap{1.10.2-5.4.2} [JourneyMap] (journeymap-1.10.2-5.4.2.jar) 
	U	jeresources{0.5.8.98} [Just Enough Resources] (JustEnoughResources-1.10.2-0.5.8.98.jar) 
	U	malisiscore{1.10.2-4.2.9} [MalisisCore] (malisiscore-1.10.2-4.2.9.jar) 
	U	malisisdoors{1.10.2-5.1.6} [MalisisDoors] (malisisdoors-1.10.2-5.1.6.jar) 
	U	mantle{1.10.2-1.1.4.203} [Mantle] (Mantle-1.10.2-1.1.4.jar) 
	U	mcmultipart{1.3.0} [MCMultiPart] (MCMultiPart-1.3.0-universal.jar) 
	U	mercurius{1.0.1} [Mercurius] (Mercurius-1.10.2-1.0.2.jar) 
	U	modularforcefieldsystem{2.5.0} [Modular ForceField System] (MFFS-1.10.2-3.0.0.0_1.10_655de1f.jar) 
	U	mob_grinding_utils{0.1.8.12} [mob_grinding_utils] (MobGrindingUtils-0.1.8.12.jar) 
	U	ModNameTooltip{1.6.0} [Mod Name Tooltip] (modnametooltip_1.10.2-1.6.0.jar) 
	U	morebees{1.10.2-1.2} [More Bees] (morebees-1.10.2-1.2.jar) 
	U	morechickens{1.0.9} [More Chickens] (MoreChickens-1.10.2-1.0.9.jar) 
	U	Morpheus{1.10.2-3.1.13} [Morpheus] (Morpheus-1.10.2-3.1.13.jar) 
	U	mousetweaks{2.6.4} [Mouse Tweaks] (MouseTweaks-2.6.4-mc1.10.2.jar) 
	U	mtlib{@VERSION@} [MTLib] (MTLib-1.0.1.jar) 
	U	multistorage{1.2.13} [Multi-Storage] (multistorage-1.10.0-1.2.13.jar) 
	U	mysticalagriculture{1.3.8} [Mystical Agriculture] (mysticalagriculture[1.10.2]-1.3.8a.jar) 
	U	notenoughwands{1.5.3} [Not Enough Wands] (notenoughwands-1.1x-1.5.3.jar) 
	U	omlib{1.10.2-3.0.0-37} [OMLib] (omlib-1.10.2-3.0.0-37.jar) 
	U	openmodularturrets{1.10.2-3.0.0-42} [Open Modular Turrets] (openmodularturrets-1.10.2-3.0.0-42.jar) 
	U	fodc{1.9.1} [Ore Dictionary Converter] (OreDictionaryConverter-1.9.1.jar) 
	U	oreexcavation{1.2.78} [OreExcavation] (OreExcavation-1.2.78.jar) 
	U	harvestcraft{1.9.4-1.10.2g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9.4-1.10.2h.jar) 
	U	platforms{1.2.7} [Platforms] (platforms-1.10.0-1.2.7.jar) 
	U	samsapples{1.1.5} [Power Apples] (PowerApples-1.10.2-1.1.5.jar) 
	U	pressure{1.3.1.21} [Pressure Pipes] (pressure-1.3.1.21-mc1.10.2.jar) 
	U	progressiveautomation{1.6.53} [Progressive Automation] (ProgressiveAutomation-1.10.2-1.6.53.jar) 
	U	ProjectE{1.10.2-PE1.1.1.2} [ProjectE] (ProjectE-1.10.2-PE1.1.1.3.jar) 
	U	quantumflux{2.0.11} [QuantumFlux] (quantumflux-1.10.2-2.0.11.jar) 
	U	quantumstorage{3.2.17} [QuantumStorage] (QuantumStorage-1.10.2-3.2.17.jar) 
	U	Quark{r1.1-70} [Quark] (Quark-r1.1-70.jar) 
	U	rangedpumps{0.3} [Ranged Pumps] (rangedpumps-0.3.jar) 
	U	reborncore{2.12.1.96} [RebornCore] (RebornCore-1.10.2-2.12.1.96-universal.jar) 
	U	reborncore-mcmultipart{2.12.1.96} [reborncore-MCMultiPart] (RebornCore-1.10.2-2.12.1.96-universal.jar) 
	U	refinedstorage{1.2.16} [Refined Storage] (refinedstorage-1.2.16.jar) 
	U	xreliquary{1.10.2-1.3.3.620} [Reliquary] (Reliquary-1.10.2-1.3.3.620.jar) 
	U	ResourceLoader{1.5.1} [Resource Loader] (ResourceLoader-MC1.9.4-1.5.1.jar) 
	U	rftools{5.76} [RFTools] (rftools-1.1x-5.76.jar) 
	U	rftoolsdim{4.52} [RFTools Dimensions] (rftoolsdim-1.1x-4.52.jar) 
	U	roots{0.208} [Roots] (roots-0.208.jar) 
	U	shadowmc{3.6.1} [ShadowMC] (ShadowMC-1.10.2-3.6.1.jar) 
	U	shetiphiancore{3.3.6} [ShetiPhian-Core] (shetiphiancore-1.10.0-3.3.6.jar) 
	U	simplegenerators{1.10.2-0.10.5c} [Simple Generators] (simplegenerators-1.10.2-0.10.5c.jar) 
	U	simplyconveyors{2.0.3} [Simply Conveyors] (SimplyConveyors-1.3.1.jar) 
	U	simplyjetpacks{2.0.3.26} [Simply Jetpacks 2] (SimplyJetpacks2-1.10.2-2.0.3.26.jar) 
	U	snad{1.10.2-1.6.09.20a} [Snad] (Snad-1.10.2-1.6.09.20a.jar) 
	U	solarfluxreborn{2.4r} [Solar Flux Reborn] (SolarFluxReborn_1.10.2-2.4r.jar) 
	U	sonarcore{3.2.1} [SonarCore] (SonarCore-1.10.2-3.2.1.jar) 
	U	soulshardstow{1.10.2-2.6.7-48} [Soul Shards - The Old Ways] (SoulShards-TOW-1.10.2-2.6.7-48.jar) 
	U	spartanshields{1.1c} [Spartan Shields] (SpartanShields-1.10.2-1.1c.jar) 
	U	StevesFactoryManager{1.0.12} [Steve's Factory Manager] (StevesFactoryManager-1.10.2-1.0.12.jar) 
	U	StorageDrawers{1.10.2-3.5.16} [Storage Drawers] (StorageDrawers-1.10.2-3.5.16.jar) 
	U	rscircuits{1.0.4} [Super Circuit Maker] (SuperCircuitMaker-1.0.4.jar) 
	U	superores{1.7} [Super Ores] (SuperOres-1.7.jar) 
	U	tconstruct{1.10.2-2.6.2.487} [Tinkers' Construct] (TConstruct-1.10.2-2.6.2.jar) 
	U	techreborn{1.4.17.141} [TechReborn] (TechReborn-1.10.2-1.4.17.141-universal.jar) 
	U	tesla{1.2.1.49} [TESLA] (Tesla-1.10.2-1.2.1.49.jar) 
	U	teslacoils{v0.2.1.0} [Tesla Coils] (teslacoils-0.2.3.0.jar) 
	U	beneath{1.1.1} [The Beneath] (The Beneath-1.10.2-1.1.1.jar) 
	U	thermaldynamics{2.0.8} [Thermal Dynamics] (ThermalDynamics-1.10.2-2.0.8.11-universal.jar) 
	U	thermalexpansion{5.1.6} [Thermal Expansion] (ThermalExpansion-1.10.2-5.1.6.8-universal.jar) 
	U	thermalfoundation{2.1.3} [Thermal Foundation] (ThermalFoundation-1.10.2-2.1.3.5-universal.jar) 
	U	TinkersAddons{1.0.3} [Tinkers' Addons] (Tinkers' Addons-1.10.x-1.0.3.jar) 
	U	tinkertoolleveling{1.10.2-1.0.1.DEV.f5def58} [Tinkers Tool Leveling] (TinkerToolLeveling-1.10.2-1.0.1.jar) 
	U	Torcherino{4.2s} [Torcherino] (Torcherino-4.2s.jar) 
	U	torchmaster{1.0} [TorchMaster] (torchmaster_1.10.2-1.1.0.11.jar) 
	U	valkyrielib{1.10.2-0.10.5d} [Valkyrie Lib] (valkyrielib-1.10.2-0.10.5e.jar) 
	U	weaponcaseloot{4.0.1} [WeaponCaseLoot] (weaponcaseloot-1.10.2-4.0.1.jar) 
	U	worldedit{6.1.4} [WorldEdit] (worldedit-forge-mc1.10.2-6.1.4-dist.jar) 
	U	zerocore{1.10.2-0.0.8.2} [Zero CORE] (zerocore-1.10.2-0.0.8.2.jar) 
	Loaded coremods (and transformers): 
MalisisCorePlugin (malisiscore-1.10.2-4.2.9.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
  net.malisis.core.util.clientnotif.ClientNotifTransformer
ForgelinPlugin (Forgelin-1.2.0.jar)
  
LoadingPlugin (ResourceLoader-MC1.9.4-1.5.1.jar)
  lumien.resourceloader.asm.ClassTransformer
AppEngCore (appliedenergistics2-rv4-alpha-9.jar)
  appeng.coremod.asm.ASMIntegration
CoFH Loading Plugin (CoFHCore-1.10.2-4.1.7.11-universal.jar)
  cofh.asm.CoFHClassTransformer
  cofh.asm.repack.codechicken.lib.asm.ClassHierarchyManager
BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.3.338.jar)
  net.darkhax.bookshelf.asm.BookshelfTransformerManager
ChiselCorePlugin (Chisel-MC1.10.2-0.0.7.7.jar)
  team.chisel.common.asm.ChiselTransformer
IC2core (industrialcraft-2-2.6.142-ex110.jar)
  
EnderCorePlugin (EnderCore-1.10.2-0.4.1.62-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
MicdoodlePlugin (MicdoodleCore-1.10.2-4.0.0.106.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
RebornCoreASM (RebornCore-1.10.2-2.12.1.96-universal.jar)
  reborncore.mixin.transformer.MixinTransformer
SFRCore (SolarFluxReborn_1.10.2-2.4r.jar)
  com.mrdimka.solarfluxreborn.core.SFRSerializedTransformer
Brandon's Core (BrandonsCore-1.10.2-2.1.3.82-universal.jar)
  com.brandon3055.brandonscore.asm.ClassTransformer
LoadingPlugin (Quark-r1.1-70.jar)
  vazkii.quark.base.asm.ClassTransformer
ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.6.jar)
  shetiphian.core.asm.ClassTransformer
CCLCorePlugin (CodeChickenLib-1.10.2-2.5.9.267-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.CCL_ASMTransformer
FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
	GL info: ' Vendor: 'Intel Inc.' Version: '2.1 INTEL-10.25.13' Renderer: 'Intel Iris Pro OpenGL Engine'
	Launched Version: forge-12.18.3.2202
	LWJGL: 2.9.2
	OpenGL: Intel Iris Pro OpenGL Engine GL version 2.1 INTEL-10.25.13, Intel Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-4570R CPU @ 2.70GHz

**Comment by MJRLegends** [comment]
Lol you need to download the Galacticraft saying it isnt on curse isnt a bug its just not on curse

**Comment by Superguz72** [comment]
I have download the original galacticraft but my launcher crash
