### ISSUE TITLE
Extra Planets Crash With Galacticraft for 1.10.2

### ISSUE THREAD

**Issue by Superguz72** [MJRLegends/ExtraPlanets#119]
The release of Extra Planets 0.5.1 for 1.10.2 crah with Galacticraft 4.0.0

**Comment by MJRLegends** [comment]
crash log?? i cant do magic tricks and know what the issue is haha

**Comment by MJRLegends** [comment]
If its the crash log on the other issues, its not my issues its galacticraft also please dont spam issue tickets

**Comment by MJRLegends** [comment]
Nothing to do with my mod sorry
