### ISSUE TITLE
[1.7.10] Duplicated Biomes IDs.

### ISSUE THREAD

**Issue by Simonmicro** [MJRLegends/ExtraPlanets#121]
### ---Issue Report---

**Have you checked Closed Issues (if applicable):No
### Description of Issue
Mobs spawn on the overworld (BUT ONLY ON SPECIFIC BIOMES).

### Steps to Reproduce Issue
1. Install first Biomes o Plenty and ExtraBiomesXL.
2. Start Minecraft
3. Install Galacticraft +  now play!

**Version of Mod using: MC 1.7.10 + ExtraPlanets 1.7.9.

### Additional Information
Your mod dont register it biomes in the biomes dictionary. After changing the biomes-IDs to values over 180 the Bug is "fixed".
Please add a check (is the ID already used?) before you try to register your biomes. And add the biomesdictionary-support, please.

In the first attachement is my biomesdictionary - and your IDs are missing:
[biome.csv.txt](https://github.com/MJRLegends/ExtraPlanets/files/1108427/biome.csv.txt)

Here is my fixed config:
[ExtraPlanets.cfg.txt](https://github.com/MJRLegends/ExtraPlanets/files/1108433/ExtraPlanets.cfg.txt)

**Comment by MJRLegends** [comment]
Thanks but this isnt a bug that needs reporting because thats why there options to change the ids in configs

**Comment by Simonmicro** [comment]
Sorry - it's not a bug, it's a feature... ;P

Could you please add the biomesdictionary support, so you could prevent that fail?

**Comment by MJRLegends** [comment]
Biomes will still require ids that's how mc/ forge needs them

**Comment by MJRLegends** [comment]
You will just need to change the config thats the best way since 1/10 times people wont need to change them, i dont wanna make them dynamic as that will take way to much cpu time to do it for all 15+ biomes

**Comment by Simonmicro** [comment]
Okay, thanks for your repley. Could you please add some instructions on your mod page how to modify the config (Using NEI to create a biomes dump etc), because I think 9/10 people wont know how to do that...

"i dont wanna make them dynamic as that will take way to much cpu time to do it for all 15+ biomes" -> What's about a one-time setup at the server start / only if the mods changes?

**Comment by spannerman79** [comment]
> Okay, thanks for your repley. Could you please add some instructions on your mod page how to modify the config (Using NEI to create a biomes dump etc), because I think 9/10 people wont know how to do that...

There is actually a mod to help out with that.  Doesn't just do biome conflicts either.  https://minecraft.curseforge.com/projects/anti-id-conflict

As to setting biomes in a config file, well its pretty clear right at the top of the config file - being and starting at line 1 of the config file - direct copy/paste
```
# Configuration file

##########################################################################################################
# biomeid
#--------------------------------------------------------------------------------------------------------#
# Change if a biome ID is causing conflicts!
##########################################################################################################
```

Pretty obvious to me what that states......

**Comment by Simonmicro** [comment]
Thanks! I was not be able to find that, but that little mod should resolve all problems - maybe the galacticraft core team should set a link for it on their wiki. But that is an other problem.

See you,

Simonmicro
