### ISSUE TITLE
[Bug] Block of Carbon / Carbon Ingot Recipe issue

### ISSUE THREAD

**Issue by BrisingrAerowing** [MJRLegends/ExtraPlanets#122]
### ---Issue Report---

**Have you checked Closed Issues (if applicable):** Yes
### Description of Issue
Carbon Blocks -> Carbon Ingots has major ingot loss.

### Steps to Reproduce Issue
View recipe for carbon ingots in JEI.

**Version of Mod using:** 1.11.2-0.1.9

### Additional Information
It takes 9 carbon ingots to make a block of carbon, but it takes 9 blocks of carbon to make 9 carbon ingots? That leads to a loss of 72 ingots!

**Comment by MJRLegends** [comment]
Thanks i will fix this :)

**Comment by BrisingrAerowing** [comment]
Sounds good!

**Comment by MJRLegends** [comment]
Release will be tonight for MC 1.7.10 & 1.10.2 & 1.11.2 :D to fix this

**Comment by MJRLegends** [comment]
MC 1.7.10 & 1.10.2 & 1.11.2 updates for ExtraPlanets are out :P
