### ISSUE TITLE
Config file

### ISSUE THREAD

**Issue by xJon** [MJRLegends/ExtraPlanets#123]
### ---Issue Report---

**Have you checked Closed Issues (if applicable):** [Yes]
### Description of Issue
Using version 1.8.0 for Minecraft 1.7.10, I was confused to see the configuration file. If Eris, for example, is tier 9, why would disabling it disable tier 10 rocket? Is it outdated?
![image](https://user-images.githubusercontent.com/8945347/27805935-4211fb72-6040-11e7-9398-3cdc4e24156d.png)
(also, in the tier 6 line, I think that the exclamation mark is in the wrong place)

### Steps to Reproduce Issue
1. Download and install the latest 1.7.10 version of Extra Planets.

**Version of Mod using:** [1.8.0]

**Comment by MJRLegends** [comment]
Because the Tier 10 rocket parts and materials and schematic are all found on Eris not the Tier 9 thats Pluto, also line 6 looks fine to me :D 
![](https://i.gyazo.com/0a913977d25d6902f7b55f0e991d9989.png)

**Comment by xJon** [comment]
Oh, I see! does it mean that the tier 10 schematics would be found tier 8, if such setting would be applied?
And, I meant the line for the tier 6 rocket :)

**Comment by MJRLegends** [comment]
No you just can get the schematic or items they will be disabled/removed
