### ISSUE TITLE
[1.11.2] Client locks on entry to DIM-13 Mercury after disabling radiation/pressure

### ISSUE THREAD

**Issue by kwpugh** [MJRLegends/ExtraPlanets#125]
### ---Issue Report---

**Have you checked Closed Issues (if applicable):** [Yes or No]
### Description of Issue
Client locks on entry to DIM-13 Mercury after disabling radiation/pressure

### Steps to Reproduce Issue
1. Visit Mercury and return to overworld
2. disable radiation and pressure in the config
3. try to return to Mercury

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
No crash, client just locks and needs to be killed locally
Console messages: https://gist.github.com/kwpugh/16cf86d38aa7ee6f37e08b8fd4ec663b

**Version of Mod using:** [VERSION]
Forge: 2345
Mods: ExtraPlanets-0.2.0-Beta-Build.jar
Galacticraft-Planets-1.11.2-4.0.0.107.jar
GalacticraftCore-1.11.2-4.0.0.107.jar
MicdoodleCore-1.11.2-4.0.0.107.jar

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Thanks will be fixed in the next version, which will be out later

**Comment by MJRLegends** [comment]
Updates are rolling out on curse now :P sorry for delay

**Comment by kwpugh** [comment]
Awesome, thank you.
