### ISSUE TITLE
Crafting Recipe: Block of Titanium

### ISSUE THREAD

**Issue by jaredstone1982** [MJRLegends/ExtraPlanets#126]
### ---Issue Report---

**Have you checked Closed Issues (if applicable):** Yes
### Description of Issue
[Block of Titanium] recipe gives 9 [Titanium Ingots] only if crafting stage is a 3x3 of [Block of Titanium]. Normal block recipes give 9 ingots with just a single block. Should be an easy fix, if this wasn't deliberate.

### Steps to Reproduce Issue
1. Open Crafting Table
2. Place 9 [Block of Titanium] in a 3x3 area

**Crash log/Log (if applicable):** Not applicable.

**Version of Mod using:** 1.7.10

### Additional Information
Thanks for such an amazing mod!

**Comment by MJRLegends** [comment]
Update your mod version

**Comment by MJRLegends** [comment]
If this is still a problem please let me know, sorry about my message earlier it was a bit blunt as i was in a rush
