### ISSUE TITLE
Block of Red Gems cannot be crafted back into Red Gems

### ISSUE THREAD

**Issue by BrisingrAerowing** [MJRLegends/ExtraPlanets#127]
### ---Issue Report---

**Have you checked Closed Issues (if applicable):** Yes
### Description of Issue
9 Red Gems can be crafted into a block, but that block cannot be crafted back.

### Steps to Reproduce Issue
1. Try to uncraft a Red Gem Block.

**Version of Mod using:** 1.11.2-0.2.2-beta

### Additional Information
A quick check from JEI shows that you seem to have used a Jupiter Red Gem Ore as the input to the uncrafting recipe.

**Comment by MJRLegends** [comment]
Thanks i will fix update will be out later

**Comment by MJRLegends** [comment]
Versions are being uploaded to curse as we speak for MC 1.10.2 and 1.11.2
