### ISSUE TITLE
[1.10.2] Crash on some planets.

### ISSUE THREAD

**Issue by Fungie2134** [MJRLegends/ExtraPlanets#128]
### ---Issue Report---

**Have you checked Closed Issues (if applicable):** [Yes]
### Description of Issue
When going on some planets ( with only your mod and it's dependency, or with some others mod ), there is an issue with the sky color. Only happen in the last release.

### Steps to Reproduce Issue
1. Start a game
2. Go on a planet lke Uranus and crash.

**Crash log/Log (if applicable):** https://pastebin.com/y506wi0d

**Version of Mod using:** latest release

### Additional Information
It happen on any material I could test in on. With any version of forge.

**Comment by MJRLegends** [comment]
This is a CustomColors related thing please report it there :D

**Comment by MJRLegends** [comment]
I might be able to do something but its not really for me to fix since my sky colour is in correct limits

**Comment by MJRLegends** [comment]
Please remove OptiFine and try again

**Comment by Fungie2134** [comment]
Same issue without or with optifine. I have already said that I got the same without any other mods unless ExtraPlanets and Galacticraft.
