### ISSUE TITLE
Powered Launch Pad bad recipe

### ISSUE THREAD

**Issue by drakray** [MJRLegends/ExtraPlanets#129]
### ---Issue Report---

**Have you checked Closed Issues (if applicable):** Yes
### Description of Issue
The Powered Launch Pad is craftable with nothing

### Steps to Reproduce Issue
1. Look at crafting inventory
2. Sort inventory with Inventory Tweak, or look at Crafting Table with [RealBench](https://minecraft.curseforge.com/projects/realbench) installed
3. Shift-click PLP to get infinite

**Version of Mod using:**
Minecraft 1.11.2
Forge 2421
ExtraPlanets 0.2.4
Relevant GC dependency
[RealBench](https://minecraft.curseforge.com/projects/realbench) 1.3.2
[NoMoreRecipeConflic](https://minecraft.curseforge.com/projects/stimmedcow-nomorerecipeconflict) 0.8

### Additional Information
Removing recipe with CraftTweak tempFix™ the problem

**Comment by MrEyeballs29** [comment]
That is super cheaty and there is no way you could get infinite. By the way what mc version are you using.

**Comment by drakray** [comment]
MC 1.11.2
It might be caused by intermod glitch, between Inventory Tweak, NoMoreRecipeConflict, RealBench, and ExtraPlanet having badly registered recipe (I shift-clicked the pad, and got 64+6 by keeping shift down, could've got more by keeping it longer)

**Comment by MrEyeballs29** [comment]
Well he has to fix that darn incapable bug. I sure that it will be fixed soon until then wait till the mod author tells you that he might fix it.

**Comment by MJRLegends** [comment]
@MrEyeballs29 i dont think rude comments are needed

**Comment by MJRLegends** [comment]
Please use v0.2.5
