### ISSUE TITLE
Unable to travel to pluto in 1.7.10 latest update

### ISSUE THREAD

**Issue by Breadabix** [MJRLegends/ExtraPlanets#130]
In the latest 1.7.10 update of the mod I am unable to travel to pluto in any way, through a rocket or the dimensiontp command. All you need to do to recreate the issue is load up a world and try and travel there, you will be unable to do so.

![2017-07-28_01 28 27](https://user-images.githubusercontent.com/19786108/28697515-5248997c-7334-11e7-8902-0565597b6914.png)

This happened in a singleplayer world, and I am unable to test this on a server. The screenshot is in the dimensiontp command screen.

**Comment by MJRLegends** [comment]
Its been disabled in the config then or a mod is stopping it registering

What other mods are you using and please post a copy of your ExtraPlanets config

**Comment by MJRLegends** [comment]
Also please post your fml-client-latest.log after trying to go there, also which tier rocket were you using?

**Comment by Breadabix** [comment]
I was using a tier 8 rocket, along with the dimensiontp command, here is the log, although I should warn you its very long with the amount of other mods included.

[fml-client-latest.zip](https://github.com/MJRLegends/ExtraPlanets/files/1182638/fml-client-latest.zip)

**Comment by MJRLegends** [comment]
please post a copy of your ExtraPlanets config

**Comment by Breadabix** [comment]
[ExtraPlanets.zip](https://github.com/MJRLegends/ExtraPlanets/files/1182649/ExtraPlanets.zip)

**Comment by MJRLegends** [comment]
> Could not register dimension -19 - does it clash with another mod?  Change the ID in config.
> Could not register dimension -42 - does it clash with another mod?  Change the ID in config.

You have dimension id conflicts change them in the config for ExtraPlanets

**Comment by Breadabix** [comment]
I have changed the Id's and it is still an issue

**Comment by MJRLegends** [comment]
please post your fml-client-latest.log after you have changed them

**Comment by Breadabix** [comment]
Never mind, it was because I joined a world already created before the changes, so they didnt take affect

**Comment by MJRLegends** [comment]
Ok
