### ISSUE TITLE
[Suggestion] Config for oreDict use in recipes

### ISSUE THREAD

**Issue by drakray** [MJRLegends/ExtraPlanets#132]
Could there be a config for your recipe to use oreDict please? Galacticraft have this itself, would be nice to have with your addon too :D
For exemple, compressed Platinum to use ingotPlatinum etc.
Config at false by default

**Comment by MJRLegends** [comment]
Which minecraft version are you looking for it?

**Comment by drakray** [comment]
1.11.2 would be nice please :D

**Comment by MJRLegends** [comment]
Ok thanks for your reply, Which materials do you need it for and which mod adds other versions of them

**Comment by drakray** [comment]
Almost every ingot, by Base Metal

**Comment by MJRLegends** [comment]
But wont it allow players to get the Tier 10 Rocket materials without going to the planets?

**Comment by drakray** [comment]
It could, hence the config. 
But i dont think any mod add Palladium, and same for Meteoric Iron. 
Also, some resources are only available on tierd planet, like liquid

**Comment by MJRLegends** [comment]
I dont feel its needed as it will make 50% of my mod invalid if players turn it on, you can always edit the recipes using CraftTweaker to allow this Sorry :P thanks for the suggestion though

**Comment by drakray** [comment]
I asked because i dont think CT can change Compressor recipe
