### ISSUE TITLE
Zinc ingot not showing in NEI

### ISSUE THREAD

**Issue by Breadabix** [MJRLegends/ExtraPlanets#135]
I dont know if this is an issue with ExtraPlanets, NEI or something removing it from NEI because of oredictionary reasons, but the zinc ingot isnt showing in NEI, both in the item list and in recipes, even for ExtraPlanets items such as zinc swords.

![2017-08-05_02 38 01](https://user-images.githubusercontent.com/19786108/28991884-26bf8294-7987-11e7-83df-43a1bc8fe060.png)

This is in singleplayer, and I have not tested this in multiplayer as of yet.

Other mods that add zinc into the modpack are Metallurgy4, BluePower (soon to be removed), and VoltzEngine.

**Comment by Breadabix** [comment]
Im an idiot, I had Unidict in the modpack without even knowing :/

**Comment by Breadabix** [comment]
Im an idiot, I had Unidict in the modpack without even knowing :/

**Comment by MJRLegends** [comment]
Haha ok no problem
