### ISSUE TITLE
Server Crash on second boot after adding ExtraPlanets Mod 0.6.2

### ISSUE THREAD

**Issue by chezpaul** [MJRLegends/ExtraPlanets#137]
Minecraft version: 1.10.2
Galacticraft version: 1.10.2-4.0.0.115
Forge version: 12.18.3.2316

Single player (SSP) or Multiplayer (SMP)? Multiplayer

Mods used: appliedenergistics2-core, ivtoolkit, Micdoodlecore, NotEnoughItems, OpenComputers|Core, , ae2stuff, animania, appliedenergistics2, arsmagica2, AnimationAPI, Baubles, bdlib, bedbugs, BiblioCraft, biomebundle, BiomesOPlenty, bookshelf, Botania, bottledmilk, cfm, Chameleon, ChickenChunks, chisel, CodeChickenCore, CodeChickenLib, ccl-entityhook, cofhcore, PTRModelLib, props, eplus, endercore, EnderIO, EnderStorage, EnderZoo, energyconverters, extrautils2, FinderCompass, fluxnetworks, forestry, microblockcbe, forgemultipartcbe, minecraftmultipartcbe, galacticraftplanets, galacticraftcore, gendustry, geographicraft, GraveStone, hammercore, Waila, immersiveengineering, imc, IC2, ironbackpacks, ironchest, JEI, jeibees, malisiscore, malisisdoors, mantle, mcmultipart, Mekanism, MekanismGenerators, MekanismTools, mercurius_updater, testdummy, Morpheus, MrTJPCoreMod, mysticalagriculture, natura, neid, notenoughwands, OpenComputers, openterraingenerator, p455w0rdslib, getalltheseeds, harvestcraft, plustic, pressure, projectred-core, projectred-integration, projectred-transmission, projectred-illumination, projectred-expansion, projectred-transportation, railcraft, reccomplex, redstonearsenal, roguelike, simplecorn, solarfluxreborn, sonarcore, special_ai, StorageDrawers, tconstruct, thermaldynamics, thermalexpansion, thermalfoundation, Translocator, unidict, wailaplugins, wanionlib, weaponcaseloot, wct, worldcontrol, worldedit, wrcbe, xtones

### ---Issue Report---
NO I haven't read closed issues.

### Description of Issue
If I add Extra Planets to my mudpack, the server will boot fine but will always crash on second boot.

### Steps to Reproduce Issue
1. Add Extra Planets to mod folder
2. Boot server (boots fine)
3. Stop server
4. Boot server
5. Crash

**Crash log/Log (if applicable): [https://pastebin.com/jiKH1v4E](https://pastebin.com/jiKH1v4E)

**Screenshots (if applicable): N/A

**Version of Mod Pack using: Personal Private modpack

**Where did this bug happen: Server

### Additional Information
Running OTG.

**Comment by MJRLegends** [comment]
This crash is due to another mod

[13:06:46] [Server thread/INFO] [OTG]: Creating world "Biome Bundle"
[13:06:46] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NullPointerException
    at com.khorn.terraincontrol.forge.ForgeEngine.unRegisterForgeBiome(ForgeEngine.java:55) ~[ForgeEngine.class:?]

**Comment by MJRLegends** [comment]
terraincontrol the issue mod

**Comment by chezpaul** [comment]
K cool
Thanks.
I've let them know already. I thought it looked like it.
I have one question for you though. Because this wasn't working, I went back to a backup server and client prior to adding Extraplanets. Both boot fine but when I try to login to the server from the client, I get booted out saying I'm missing 5 celestial objects. ( Jupiter, Mercury, Neptune, Saturn and Uranus)
But how can that backup server or client know about Extraplanet objects when it's never had them in it?
