### ISSUE TITLE
[1.7.10, 1.10.2, 1.8.9, 1.11.2, Bug] Fire Bats don't have a fire texture

### ISSUE THREAD

**Issue by MrEyeballs29** [MJRLegends/ExtraPlanets#138]
### ---Issue Report---
**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Of Course

### Description of Issue
This is not the priority issue but the texture is wrong though.

### Steps to Reproduce Issue
1. Spawning a Fire Bat Boss
2. It looks like a normal bat

**Crash log/Log (if applicable):** Not a Crash

**Screenshots (if applicable):** ![Imgur](http://i.imgur.com/VkLimC0.png)

**Version of Mod Pack using:** Extra Planets 1.8.3, Haven't Tested Others

**Where did this bug happen:** Client

### Additional Information
At least it is not a creeper boss no more

**Comment by MJRLegends** [comment]
Does it have red eyes?

**Comment by MJRLegends** [comment]
Im sure its the right texture so im closing this since the only difference is the eyes for now
