### ISSUE TITLE
[1.7.10] Another Boss dropping a wrong key

### ISSUE THREAD

**Issue by MrEyeballs29** [MJRLegends/ExtraPlanets#139]
### Description of Issue
Once again you made another mistake dropping a wrong key 

### Steps to Reproduce Issue
1. kill a jupiter boss
2. the key it dropped was a tier 6 not 5

**Crash log/Log (if applicable):** Not a Crash Again

**Screenshots (if applicable):** ![Imgur](http://i.imgur.com/2B3bYRA.png) At least I have to cheat it in though to get the teir 5 schematic

**Version of Mod Pack using:** Galaxy Wars T0.4.5b that contains 

**Where did this bug happen:** Client Only

### Additional Information
This is a problem, you need to fix it. Otherwise they cannot go further beyond Jupiter. Well   I am also a mod tester to see whether or not your mod has a bug or a crash. I also request features just in case if your mod needs more features.

**Comment by MJRLegends** [comment]
I find your attitude rude in this issue report, People treat people how you want to be treated :P

**Comment by MJRLegends** [comment]
Fixed in v1.8.5 which is uploading on to Curse as we speak :D

**Comment by MrEyeballs29** [comment]
@MJRLegends I wasn't trying to be rude. I am mod tester to see whether or not your mod has a bug or a crash. I also request features just in case if your mod needs more features. Oh by the way what was I rude on and sorry about that. 😞 I will become nice again. 😄

**Comment by MJRLegends** [comment]
"Once again you made another mistake dropping a wrong key" is rude

**Comment by MrEyeballs29** [comment]
Now I am being nice 😉 
> ![image](https://user-images.githubusercontent.com/27930788/29295206-ca198924-8118-11e7-99f6-6189167ec275.png)
