### ISSUE TITLE
Crash after changes in the Config

### ISSUE THREAD

**Issue by Markezzz** [MJRLegends/ExtraPlanets#14]
We wanted to update ExtraPlanets to version 1.0-Pre 3.5.1. But with this version we cant change the config without a crash.

Here are the crash report and our config:
[crash-2016-05-01_23.30.37-client.txt](https://github.com/MJRLegends/ExtraPlanets/files/244356/crash-2016-05-01_23.30.37-client.txt)
[ExtraPlanets.txt](https://github.com/MJRLegends/ExtraPlanets/files/244357/ExtraPlanets.txt)

**Comment by MJRLegends** [comment]
you need to disable the space stations in the config also for the planets you have disabled

**Comment by Markezzz** [comment]
Okay. I'll test it later and give you feedback. :)
Thanks for the fast respond.

**Comment by MJRLegends** [comment]
No problem im 1000% sure thats the issue

**Comment by Markezzz** [comment]
Okay, i checked my config and fixed the spacestations. But I cant deactivate the spacestation for Phobos because their is no option for this. The client crashes in the loading phase.

Here the fixed config and the new crash report:
[ExtraPlanets.txt](https://github.com/MJRLegends/ExtraPlanets/files/244687/ExtraPlanets.txt)
[crash-2016-05-02_09.59.09-client.txt](https://github.com/MJRLegends/ExtraPlanets/files/244689/crash-2016-05-02_09.59.09-client.txt)

**Comment by MJRLegends** [comment]
Disable the Neptune space station because I made a error in the code that when Venus is disabled it will cause the Neptune space station code to crash

**Comment by MJRLegends** [comment]
@Markezzz did my temp fix work?

**Comment by Markezzz** [comment]
I test it now. I wasnt earlier at home. :)

**Comment by MJRLegends** [comment]
Yeah im planning on releasing a update tonight that will contain a fix for this anyways

**Comment by Markezzz** [comment]
The Temp fix works for me on client and server. So I wait for the new update. :)

**Comment by MJRLegends** [comment]
Good yeah it was just a typo

**Comment by MJRLegends** [comment]
Update has been released, give it 5 mins or so and it will be available
