### ISSUE TITLE
[Suggestion] Jupiter

### ISSUE THREAD

**Issue by confol1** [MJRLegends/ExtraPlanets#140]
When you turn on More Planets compatible, you should turn on Jupiter because More Planets doesn't have Jupiter. (Yes More Planets has Jupiter enabled but, that's only for the space station)

**Comment by MJRLegends** [comment]
Maybe it's hard because i would need to turn off loads of stuff to make that happen, i will defo give it some thought though and see what i can do for you

**Comment by confol1** [comment]
Ok! Thxs!

**Comment by MJRLegends** [comment]
Addon compatibility is very hard due to how things like rockets, dungeons etc work, its something im going to re look at for 1.7.10 and 1.8.9 and 1.10.2 and 1.11.2 versions

**Comment by confol1** [comment]
I Understand. I was asking this because I'm playing with more planets but, I want to go to Jupiter and the only way to get there is when more planets compatibility is false and when that happens I can't go to Eris an kepler 22b because they require tier 9/tier 10 rockets and I can't get them with More Planets on! (Only on creative but, I want to do Survival without cheating)

**Comment by MJRLegends** [comment]
Which version are you using as that was fixed in the latest few versions ( the fact you cant do to kepler22b with that config option on

**Comment by confol1** [comment]
1.7.10 (Also when Jupiter's moon's are disabled as well)

**Comment by MJRLegends** [comment]
I meant which version for 1.7.10 are you using?

**Comment by confol1** [comment]
ExtraPlanets 1.8.5

**Comment by confol1** [comment]
Galacticraft build 502 and More Planets 1.4.2

**Comment by MJRLegends** [comment]
Kepler22b should require a tier 7 rocket when you have that options on

**Comment by confol1** [comment]
It does. I was saying when I have it disabled, It requires a tier 10 rocket which I can't get with More Planets On

**Comment by MJRLegends** [comment]
Yeah you need to use the advanced more planets compatibility option to make it I might work with progression

**Comment by confol1** [comment]
Yeah I can get to all planets with the option on. I just can't get to Jupiter and it's moons with the option on.

**Comment by confol1** [comment]
I even have the space station and Jupiter set to false on More Planets

**Comment by MJRLegends** [comment]
yeah its disabled, you dont need to go there to go to the rest of the planets

**Comment by confol1** [comment]
I know but, I want to explore Jupiter and it's moons because I love exploring all the planets and all the moons and this is the only addon that has jupiter.

**Comment by MJRLegends** [comment]
You will have to remove more planets then

**Comment by confol1** [comment]
I really don't want to do that :( I think what you can do is when the more planets compatbility is true, Jupiter is on. I don't think it's that hard. (I don't know, I never created mods.) Also, I have Jupiter set to true on your extraplanets config and More Planets compatibilty on and there is no Jupiter. P.S. I'm sorry if I sound rude.

**Comment by MJRLegends** [comment]
Jupiter is being taken by more planets, i cant really override it easily

**Comment by confol1** [comment]
BTW all the moons for Jupiter are gone too.

**Comment by MJRLegends** [comment]
Yeah all disabled as i said, "Jupiter is being taken by more planets, i cant really override it easily"

**Comment by confol1** [comment]
I have Jupiter disabled on More Planets. P.S. Your comment wasn't on my screen till I typed My moons comment. XD

**Comment by confol1** [comment]
I guess if it can't be fixed then I have to cheat in a tier 9 and tier 10 rocket on survival :(

**Comment by MJRLegends** [comment]
or just use the compatibility options
