### ISSUE TITLE
(I Know you probably don't wanna talk but, I will give you the full Summary and I'm pretty sure it's your mod doing this.)When I have Advanced More Planets Compatibility false and Jupiter False on More Planets, Jupiter and it's moons are working but, when I have Advanced More Planets compatibility true and Jupiter false on More Planets, There isn't Jupiter.

### ISSUE THREAD

**Issue by confol1** [MJRLegends/ExtraPlanets#141]
(I Know you probably don't wanna talk but, I will give you the full Summary and I'm pretty sure it's your mod doing this.) When I have Advanced More Planets Compatibility false and Jupiter False on More Planets, Jupiter and it's moons are working but, when I have Advanced More Planets compatibility true and Jupiter false on More Planets, There isn't Jupiter.

**Comment by MJRLegends** [comment]
Please dont make moee issues

**Comment by MJRLegends** [comment]
*more
