### ISSUE TITLE
Jupiter Dungeons Not Spawning (Space Astronomy 2 Modpack / 0.6.4 Extra Planets)

### ISSUE THREAD

**Issue by vryclct** [MJRLegends/ExtraPlanets#144]
### ---Issue Report---
**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** YES

### Description of Issue
Jupiter Dungeons not spawning

### Steps to Reproduce Issue
1. Go to jupiter
2. Look for dungeon

**Crash log/Log (if applicable):** N/A

**Screenshots (if applicable):** 

**Version of Mod using:** Galacticraft 4 / Extra Planets 0.6.4

**Where did this bug happen:** [Single Player or Server]  FrozenSoul Space Astronomy 2 (Minecraft 1.10.2)

### Additional Information
I attempted to find dungeons on jupiter couldn't find one.  Found someone who told me despite only being in the JEI the dungeon locator can still be used.  So I used it, it took me to where a dungeon should be... it wasn't there.  I dug and cleared the area out with a quarry and it mined about  3 dungeon bricks... there was scattered dungeon bricks either single or in small groups but it looks like the entire dungeon was overridden by world gen.

**Comment by MJRLegends** [comment]
They spawn ok just that world needs resetting
