### ISSUE TITLE
[1.8.9/1.10.2/1.11.2] More Suggestions... Please Read

### ISSUE THREAD

**Issue by CaveMiner1215** [MJRLegends/ExtraPlanets#145]
I have a few more suggestions that you could undertake.  I certainly hope you aren't getting annoyed at my suggestions.  I'm sure you are very busy with the mod as it is, so you don't have to implement these if you don't want...but they would make this addon more realistic.  If you are going to close this issue, please read the suggestions first and tell me what you think of each one.

Here they are:
•As you probably know, from thee view of planetary moons, the host planets appear little larger than a star, when they should appear much closer.  Perhaps you could use similar code as was used for the sky of the Moon in normal Galacticraft.  That way, we would have the host planet no only closer, but also locked in the sky at a certain point, which is also realistic.  You could also use this to get rid of the colored skys of every moon except for Triton and Titan (and perhaps Ganymede), and replace them with a clear stary sky, like the Moon's, which is realistic.
•You also probably know from my previous suggestion post that Titan's surface and sky are not the right color.  The pictures that were taken of titan's surface, showing it to be blue and green, are **false color**.  In reality, Titan's surface and sky should be a pale yellow, as shown in images of Titan's surface and sky taken by the Huygens probe that landed on Titan's surface.  If you would like, I can make new textures for the Titan surface, sub-surface, stone, and ore blocks, as well as for the liquid methane, but it would be up to you to change the sky color.
•A quick suggestion...You could use code similar to Galacticraft 4's Venusian sulfur vents and make Geysers for Triton's (moon of Neptune) surface.  Not a big suggestion, but it would add to the realism.
•Another quick suggestion...Perhaps you could somehow make the liquid methane on Titan's surface usable in the gas liquifier to make rocket fuel.
•I've noticed that the surface blocks for Ganymede, Rhea, and Titan appear tiled.  If you want, I could supply you with new textures for all of the naturally spawning blocks on those moons.

Remember, please read these and let me know of what you think of them before you close the issue.  I would love to help you with this addon, but I am nowhere near the coding mastermind that you are, so I have to find other ways of helping out.  Letting you know what is realistic about the addon and what is not, as well as trying to help you figure out ways to implement things to remove the unrealism, seems like what I'm best at.

**Comment by MJRLegends** [comment]
Im not going for realistic
