### ISSUE TITLE
Mercury skybox in 1.10?

### ISSUE THREAD

**Issue by Trinsdar** [MJRLegends/ExtraPlanets#146]
could you make the sun big in mercury again like it was in 1.7.10?
I am using Extra Planets-0.6.4 and I know it is an older version; I just haven't gotten the chance to load the latest version yet.

**Comment by MJRLegends** [comment]
Yeah im planning on working the sky stuff for all the planets and moon next

**Comment by MJRLegends** [comment]
This will be in the versions that will be out in the next 48 hours
