### ISSUE TITLE
Jupiter Dungeons still not spawning properly

### ISSUE THREAD

**Issue by vryclct** [MJRLegends/ExtraPlanets#147]
Follow up from https://github.com/MJRLegends/ExtraPlanets/issues/144

---Issue Report---

Have you checked Closed Issues: Yup

Description of Issue

Jupiter Dungeons not spawning

**Jupiter was reset** since the last issue was asked and the world reset (I took a long break as did a lot of players that reached jupiter) after jupiter was reset I came back and checked recently... I ran for a few hours... about 10k blocks... never found a dungeon entrance.  Got my builder and dug a straight line for like an hour and a half.   Never found a dungeon... instead I found the **EXACT** same problem I had found when I first asked the issue.   Random dungeoen bricks where a dungeon should be.

Picture is at the bottom... its "random" and scattered dungeon bricks.

Crash log/Log (if applicable): N/A

Screenshots (if applicable):

Version of Mod using: Galacticraft 4 / Extra Planets 0.6.6

Where did this bug happen: [Single Player or Server] FrozenSoul Space Astronomy 2.7 (Minecraft 1.10.2)

![2017-09-03_00 37 30](https://user-images.githubusercontent.com/31329784/30001669-f64c1552-9040-11e7-87a8-4ab48b788ba0.png)

**Comment by MJRLegends** [comment]
Its fixed it the world on the server thats the issue

**Comment by vryclct** [comment]
How does one fix that?  The world was completely deleted and regenerated.

**Comment by MJRLegends** [comment]
I will speak to them

**Comment by MJRLegends** [comment]
Ok, i've personally been on the servers and they do spawn, i have talked to the Frozen Soul owner on it, you might see some changes from them on it but they do spawn.
