### ISSUE TITLE
[1.10.2] Deconstructor destroys rockets 

### ISSUE THREAD

**Issue by SamDaywalker** [MJRLegends/ExtraPlanets#152]
### ---Issue Report---
**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING): YES

### Description of Issue
The deconstructor "eats" any standard GC rocket without giving back anything, other GC blocks or items work correctly. This seems to be not intended, as for extra planets' rockets the deconstructor is working properly.

### Steps to Reproduce Issue
Craft any Tier 1 - 3 GC rocket and put into deconstructor

Minecraft version: 1.10.2
Galacticraft version: 4.0.0.117
ExtraPlanets version 0.7.0
Forge version: 12.18.3.2254

**Where did this bug happen: SSP, SMP

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Since my rockets work this is a Galacticraft related issue

**Comment by MJRLegends** [comment]
Thanks for the bug report though
