### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by steenooo** [MJRLegends/ExtraPlanets#156]
### ---Issue Report---
**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue
[Description of the issue]
When i launch the game, it'll crash due an ClassNotFoundException
### Steps to Reproduce Issue
1. [First step] Start the game
**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
https://pastebin.com/QaY6x8aK
**Screenshots (if applicable):** 
nope
**Version of Mod using:** [VERSION]
1.10.2
**Where did this bug happen:** [Single Player or Server]
On startup
### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Your Galacticraft is very out of date please update
