### ISSUE TITLE
[1.10.2] "Ceres Uranium ore" appears not to be generating on Ceres.

### ISSUE THREAD

**Issue by TeetoKaziim** [MJRLegends/ExtraPlanets#158]
### ---Issue Report---
**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

### Description of Issue
Ceres Uranium Ore is nowhere to be found.

Huge amounts of mining, 10's of thousands of blocks mined, at all Y levels on Ceres, have yielded no Uranium ores. 

Maybe there's something I don't know about how Uranium generates. But a lot of flying around has revealed no surface features that would hint at Uranium, digging under radioactive water pools has gotten me no uranium.

### Steps to Reproduce Issue
1. Get To Ceres.
2. Look For Uranium.

**Screenshots (if applicable):** 
Pictured here is the outer walls of a 6x6 chunk gouge I tore out of the planet with the "Worldstripper" mod. Not a single uranium ore is visible, but the other Ceres Ores are.
![2017-10-19_16 08 55](https://user-images.githubusercontent.com/25490944/31794404-df61a7aa-b4e7-11e7-9bd0-2aa20c7439c7.png)
![2017-10-19_16 09 46](https://user-images.githubusercontent.com/25490944/31794453-fd047cd8-b4e7-11e7-92a0-2cda937cbac9.png)

**Version of Mod using:** [VERSION]
ExtraPlanets-0.7.3
MicdoodleCore-1.10.2-4.0.0.118
Galacticraft-Planets-1.10.2-4.0.0.118
GalacticraftCore-1.10.2-4.0.0.118
**Where did this bug happen:** In Single Player and on a Server

### Additional Information
I'm not super sure. Thanks for your time and consideration in any case.

**Comment by MJRLegends** [comment]
Update will be out within the next hour for this, thanks for the bug report

**Comment by MJRLegends** [comment]
Versions are rolling out, they should show soon
