### ISSUE TITLE
Crash: NullPointerException during startup, not urgent

### ISSUE THREAD

**Issue by zetti68** [MJRLegends/ExtraPlanets#159]
### ---Issue Report---
**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]
And I checked sources

### Description of Issue
We have a server with a lot of mods, includes a few Galacticraft addons (not only ExtraPlanets).
MC: 1.7.10
Forge: 10.13.4.1614
GC: 3.0.12.502
ExtraPlanets: 1.8.7 

I get a NullPointerException during init in class ExtraPlanets_Planets in line 205
Reason: makemake is null

My workaround: I checked the source code and disabled makemake in config.

Reason of crash in class _ExtraPlanets_Planets_

Current code without brackets:

```
  if (makemake != null)
    makemake.setRingColorRGB(...);
  makemake.setBodyIcon(...);

```
should be:

```
  if (makemake != null) {
    makemake.setRingColorRGB(...);
    makemake.setBodyIcon(...);
  }

```

(and at all other places in this class)

### Steps to Reproduce Issue
I hope, not necessary.

1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

**Screenshots (if applicable):** 

**Version of Mod using:** [MC 1.7.10, 1.8.7]

**Where did this bug happen:** [both]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Lol 
  
```
if (makemake != null)
    makemake.setRingColorRGB(...);
  makemake.setBodyIcon(...);

should be:

  if (makemake != null) {
    makemake.setRingColorRGB(...);
    makemake.setBodyIcon(...);
  }

```

isnt going to cause a crash haha

Please post the crash log and i will reopen it

**Comment by MJRLegends** [comment]
You probably havent configured the addons to work together

**Comment by zetti68** [comment]
Sorry I didn't understand your answer. It is a potential NullPointerException in source.
Your line: you check, if makemake is not null and skip only one line (without brackets). But in the second line you will call a function at a null-instance?!

Change it or not, but the bug exists.

**Comment by MJRLegends** [comment]
You need to edit configs to turn planets off
