### ISSUE TITLE
Crash with active Micro Blocks Support

### ISSUE THREAD

**Issue by Markezzz** [MJRLegends/ExtraPlanets#16]
Hello again :>

with the new update we get a crash at the loading phase. the client starts normal if we deactivate the mico blocks support.

Here the config and the crash log:
[ExtraPlanets.txt](https://github.com/MJRLegends/ExtraPlanets/files/247551/ExtraPlanets.txt)
[crash-2016-05-03_10.51.47-client.txt](https://github.com/MJRLegends/ExtraPlanets/files/247552/crash-2016-05-03_10.51.47-client.txt)

**Comment by MJRLegends** [comment]
Update v1.0 Pre-3.6.1 has been released, please give it a short while for curse to do its processing and that and then it will be available

**Comment by Markezzz** [comment]
Looks good! Thanks for the fast fix. :)

**Comment by MJRLegends** [comment]
No problem, im releasing another update in a min again to fix a issue that has just been posted
