### ISSUE TITLE
I can't get in any rocket

### ISSUE THREAD

**Issue by Chuck240607** [MJRLegends/ExtraPlanets#160]
I really like this add-on, but if I try to get in a rocket, it breaks every time.

**Comment by MJRLegends** [comment]
Does Galacticraft rockets work?

**Comment by Chuck240607** [comment]
no

**Comment by MJRLegends** [comment]
Please report this on the Galacticraft issue tracker with more detail than it doesnt work

**Comment by Chuck240607** [comment]
ok

**Comment by Chuck240607** [comment]
galactic raft rocket do work
