### ISSUE TITLE
"Use NearestAttackableTargetGoal.class for PathfinerMob mobs !"

### ISSUE THREAD

**Issue by HarryPOPO** [MJRLegends/ExtraPlanets#162]
### ---Issue Report---
**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

### Description of Issue
Hi, I contact you because I have a problem with Extra Planets mod on my server (see the log). Is there any solution ? (I think this bug has a link with Mo' Creature).

### Steps to Reproduce Issue
1. Use FML server [forge-1.10.2-12.18.3.2511-universal.jar]
2. Put Extra Planets and Mo' Creatures in the mods folder
3. Start the server

**Crash log/Log (if applicable):**

/

**Screenshots (if applicable):** 
![capture](https://user-images.githubusercontent.com/33255322/32223902-922cc508-be3f-11e7-98ac-80b5cbf6367c.PNG)
**Version of Mod using:** [V0.7.6]

**Where did this bug happen:** [Server]

### Additional Information

/

**Comment by MJRLegends** [comment]
Thanks for the bug report but, How do you know this error is talking about ExtraPlanets, not mo creatures or Galacticraft?

**Comment by HarryPOPO** [comment]
Mo' Creature work properly with galacticraft. This bug only occurs when I add Extra Planets. But he can come from Mo' Creature :/ ...

**Comment by HarryPOPO** [comment]
No, ExtraPlanets work properly with galacticraft, the bug occurs with Mo' Creature.

**Comment by MJRLegends** [comment]
Ok i think i can fix it

**Comment by HarryPOPO** [comment]
Ok, keep me up to date.

**Comment by MJRLegends** [comment]
But its no issue, its just a bit of messages showing up like for warning. stuff will still work fine

**Comment by HarryPOPO** [comment]
Yes, but this message spam the console ... xD

**Comment by MJRLegends** [comment]
Update will be out later or tomorrow :D Doing some more work on cleaning up some code and optimizing code

**Comment by HarryPOPO** [comment]
Ok, thank you for your responsiveness !

**Comment by MJRLegends** [comment]
Sorry for the delay, updates are rolling out currently
