### ISSUE TITLE
[1.7+] Color wood from kepler22b only has certain uses

### ISSUE THREAD

**Issue by rockclimber36** [MJRLegends/ExtraPlanets#163]
### ---Issue Report---
**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
yes
### Description of Issue
[Description of the issue]
When trying to craft with kepler22b wood it doesnt allow you to craft most things. such as crafting table for one.
### Steps to Reproduce Issue
1. try to craft something with kepler22b wood.
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

**Screenshots (if applicable):** 

**Version of Mod using:** [VERSION]
0.3.8

**Where did this bug happen:** [Single Player or Server]
Server

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Yeah its intended to only have certain cracting recipes

**Comment by rockclimber36** [comment]
Oh okay. May I ask why?

**Comment by MJRLegends** [comment]
Im reopening this as its something i want to change :P

**Comment by MJRLegends** [comment]
Changes for this have been released for MC 1.8.9, MC 1.10.2, MC 1.11.2, MC 1.12.2 version, MC 1.7.10 will be soon

**Comment by MJRLegends** [comment]
1.7 Update will be coming out very soon

**Comment by MJRLegends** [comment]
Update is rolling out now
