### ISSUE TITLE
Terrain generation topography is too similar for many planets/moons

### ISSUE THREAD

**Issue by donqixot** [MJRLegends/ExtraPlanets#164]
### ---Issue Report---
**Have you checked Closed Issues:** [Yes]

### Description of Issue
Many moons (Dim-35 and up I think) have same terrain topography, only different blocks. Same mountains, ravine, even caves seem the same. If you have been on one of them, you can easy navigate in another. This is probably because terrain generator using same world type and seed. Would it be possible to dynamically change seed for different dimensions so they are different?

### Steps to Reproduce Issue
1. Go to Deimos, check topography.
2. Go to Ganymede, compare topography.

**Screenshots (if applicable):** will attach shortly

**Version of Mod using:** [0.4.2]

**Where did this bug happen:** [Single Player]

### Additional Information
MC version 1.11.2, forge 13.20.1.2530

**Comment by MJRLegends** [comment]
Work on adding more biomes to planets and moons are being worked on and will take time

**Comment by donqixot** [comment]
I was hoping for simple fix where seed is different for different dimensions.
