### ISSUE TITLE
[1.11.2] NullPointerException: Exception generating new chunk

### ISSUE THREAD

**Issue by donqixot** [MJRLegends/ExtraPlanets#165]
### ---Issue Report---
**Have you checked Closed Issues:** [Yes]

### Description of Issue
Hopping between planets in creative, went to Keppler 22b, all good at first, flying to the north to unexplored chunks, crash.

### Steps to Reproduce Issue
1. Go to Keppler22b
2. Explore

**Crash log/Log:** https://pastebin.com/D0aVCvkG

**Version of Mod using:** [0.4.2]

**Where did this bug happen:** [Single Player]

### Additional Information
MC Version - 1.11.2, Forge 13.20.1.2530, Galacticraft version 1.11.2-4.0.0.118. Biome'O'Plenty version 1.11.2-6.2.0.2267.

**Comment by MJRLegends** [comment]
Will take a look later, i think i know the issue

**Comment by MJRLegends** [comment]
Please can you provide a copy of your ExtraPlanets config, and please post your fml-server-latest.log fml-client-latest.log and latest.log

**Comment by MJRLegends** [comment]
Also was the whole dimension ocean biome for you?

**Comment by MJRLegends** [comment]
@donqixot Ignore the messages that were here and have now been deleted, i can reproduce the issue but only with this seed it seems, something is messed up due to what the game is trying to generate. im going to look in to what the issue is now

**Comment by donqixot** [comment]
Thanks!

**Comment by MJRLegends** [comment]
Please can you create a new world with a different seed and test @donqixot

**Comment by donqixot** [comment]
Sure, I also see new version now, will try it both. Close for now, if I see it again, will reopen or open a new one, thank you very much!!!

**Comment by MJRLegends** [comment]
Ok as i think your seed was just a broke mc one as they do exist

**Comment by donqixot** [comment]
Ok, thanks!
