### ISSUE TITLE
Problem with Galaxyspace + ExtraPlanets

### ISSUE THREAD

**Issue by Frafx** [MJRLegends/ExtraPlanets#166]
### ---Issue Report---
Can't launch my rocket to some planets and missing satellites.

### Description of Issue
I can't launch my rocket to planets; Jupiter,satur,uranus,neptune,eirs.
And there are no satellites on these planets

### Steps to Reproduce Issue
1) install galacticraft,micdodlecore,extra planets and gaklaxy space mod 
Go to config of extraplanets and set true to compatibily with galaxy space

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

**Screenshots (if applicable):** 
![image](https://user-images.githubusercontent.com/33761655/32966738-1c41cb46-cbdb-11e7-8584-af7b2f8870ff.png)

**Version of Mod using:** [VERSION]
galaxy space: 1.1.7
Extra planets: last of 1.7.10

**Where did this bug happen:** [Single Player or Server]
SinglePlayer

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
This is a galaxy space issue i would say

**Comment by Frafx** [comment]
So i must write the issue to GalaxySpace forum?

**Comment by MJRLegends** [comment]
no i will take a look later and get back to you, but you really need to be using latest GalaxySpace

**Comment by Frafx** [comment]
Alright i try

**Comment by MJRLegends** [comment]
Yeah this is a galaxy space issue
