### ISSUE TITLE
GalactiCraft map crash

### ISSUE THREAD

**Issue by Frafx** [MJRLegends/ExtraPlanets#167]
### ---Issue Report---
Crash when i open galacticraft map

https://pastebin.com/z5rBbNXK

**Version of Mod using:** [VERSION]
ExtraPlanets last of 1.7.10
GalaxySpace 1.19 last in 1.7.10

**Where did this bug happen:** [Single Player or Server]
 SinglePlayer

**Comment by MJRLegends** [comment]
This is GalaxySpace nothing to do with me, please see the crash log before posting as it says nothing to do with ExtraPlanets
