### ISSUE TITLE
[1.10.2] Server crashed upon generating Mercury and now crashes when attempting to load Mercury

### ISSUE THREAD

**Issue by Kaltonase** [MJRLegends/ExtraPlanets#168]
### ---Issue Report---
**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

### Description of Issue
When Mercury was visited for the first time the server shut down as it was being generated. since then any player that attempts to visit Mercury will crash the server as it tries to load Mercury.

### Steps to Reproduce Issue
1. Start game
2. try to visit Mercury

**Crash log/Log (if applicable): https://pastebin.com/sFkyi7pU

**Version of Mod using: 1.10.2

**Where did this bug happen: Server

### Additional Information
This is using the Space Astronomy 2 modpack, originally had this same problem on Venus but updating the Galacticraft related mods to release 119 fixed the problem

**Comment by MJRLegends** [comment]
Yeah, downgrade you shouldnt be updating stuff for packs unless you own them.

And yeah the latest builds say to use GC build 117

**Comment by MJRLegends** [comment]
Or build 118
