### ISSUE TITLE
Extra Planets 0.8.1 causes crash with Ender Zoo

### ISSUE THREAD

**Issue by BrisingrAerowing** [MJRLegends/ExtraPlanets#169]
### ---Issue Report---
**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

### Description of Issue
Extra Planets 0.8.1 for 1.10.2 causes Ender Zoo (and possibly other mods) to crash

### Steps to Reproduce Issue
1. Install Extra Planets 0.8.1 and dependencies alongside Ender Zoo
2. Try to run MC

**Crash log/Log (if applicable):** [Crash Log](https://gist.github.com/BrisingrAerowing/7533209c913a45f884acb6f2fe5dd01a)

**Screenshots (if applicable):** 

**Version of Mod using:** 0.8.1 for 1.10.2

**Where did this bug happen:** Single Player

### Additional Information
Nothing that I could find.

**Comment by BrisingrAerowing** [comment]
I just saw that 0.8.2 is out. I'll test with that.

**Comment by BrisingrAerowing** [comment]
This is caused by you returning an Immutable List in the getSpawnableList method for custom biomes. Forge does NOT like that, as it doesn't check (and I don't know if it can check).

**Comment by MJRLegends** [comment]
Your crash shows that you didn't install ender zoo corrrctly as your missing its core mod

**Comment by MJRLegends** [comment]
Please test with just the needed mods as you have to many there that could be the cause

**Comment by MJRLegends** [comment]
Ender zoo is the problem mod, the way ive done it is how forge/mojangs code is

**Comment by BrisingrAerowing** [comment]
[New Crash Report](https://gist.github.com/BrisingrAerowing/b8a30dd70609378c5a2ef8f2ee8e1a98)

And it is your mod. Removing it allows MC to load perfectly fine.

**Comment by MJRLegends** [comment]
I fine your messages very rude, im trying to help you here dont work against that

**Comment by BrisingrAerowing** [comment]
And the crash actually occurs on [this line in Forge](https://github.com/MinecraftForge/MinecraftForge/blob/1.10.x/src/main/java/net/minecraftforge/fml/common/registry/EntityRegistry.java#L259) where it tried to add something to the list.

**Comment by BrisingrAerowing** [comment]
According to Java's Documentation Collections.emptyList

> Returns the empty list (immutable). This list is serializable.

**Comment by BrisingrAerowing** [comment]
I give up with this. I am removing this mod.

**Comment by MJRLegends** [comment]
You cant expect someone to fix it within seconds. That's fine by me

**Comment by MJRLegends** [comment]
Fixed versions are on curseforge they will show onxe they are aboved.

But please in future when you report any issues to people making comments that are just plain rude then removing them is just not going to get your issue your reporting helped. People are there to help you when you report issues dont insult them

**Comment by MJRLegends** [comment]
They are now approved too, problem solved :)

**Comment by MJRLegends** [comment]
@BrisingrAerowing please take 5 mins to read above
