### ISSUE TITLE
missing textures

### ISSUE THREAD

**Issue by Cronosus** [MJRLegends/ExtraPlanets#17]
Eris Stone Bricks and Uranus Stone Bricks missing textures
![2016-05-03_22 26 15](https://cloud.githubusercontent.com/assets/5349950/14997302/61af504a-117e-11e6-9c0f-6c99ba37780f.png)

maybe other Stone Bricks too,as you know i have only some planets.. :)

**Comment by MJRLegends** [comment]
Fixing now and will have another update out in the next 5 mins, its weird because eclipse still finds them even though there wrong so this is why errors like this happen as eclipse seems to just ignore uppercase/lowercase in the dev environment

**Comment by MJRLegends** [comment]
Update v1.0 Pre-3.6.2 has been released, please give it a short while for curse/curseforge to do its processing and that and then it will be available
