### ISSUE TITLE
Kepler22b

### ISSUE THREAD

**Issue by Frafx** [MJRLegends/ExtraPlanets#170]
when you click to see blocks of cobblestone chisel the block is the land of kepler22b dirt

### Steps to Reproduce Issue
1. take the cobblestone
2. chisel the cobblestone

**Screenshots (if applicable):** 
![image](https://user-images.githubusercontent.com/33761655/33375746-37cff944-d50b-11e7-8252-1005f564fcab.png)

**Version of Mod using:** 
lastest

**Where did this bug happen:** [Single Player or Server]
sigleplayer

I think you put the cobblestone in the dirt oredict

**Comment by MJRLegends** [comment]
See issue #54, i will close this but will look at it for the next update
