### ISSUE TITLE
[1.7.10] Missing textures

### ISSUE THREAD

**Issue by SuumCW** [MJRLegends/ExtraPlanets#172]
### Description of Issue
On every planet of extra planets are the false blocks

### Steps to Reproduce Issue
1. dimensiontp to any planet of extra planets

**Screenshots** https://cdn.discordapp.com/attachments/382616810769350657/385944565556707329/unknown.png https://cdn.discordapp.com/attachments/382616810769350657/385945309248749568/unknown.png https://cdn.discordapp.com/attachments/382616810769350657/385945924574380032/unknown.png (the last picture is keppler 22b)

**Version of Mod using:** 1.8.8 (1.7.10)

**Where did this bug happen:** Server

**Comment by MJRLegends** [comment]
There not fale blocks there fluid without a texture lol

**Comment by MJRLegends** [comment]
*false

**Comment by SuumCW** [comment]
keppler 22b is like venus

**Comment by SuumCW** [comment]
https://cdn.discordapp.com/attachments/382616810769350657/385945924574380032/unknown.png

**Comment by SuumCW** [comment]
thats kepler 22b

**Comment by SuumCW** [comment]
https://cdn.discordapp.com/attachments/382616810769350657/385947632717004800/unknown.png thats pluto

**Comment by MJRLegends** [comment]
Yeah they are fluids as i said lol

**Comment by SuumCW** [comment]
Mars changed to kepler22b

**Comment by SuumCW** [comment]
https://cdn.discordapp.com/attachments/382616810769350657/385948297866641408/unknown.png mars changed to kepler22b

**Comment by MJRLegends** [comment]
This issue is messy please make different issues for each type of issue

**Comment by MJRLegends** [comment]
You can make new ones thats ok with me

**Comment by SuumCW** [comment]
ok

**Comment by MJRLegends** [comment]
@SuumCW v1.8.8 is out that fixes all these texture issues, just uploaded it to curseforge so give it a few mins to get approved :D sorry for the delay on the version
