### ISSUE TITLE
Mars using kepler22b surface

### ISSUE THREAD

**Issue by SuumCW** [MJRLegends/ExtraPlanets#173]
### Description of Issue
Mars generates kepler22b surface

### Steps to Reproduce Issue
1. Dimensiontp to mars

**Screenshots (if applicable):**  https://cdn.discordapp.com/attachments/382616810769350657/385948297866641408/unknown.png

**Version of Mod using:** 1.8.8 (1.7.10)

**Where did this bug happen:** Server

### Additional Information
[Any other information that may be able to help me with the problem]
It could be a problem because I deleted my entire config

**Comment by MJRLegends** [comment]
I think you have biome conflicts this isnt a ExtraPlanets thing

**Comment by SuumCW** [comment]
Should I delete the world and look if it works?

**Comment by MJRLegends** [comment]
Try with just gc and ExtraPlanets

**Comment by SuumCW** [comment]
doesn't work https://cdn.discordapp.com/attachments/382616810769350657/385953947539472384/unknown.png

**Comment by MJRLegends** [comment]
with new world?

**Comment by MJRLegends** [comment]
and delete all configs for gc and ExtraPlanets

**Comment by SuumCW** [comment]
and amunra too?

**Comment by MJRLegends** [comment]
no test with just gc and ExtraPlanets as i said above

**Comment by SuumCW** [comment]
still not working

**Comment by SuumCW** [comment]
I go to sleep now I will work on the problem tomorrow

**Comment by SuumCW** [comment]
So back how can I fix it?

**Comment by MJRLegends** [comment]
![2017-12-01_14 39 41](https://user-images.githubusercontent.com/8526321/33487765-3c61e174-d6a6-11e7-986c-b8b8d883fbd1.png)
![2017-12-01_14 51 53](https://user-images.githubusercontent.com/8526321/33488017-3432a5f0-d6a7-11e7-90a5-b4acc70b8e0b.png)
Seems all good to me, something is changed or messed up on yourside sorry i cant help with that
