### ISSUE TITLE
Suggestion and question - Mars moons

### ISSUE THREAD

**Issue by spylor** [MJRLegends/ExtraPlanets#174]
I went to the Mars moons and found... nothing special...
I thinks it could be nice if one moon contained cheese ore in a little higher quantities than the overworld moon, let's say make it still a rare find but make the pockets a little bigger or something and the other moon could have Lead ore now and then. It's just not so rewarding to find just Tin, Copper and Iron.
This is just an idea, I don't think it would disrupt the progression. Maybe you could also add some packed ice on the mountain peaks or so, but this will probably be harder to code in. 

Oh, and what are fossils good for? :-)

**Comment by MJRLegends** [comment]
Mars is Galacticraft not ExtraPlanets

**Comment by MJRLegends** [comment]
But for the moons of mars content for them will be coming soon

**Comment by MJRLegends** [comment]
Fossils can be broken for a source of bone meal. They will have more use in future

**Comment by spylor** [comment]
Ah I must have silk touched them. I tried to break them in the crafting menu, but that didn't work. :-)
Thanks for the answer. (I was ofc talking about Mars moons, not Mars as such.)

**Comment by MJRLegends** [comment]
Sorry for the slow reply, but No problem, if you got any more suggestions feel free to send them over :D
