### ISSUE TITLE
translating questions

### ISSUE THREAD

**Issue by SpongebobFan123** [MJRLegends/ExtraPlanets#176]
I just got started with making the Korean .lang file, and I have some questions:

should I tag the file to an issue or if not, how should I send the file?
do I get to have my name up on the change log when this goes up? (cuz that would be AWESOME)

btw can you add some advice that I should  take in mind just in case?

**Comment by MJRLegends** [comment]
All can be found here https://github.com/MJRLegends/ExtraPlanets/blob/master/README.md

And yes it will say you did it in the change log
