### ISSUE TITLE
[1.11.2] Error with BasicCrystallizer

### ISSUE THREAD

**Issue by MUHAKLorTheDorfTrottel4Github** [MJRLegends/ExtraPlanets#179]
Mc version : 1.11.2
forge-1.11.2-13.20.1.2563
ExtraPlanets-0.4.8.jar
MicdoodleCore-1.11.2-4.0.0.119.jar
Galacticraft-Planets-1.11.2-4.0.0.119.jar
Galacticraft-Planets-1.11.2-4.0.0.119.jar

Playing SURVIVAL , no cheat at all 

Once you place BasicCrystallizer , the game crash, as well on restart,
world unloadable ( need to load backup )

Crash log: https://pastebin.com/eBn5gYcS

until this everything was ok ( crafting rockets, went to mercur, ceres, etc )

Is there an other way to get rid of tschernobil.effect as using Anti-Rad

regards

**Comment by MrEyeballs29** [comment]
Are you using a template that @MJRLegends provided for you.

**Comment by MJRLegends** [comment]
Its fine the provided information is shown here, just logs should be in a pastebin @MrEyeballs29  Thanks tho

**Comment by MJRLegends** [comment]
@MUHAKLorTheDorfTrottel4Github Did you just place it down or did you have any automation hooked up to it?

**Comment by MUHAKLorTheDorfTrottel4Github** [comment]
It was ok to craft it 
the crash occurs if you want to place it somewhere

if i find some time, i'll test it on a new flat-world without any other mods
My guess is that it has something to do with MEKANISM crystalizer
regards

**Comment by MJRLegends** [comment]
@MUHAKLorTheDorfTrottel4Github Does it crash in a new world?

**Comment by MJRLegends** [comment]
Dont worry this seems to be a bug, i will get it fixed up :D

**Comment by MJRLegends** [comment]
I found a few other issues with my machines that are only in MC 1.11.2 so i've fixed them too, sorry for the delay. A version should be out within the next few days

**Comment by MJRLegends** [comment]
v0.4.9 has been released this will fix your issue :D sorry for the wait
