### ISSUE TITLE
[1.7.10]Tier 4 and 5 Rockets, Mars Rover and Venus Rover Names

### ISSUE THREAD

**Issue by janagyjr** [MJRLegends/ExtraPlanets#180]
### ---Issue Report---
**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes

### Description of Issue
Tier 4 & 5 rocket, Mars and Venus rover don't have proper names.

### Steps to Reproduce Issue
1. Unlock schematic
2. view in NASA workbench

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

**Screenshots (if applicable):** 
![2017-12-11_17 03 02](https://user-images.githubusercontent.com/23646259/33858663-21ca65dc-de96-11e7-87bf-822acfb716b6.png)
![2017-12-11_17 03 04](https://user-images.githubusercontent.com/23646259/33858664-21de8d00-de96-11e7-9c0e-a305944bfc8a.png)
![2017-12-11_17 03 06](https://user-images.githubusercontent.com/23646259/33858665-21f276a8-de96-11e7-81bf-17182e5fc1ba.png)
![2017-12-11_17 03 09](https://user-images.githubusercontent.com/23646259/33858666-22081e5e-de96-11e7-95a0-718ab27c7caa.png)

**Version of Mod using:** [VERSION]
Minecraft 1.7.10
Forge 1614
ExtraPlanets 1.8.9

**Where did this bug happen:** [Single Player or Server]
Server, hadn't checked sp yet.

**Comment by MJRLegends** [comment]
Thanks, update will be out probably by the end of the week as got a lot to do with the 1.7.10 version

**Comment by janagyjr** [comment]
I also encountered this, everything is the same as above.

![image](https://user-images.githubusercontent.com/23646259/33864465-5954a096-deb2-11e7-97c9-4fff7284c1e9.png)

The other achieves may be the same.

**Comment by MJRLegends** [comment]
Yeah I've already fixed that one

**Comment by MJRLegends** [comment]
Change of plan, the update is coming out now, please wait 5 mins and it will be on curseforge

**Comment by MJRLegends** [comment]
@janagyjr also for forgot to say the 1.7.10 version is getting a major revamp to match 1.8+ versions so changes like this can sometimes cause small bugs. So any more after using the new v1.8.0 please let me know
