### ISSUE TITLE
[1.7+] Certain Recipes becoming invalid/missing on certain config option disabling

### ISSUE THREAD

**Issue by waitLH** [MJRLegends/ExtraPlanets#181]
![gc2](https://user-images.githubusercontent.com/23034672/33989084-3d6e4296-e101-11e7-8129-c0f2f930d6b7.png)
### ---Issue Report---
**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):No

### Description of Issue
No tier 9 Rocket and others tier 9 item like NASA schematic and heavy-duty plate
And tier 10 heavy-duty plate recipes change to a fire and a compressed dark iron plate

### Steps to Reproduce Issue
1. Install galacticraft , extra planets and galaxyspace
2. Set config: B:"Enable Basic Galaxy Space Compatibility" to true 

**Screenshots (if applicable):** 
![gc](https://user-images.githubusercontent.com/23034672/33989076-39e2b922-e101-11e7-9982-02193297dd06.png)
![gc2](https://user-images.githubusercontent.com/23034672/33989127-593155ae-e101-11e7-96c7-0e6e582446e8.png)

**Where did this bug happen:**

### Additional Information
Maybe the support to galaxy space what will disable extra planet's tier 9 planet and others tier 9 item,because this won't happen when only galacticraft and extra planets

**Comment by waitLH** [comment]
minecraft version is 1.7.10 , forge 10.13.4.1614

**Comment by waitLH** [comment]
Tier 4 rocket and others item has the same issue

**Comment by MJRLegends** [comment]
This is intentional

**Comment by MJRLegends** [comment]
This is something i wanted to look at try and fix so im going to reopen this

**Comment by MJRLegends** [comment]
Changes for this have been released for MC 1.8.9, MC 1.10.2, MC 1.11.2, MC 1.12.2 version, MC 1.7.10 will be soon
