### ISSUE TITLE
1.11.2 / 0.4.9 missing fluid after update

### ISSUE THREAD

**Issue by MUHAKLorTheDorfTrottel4Github** [MJRLegends/ExtraPlanets#182]
mc 1.11.2
forge 2563
ExtraPlanets-0.4.9.jar

after changing to 0.4.9 the fluid crystallized water "disappeared" in world/dimension like mercury.

tried to fall back to 0.4.8 , but it was impossible due to somewhow dimension ID conflict
( missing dimension id 15 to 40)

i continue to cheat-in the anti-rad

if you want to force me to fill out the -form- ,  just delete the issue, 
and i will forget about the mod.
i'm always open for serious questions 

regards

**Comment by MJRLegends** [comment]
That fluid is found on Ceres not mercury and it seems you maybe have a messed up config file too

**Comment by MJRLegends** [comment]
Nothing changed with the fluids in v0.4.9

**Comment by MJRLegends** [comment]
Delete your config and try again

**Comment by MJRLegends** [comment]
Im going to close this as i dont see a mod related issue here, if you can reproduce this on a new world with a newly generated config please repost using the template
