### ISSUE TITLE
[1.8+] Space Suit model doesnt render on vanilla armor stand

### ISSUE THREAD

**Issue by MUHAKLorTheDorfTrottel4Github** [MJRLegends/ExtraPlanets#183]
mc 1.11.2 
extraplanets 0.4.8 and 0.4.9 
Tier Armor ( space suit) is not visible on vanilla armor-stand
- you can place it 
- you can take it
- it's there
- you just can not see it 

regards

**Comment by MJRLegends** [comment]
Thanks for the suggestion, this isnt a bug just lack of a feature also please use the template in your future posts theres no reason to not use it

**Comment by MJRLegends** [comment]
I'll add this to the todo list as a small change

**Comment by MJRLegends** [comment]
Seems like this just got fixed by or another comment https://github.com/MJRLegends/ExtraPlanets/commit/db1624b31d0f272bbe99d296a644c096a2285915 Please use the latest versions that just came out
