### ISSUE TITLE
how to get "clean water"

### ISSUE THREAD

**Issue by MUHAKLorTheDorfTrottel4Github** [MJRLegends/ExtraPlanets#185]
1.11.2 , 0.4.9 
jei_1.11.2-4.5.1.296.jar
as there is NO wiki at all
please inform 
how to get clean water,
- which item is used in "Basic Purifier" as filter 
- message : missing items ---------> isn't  very helpful
- message : press R to see how to obtain  ---------> isn't  very helpful
regards

**Comment by MJRLegends** [comment]
Please join my discord link is on my mod packs description and we will help you out
