### ISSUE TITLE
[1.7.10] Texture Bug when in galaxy map

### ISSUE THREAD

**Issue by SuumCW** [MJRLegends/ExtraPlanets#186]
---Issue Report---

Description of Issue
Screen Bug
 
Steps to Reproduce Issue
1. /dimensiontp or flying with a rocket

**Screenshots (if applicable): https://cdn.discordapp.com/attachments/251450421623652352/393856024580456448/unknown.png

Version of Mod using:** 1.9.1 (1.7.10)

Where did this bug happen: Server

**Comment by MJRLegends** [comment]
See #184

**Comment by SuumCW** [comment]
How to fix it?

**Comment by MJRLegends** [comment]
You need to change youe dimension ids if they have conflicts

**Comment by SuumCW** [comment]
How do I know if they have conflicts

**Comment by MJRLegends** [comment]
Read in your logs/console, i cant fix them for you. Thats why mods have configs to change stuff to work together. You can just through mods in a folder

**Comment by SuumCW** [comment]
ok

**Comment by MJRLegends** [comment]
Dont worry im stupid, its a bug

**Comment by MJRLegends** [comment]
Sorry for my earlier comments being wrong but Fix will be out within the next hour

**Comment by MJRLegends** [comment]
a new version has been uploaded, it will be downloadable once curse staff approve it

**Comment by MJRLegends** [comment]
You can download it here in till its approved on curseforge http://ci.mjrlegends.com:8080/job/ExtraPlanets%20-%20MC%201.7.10/lastSuccessfulBuild/artifact/build/libs/ExtraPlanets-1.9.2.jar

**Comment by MJRLegends** [comment]
I appreciate the bug report though feel free to post anymore you find

**Comment by SuumCW** [comment]
ok thank you
