### ISSUE TITLE
[1.7.10] Possible world generation issues

### ISSUE THREAD

**Issue by Breadabix** [MJRLegends/ExtraPlanets#187]
In the latest 1.7.10 version the titan methane seas have gravel and neptune sub-surface rock in, instead of Titan gravel and sub-surface rock. For all I know it might be intentional, but I wouldnt think so.

![2017-12-22_20 33 20](https://user-images.githubusercontent.com/19786108/34311778-88b7cd92-e757-11e7-8d2d-84e56dfaeca3.png)

Version: 1.9.1 (1.7.10)

Singleplayer, I dont know if this also happens in multiplayer

**Comment by MJRLegends** [comment]
Yeah thats intention

**Comment by MJRLegends** [comment]
the neptune sub-surface rock isnt though

**Comment by MJRLegends** [comment]
Fix will be out within the next hour

**Comment by MJRLegends** [comment]
a new version has been uploaded, it will be downloadable once curse staff approve it

**Comment by MJRLegends** [comment]
You can download it here in till its approved on curseforge http://ci.mjrlegends.com:8080/job/ExtraPlanets%20-%20MC%201.7.10/lastSuccessfulBuild/artifact/build/libs/ExtraPlanets-1.9.2.jar

**Comment by MJRLegends** [comment]
I appreciate the bug report though feel free to post anymore you find
