### ISSUE TITLE
[1.7.10] Neptune Stone Brick Stairs

### ISSUE THREAD

**Issue by Breadabix** [MJRLegends/ExtraPlanets#188]
### ---Issue Report---
**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes]

### Description of Issue
Neptune stone brick stairs are crafted with zinc blocks.

### Steps to Reproduce Issue
1. Look up Recipe in JEI

**Screenshots (if applicable):** 
![2017-12-22_22 20 01](https://user-images.githubusercontent.com/19786108/34313840-47fd1050-e766-11e7-88a4-d606c129b2bf.png)

**Version of Mod using:** [VERSION]
1.9.2

**Where did this bug happen:** [Single Player or Server]
Both

**Comment by MJRLegends** [comment]
Thanks for the bug report but please use this template, its so its easy for peopleto understand the issue, Will reopen when its been changed

```
### ---Issue Report---
**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue
[Description of the issue]

### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

**Screenshots (if applicable):** 

**Version of Mod using:** [VERSION]

**Where did this bug happen:** [Single Player or Server]

### Additional Information
[Any other information that may be able to help me with the problem]
```

**Comment by Breadabix** [comment]
Other than the version I used this template?

**Comment by MJRLegends** [comment]
Nope you have not used the template also you must have them edited somewhere as they seem good for me 

![](https://i.gyazo.com/2fc26e8bcaa0b78bcf75df3024fc5931.png)

**Comment by MJRLegends** [comment]
Nope you have not used the template also i've fixed the issue but you will still need to change the issue template please

**Comment by MJRLegends** [comment]
Dont worry i've corrected it for you, but when posting future issues i will just close them if template isnt used

**Comment by MJRLegends** [comment]
Update containing this fix has been released
