### ISSUE TITLE
[1.7+] Launch button sometimes not working

### ISSUE THREAD

**Issue by Breadabix** [MJRLegends/ExtraPlanets#189]
### ---Issue Report---
**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

### Description of Issue
The launch button often doesnt work, however if it doesnt work a game restart fixes it temporarily

### Steps to Reproduce Issue
1. Install latest version
2. Run minecraft and either do /dimensiontp or get in a high tier rocket a few times. The first few times it works but after that a restart is required to do anything. (It can work sometimes for a long time before breaking, but keep going between planets/moons and it will break)

**Crash log/Log (if applicable): N/A
**Screenshots (if applicable): N/A

**Version of Mod using:** [VERSION]
1.9.2

**Where did this bug happen:** [Single Player or Server]
Both (I think)

### Additional Information
This isnt an issue with tiers of rockets, In tests I always used tier 10 rocket or /dimensiontp
Sometimes if you tab out and come back a couple mins later it will work, however this is not guaranteed

**Comment by MJRLegends** [comment]
Since it doesn't happen all the time, i dont think anything can be done for this sorry
You can always disable the custom Celestial Galaxy map in ExtraPlanets config

**Comment by Breadabix** [comment]
Just out of curiosity what does the custom Celestial map do differently to the default one?

**Comment by MJRLegends** [comment]
I've found the bug and fixed it for next versions, affects 1.7+

**Comment by MJRLegends** [comment]
Update will be out very soon :D

**Comment by MJRLegends** [comment]
Updates are rolling out now
