### ISSUE TITLE
[1.10.2] Missing icon for Kepler 22b

### ISSUE THREAD

**Issue by Jason505** [MJRLegends/ExtraPlanets#191]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue
In /dimensiontp is not showing icon of Kepler 22b and his Space Station.
### Steps to Reproduce Issue
1. Type /dimensiontp
2. Create Space Station on Kepler 22b
3. Double-click on Kepler 22b

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

**Screenshots (if applicable):** 
![2017-12-27_19 56 35](https://user-images.githubusercontent.com/28407251/34390527-950b5fa4-eb40-11e7-8c18-20de7e82f10a.png)
**Version of Mod using:** [0.7.8]

**Where did this bug happen:** [Server]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Please post your fml client latest log

**Comment by Jason505** [comment]
There it is, last I tried it at 20:09.
[fml-client-latest.log](https://github.com/MJRLegends/ExtraPlanets/files/1589691/fml-client-latest.log)

**Comment by MJRLegends** [comment]
Your using a old ExtraPlanets, please update

**Comment by MJRLegends** [comment]
Also ExtraPlanets-[1.10.2]-0.7.8.jar isn't a offical file name, download from official sources please
http://minecraft.curseforge.com/projects/extraplanets

**Comment by Trochu** [comment]
It is only renamed file by US and downloaded from your official Curse Forge page.....

**Comment by MJRLegends** [comment]
@Trochu how do you know that? there are plenty of sites hosting unofficial downloads for mods. Take a read of http://stopmodreposts.org/

**Comment by Trochu** [comment]
Yes, I know it, cause I have rename it. We cooperate on that modpack together and I wanted to have all the mods have same name style like "Name-[MCversion]-Modversion.jar"

We try to update Extraplanets mod to fix that issue with Kepler icon.
