### ISSUE TITLE
[1.8+] Error while landing on Kepler 22b

### ISSUE THREAD

**Issue by Xmair** [MJRLegends/ExtraPlanets#192]
### ---Issue Report---
*Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No] Yes

### Description of Issue
Whenever I try to land on Kepler 22b, my game crashes.

### Steps to Reproduce Issue
1. Get a tier 10 rocket.
2. Land on Kepler 22b.

**Crash log/Log (if applicable):**https://pastebin.com/FFDNHFGV

**Screenshots (if applicable):** --

**Version of Mod using:** 1.8.9

**Where did this bug happen:** SP

### Additional Information: None

**Comment by MJRLegends** [comment]
Thanks this is a easy fix

**Comment by MJRLegends** [comment]
Its only a certain use case crash too so you just got unlucky with it

**Comment by Xmair** [comment]
So how long should I expect the next update :smile: ?

**Comment by MJRLegends** [comment]
In the next 48 hours

**Comment by MJRLegends** [comment]
Update is coming, just working on some new features for the update so a few days delay on it :D
