### ISSUE TITLE
[1.11.2] extra planets searches for missing mods

### ISSUE THREAD

**Issue by bigmolla** [MJRLegends/ExtraPlanets#193]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**
Minecraft crashes after adding  Extra Planet mod to my existing world.
**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
NO

### Description of Issue
I have a world with galacticraft (GalacticraftCore-1.11.2-4.0.0.119.jar, Galacticraft-Planets-1.11.2-4.0.0.119.jar, MicdoodleCore-1.11.2-4.0.0.119.jar), and other few mods, happily working with no problems.
I decided to add Extra planets mod and according to your suggestions:

```
-----------------------------------------------------------------------------------------------------
1.11.2 Version
Please report them here and use [1.11.2] in the title.
Requires Galacticraft 4 Builds, (119 Build and higher) and Forge 13.20.0.2282 or higher!

v0.4.9 is available, check change log for details
-------------------------------------------------------------------------------------------------------
```

 I checked my galacticraft version, and Forge version (13.20.1.2454) .
They are both ok.
Well, MC does not start and an error message appears saying that I miss a mod to use Extra planets but does not say what is missing.

You find attached the error message.

### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

No crash log is generated

**Screenshots (if applicable):** 
![extraplanet_error](https://user-images.githubusercontent.com/35007841/34470259-262c6adc-ef2e-11e7-86fb-e9f661ca6ce8.jpg)
**Version of Mod using:** [VERSION]
0.4.9 for minecraft 1.11.2

**Where did this bug happen:** [Single Player or Server]
Single player

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
what forge version are you on?

**Comment by MJRLegends** [comment]
update your forge you using a very old one

**Comment by MJRLegends** [comment]
I've updated the requirements message to say 13.20.1.2513 as the minimum but you really shouldn't be using 13.20.1.2454 that is a very very old version

**Comment by MJRLegends** [comment]
Sorry for any confusion

**Comment by bigmolla** [comment]
Thank you for the quick answer.

I use that version of forge because it still works ok with my collection of mods. No need to change something working :-)

Anyway I'll definitely upgrade it if it is necessary to use extra planets.

Thanks again and please go on with your excellent work!!!

Bigmolla




  ----Messaggio originale----
 
 Da: notifications@github.com
 
 Data: 1-gen-2018 20.34
 
 A: "MJRLegends/ExtraPlanets"<ExtraPlanets@noreply.github.com>
 
 Cc: "bigmolla"<bigmolla@alice.it>, "Author"<author@noreply.github.com>
 
 Ogg: Re: [MJRLegends/ExtraPlanets] [1.11.2] extra planets searches for missing mods (#193)
 

 

 
I've updated the requirements message to say 13.20.1.2513 as the minimum but you really shouldn't be using 13.20.1.2454 that is a very very old version

**Comment by MJRLegends** [comment]
Just because something works doesnt mean you dont need to update it
