### ISSUE TITLE
[1.7.10+] Wrong information on galaxy map

### ISSUE THREAD

**Issue by SuumCW** [MJRLegends/ExtraPlanets#194]
**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

### Description of Issue
In the galaxy map information is the earth not breathable

### Steps to Reproduce Issue
1. dimensiontp
2. press at earth

**Screenshots (if applicable):** 

**Version of Mod using:** 1.9.2 (1.7.10 mc)

**Where did this bug happen:** Server

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
@SuumCW Please could you update the version with the version number as 'latest' isnt a good version marker to use

**Comment by SuumCW** [comment]
ok

**Comment by MJRLegends** [comment]
Thanks

**Comment by MJRLegends** [comment]
Also which language do you use for mc?

**Comment by SuumCW** [comment]
german

**Comment by SuumCW** [comment]
its the 1.9.2 (1.7.10 mc)

**Comment by MJRLegends** [comment]
No problem, thanks for the update on the information in the initial post

**Comment by SuumCW** [comment]
is this going to be fixed in the 1.9.3?

**Comment by MJRLegends** [comment]
Yeah, this seems to be a bug in all versions so it will be fixed in next update for all versions

**Comment by MJRLegends** [comment]
Updates for MC 1.8.9 and 1.10.2 and 1.11.2 are about to come out fixing this, the MC 1.7.10 one will be in a few days :D

**Comment by MJRLegends** [comment]
MC 1.7.10 update with this fix is out now too
