### ISSUE TITLE
1.7.10 Galaxy Map Causing a error when used with Armua Ru addon

### ISSUE THREAD

**Issue by SuumCW** [MJRLegends/ExtraPlanets#195]
**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

### Description of Issue
When you make /dimensiontp your galaxy map keeps restarting (you can't click at something)

### Steps to Reproduce Issue
1. /dimensiontp

**Version of Mod using:** 1.9.3

**Where did this bug happen:** Server

**Comment by SuumCW** [comment]
The only way getting out is resetting the playerdata

**Comment by MJRLegends** [comment]
Im unable to reproduce this

**Comment by SuumCW** [comment]
I used a shuttle of amun-ra

**Comment by SuumCW** [comment]
maybe thats the problem too

**Comment by MJRLegends** [comment]
Yeah i dont see a issue with ExtraPlanets, let me know if you find out anything to do with this.

Try with just Galacticraft and ExtraPlanets if it keeps happening

**Comment by SuumCW** [comment]
Its only happening when I have extraplanets and amunra. without extra planet is it not bugging

**Comment by SuumCW** [comment]
the shuttle bugs with extraplanets

**Comment by MJRLegends** [comment]
Will look in a bit

**Comment by SuumCW** [comment]
ok

**Comment by MJRLegends** [comment]
Could you send me your fml-client-latest.log contain a time when you tried it

**Comment by SuumCW** [comment]
ok

**Comment by SuumCW** [comment]
Where do I find the fml-client-latest.log ?

**Comment by MJRLegends** [comment]
in the logs folder

**Comment by SuumCW** [comment]
"latest"?

**Comment by SuumCW** [comment]
[latest.log](https://github.com/MJRLegends/ExtraPlanets/files/1604461/latest.log)

**Comment by MJRLegends** [comment]
no theres a file called fml-client-latest.log

**Comment by MJRLegends** [comment]
it will be on your client not server

**Comment by SuumCW** [comment]
there is no file called like that

**Comment by MJRLegends** [comment]
rip 1.7.10 then

**Comment by SuumCW** [comment]
Should I send you my mod list?

**Comment by MJRLegends** [comment]
why are all the dimensions being loaded with the name "test"? that shouldnt happen..

**Comment by MJRLegends** [comment]
dw im a idiot and nope its fine

**Comment by SuumCW** [comment]
ok

**Comment by MJRLegends** [comment]
so you mean its doing this ? 

![](https://i.gyazo.com/938af51f935bdce6f81e5b64bd8f8bb0.png)

**Comment by SuumCW** [comment]
Yea

**Comment by SuumCW** [comment]
but it shows the names sometimes too

**Comment by MJRLegends** [comment]
ok, your issue report describes something different thats why i didnt get what you mean

**Comment by SuumCW** [comment]
My english is not good ik

**Comment by MJRLegends** [comment]
Please send me a copy of both your ExtraPlanets and Armua configs

**Comment by SuumCW** [comment]
I edited the amunra config so they are compatible

**Comment by SuumCW** [comment]
I can't send it here I'm sending it you in discord

**Comment by MJRLegends** [comment]
disabling 
  B:"Use Custom Galaxy Map/Celestaial Selection Screen"=true
 in the ExtraPlanets config will fix this issue

Im unable to make it compatible
