### ISSUE TITLE
Tier 3-10 Rockets Crashing whilst Rocket is launching

### ISSUE THREAD

**Issue by DonkeyMonkey** [MJRLegends/ExtraPlanets#196]
---Issue Report---
Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

**Description of Issue**
Tier 3 - 10 Rockets(Creative Rockets) Crashing, i haven't checked the Survival ones
java.lang.NullPointerException: Exception generating new chunk

**Steps to Reproduce Issue**
1. Launch Tier 3 - 10 Rockets(Creative Rockets)
2. Crashes

**Crash log/Log (if applicable):[PASTEBIN. Do NOT copy an paste the log into the issue post itself.]**
https://pastebin.com/0S6VWW0W

**Version of Mod using[VERSION]**
1.7.10

**Where did this bug happen:** [Single Player or Server]
SinglePlayer

### Additional Information
Processor:   AMD Sempron(tm) 140 Processor 2.70GHz
RAM to Minecraft:   2560MB/ 4000MB
System Type:   64bit

**Comment by MJRLegends** [comment]
You can downloaded this version of the mod from a official source my downloads are only ever hosted on curseforge, this means you could of downloaded a infected version as it was not posted by me check out http://stopmodreposts.org/ This means your using a very old version too

**Comment by DonkeyMonkey** [comment]
thanks!... its running smoothly now... turns out i download mine on an infected site
