### ISSUE TITLE
The ExtraPlanets mod does not start

### ISSUE THREAD

**Issue by danilo-romao** [MJRLegends/ExtraPlanets#197]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue
[the ExtraPlanets mod does not start]

### Steps to Reproduce Issue
1. [even before the forgemod load all mods and start minecraft, the game closes]
2. [the other mods in the mods folder work normally but when I install ExtraPlanets and start the launcher, before even entering the game menu, the game ends]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [ExtraPlanets-0.8.9]

**Where did this bug happen:** [Single Player]

### Additional Information
[I would very much like to use your mod in a modpack and show others your work, so I come here to report this problem]

![crash](https://user-images.githubusercontent.com/35278185/34749009-9e5e9e86-f586-11e7-88f2-0de43f2030cf.png)

[crash-2018-01-09_21.31.46-client.txt](https://github.com/MJRLegends/ExtraPlanets/files/1617039/crash-2018-01-09_21.31.46-client.txt)

**Comment by MJRLegends** [comment]
This isnt a ExtraPlanets issue, sorry i cant help you with this one :D

**Comment by danilo-romao** [comment]
OK thank you

**Comment by MJRLegends** [comment]
@danilo-romao Please test latest versions of ExtraPlanets things have improved if you still wanna try it out you should need less GPU ram for ExtraPlanets now :D

**Comment by danilo-romao** [comment]
humm ok thank you!!!!! I really liked your mod but for now I do not have a
good pc 😋

2018-03-12 17:16 GMT-03:00 MJRLegends <notifications@github.com>:

**Comment by danilo-romao** [comment]
it's working on my computer !!! Thank you for doing a more light update.

2018-03-13 22:16 GMT-03:00 Danilo Romão Nogueira de França <
daniloromaonf@gmail.com>:
