### ISSUE TITLE
Tier 3 Rocket unable to select Venus

### ISSUE THREAD

**Issue by aetherpirate** [MJRLegends/ExtraPlanets#20]
Galacticraftcore 460
GalactiraftPlanets 460
Microdoodle 460
ExtraPlanets-1.0-Pre 3.6.2.jar

Venus is in red on my menu, and I cannot choose to land there with my Tier 3 Rocket. I have removed all GC configs on both client and server to reset them. I can land on the Asteroids.

**Comment by MJRLegends** [comment]
Let me double check on my side if it works...

**Comment by MJRLegends** [comment]
I will release a new update now to fix this

**Comment by MJRLegends** [comment]
Released updated, give it 5 to 10 mins to show on the curse forge page
