### ISSUE TITLE
Saturn texture on Titan

### ISSUE THREAD

**Issue by Jason505** [MJRLegends/ExtraPlanets#200]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

### Description of Issue
On Saturn's moon, Titan, there is a missing texture of Saturn (expecting, maybe it's another Saturn's moon, but I don't think so) on the sky. Just black/purple block floating here...
_**Only on Titan!**_

### Steps to Reproduce Issue
1. Go to Titan
2. Look up

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

**Screenshots (if applicable):** 
![2018-01-14_20 20 35](https://user-images.githubusercontent.com/28407251/34919846-6e363782-f969-11e7-9159-9a35448f296e.png)

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [0.8.5]

**Where did this bug happen:** [Server]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Thanks i will fix at some point

**Comment by MJRLegends** [comment]
Ok i just took a look at this issue and it turns out its already fixed. You are using 4 version behind. Please update
