### ISSUE TITLE
[Request] Oredict in item registry event & Recipes in recipe event

### ISSUE THREAD

**Issue by justinrusso** [MJRLegends/ExtraPlanets#203]
Hello MJRLegends,

Would you be able to do oredictionary registration during the item registration event, and recipes during the recipe event? Just looking it possible issues Darkosto and I might run into while working with the mod.

I'm also noticing that *mostly* the planet/moon blocks are not "seen" when crafttweaker is run - are you registering any blocks during init or any time after? Theres about 1.5 of 5 pages of items that seem to not be "seen".

Thanks for your help!

**Comment by MJRLegends** [comment]
Yeah but atm my 1.12.2 version isnt released yet and shouldnt be used

**Comment by justinrusso** [comment]
But.. Darkosto is using it, and I'm working with him :P

**Comment by MJRLegends** [comment]
Yeah only Darksoto has access to it atm

**Comment by Darkosto** [comment]
Hey MJR,

Justin is helping me out on SevTech and is reporting some issues on my behalf so we can get more work finished up rather than me just working on my own :)

**Comment by MJRLegends** [comment]
I will change the ore dict but the rest is already done in events

**Comment by MJRLegends** [comment]
You can remove my ore dict entries through the config with me needing to do this yet

**Comment by MJRLegends** [comment]
Well most of them you can
