### ISSUE TITLE
Jupiter causes Minecraft to crash

### ISSUE THREAD

**Issue by DavThePiggyBoy** [MJRLegends/ExtraPlanets#204]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**
minecraft crashes when loading Jupiter
**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes
### Description of Issue
[Description of the issue]
When I take a rocket to Jupiter minecraft freezes at the loading screen and crashes with exception in sever tick/
### Steps to Reproduce Issue
1. use /dimensiontp or take a rocket
2. Select Jupiter from the selection screen

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
https://pastebin.com/gnJWpFKL
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
1.11.2
**Where did this bug happen:** [Single Player or Server]
Single Player
### Additional Information
[Any other information that may be able to help me with the problem]
I tested this on another world and still crashes
Also I cannot open the world because it crashes when trying to load Jupiter

**Comment by MJRLegends** [comment]
You need to post the crash log, i wont be able to do anything without it

**Comment by DavThePiggyBoy** [comment]
I put the link

**Comment by MJRLegends** [comment]
Oh ok you posted it half way through the template text so i missed it sorry

**Comment by MJRLegends** [comment]
Your Galacticraft is out of date, thankfully ive posted the requirements for people to see on  https://www.curseforge.com/minecraft/mc-mods/extraplanets

**Comment by DavThePiggyBoy** [comment]
So if i update will it fix the issue?

**Comment by MJRLegends** [comment]
Yes, your using a version lower than the need one, which is why i tell peolle that version on thr curseforge page

**Comment by MJRLegends** [comment]
Please make sure to take the time to read through any helpful information mod devs provide through the descriptions on the mod pages

**Comment by MJRLegends** [comment]
@DavThePiggyBoy any chance you could please send me a copy of your fml-client-latest.log as im surprised my force checker to make sure the correct version is being used didnt go off
