### ISSUE TITLE
[1.7.10] Compatibility with MooFluids

### ISSUE THREAD

**Issue by spannerman79** [MJRLegends/ExtraPlanets#205]
Edit:  Hit enter before filling this out - sorry about that.

ExtraPlanets-1.9.5
MooFluids-1.7.10-1.5.01.19a

It seems between 1.9.4 and 1.9.5 whatever new fluid was introduced has created a mod incompatibility with MooFluids.

Just by themselves (MooFluids, GC & ExtraPlants) there is no crash so I cannot effectively show a crash log to help pin point this issue down.

Rolling back to 1.9.4 there isn't an issue.

Edit:  Full log https://paste.ee/p/PtbId

**Comment by spannerman79** [comment]
I tested with 1.9.6 - same issue https://paste.ee/p/xN3rH

**Comment by MJRLegends** [comment]
Yeah it will be as its not fixed haha

**Comment by MJRLegends** [comment]
![](https://i.gyazo.com/c31da023d7b0f3f54258f10f5816a608.png)
Seems to work ok for me. Please test with just Galacticraft and ExtraPlanets and Moo Fluids
