### ISSUE TITLE
Config option to disable ore gen on planets

### ISSUE THREAD

**Issue by WesTroy** [MJRLegends/ExtraPlanets#208]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes

### Description of Issue
Please add a config option to disable ore gen on planets. Many users have CoFH determining ore gen. Vanilla GC allows this, but it is currently unavailable with ExtraPlanets.

### Steps to Reproduce Issue
No steps required.

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
Not applicable.

**Screenshots (if applicable):** 
Not applicable.

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
ExtraPlanets-1.12.2-0.1.5

**Where did this bug happen:** [Single Player or Server]
Not applicable.

### Additional Information
Love the mod - gets better each version. Keep up the great work!

**Comment by MJRLegends** [comment]
Which ore are you looking to disable?

**Comment by WesTroy** [comment]
The option should be available for all ores. Almost every modern mod has this option (most often for compatibility or modpack tailoring). Thanks for the consideration!

**Comment by MJRLegends** [comment]
Yeah but it works differently with planets as they are there own dimensions from the mod and the ores are the progression in the mod, most other mods add worldgen to the overworld and that when config options are good

**Comment by WesTroy** [comment]
I understand your point - but designing modpacks might entail many other concepts, and allowing the choice seems a good offer.

Even using your logic: as a random hypothetical example, what if a pack maker wants Neptune's blue gems to generate on Neptune below Y-30 in a geode formation with lava inside? This could be quickly done by disabling the default generation in your config and creating the geode in CoFH World.

It's your mod, so you may certainly handle things how you'd like, but folks have far more freedom if this option exists.

**Comment by MJRLegends** [comment]
I wont be able to add cofh support sorry, but will add some config options for ores at something. Expect to see it added in next week

**Comment by WesTroy** [comment]
This was closed but not implemented - can it be reopened? Thanks!

**Comment by MJRLegends** [comment]
Its a suggestion and all suggestions get closed after ive seen them closed.

Sorry for thr delay but its not a major thing as it is a suggestion not a bug

**Comment by MJRLegends** [comment]
But don't worry its on the todo list

**Comment by MJRLegends** [comment]
@WesTroy im adding config options to disable all ores for each planet/moon in the next update :D for 1.8+ versions

**Comment by WesTroy** [comment]
Awesome - thanks! Keep up the great work!
