### ISSUE TITLE
[1.8+] Crash when disabling Kepler22b Tools & Armor option in the Config

### ISSUE THREAD

**Issue by robjw95** [MJRLegends/ExtraPlanets#209]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** yes

### Description of Issue
crash

### Steps to Reproduce Issue
1. disable extra planets tools in config

**Crash log/Log (if applicable)
[crash-2018-01-28_18.48.55-client.txt](https://github.com/MJRLegends/ExtraPlanets/files/1671770/crash-2018-01-28_18.48.55-client.txt)

**Screenshots (if applicable):** 

**ExtraPlanets-1.12.2-0.1.6

**Where did this bug happen:  singleplayer

### Additional Information
I disable the tools in extraplanet config and get this crash.  Loaded fine before I did that.

**Comment by MJRLegends** [comment]
Thank you for the bug report, i will fix

PS. Please use pastebin.com for your logs for future as it makes it easier to see the crash log without having to download files :D

**Comment by MJRLegends** [comment]
I believe its the "Kepler22b Tools & Armor" option causing the crash, setting that one back to true will make it not crash for the time being :D

**Comment by robjw95** [comment]
Thanks

**Comment by MJRLegends** [comment]
The updates are being uploaded as we speak should show on Curse very soon (Depending on how long it takes for them to approve it)
