### ISSUE TITLE
Venus Dungeon issues 

### ISSUE THREAD

**Issue by aetherpirate** [MJRLegends/ExtraPlanets#21]
The chests in the Venus dungeon are empty, and the spawners are all pig spawners

Galacticraft v460
Running extraplanets 3.6.3

**Comment by aetherpirate** [comment]
Running extraplanets 3.6.3

**Comment by MJRLegends** [comment]
Its impossible for the chests to be empty and its impossible for them to be pig spawners

**Comment by aetherpirate** [comment]
False alarm. Went to 2nd dungeon and all is well. Fluke or server weirdness I guess. Cannot reproduce.

**Comment by MJRLegends** [comment]
@aetherpirate im 100% sure it had nothing to do with my addon to why it happened, probably another mod or minecraft derping
