### ISSUE TITLE
GalacticMap missing exit

### ISSUE THREAD

**Issue by DerMilchkarton** [MJRLegends/ExtraPlanets#210]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

### Description of Issue
Exit-Button missing and ESC-Key not working when opening Galactic Map
I tried it with GalaxySpace [ver1.1.9 STABLE] and with stock Galacticraft

### Steps to Reproduce Issue
1. Open the Galactic Map

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

**Screenshots (if applicable):** 
![extra_planets_and_galaxyspace](https://user-images.githubusercontent.com/36045340/35689217-41213a04-0773-11e8-8c1a-3e9585fd333f.png)
![only_with_extra_planets](https://user-images.githubusercontent.com/36045340/35689218-41447816-0773-11e8-8761-d3fb240b9364.png)
![only_with_galaxyspace](https://user-images.githubusercontent.com/36045340/35689219-416260ba-0773-11e8-9ca2-d34fcccd7592.png)

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [ExtraPlanets-1.7.10-1.9.6]

**Where did this bug happen:** [SinglePlayer]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Your screenshots are for galaxy space addon. ExtraPlanets one isnt active. Please report to that dev

**Comment by DerMilchkarton** [comment]
Sorry to bother again, but it is a ExtraPlanets problem, i disabled GalaxySpace and still no exit option, other than closing the game completly


![extraplanets](https://user-images.githubusercontent.com/36045340/35692961-0304bc00-077d-11e8-9c42-ee61fd78266b.png)

its has to do with the config i guess, because when completly resetting the extraplanets.cfg the button is actually there again
guess im going to experiment with the configs to find out what causes the issue

**Comment by MJRLegends** [comment]
It seems to work fine with just Galacticraft and ExtraPlanets
![](https://i.gyazo.com/2bcba5981f6aa064d6688b0861d770cb.png)

if you have the galaxy space compatibility option on in ExtraPlanets then my custom galaxy map screen i disabled fully

**Comment by MJRLegends** [comment]
From the screenshots i can see that this option is on, which means its something else than ExtraPlanets which is the issue
