### ISSUE TITLE
[1.7.10] Minor Config Description Issue

### ISSUE THREAD

**Issue by DerMilchkarton** [MJRLegends/ExtraPlanets#211]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

### Description of Issue
ExtraPlanets.cfg "other dimensions" wrong descripton
(always: "Setting this option to false will disable & remove the Mercury Space Station")

### Steps to Reproduce Issue
1. open ExtraPlanets.cfg

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

**Screenshots (if applicable):** 
![config](https://user-images.githubusercontent.com/36045340/35689542-12370100-0774-11e8-9907-99993f0b2d88.PNG)

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [ExtraPlanets-1.7.10-1.9.6]

**Where did this bug happen:** []

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Thanks i will fix in the next version

**Comment by MJRLegends** [comment]
Updates for affected versions are now on Curseforge, might be to give it 10 mins for them to be approved
