### ISSUE TITLE
Ghost button when trying to visit spacestations

### ISSUE THREAD

**Issue by DerMilchkarton** [MJRLegends/ExtraPlanets#212]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

### Description of Issue
After creating a spacestation the launch-button in the upper right doesnt get shown, but its there if you click the mouse on the actual button position, this happens with no configs changed

### Steps to Reproduce Issue
1. create a ExtraPlanets spacestation
2. try to visit it

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

**Screenshots (if applicable):** 
![2018-02-01_18 30 32](https://user-images.githubusercontent.com/36045340/35693655-1a16105e-077f-11e8-9761-7d28e17bd1db.png)

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [ExtraPlanets-1.7.10-1.9.6.]

**Where did this bug happen:** SinglePlayer

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Venus doesnt have a space station in ExtraPlanets, GalaxySpace does, and you will need to disabled this option 
`B:"Use Custom Galaxy Map/Celestial Selection Screen"=true`

or enable 
`B:"Enable Basic Galaxy Space Compatibility"=false`

Please only post ExtraPlanets bugs here :D

**Comment by MJRLegends** [comment]
![](https://i.gyazo.com/28ba730858ea50183a675ef3eec32c09.png)
Works fine with Galacticraft and ExtraPlanets

**Comment by MJRLegends** [comment]
You will also see this if the station was created with galaxy space installed and its probably there station that was added

**Comment by MJRLegends** [comment]
I think there is a issue here which i can fix, for cleanness i have made a new issue about it https://github.com/MJRLegends/ExtraPlanets/issues/213

**Comment by MJRLegends** [comment]
Thanks for your issue reports @DerMilchkarton any defo ExtraPlanets ones let me know
