### ISSUE TITLE
Updated German Language File

### ISSUE THREAD

**Issue by DerMilchkarton** [MJRLegends/ExtraPlanets#214]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

### Description of Issue
i updated all the ##TRANSLATION## markers and a few wrong translations, not finished yet
but im going to do a complete overhaul

https://pastebin.com/HiARnPxr

### Steps to Reproduce Issue

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [ExtraPlanets-1.7.10-1.9.6]

**Where did this bug happen:** [Single Player or Server]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Thank you, please see https://github.com/MJRLegends/ExtraPlanets/commit/070ad20823925c8c67f4eddd8b47be21dd655a3a :D
