### ISSUE TITLE
[1.8+] Mercury/Nickel and Zinc batterys are fully powered after crafting

### ISSUE THREAD

**Issue by wamc2017** [MJRLegends/ExtraPlanets#215]
### ---Issue Report---

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** yes

### Description of Issue
Mercury, Nickel and Zinc batterys should be empty after crafting

### Steps to Reproduce Issue
1. Craft one of these batterys, they're full from the beginning

**Crash log/Log (if applicable):**
No log needed I think.

**Screenshots (if applicable):** 
![battery](https://user-images.githubusercontent.com/33242447/35698414-3e2ddb62-078d-11e8-9dd2-c3e678186756.png)

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** 1.12.2-0.1.6

**Where did this bug happen:** Single Player

### Additional Information
Modlist: https://pastebin.com/AiJ0MwmD

**Comment by MJRLegends** [comment]
Thanks will be fixed in the next version which will probably be out in a bit

**Comment by MJRLegends** [comment]
The updates are being uploaded as we speak should show on Curse very soon (Depending on how long it takes for them to approve it)
