### ISSUE TITLE
[1.8+] Dark Iron blocks on Eris instead of Ore

### ISSUE THREAD

**Issue by wamc2017** [MJRLegends/ExtraPlanets#216]
### ---Issue Report---

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** yes

### Description of Issue
On Eris you can find Blocks of Dark Iron instead of Dark Iron ore

### Steps to Reproduce Issue
1. Travel to Eris and go mining
2. find some Blocks of Dark Iron instead of Dark Iron ore

**Crash log/Log (if applicable):**
No log needed I think.

**Screenshots (if applicable):** 
![darkironore](https://user-images.githubusercontent.com/33242447/35698554-adeb0808-078d-11e8-99e8-a2b5aa2b9711.png)

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** 1.12.2-0.1.6

**Where did this bug happen:** Single Player

### Additional Information
Modlist: https://pastebin.com/AiJ0MwmD

**Comment by MJRLegends** [comment]
Thanks will be fixed in the next version which will probably be out in a bit

**Comment by MJRLegends** [comment]
The updates are being uploaded as we speak should show on Curse very soon (Depending on how long it takes for them to approve it)
