### ISSUE TITLE
[1.11+] Tier 10 key doesn't work in Tier 10 chest

### ISSUE THREAD

**Issue by wamc2017** [MJRLegends/ExtraPlanets#217]
### ---Issue Report---

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** yes

### Description of Issue
Tier 10 key doesn't work in Tier 10 chest

### Steps to Reproduce Issue
1. Travel to Eris, find a dungeon, kill the giant zombie and get his key
2. Try to open the chest with the key

**Crash log/Log (if applicable):**
No log needed I think.

**Screenshots (if applicable):** 
![key](https://user-images.githubusercontent.com/33242447/35698580-ce8dca6e-078d-11e8-9250-2abae577d8e5.png)

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** 1.12.2-0.1.6

**Where did this bug happen:** Single Player

### Additional Information
Modlist: https://pastebin.com/AiJ0MwmD

**Comment by MJRLegends** [comment]
@wamc2017 Thanks for the bug report, was this the only chest that had the issue?

**Comment by wamc2017** [comment]
So far the tier 10 chest was the only one. :smile:

**Comment by MJRLegends** [comment]
Ok thanks you, i should be able to fix this :D

**Comment by MJRLegends** [comment]
Seems something is wrong with the key as the Tier 10 key works in a Tier 9 chest.... very weird. i will keep trying to work it out :D

**Comment by MJRLegends** [comment]
i've fixed it, seems its a MC 1.11.2 and MC 1.12.2 issue :D

**Comment by MJRLegends** [comment]
Will be fixed in the next version

**Comment by MJRLegends** [comment]
The updates are being uploaded as we speak should show on Curse very soon (Depending on how long it takes for them to approve it)
