### ISSUE TITLE
[1.11+] Shift clicking in any ExtraPlanets machine causes a crash

### ISSUE THREAD

**Issue by wamc2017** [MJRLegends/ExtraPlanets#218]
### ---Issue Report---

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** yes

### Description of Issue
Shift+Left Click Potassium into a Basic Chemical Injector crashes the game (not everytime, but mostly)

### Steps to Reproduce Issue
1. Try to shift+left click Potassium into a Basic Chemical Injector

**Crash log/Log (if applicable):**
https://pastebin.com/BMb1MqZF

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** 1.12.2-0.1.6

**Where did this bug happen:** Single Player

### Additional Information
Modlist: https://pastebin.com/AiJ0MwmD

**Comment by MJRLegends** [comment]
Seems to be all machines, will try and fix now

**Comment by MJRLegends** [comment]
Found the issue, it will be fixed in the next version too :D

**Comment by MJRLegends** [comment]
@wamc2017 a bit off topic but do you have anymore bugs to report or did you report all of them (Im thinking about releasing updates now)

**Comment by wamc2017** [comment]
Hmm, currently everything is fine so far, but I haven't seen everything of the mod yet, because of the Tier 10 chest bug... :smile:

**Comment by MJRLegends** [comment]
No problem i will go ahead and do the updates then :D

**Comment by MJRLegends** [comment]
The updates are being uploaded as we speak should show on Curse very soon (Depending on how long it takes for them to approve it)

**Comment by wamc2017** [comment]
Thanks for the update, everything looks fine so far, cya in space (or in the next bugreport... :smile:)

**Comment by MJRLegends** [comment]
No problem :D

**Comment by wamc2017** [comment]
@MJRLegends,
It happened again in 0.1.7, this time by Shift clicking Potash into the smasher:
https://pastebin.com/kwArZKtW

**Comment by MJRLegends** [comment]
Please make a new ticket this is a different cause of crash to the other issue earlier

**Comment by wamc2017** [comment]
Done: https://github.com/MJRLegends/ExtraPlanets/issues/222 :smile:
