### ISSUE TITLE
[1.12.2] Oredicted Tungsten blocks doesn't work for Tier 3 Launch Pads

### ISSUE THREAD

**Issue by wamc2017** [MJRLegends/ExtraPlanets#219]
### ---Issue Report---

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** yes

### Description of Issue
If a mod which adds oredicted Tungsten blocks (like TechReborn or BaseMetals) is added, the Tier 3 Launch Pad cannot be crafted, because the recipe doesn't use the oredict entry for the block.

### Steps to Reproduce Issue
1. Try to craft a Tier 3 launchpad with a Tungsten steel block from another mod

**Crash log/Log (if applicable):**
No log needed I think.

**Screenshots (if applicable):** 
![tier3rocketlaunchpad](https://user-images.githubusercontent.com/33242447/35698755-4aecc704-078e-11e8-9c7f-f1b359d460ab.png)

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** 1.12.2-0.1.6

**Where did this bug happen:** Single Player

### Additional Information
Modlist: https://pastebin.com/bNBj1pND

**Comment by MJRLegends** [comment]
Yeah this is intentional so you cant skip rocket progression. Your welcome to use crafttweaker to change this if you want but it will cause cheating

**Comment by wamc2017** [comment]
Hmm, the problem is, if the EP Tungsten ingots are crafted together, I don't get the Tungsten Block from EP, I get the one from TechReborn...
![2018-02-01_20 38 32](https://user-images.githubusercontent.com/33242447/35699296-e815fbb2-078f-11e8-9f1c-4200b6a6e86d.png)

I know I could use Crafttweaker to resolve this, but maybe some guys who don't know how to use crafttweaker couldn't be progress further because of this problem... :smile:

**Comment by MJRLegends** [comment]
Yeah ExtraPlanets is designed in the same way that Galacticraft to where you need to get resources from the planet or moons to create the next tier stuff. Adding this recipe to a ore dict will allow the player to make this item/block much before they are ment to have access for it.

If you install CraftTweaker and MineTweaker RecipeMarker you can do /mtrm to remove and create new recipes from within game using a gui

**Comment by MJRLegends** [comment]
Later on i might add the option to change recipes to ore dict but its a massive job and isn't really worth it right now due to it will cause cheating :D
