### ISSUE TITLE
[1.11+] Tier 10 Electric Rocket Schematic in Nasa Workbench crash

### ISSUE THREAD

**Issue by wamc2017** [MJRLegends/ExtraPlanets#220]
### ---Issue Report---
**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

### Description of Issue
Tier 10 Electric Rocket Schematic crashes the game if selected in the Nasa Workbench

### Steps to Reproduce Issue
1. Add Tier 10 Electric Rocket Schematic to the Nasa Workbench, unlock it and switch to the responding page

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
https://pastebin.com/DYB82Dk5

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** 1.12.2-0.1.7

**Where did this bug happen:** Single Player

### Additional Information
Modlist: https://pastebin.com/ZiXEDVQj

**Comment by MJRLegends** [comment]
Thanks will be fixed in next update for MC 1.11.2 and 1.12.2

**Comment by MJRLegends** [comment]
Updated Versions are uploaded to Curseforge , they are awaiting approval
