### ISSUE TITLE
[1.12.2] Screen should turn black/grey when looking at Schematics in Nasa Workbench

### ISSUE THREAD

**Issue by wamc2017** [MJRLegends/ExtraPlanets#221]
### ---Issue Report---
**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

### Description of Issue
The screen should turn black/grey (see the screenshots) when looking at EP schematics in the Nasa Workbench

### Steps to Reproduce Issue
1. Put an EP schematic in the Nasa Workbench

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
No crashlog

**Screenshots (if applicable):** 
Tier 1 Rocket, how it should look:
![2018-02-02_03 25 18](https://user-images.githubusercontent.com/33242447/35715133-f9100e26-07d0-11e8-9e6a-b3163ba7feee.png)

Tier 4 Rocket (way to bright :smile: )

![2018-02-02_03 25 20](https://user-images.githubusercontent.com/33242447/35715154-13c8b16e-07d1-11e8-9ea7-19d99256c1e1.png)

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** 1.12.2-0.1.7

**Where did this bug happen:** Single Player

### Additional Information
Modlist: https://pastebin.com/ZiXEDVQj

**Comment by MJRLegends** [comment]
Thanks will be fixed in next update, this is a MC 1.12.2 only issue but for cleanness i have made the change in 1.8+ versions expect it wont be anything apart from for MC 1.12.2 it will fix this issue :D

**Comment by MJRLegends** [comment]
Updated Versions are uploaded to Curseforge , they are awaiting approval
