### ISSUE TITLE
[1.11+] Shift clicking Potash into Smasher crash

### ISSUE THREAD

**Issue by wamc2017** [MJRLegends/ExtraPlanets#222]
### ---Issue Report---
**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** yes

### Description of Issue
Tried to shift click Potash into the smasher

### Steps to Reproduce Issue
1. Shift click Potash into the smasher

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
https://pastebin.com/kwArZKtW

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** 1.12.2-0.1.7

**Where did this bug happen:** Single Player

### Additional Information
Modlist: https://pastebin.com/ZiXEDVQj

**Comment by MJRLegends** [comment]
Thanks will be fixed in next update, Do you have any more issues to report @wamc2017

**Comment by wamc2017** [comment]
I think that's all for today... :smile:

I'm sorry for bothering you with so many reports... :disappointed:

**Comment by MJRLegends** [comment]
No problem, and dont worry i like the reports the more bugs you can find the better

**Comment by MJRLegends** [comment]
Means my mod will be even more stable

**Comment by MJRLegends** [comment]
Im going update the MC 1.11.2 & 1.12.2 right now :D

**Comment by MJRLegends** [comment]
Updated Versions are uploaded to Curseforge , they are awaiting approval
