### ISSUE TITLE
[1.8+] Decontamination Unit could break/void blocks

### ISSUE THREAD

**Issue by wamc2017** [MJRLegends/ExtraPlanets#224]
### ---Issue Report---
**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** yes

### Description of Issue
The Basic Decontamination Unit could break and void blocks if placed wrongly. It only happens when only one row is in the way flying around, when a second row is placed there is a message "not enough room!"

### Steps to Reproduce Issue
1. See the screenshot, it breaks the flying diamond blocks if placed where the lime wool is located...

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
No crashlog

**Screenshots (if applicable):** 
![2018-02-02_15 34 40](https://user-images.githubusercontent.com/33242447/35739798-19dc571a-0833-11e8-92da-3c79e31f99ea.png)

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** 1.12.2-0.1.8

**Where did this bug happen:** Single Player

### Additional Information
Modlist: https://pastebin.com/08Xjz7Ws

**Comment by MJRLegends** [comment]
Yeah i know about this issue, but thanks for the bug report

**Comment by MJRLegends** [comment]
Versions are uploading to curse, please see change log for the MC 1.12 its got important information in :D
