### ISSUE TITLE
[FeatureRequest] Decontamination Chamber

### ISSUE THREAD

**Issue by wamc2017** [MJRLegends/ExtraPlanets#225]
### ---Issue Report---
**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** yes

### Description of Issue
Currently I'm not able to wire up the Decontamination Chamber, it would be nice if it could be powered by a cable. If it's intended to not be able to use wires to power the decontamination chamber, feel free to close this feature request... :smile:

### Steps to Reproduce Issue

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** 1.12.2-0.1.8

**Where did this bug happen:** No bug, more a feature request :D

### Additional Information

**Comment by MJRLegends** [comment]
Yeah this is intended to make sure of batteries more
