### ISSUE TITLE
[1.11+] Landing on a planet with an Electric Rocket gives back the wrong Launch Pad

### ISSUE THREAD

**Issue by wamc2017** [MJRLegends/ExtraPlanets#226]
### ---Issue Report---
**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** yes

### Description of Issue
Landing on any planet with an Electric Tier 10 rocket gives back a Tier 3 Rocket Launch Pad instead of a Powered Rocket Launch Pad.

### Steps to Reproduce Issue
1. Build an Electric Rocket Launch Pad and an Electric Tier 10 rocket
2. Fly to any planet
3. Look at the entry pot/parachest and see you got Tier 3 Rocket Launch Pads instead of Powered Rocket Launch Pads

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Screenshots (if applicable):** 
![2018-02-02_15 43 43](https://user-images.githubusercontent.com/33242447/35739922-838c120e-0833-11e8-9e9a-fe0708c37b02.png)

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** 1.12.2-0.1.8

**Where did this bug happen:** Single Player

### Additional Information
Modlist: https://pastebin.com/08Xjz7Ws

**Comment by MJRLegends** [comment]
Versions are uploading to curse, please see change log for the MC 1.12 its got important information in :D
