### ISSUE TITLE
[1.7+] Custom Galaxy Map/Celestial Selection Config option not working (1.7.10 Left only!)

### ISSUE THREAD

**Issue by DerMilchkarton** [MJRLegends/ExtraPlanets#227]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

### Description of Issue
When the custom celestial selection is disabled in the config, the exit-button disappears on the galaxy-map and its not possible to close the map again, thats why it didnt work either without any mods other than ExtraPlanets or with GalaxySpace installed because of the compatibility option disabling the custom celestial selection aswell. So it is an ExtraPlanets issue. :(

### Steps to Reproduce Issue
1. install only ExtraPlanets
2. disable the custom selection or enable the GalaxySpace compatibility
3. open GalaxyMap and check if there's a exit button
4. the launch button is available when a reachable planet is selected, but it doenst do anything
5. you can create spacestations by using the galaxy map without a rocket

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

**Screenshots (if applicable):** 
![2018-02-02_16 15 55](https://user-images.githubusercontent.com/36045340/35740606-a4c657c0-0835-11e8-91ee-65aad478677a.png)
![2018-02-02_16 18 01](https://user-images.githubusercontent.com/36045340/35740607-a4e4e078-0835-11e8-9e0f-d55420c31a5e.png)

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [ExtraPlanets-1.7.10-1.9.6]

**Where did this bug happen:** [SinglePlayer]

### Additional Information
i know im annoying but is there any chance you can fix the custom galaxy map?  because otherwise your mod isnt compatible with any other GC-addons
 thanks a lot!

**Comment by MJRLegends** [comment]
The exit button only shows on the pressing on the m key version of the galaxy map.

**Comment by MJRLegends** [comment]
It is compatible you just need to disable it when using with GalaxySpace. and yeah the GalaxySpace compact option is meant to disable the custom Custom Galaxy Map/Celestial Selection Screen

**Comment by MJRLegends** [comment]
Its possible for it to effect the galaxy map, its either on or off. it cant be touched if its turned off

**Comment by MJRLegends** [comment]
Its impossible for it to effect the galaxy map, its either on or off. it cant be touched if its turned off

**Comment by MJRLegends** [comment]
**To put it simple, when the** 
`B:"Use Custom Galaxy Map/Celestial Selection Screen"`
**is set to false it ExtraPlanets doesnt touch the Celestial Selection Screen**

**When the **
` B:"Enable Basic Galaxy Space Compatibility"`
**is set to true, ExtraPlanets doesnt touch the Celestial Selection Screen**

**Comment by MJRLegends** [comment]
Will be fixed in the next update

**Comment by DerMilchkarton** [comment]
> The exit button only shows on the pressing on the m key version of the galaxy map.
i know thats what i meant by opening the galaxyspace map

> To put it simple, when the
B:"Use Custom Galaxy Map/Celestial Selection Screen"
is set to false it ExtraPlanets doesnt touch the Celestial Selection Screen

**When the **
B:"Enable Basic Galaxy Space Compatibility"
is set to true, ExtraPlanets doesnt touch the Celestial Selection Screen
but try it for urself pls, something is messing with the button

**Comment by MJRLegends** [comment]
Updates for affected versions are now on Curseforge, might be to give it 10 mins for them to be approved
