### ISSUE TITLE
[1.12.2] Immediate crash upon launching the game

### ISSUE THREAD

**Issue by Asrizuma** [MJRLegends/ExtraPlanets#228]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

### Description of Issue
Upon launching the game, the launcher will reach the final stage before crashing. Only happens when ExtraPlanets is installed.

### Steps to Reproduce Issue
1. Install ExtraPlanets and MJRLegendsLib with the required 1.12.2 Forge version
2. Launch the game

**Crash log/Log (if applicable):** https://pastebin.com/r9NnWihN

**Screenshots (if applicable):** Sorry

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [0.1.9 (released on CurseForge Feb. 2)]

**Where did this bug happen:** Single Player

### Additional Information
1) The Forge version is 14.23.1.2610
2) I verified it was a problem with this mod by taking it out and launching the game, which worked

Thank you!

**Comment by wamc2017** [comment]
I think you'll have to update Galacticraft (and dependencies) to version 1.12.2-4.0.1.132. ;)

**Comment by MJRLegends** [comment]
It does say it at the top of the ExtraPlanets description https://gyazo.com/59b5136918dd1dc40b27b7229dc439c9

also i tweet it out https://twitter.com/mjrlegends?lang=en-gb

or feel free to join my discord i post it there too
https://discord.gg/VEgV7Pk

and i post it on https://forum.micdoodle8.com/index.php?threads/1-7-10-1-8-9-1-10-2-1-11-2-1-12-2-extra-planets-updated-02-02-2018.5294/page-27#post-44635

and on https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/2564761-1-7-10-1-8-9-1-10-2-1-11-2-1-12-2-extra-planets

haha ok im done :D but yeah feel free to save one of the sources so you can check it when i update :D

**Comment by Asrizuma** [comment]
crap, thanks.. i'm so blind
your mod's really cool! even if space is scary af

**Comment by MJRLegends** [comment]
No problem :D
