### ISSUE TITLE
[1.12.2] Mod Conflict with Custom Mob Spawner

### ISSUE THREAD

**Issue by DarkMatterXCIX** [MJRLegends/ExtraPlanets#229]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes
### Description of Issue
[Description of the issue]
recently I sent a crash log to DrZharks mo creatures dev team and Galacticraft and they both said the Extra Planets mod I have is having a conflict with Custom Mob spawner and is fixable by your end
### Steps to Reproduce Issue
1. [First step] 
Install Galactic craft most recent items, extra planets most recent, and mo creatures most recent
2. [Second step]
run server and then it loads for a while then crashes when getting to loading dimension area

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
Crash Log - https://pastebin.com/qLmaB9jn

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
Extra Planets 1.12.2-0.1.9 and MJRLegendsLib-1.12.2-1.0.6
**Where did this bug happen:** [Single Player or Server]
Server Side

### Additional Information
[Any other information that may be able to help me with the problem]
Just curious as to if you can fix this, no hurry, but hopefully you can as this mod adds so so much to the game

**Comment by MJRLegends** [comment]
Please can you post the links to where the devs have said its ExtraPlanets

**Comment by DarkMatterXCIX** [comment]
It was in Discord

**Comment by MJRLegends** [comment]
And for Galacticraft? As i dont think the dev use discord often?

**Comment by DarkMatterXCIX** [comment]
just removed your mod and it works fine now

**Comment by DarkMatterXCIX** [comment]
no, but i asked some mod developers of ICBM and Mo Creeatures and they said they noticed that extra planets has conflicts with their mod

**Comment by DarkMatterXCIX** [comment]
once i remove the mod it works as intended.

**Comment by DarkMatterXCIX** [comment]
ill send you some more logs to narrow it down one second

**Comment by MJRLegends** [comment]
No need i have enough here, thanks tho

**Comment by DarkMatterXCIX** [comment]
yeah, do u know if it is your side? cause i mean they could be wrong but idk

**Comment by MJRLegends** [comment]
I will take a look when i can

**Comment by DarkMatterXCIX** [comment]
okay sounds good, thanks much!!! means a ton!!! Beautiful mod btw!

**Comment by DarkMatterXCIX** [comment]
okay so.... i did it without your mod... with more mods.. and now it says same thing but galactic craft side.... ughh.. may not be you idk

**Comment by MJRLegends** [comment]
@radfast Galacticraft conflict from new biome system?

@DarkMatterXCIX no need to worry i will work it out please leave it with me

**Comment by DarkMatterXCIX** [comment]
Okay thank you so so much!

**Comment by radfast** [comment]
It's nothing to do with the new biome system or anything in Galacticraft.

It's a filesystem access problem in CustomMobSpawner.

**Comment by MJRLegends** [comment]
Yeah @radfast i though it was but didnt have time to look at the crash log for more than 2 seconds :) thanks for the reply
