### ISSUE TITLE
[1.7.10] Rendering bug

### ISSUE THREAD

**Issue by DerMilchkarton** [MJRLegends/ExtraPlanets#230]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

### Description of Issue
the custom leaves do have a graphical glitch, you can see trough adjacent blocks
compared to regular leaves this looks like a glitch
if it's intended dont mind the issue :)

### Steps to Reproduce Issue
1. load world
2. place ExtraPlanets' leaves

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

**Screenshots (if applicable):** 
![2018-02-03_14 32 33](https://user-images.githubusercontent.com/36045340/35767591-a3f90f1c-08ef-11e8-9473-e698f661e663.png)
![2018-02-03_14 06 34](https://user-images.githubusercontent.com/36045340/35767593-adb1fa28-08ef-11e8-8061-2625df33ca34.png)

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [ExtraPlanets-1.7.10-1.9.7]

**Where did this bug happen:** [Single Player]

### Additional Information
btw love ur work! thanks for this mod! :)

**Comment by DarkMatterXCIX** [comment]
im 100% sure this is a optifine edition for trees, it is not a issue or bug, its just how they wanted it to be since u can see through leaves in real life, as in try vanilla trees, should do same thing

**Comment by DarkMatterXCIX** [comment]
pretty sure in optifine u can turn trees from fast, to fancy, or default.

**Comment by DerMilchkarton** [comment]
Im not using optifine, and i downloaded my ExtraPlanets mod from curseforge so i guess optifine isnt an option? i just think there is something wrong with the ExtraPlanets leaves source code not registring to render blocks behind the leaves, similar to vanilla leaves or vanilla glass blocks

**Comment by DarkMatterXCIX** [comment]
ohhh i see!! i looked at your bottom picture! yes i had the same issue as your top one does

**Comment by MJRLegends** [comment]
Yeah its intended as leaves  in real life are intended

**Comment by MJRLegends** [comment]
This is intended, for my leaves i dont have fancy and fast types they are all fancy which match vanilla  see https://d1u5p3l4wpay3k.cloudfront.net/minecraft_gamepedia/thumb/9/9b/Leaves.PNG/300px-Leaves.PNG?version=5bf7fc1f986e7122c0d5a5bb5c505212
