### ISSUE TITLE
[1.12.2] Crash when launching with Tier 10 rocket

### ISSUE THREAD

**Issue by DarkMatterXCIX** [MJRLegends/ExtraPlanets#231]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
yes
### Description of Issue
[Description of the issue]
Crashes when pressing launch in rocket
### Steps to Reproduce Issue
1. [First step] I placed down tier 3 launch pad 5x5, then placing pre fueled tier 10 rocket onto pad
2. [Second step] i then got into rocket, double tapped space to launch! and Crash! normal galacticraft rockets seem to work.

**Crash log/Log (if applicable):**
https://pastebin.com/cc2v2u56

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
Extra Planets 1.12.2-0.1.9
**Where did this bug happen:** [Single Player or Server]
Server

### Additional Information
[Any other information that may be able to help me with the problem]
Just the usual, thanks again!

**Comment by MJRLegends** [comment]
Im updating the MC 1.12.2 version to fix this right now, thanks for the bug report

**Comment by MJRLegends** [comment]
This is proving hard to find the issue but i will find it dont worry :D

**Comment by MJRLegends** [comment]
I think this is a GC issue, im talking to the developer on it :D will get back to you on this issue

**Comment by DarkMatterXCIX** [comment]
okay.. so i didn't change anything and all the sudden it started working for me so idk what caused it i didnt do anything at all other than change it. were u able to replicate it?

**Comment by MJRLegends** [comment]
Yeah only seems to be on the Tier 10 Rocket and its due to the kepler22b planet

**Comment by DarkMatterXCIX** [comment]
Yeah I got my tier 10 rocket to work and I didn't change anything on my server, but it's random I guess

**Comment by DarkMatterXCIX** [comment]
https://pastebin.com/eFZtrvD8Is this the crash for Kepler 22B?>?? my server is getting this, idk if its extra planets or what

**Comment by MJRLegends** [comment]
@DarkMatterXCIX Yeah, no need to worry i know the kinda cause but not fully, Please leave it with me to deal with :D

**Comment by DarkMatterXCIX** [comment]
okay awesome! thanks much! is there a way i can delete the dimension in my folder so my world isnt corrupted as of rn? hahahaha

**Comment by MJRLegends** [comment]
Will be fixed in the next update that is out today

**Comment by MJRLegends** [comment]
Update has been uploaded to curseforge just waiting on approval
