### ISSUE TITLE
[1.8+] NullPointerException when disabling features in config

### ISSUE THREAD

**Issue by DerMilchkarton** [MJRLegends/ExtraPlanets#232]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue
when u disable the advanced version of for instance the refinery, but leave the ultimate version enabled the game crashes on startup, so maybe it shouldnt be possible to disable the advanced version with the ultimate being enabled

### Steps to Reproduce Issue
1. disable advanced refinery in config
2. enable ultimate refinery in config

**Crash log/Log (if applicable):** 
https://pastebin.com/kRuwDWd1

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [ExtraPlanets-1.7.10-1.9.7]

**Where did this bug happen:** [Single Player and Server]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Updates are rolling out as we speak, give them a bit to get approved by Twitch sorry for the delay
