### ISSUE TITLE
[1.12.2] Wrong biomes on some planets/moons

### ISSUE THREAD

**Issue by wamc2017** [MJRLegends/ExtraPlanets#233]
### ---Issue Report---

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** yes

### Description of Issue
Following planets/moons show the wrong biome [plains]:
Mercury
Deimos
Phobos
Ceres
Callisto
Ganymede
Iapetus
Rhea
Titania
Pluto

Titan also shows the wrong biome [Callisto]

### Steps to Reproduce Issue
1. Start a new world
2. Use /dimensiontp to teleport to any of those planets
3. Wait until you're on the ground and press F3 to check the biome

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
No crashlog.

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** 1.12.2-0.2.0

**Where did this bug happen:** Single Player

### Additional Information
Modlist: https://pastebin.com/jcwgXF7P

That's not the issue which happens when migrating a world from prior GC 132 without deleting the folders, it happens on a new world! :smile:
Also happened in 1.12.2-0.1.9, I only wanted to wait for 1.12.2-0.2.0 to see if that fixes this problem...

**Comment by MJRLegends** [comment]
@radfast :( i kinda wish i stayed in the old system

**Comment by MJRLegends** [comment]
@radfast ping, (i wished i stayed on the old way, this is exactly what i meant by i want it to be stable before i used it)

**Comment by radfast** [comment]
not sure without reviewing all your code

maybe all planets need the ```.setBiomeInfo()``` to be in preInit?

PLAINS is the default biome the game gives if it can't find the specified biome at all.  If your WorldProvider is correct, that should be replaced by ```BiomeAdaptive.biomeDefault``` on each dimension.

**Comment by MJRLegends** [comment]
I have more the whole registering of all planets and moons to the pre int

**Comment by MJRLegends** [comment]
I dont see this issue when i test it too...

**Comment by MJRLegends** [comment]
I've fixed the issue update is coming out now :D

**Comment by MJRLegends** [comment]
Just waiting on approval, sorry for any trouble caused @wamc2017 

Thanks for your time today :D @radfast

**Comment by wamc2017** [comment]
Thanks for the update, everything works as intended now. :+1: 
And you don't have to apologize, your mod is very big and based on another mod which made a "big" update changing some of the chore mechanics, I don't know how to develop mods myself, so I'm very glad you put so much effort into fixing bugs and make your great mod even better... :smile:

**Comment by MJRLegends** [comment]
No problem :)
