### ISSUE TITLE
Galacticraft Crash [1.12.2]

### ISSUE THREAD

**Issue by orangeninja27** [MJRLegends/ExtraPlanets#234]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes
### Description of Issue
When I launch Galacticraft with Extra Planets, it does not work. The game stops and acts like it has run out of RAM for textures, when it has not. Changing my RAM size has not worked. I used the newest build of Galacticraft, as well as the current Extra Planets build on Curseforge. And yes, I do have Forge 1.12.2-forge1.12.2-14.23.1.2555. This is NOT a FoamFix crash. (it's been shown that FoamFix will suggest to try the Lawful version in crashes completely unrelated with it, not to mention the crash has been happening before I even got FoamFix)

### Steps to Reproduce Issue
1. Download the files for Galacticraft
2. Download Extra Planets

Crash log https://pastebin.com/ZMn4aLcc

**Screenshots (if applicable):** 
None as of now, sorry.

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** ExtraPlanets-1.12.2-0.2.0

**Where did this bug happen:** [Single Player or Server]
Singleplayer

### Additional Information
[Any other information that may be able to help me with the problem]
This seems to happen regardless of what other mods I have installed, and the mod launches perfectly fine without Extra Planets.

**Comment by MJRLegends** [comment]
Sorry to say but this isnt a ExtraPlanets bug its a issue to where your gpu ram doesnt have enough room to load the textures.

I dont know of a fix for this sorry

**Comment by MJRLegends** [comment]
@orangeninja27 Please test latest versions of ExtraPlanets things have improved if you still wanna try it out you should need less GPU ram for ExtraPlanets now :D
