### ISSUE TITLE
Crash when entering any new planet

### ISSUE THREAD

**Issue by DarkMatterXCIX** [MJRLegends/ExtraPlanets#235]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue
[Description of the issue]
i always get this crash report, im not to sure if its just your mod, is it optifines custom colors or what?

### Steps to Reproduce Issue
1. [First step] launch rocket anywhere to any planet with custom sky color, it crashes
2. [Second step]

**Crash log/Log (if applicable):**
https://pastebin.com/Nmh2hW5x

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
ExtraPlanets-1.12.2-0.2.0.jar  
**Where did this bug happen:** [Single Player or Server]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Sorry to say but optifine isnt supported

**Comment by MJRLegends** [comment]
Yeah that could work
