### ISSUE TITLE
Minecraft Crash by Load or Create a World 1.7.10

### ISSUE THREAD

**Issue by xXDarkNovaXx** [MJRLegends/ExtraPlanets#238]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes
### Description of Issue
Minecraft crashed by load or create a World
Even with the update to a newer version, the problem always remains
Sorry for Error I have this Translate with my English is not good
I hope one can understand everything 

### Steps to Reproduce Issue
1. [I install the Mod and have start Minecraft an i have load my World]
2. [I have create a new World for Test]

**Crash log/Log (if applicable):** 
The Logs is from: 08.02.2018
Log 1: https://pastebin.com/YqM1pgdR
Log 2: https://pastebin.com/vntajL91
Log 3: https://pastebin.com/S7WhQ70B
FML Log 1: https://pastebin.com/FHphrfsA
FML Log 2: https://pastebin.com/p27w35E6

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'): [ before ExtraPlanets-1.7.10-1.9.5]
                                                   [Since 08.02.2018 03:31 I have upgrade to ExtraPlanets-1.7.10-1.9.7]

**Where did this bug happen: [Singleplayer]

### Additional Information
[I have delete Easy Crafting because Easy Crafting and Extra Planet have a Conflict by load or Create a World. There was a crash to Main Menu. Easy Crafting is no longer in my Minecraft because it was not important and I wanted to use Extra Planets]

**Comment by MJRLegends** [comment]
You have dimension conflicts, you need to change the ids the crash log is saying in the ExtraPlanets config.

This is no way a bug, but thanks for the issue report

**Comment by xXDarkNovaXx** [comment]
In which log is that?

[java.lang.IllegalArgumentException: Could not get provider type for dimension -17, does not exist]
This Message is a ID conflict?

**Comment by MJRLegends** [comment]
Yeah
