### ISSUE TITLE
[1.8+] Machines Power input on wrong side for some Machines

### ISSUE THREAD

**Issue by EmosewaPixel** [MJRLegends/ExtraPlanets#239]
### Description of Issue
 The Advanced and Ultimate machines simply don't accept any power.

### Steps to Reproduce Issue
1. Put a machine next to any type of generator/cable

**Screenshots (if applicable):
![image](https://user-images.githubusercontent.com/25333164/35991305-1d1b9d36-0d07-11e8-8e23-24943009c8f7.png)

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** 1.12.2-0.2.1

**Where did this bug happen:** Single Player

**Comment by wamc2017** [comment]
I thought I posted something about this issue.... :smile:

The machines accept power at the wrong side I think:

![2018-02-08_21 34 06](https://user-images.githubusercontent.com/33242447/35996811-cc63d384-0d17-11e8-8641-fc5163c0a784.png)

**Comment by MJRLegends** [comment]
Thanks will be fixed in the next update

**Comment by MJRLegends** [comment]
Updates are currently rolling out as we speak, please give them a short while for them to show on Curseforge
