### ISSUE TITLE
[1.8+] Some wrong Oredictionary entrys

### ISSUE THREAD

**Issue by wamc2017** [MJRLegends/ExtraPlanets#240]
### ---Issue Report---
**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** yes

### Description of Issue
Checked some oredictionary entries today, because some Tin smelted into some Copper while playing :smile:

Keppler 22B Iron: https://github.com/MJRLegends/ExtraPlanets/blob/dev_1.12.2/src/main/java/com/mjr/extraplanets/blocks/ExtraPlanets_Blocks.java#L1212 (there is some whitespace between or and e :D)
Keppler 22B Copper: https://github.com/MJRLegends/ExtraPlanets/blob/dev_1.12.2/src/main/java/com/mjr/extraplanets/blocks/ExtraPlanets_Blocks.java#L1213 (Metadata should be 4 instead of 3)
Keppler 22B Tin: https://github.com/MJRLegends/ExtraPlanets/blob/dev_1.12.2/src/main/java/com/mjr/extraplanets/blocks/ExtraPlanets_Blocks.java#L1213 (Metadata should be 3 instead of 4)
Uranus White Gem Ore: https://github.com/MJRLegends/ExtraPlanets/blob/dev_1.12.2/src/main/java/com/mjr/extraplanets/blocks/ExtraPlanets_Blocks.java#L1123 (Metadata should be 7 instead of 6)
Block of White Gem: https://github.com/MJRLegends/ExtraPlanets/blob/dev_1.12.2/src/main/java/com/mjr/extraplanets/blocks/ExtraPlanets_Blocks.java#L1125 (Metadata should be 8 instead of 7)

Not that much of an issue, but I think you should know about it... :smiley: 

### Steps to Reproduce Issue
..

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
...

**Screenshots (if applicable):** 
...

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** 1.12.2-0.2.1

**Where did this bug happen:** Singleplayer (but should affect also multiplayer)

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Will be fixed in the next update

**Comment by MJRLegends** [comment]
Updates are rolling out as we speak, give them a bit to get approved by Twitch sorry for the delay
