### ISSUE TITLE
[1.11+] Crash/Server Overload related to Launch Pads

### ISSUE THREAD

**Issue by CDAGaming** [MJRLegends/ExtraPlanets#241]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

### Description of Issue
A Crash and Server Error/Overload occures between Hwyla and ExtraPlanets. Talking with TehNut via https://github.com/TehNut/HWYLA/issues/112 It seems that the issues falls onto this mod unfortunately.

### Steps to Reproduce Issue
Unknown, as It only occurs some times.

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
https://hastebin.com/iqejijazos.sql (Client Side Crash)
https://hastebin.com/fetavubayu.vbs (Server-Side, after I crash)

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
1.12.2-0.2.1 (Has occurred on Older Versions)
**Where did this bug happen:** [Single Player or Server]
Both
### Additional Information
[Any other information that may be able to help me with the problem]
Reference: https://github.com/TehNut/HWYLA/issues/112

**Comment by TehNut** [comment]
https://github.com/MJRLegends/ExtraPlanets/blob/e3060ce4ef6b665011086e9619337fc78f9b22c0/src/main/java/com/mjr/extraplanets/blocks/BlockCustomMulti.java#L180-L196

**Comment by seeker2921** [comment]
I just added this mod today, in testing I lay a powered launch pad and it crashes. I come here and I see that the Dev is already on top of it! 14 hours from issue report to a fix. that's simply awesome!

@MJRLegends When do you plan to send out the next update? Would it be quicker just to compile from source to get the fix?

**Comment by MJRLegends** [comment]
Within the next 48 hours you can always remove waila/Hwyla for the time being

**Comment by MJRLegends** [comment]
Updates are rolling out as we speak, give them a bit to get approved by Twitch sorry for any pain caused from this bug :D
