### ISSUE TITLE
[1.7+ Excluding 1.12.2] Creative Tabs crash when disabling certain config options

### ISSUE THREAD

**Issue by DerMilchkarton** [MJRLegends/ExtraPlanets#242]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

### Description of Issue
when in creative mode, changing creative tab page causes a nullpointer crash

### Steps to Reproduce Issue
1. go creative mode
2. change page 

**Crash log/Log (if applicable):** https://pastebin.com/n5JjUsp5
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [ExtraPlanets-1.7.10-1.9.7]

**Where did this bug happen:** [Single Player]

### Additional Information
modlist: Galacticraft Core, Galacticraft Planets, Micdoodle Core, Extra Planets

**Comment by MJRLegends** [comment]
Please can you send me a copy of your config file for ExtraPlanets

**Comment by DerMilchkarton** [comment]
https://pastebin.com/BMu4XXJa

**Comment by MJRLegends** [comment]
Thanks i can fix i think i know the issue but you can use nei for the meantime to spawn stuff in

**Comment by DerMilchkarton** [comment]
yeah sure, just wanted to tell u the issue :)

**Comment by xJon** [comment]
@MJRLegends Any update? A lot of people are complaining in [my modpack's repo](https://github.com/xJon/The-1.7.10-Pack) :P

**Comment by MJRLegends** [comment]
You should be using jei, people shouldnt be playing a mod pack in creative mode

**Comment by MJRLegends** [comment]
You should be using nei, people shouldnt be playing a mod pack in creative mode

**Comment by xJon** [comment]
@MJRLegends You're telling me.. but as thousands of people play my modpack, I get dozens of reports about this creative tab bug. Could be nice if it has a fix :)

**Comment by MJRLegends** [comment]
@xJon It will have a fix but its not a major issue, you can enable the config options you disabled to stop it crashing the meantime. I appreciate your situation but theres many of ways around it and the creative menus are something that is optional to use when it comes to modded.

Updates will be out soon but i currently have real life things to attend too

**Comment by MJRLegends** [comment]
@xJon Extending on the message above,

Most of the issues you have gotten are back in August 2017 :D Reporting the bug back during August 2017 would of been the best thing as i would of fixed it for you back then :D

**Comment by xJon** [comment]
Yes I know it's a minor issue :) That's why I thought it would already be reported or something. It's no big deal, but it's nice to have it fixed. I'll make sure to update the mod in the next modpack update!

**Comment by MJRLegends** [comment]
Updates are currently rolling out as we speak, please give them a short while for them to show on Curseforge

**Comment by xJon** [comment]
I still can't find a 1.7.10 build with the fix?

**Comment by MJRLegends** [comment]
Yeah only 1.8+ has the fix atm

**Comment by MJRLegends** [comment]
I still need to update the 1.7.10 with it

**Comment by MJRLegends** [comment]
Will get it done today if i can do

**Comment by MJRLegends** [comment]
@xJon I will have the 1.7.10 out today that includes this fix, and for 1.12.2 it will be this weekend

**Comment by MJRLegends** [comment]
Update has been uploaded for MC 1.7.10 with this fix sorry for the delay :D
