### ISSUE TITLE
Server Side Crash on ExtraPlanets // MJRLegendsLib

### ISSUE THREAD

**Issue by CDAGaming** [MJRLegends/ExtraPlanets#244]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No] Yes

### Description of Issue
Exactly as title implies, a server side crash on ExtraPlanets & MJRLegends Lib

### Steps to Reproduce Issue
1. Use ExtraPlanets v0.2.3 with MJRLegendsLib v1.0.9 or v1.0.8

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
https://hastebin.com/ivadavasep.sql

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
ExtraPlanets v0.2.3
MJRLegendsLib v1.0.8 & v1.0.9

**Where did this bug happen:** [Single Player or Server]
Server, though SP not tested

**Comment by CDAGaming** [comment]
Saw Fix, Closing (https://github.com/MJRLegends/MJRLegendsLib/commit/bc4c7e10b5219c75d8da7f6637383c81b38161ad)

**Comment by MJRLegends** [comment]
Yes please make sure you reporting stuff correctly this is like the 4th time now

**Comment by MJRLegends** [comment]
Thanks for the bug report though
