### ISSUE TITLE
ExtraPlanets Server Lag

### ISSUE THREAD

**Issue by HideAwayDk** [MJRLegends/ExtraPlanets#245]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

### Description of Issue
Server lag when ExtraPlantes is installed

### Steps to Reproduce Issue
1. Lag comes when the server is runing ExtraPlantes 
2. None

**Crash log/Log (if applicable):** No crash log but i did talk to you aboudt the .nps file on discord
> *How do i locate a crash log on Minecraft on Curse/Twitch? see*

> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** ExtraPlanets-1.12.2-0.2.2

**Where did this bug happen:** Server

### Additional Information
Link to the .nps file:
http://extremtech.net/_files/lagExtraPlanets.nps

**Comment by MJRLegends** [comment]
Your sample doesnt contain anything from ExtraPlanet which is causing lag, if you are unable to prove its ExtraPlanets please post back as from our convo earlier you were having server lag by a backpacks mod.

**Comment by MJRLegends** [comment]
If you have any more comments for this please post them here, please dont make another issue for it :D

**Comment by HideAwayDk** [comment]
As i told you MJRLegends, iam not a modder or anything i just know the 1st think i tryed to remve after i did see the sponge timings was remove the backpack mod, and that didden help, then i tryed to remove GC and EP that removede the lag, i then tryed to only use GC and no EP and the lag is still gone, but when i put in EP it strat lagging again, but anyway i expaited that anwser anyway, so np i can live with GC and no EP, just trying to let you know

**Comment by MJRLegends** [comment]
![](https://i.gyazo.com/27849531be3a82ae2de12eec42893a88.png)
![](https://i.gyazo.com/5472019b8203e608686e1d39d6ed4992.png)
![](https://i.gyazo.com/3edaffc647d006c06c51a741343c57b6.png)

unless i see proof of lag with a sampler or things like tick profiler i cant do anything for you. Its impossible for me to fix something that doesnt show

**Comment by MJRLegends** [comment]
also note your world will lag on worldgen this is part of minecraft

**Comment by MJRLegends** [comment]
The biggest lag on your server is entities such as Creepers, this is in no way related to ExtraPlanets too i dont touch the creeper code.

**Comment by HideAwayDk** [comment]
ofc it will lag when all the worlds are created, i did wait for that to complete shot down the server er stated it again, i cant proof anything beside there is lag and you can log on and try it for your self, and when there is no EP there is no lag, anyway as i told you, i can live with GC and no EP just letting you know

**Comment by MJRLegends** [comment]
You need to understand, you need to prove this with a sample or tick profiler. I cant work off it lags for you but for no one else it seems fine... sorry

**Comment by HideAwayDk** [comment]
its okay MJRL i did try all i can to help, with the .nps file, cant do much more iam sorry i cant be to any help

**Comment by MJRLegends** [comment]
If extraplanets was causing lag it would show in the sample. 10ms of your server thread is due to creeper related actions

![](https://i.gyazo.com/9ac34f3c77213c4e4d4a02bc2b2554ad.png)

removing this 10mc brings it down to 40mc ish which is normal and would give you 20tps for sure

**Comment by MJRLegends** [comment]
Due to im seeing a bug here it will remain closed in till anything to posted to show this lag pointing to anything but creepers

**Comment by MJRLegends** [comment]
From what i can see your server has tps 20 even being at 50ms

**Comment by MJRLegends** [comment]
Also disabling the Mekanism voice server might help you

**Comment by HideAwayDk** [comment]
yeah its np, but i cant play with blocks the repop after got mined from time to time or mobs flying in the air , and the only thing i found trying to remove that worked was the mod, All of my worlds are on 20 TPS when i use /forge tps and low ms, but it still comes and i cant play with that, anyway this is just a waste of your and my time, so lets close it here. Thanks for the help take care MJRL :)

**Comment by MJRLegends** [comment]
No problem, im happy to help you more if you can show something ExtraPlanets causing lag like with tick profiler or that sampler mod :D

**Comment by HideAwayDk** [comment]
yeah i made that file and there was lag when it was runing, so if you cant find it there i guess iam out of luck
