### ISSUE TITLE
[1.12.2] Issues with Moon Biomes and Generation

### ISSUE THREAD

**Issue by RoseQuartz-z** [MJRLegends/ExtraPlanets#246]
### ---Issue Report---

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

### Description of Issue
With the new MJRLegendsLib update, I can now access all planets, (including Mars and Venus), but there seems to be bugs with the moons. I spawned on the Earth's moon, and saw alerts telling me that I was under high pressure. The sky was also red, and the sun looked way farther away than it should have looked. In addition, the Journeymap mod told me that there were several biomes in the landscape, all named after other moons (Titan, Triton, etc.). I shrugged it off, thinking it wasn't much of a problem. I then tested out Mars and Neptune, and there were absolutely no issues whatsoever. I decided to attempt returning to the moon, when I ran into the infinite loading screen again - after about seven minutes, I closed it. The next day, I booted up Minecraft again, and it spawned me in a strange landscape made of Oberon stone, but it was marked by Journeymap as "Phobos". Attached is a screenshot of the strange Oberon/Phobos hybrid.

### Steps to Reproduce Issue
1. Update MJRLegendsLib
2. Travel to a moon

**Crash log/Log (if applicable):** No crash log available.

**Screenshots (if applicable):** 
![2018-02-19_10 50 14](https://user-images.githubusercontent.com/36617928/36399606-6ed23aea-1581-11e8-927f-718a5501edb3.png)
**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** ExtraPlanets-1.12.2-0.2.3.jar and MJRLegendsLib-1.12.2-1.1.0.jar

**Where did this bug happen:** Single Player

### Additional Information
Again, I am running Biomes O'Plenty, but I doubt that's the issue because it doesn't affect these dimensions. I am also running Dr. Zhark's Mo' Creatures mod, which has been shown to have some conflicts in other occasions.

**Comment by MJRLegends** [comment]
Your world got messed up plesse test with just GC and ExtraPlanets and MJRLegendsLib and on a new world

**Comment by RoseQuartz-z** [comment]
I cleared out some of my more obsolete mods and that seems to have done the
trick. I'm not 100% sure which mod caused the conflict, but I'm willing to
bet that it was Dr. Zhark's Mo' Creatures Mod because it's terribly
optimized and it's the only other mod I have that adds other dimensions. I
was thinking a possible fix would be to go into the Extra Planets config
and change some of the dimension ID's, but to be frank, I'm too tired and
lazy to do that!
Thank you for your patience.
Jaelyn
