### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Dyneteve** [MJRLegends/ExtraPlanets#248]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue
[Description of the issue]
It crashes the game when going to mercury

### Steps to Reproduce Issue
1. [First step]
Get a tier 3 rocket
2. [Second step]
Go to mercury

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
https://pastebin.com/snhxCsFc

**Screenshots (if applicable):** 
No need

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
Latest

**Where did this bug happen:** [Single Player or Server]
Server

### Additional Information
After reopening the game agin it spawns me on mercury without crashing

**Comment by MJRLegends** [comment]
Optifine isnt supported please remove it
