### ISSUE TITLE
Phobos lead ore gives IC2 lead ore

### ISSUE THREAD

**Issue by PulzHF** [MJRLegends/ExtraPlanets#249]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

### Description of Issue
Smelting Phobos lead ore gives IndustrialCraft 2 lead ingot, rather than a ExtraPlanets lead ingot.

### Steps to Reproduce Issue
1. Smelt Phobos ore
2. Be disappointed

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
ExtraPlanets-1.7.10-1.9.7

**Where did this bug happen:** [Single Player or Server]
Server & Singleplayer
### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
This is a conflict within your pack as the lead ore is get to give you a ore dict version

**Comment by MJRLegends** [comment]
It will pick the first ore dict version of lead

**Comment by PulzHF** [comment]
I see. I fixed this by adding Ore Dictionary Converter to the pack.

Thanks anyway.
