### ISSUE TITLE
[1.7.10-1.9.8] Server crash upon visiting Venus

### ISSUE THREAD

**Issue by PulzHF** [MJRLegends/ExtraPlanets#252]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

### Description of Issue
If this isn't something on your end, I apologize- but it is only occurring (to my knowledge) to Venus within ExtraPlanets. 
A straightforward issue- crashing when visiting Venus.

### Steps to Reproduce Issue
1. Visit venus
2. Enjoy the restart

**Crash log/Log (if applicable):**
This seems to be the most common crash log I see
https://pastebin.com/u9TEFf21
But I've also seen this one
https://pastebin.com/Vp1CCi3m

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
1.7.10-1.9.8

**Where did this bug happen:** [Single Player or Server]
Server, I haven't managed to replicate this in Single Player (yet!)

**Comment by MJRLegends** [comment]
Changing the option "load chunk on request" to false in cauldron.yml

Its a kcauldron issue

**Comment by PulzHF** [comment]
After applying this change and setting the cauldron.yml to read only, I still get crashes when visiting Venus.
https://pastebin.com/FTBAmHsu
