### ISSUE TITLE
[1.12.2] recipes for radiation layers don't use oredict

### ISSUE THREAD

**Issue by lag42** [MJRLegends/ExtraPlanets#253]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]yes

### Description of Issue
the recipes for radiation layers don't use oredict so it uses only the lead from this mod making it really obnoxious to craft
### Steps to Reproduce Issue
1. attempt to craft a radiation layer with another mod's lead
2. be annoyed

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

**Screenshots (if applicable):** 
https://imgur.com/a/CX0RA
**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]1.12.2-0.2.6

**Where did this bug happen:** [Single Player or Server]Single Player

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
This is intended

**Comment by MJRLegends** [comment]
I will change it though thanks for the report

**Comment by MJRLegends** [comment]
Updates are being released as we speak they will be showing on CurseForge as soon as they approve them :D
