### ISSUE TITLE
[1.11+] Unnecessary server console spam leading to low TPS

### ISSUE THREAD

**Issue by b0bst3r** [MJRLegends/ExtraPlanets#254]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No] Yes

### Description of Issue
Server console is being spammed non-stop dozens of times per second, this as we all know causes TPS to drop as the server struggles to keep up.

The number varies at the end and I have figured out what's causing it, the number represents the amount of Potassium Iodide in the Basic Chemical Injector.  I played around with adding and removing the amounts to change the figure and it corresponded each time.  When the machine stops making, the spam stops in the server console.

02.03 18:16:23 [Server] INFO 3 
02.03 18:16:23 [Server] INFO 3 
02.03 18:16:23 [Server] INFO 3 
02.03 18:16:23 [Server] INFO 3 
02.03 18:16:23 [Server] INFO 3 
02.03 18:16:23 [Server] INFO 3 
02.03 18:16:23 [Server] INFO 3 
02.03 18:16:23 [Server] INFO 3 
02.03 18:16:23 [Server] INFO 3 
02.03 18:16:23 [Server] INFO 3 
02.03 18:16:23 [Server] INFO 3 
02.03 18:16:23 [Server] INFO 3 
02.03 18:16:23 [Server] INFO 3 
02.03 18:16:23 [Server] INFO 3 
02.03 18:16:23 [Server] INFO 3 
02.03 18:16:23 [Server] INFO 3 
02.03 18:16:23 [Server] INFO 3 
02.03 18:16:23 [Server] INFO 3 
02.03 18:16:23 [Server] INFO 3 
02.03 18:16:23 [Server] INFO 3

### Steps to Reproduce Issue
1. My Anti-rad pot production setup is like this (see below screenshot)  those are Mekanism power cables and Mekanism logistical item and fluid transport pipes.
2. I drop the drums of Liquid Crystaline and Infested water (both shown) down and place a container on top of the hopper with potash inside, everything else is automatic.
3. Basic Chemical Injector is making Potassium Iodide and the number being spammed in the server console appears to match that of the completed Potassium Iodide quantity inside the Chemical Injector.

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

Rather oddly I cannot find said spam in any server log file it just appears to be spamming the console and not logging it.

**Screenshots (if applicable):**  
https://i.imgur.com/uhXF3D8.jpg

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
ExtraPlanets-1.12.2-0.2.6

**Where did this bug happen:** [Single Player or Server]
In server console

**Comment by MJRLegends** [comment]
Please provide your full log files

**Comment by b0bst3r** [comment]
I can but as I said it's not being logged.

**Comment by MJRLegends** [comment]
Dont worry i've fixed it already

**Comment by b0bst3r** [comment]
https://pastebin.ubuntu.com/p/77Rd5hzqFW/ Line 47691 onwards for more

**Comment by MJRLegends** [comment]
Updates are being released as we speak they will be showing on CurseForge as soon as they approve them :D
