### ISSUE TITLE
[1.12.2]Crash when disabling Ceres in the Config

### ISSUE THREAD

**Issue by Boolyman** [MJRLegends/ExtraPlanets#256]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue
[Description of the issue]
Game crashes when I attempt to load after disabling planets in the config.

### Steps to Reproduce Issue
1. [First step]
Disable planets.

2. [Second step]
Load game.

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
https://pastebin.com/JwG76V8K
https://pastebin.com/hpGCEX18

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
0.2.6

**Where did this bug happen:** [Single Player or Server]
Single Plater

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
see comments in #255 as already fixed :D

**Comment by MJRLegends** [comment]
For future reference for Fixed via https://github.com/MJRLegends/ExtraPlanets/commit/c9eec3e045808f8fb39e31e2f3a808729b6444e8

**Comment by Boolyman** [comment]
Thank you.

**Comment by MJRLegends** [comment]
Update is being released as we speak it will be showing on CurseForge as soon as they approve it :D
