### ISSUE TITLE
[1.10+] Axes not being treated as Axes, when using Tool Progression

### ISSUE THREAD

**Issue by Kaperios** [MJRLegends/ExtraPlanets#257]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

### Description of Issue
So, apparently axes in ExtraPlanets are not axes. When i try to break a log which is set to require tool to break I can't. Every other axe works

### Steps to Reproduce Issue
1. Change wood block properties to require tool to break.
2. Try to break wood with ExtraPlanets' axe.

**Crash log/Log (if applicable):** No crashlog

**Screenshots (if applicable):** No Screenshots

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** 1.12.2-0.2.8

**Where did this bug happen:** Single Player

### Additional Information
For changing wood properties i've used mod called [Tool Progression](https://minecraft.curseforge.com/projects/tool-progression)

**Comment by MJRLegends** [comment]
does it work on vanilla wood?

**Comment by Kaperios** [comment]
I've tried it only on vanilla wood

**Comment by MJRLegends** [comment]
Yeah i can fix it no worries, its a MJRLegendsLib issue not ExtraPlanets :D

**Comment by MJRLegends** [comment]
I've linked the MJRLegendsLib issue report above, any more comments for this issue please post over at that issue

https://github.com/MJRLegends/MJRLegendsLib/issues/4
