### ISSUE TITLE
[1.7+] Kepler22b dense coal block has wrong meta

### ISSUE THREAD

**Issue by b0bst3r** [MJRLegends/ExtraPlanets#258]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No] Yes

### Description of Issue
Kepler22b dense coal block furnaces into a textureless block of coal with incorrect meta (according to crafttweaker).

Doing a /ct hand on a normal block of coal returns <minecraft:coal_block>
Doing a /ct hand on a block of coal furnaced from the dense coal block returns <minecraft:coal_block:1>

If you take the textureless coal block and place it in to the world and then break it, it reverts to a proper coal block.

### Steps to Reproduce Issue
1. Furnace a dense coal block
2. Look at coal block it returns it's textureless and does show up the same data as a normal coal block (se images below.

**Screenshots (if applicable):** 
Normal Block of coal - 

![64lpnr1](https://user-images.githubusercontent.com/2760085/37074236-b3ee25e6-21c3-11e8-9457-c3e9540f92b9.png)

Your coal block furnaced from a dense coal block -

![rudijf5](https://user-images.githubusercontent.com/2760085/37074243-c53a26f6-21c3-11e8-9edf-a3096fd780ae.png)

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]

ExtraPlanets-1.12.2-0.2.6

**Where did this bug happen:** [Single Player or Server]

Server

**Comment by MJRLegends** [comment]
Updated version to fix this issue are being uploaded as we speak
