### ISSUE TITLE
[1.8+] Known change with build 502+ of GC

### ISSUE THREAD

**Issue by wamc2017** [MJRLegends/ExtraPlanets#261]
### ---Issue Report---
**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** yes

### Description of Issue
Game crashes during start, if Galacticraft is updated to 4.0.1.152 (4.0.151 works fine... :))

### Steps to Reproduce Issue
1. Update to 4.0.1.152
2. Start the game

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
https://pastebin.com/D9Ary9ns

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** 1.12.2-0.2.8

**Where did this bug happen:** Both

**Comment by MJRLegends** [comment]
Yeah ive already made the changes needed just not released anything but thank you

**Comment by MJRLegends** [comment]
Updated version to fix this issue are being uploaded as we speak
