### ISSUE TITLE
Jupiter Dungeon Walls Breaking with Bat Attack 1.12.2

### ISSUE THREAD

**Issue by mgwerner** [MJRLegends/ExtraPlanets#262]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue
Bat attack explosions break the dungeon walls, allowing in lava flows, which destroy loot after bat is killed.  Key is destroyed, chest inaccessible.

### Steps to Reproduce Issue
1. Fight Bat
2. See lava

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
1.12.2-0.2.8
**Where did this bug happen:** [Single Player or Server]
SSP
### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Im unable to reproduce this, please can you provide anything else that will help me see this issue

**Comment by MJRLegends** [comment]
Also please test with latest which is 1.12.2-0.2.9

**Comment by mgwerner** [comment]
I just did it again, but did not get a screenshot.  It seems that most of the lava leakage is from where the bat fires against the wall and not toward the player, the explosion takes out the glowstone blocks.  There were two places about halfway down the wall with dungeon blocks blown out, and lava coming through.  I am unsure of how that came to pass.  I was at the ceiling with a jetpack and volleyed almost every shot back to the bat.  The two that I missed exploded at the ceiling with me, not against the wall.

Suggestions?

**Comment by MJRLegends** [comment]
Ok so your saying the glowstone gets hit on the roof?

**Comment by mgwerner** [comment]
OK, will update this afternoon and try again.

I suspect it is the glowstone, since the leaks are either one or two blocks and are widely separated.  I filled in the holes after defeating the bat, and the glowstone was missing in that area.

**Comment by MJRLegends** [comment]
Ok yeah this is intended, you can always stay away from the roof. Glowstone isn't blast protected which is the same with all tiers of dungeons. thanks for the bug report but on this occasion its not a bug :D

**Comment by mgwerner** [comment]
Understood.  Thanks for the rapid feedback.

Can something be done about the key?  Perhaps making it resuable once it is placed in a chest.  I have half a dozen dungeons with sealed chests, since the key burned.

**Comment by MJRLegends** [comment]
![2018-03-14_02 33 59](https://user-images.githubusercontent.com/8526321/37380350-2e8ff57e-2730-11e8-9c46-95d8405c51c7.png)
The floor or walls have no glowstone for this reason. The roof does but its very high up. the best was to fight bosses is always on the floor for the best chance of getting hit correctly and not take out glowstone.

Sorry no if theres lava in the room its down to the player to get rid of it, this matches all dropped items in mc

**Comment by mgwerner** [comment]
OK, thanks anyway.  

Great mod, keep it up!

**Comment by MJRLegends** [comment]
No problem let me know if you get any other issues :D
