### ISSUE TITLE
Unclosable Planet selection map + not sure if this belongs here

### ISSUE THREAD

**Issue by 1a310** [MJRLegends/ExtraPlanets#263]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

### Description of Issue
 stuck on the planet selection thing and I dont see any ways to get out..

### Steps to Reproduce Issue
1. [I launched a t1 galacticraft rocket w/ 36 slots off a sattelite]
2. [I am stuck in this shit that I cant get out of no matter what I tried..]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

**Screenshots (if applicable):** 
![2018-03-15_23 58 58](https://user-images.githubusercontent.com/37432437/37505394-1c4dcc06-28bb-11e8-9645-4b58007d90db.png)
![2018-03-16_01 37 35](https://user-images.githubusercontent.com/37432437/37505406-24cd63aa-28bb-11e8-9d66-87ca9b8a503c.png)
![2018-03-16_01 37 39](https://user-images.githubusercontent.com/37432437/37505410-2762c42a-28bb-11e8-818d-fc77120cf56a.png)
![2018-03-16_01 37 41](https://user-images.githubusercontent.com/37432437/37505419-2c17de2e-28bb-11e8-936c-08bd4e8db35d.png)
![2018-03-16_01 37 44](https://user-images.githubusercontent.com/37432437/37505422-2ea152f6-28bb-11e8-9e98-d24b7bf3c826.png)
![2018-03-16_01 37 47](https://user-images.githubusercontent.com/37432437/37505428-30ef329e-28bb-11e8-8d14-98a02eb87022.png)

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
GalacticraftCore&Galacticraft-planets 1.12.2-4.0.1.144 Planet progression 1.12.2-0.1.8 Extra Planets 1.12.2-0.2.6 on the mod pack Modern Skyblock 3 Departed 3.1.5.3 running forge 14.23.2.2624 launched from Twitch launcher
**Where did this bug happen:** [Server]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Wrong issue tracker post on Planet progression
