### ISSUE TITLE
Loader Exception crash

### ISSUE THREAD

**Issue by Foxgreat** [MJRLegends/ExtraPlanets#264]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [**Yes**]

### Description of Issue
Server-side crash on load of mods on spongeforge server.

### Steps to Reproduce Issue
1. Load Pack on SpongeForge 2963
2. Launch it

**Crash log/Log (if applicable):** [https://paste.ofcode.org/36EYaV4p2X2DrC2UCiFjymW (pastebin not works in my internet for now, strange)]

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [1.12.2-0.2.9]

**Where did this bug happen:** [Server]

**Comment by Foxgreat** [comment]
On crash i see that it causes on the final loading. Causes it some axe from extra planets

**Comment by MJRLegends** [comment]
Update MJRLegendsLib always update your mods
