### ISSUE TITLE
Unable to place rocket

### ISSUE THREAD

**Issue by DanTheDetermined** [MJRLegends/ExtraPlanets#266]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue
Can't place down ExtraPlanets Rockets.

### Steps to Reproduce Issue
1. Open Minecraft with mod and dependencies installed
2. Build launch pad
3. Right click on launch pad with a rocked tiers 4-10.
4. Nothing happens

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** 1.12.2, 0.3.0

**Where did this bug happen:** Single Player
### Additional Information
I don't get any errors of any kind in chat, but I did get the "wiki help" message in chat the first time I attempted to place it.

**Comment by MJRLegends** [comment]
Use the tier 2 and 3 launch pads as it says on the tool tip of the rockets
