### ISSUE TITLE
[Question] Something about localization

### ISSUE THREAD

**Issue by SihenZhang** [MJRLegends/ExtraPlanets#272]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

### Description of Issue
Hey, MJRLegends. There are some problems about Chinese localization. In English, an adverbial is behind the predicate, while in Chinese, an adverbial is in front of the predicate. So you can have a look at below. https://github.com/MJRLegends/ExtraPlanets/blob/841b51584abd146a3bcbc688ab9bc70e61a5e8ba/src/main/resources/assets/extraplanets/lang/en_US.lang#L490-L502
https://github.com/MJRLegends/ExtraPlanets/blob/841b51584abd146a3bcbc688ab9bc70e61a5e8ba/src/main/resources/assets/extraplanets/lang/en_US.lang#L522-L523

And in https://github.com/MJRLegends/ExtraPlanets/blob/841b51584abd146a3bcbc688ab9bc70e61a5e8ba/src/main/resources/assets/extraplanets/lang/en_US.lang#L516-L520 , each part of the sentences has been separated, which is a big challenge for me.

So what I want to say is : 
1. Since you have set different keys according to the various fluids, would you please combine the first half part and the second half? 
2. Also, you can take a look at how Foresty handles it. Just like below. 
https://github.com/ForestryMC/Forestry-Localization/blob/24c55f48250a598b8565f3905ce8398f69a81368/assets/forestry/lang/en_US.lang#L237-L238  

I'll appreciate it if you can do these changes for easier, more comfortable localization.

**Comment by MJRLegends** [comment]
Thanks for the suggestion i will see if i can change anything but i might not be able to do much for it

**Comment by MJRLegends** [comment]
Cant really do anything for this sorry
