### ISSUE TITLE
[1.7.10] Crash of Minecraft after a while when playing 

### ISSUE THREAD

**Issue by pitris90** [MJRLegends/ExtraPlanets#276]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues:** [Yes]

### Description of Issue
Crash of the game after a while. The game will simply crash after some time you play (time is no longer than 1-2 minutes)

### Steps to Reproduce Issue
1. Install Latest version of Extra Planets for 1.7.10 (2.0.0)
2. Have same mods as me (https://pastebin.com/33kCSsU0)

**Crash log/Log (if applicable):** https://pastebin.com/Gu2aMRMQ

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** 2.0.0

**Where did this bug happen:** SinglePlayer with Opened LAN

### Additional Information
I saw there is some Dimension error or what. Maybe its caused by conflict of Thaumcraft Eldritch dimension and this, but thats only my opinion. Please fix this, i want to have your mod in my custom private modpack :)

**Comment by MJRLegends** [comment]
This is a dimension id conflict you need to change them in the config. Its not a bug

**Comment by pitris90** [comment]
Ok, and how can I do it? I mean on which ID i can change this dimension. Thanks for reply
