### ISSUE TITLE
Startup crash 3.6.6

### ISSUE THREAD

**Issue by Cronosus** [MJRLegends/ExtraPlanets#28]
### Description of Issue
game crashed

### Steps to Reproduce Issue
1. start

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
http://pastebin.com/pAS6YRAq

**Version of Mod using:** [VERSION]
3.6.6

**Comment by MJRLegends** [comment]
What did you disable in the config?

**Comment by Cronosus** [comment]
http://pastebin.com/HgAZAHrT

**Comment by MJRLegends** [comment]
Give me 10-20 mins and i will have a bug fix out for you

**Comment by MJRLegends** [comment]
Released v1.0 Pre-3.6.7 is out give it 5 mins and it will show to download

**Comment by Cronosus** [comment]
thanks :)

**Comment by MJRLegends** [comment]
seems to be taking a bit for them to review the update on curse...

**Comment by MJRLegends** [comment]
https://minecraft.curseforge.com/projects/extraplanets/files/2327108

**Comment by MJRLegends** [comment]
@Cronosus please let me know if your issue is fixed :D

**Comment by Cronosus** [comment]
ah sorry
yes, its fixed
