### ISSUE TITLE
Crash while loading EP 1.12.2-0.3.2 

### ISSUE THREAD

**Issue by TempusFinis** [MJRLegends/ExtraPlanets#280]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue
[Description of the issue]

### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** 1.12.2-0.3.2 

**Where did this bug happen:** Single Player]

### Additional Information
[Any other information that may be able to help me with the problem]

Minecraft crashes while loading with other mods.

https://pastebin.com/U6CPg9aG

**Comment by MJRLegends** [comment]
Update mjrlegendslib

**Comment by MJRLegends** [comment]
Also wrong issue tracker its got nothing to do with ExtraPlanets

**Comment by MJRLegends** [comment]
Also make sure to check closed issues as this has been posted lots of times by now
