### ISSUE TITLE
Crash while going to Saturn.

### ISSUE THREAD

**Issue by TempusFinis** [MJRLegends/ExtraPlanets#281]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue
Game crashes after clicking Launch (Also countdown would go to 4 then back to 5 and repeated a few times is this Intentional?

### Steps to Reproduce Issue
1. Get to Space Tier 10 Rocket
2. Click launch on Saturn
**Crash log/Log (if applicable):** https://pastebin.com/TAzvkJiJ

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** 1.12.2 0.3.2

**Where did this bug happen:** Single Player

**Comment by MJRLegends** [comment]
Remove optifine its not supported

**Comment by TempusFinis** [comment]
Thank You!

**Comment by TempusFinis** [comment]
Specific Part or not? Thanks again (Part as in settings)

**Comment by MJRLegends** [comment]
Also make sure to check closed issues as this has been posted 10+ times by now
