### ISSUE TITLE
Add support for Radiation Shielding from Modular Powersuits Mod

### ISSUE THREAD

**Issue by MJRLegends** [MJRLegends/ExtraPlanets#282]
Add same system that space suit offers for Radiation Shielding module from Modular Powersuits Mod

**Comment by 23Link89** [comment]
And possibly grav boots aswell?

**Comment by ZenithAstralis** [comment]
I would also really like to see these implemented. The Extra Planets space suits aren't really very fun. Functional, but when more enjoyable alternatives clearly are trying to provide the same functionality, it would be nice to have a config option to enable compatibility with them.

**Comment by MJRLegends** [comment]
See https://github.com/MJRLegends/ExtraPlanets/issues/341
