### ISSUE TITLE
[1.12.2] Crash with bucket tool tips

### ISSUE THREAD

**Issue by The-Fireplace** [MJRLegends/ExtraPlanets#283]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

### Description of Issue
When I load a world, the game crashes.

### Steps to Reproduce Issue
1. Load the game
2. Attempt to load a world. I've only tested this in SP.

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
https://pastebin.com/bQ2JBG4D

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):**
ExtraPlanets 1.12.2-0.3.2
Galacticraft Core/Planets 1.12.2-4.0.1.174
Forge 14.23.3.2657

**Where did this bug happen:** Single Player

### Additional Information
The line numbers in the source don't match up with the line number in the log, but looking at the code, one thing I immediately saw (Which is probably unrelated to the issue) is that ItemStack is never supposed to be null in 1.12.2, so [here](https://github.com/MJRLegends/ExtraPlanets/blob/dev_1.12.2/src/main/java/com/mjr/extraplanets/client/handlers/MainHandlerClient.java#L357) you should check if !stack.isEmpty() instead of or in addition to null checking.

**Comment by MJRLegends** [comment]
Crash isnt to do with my mod sorry

**Comment by The-Fireplace** [comment]
@wamc2017 was correct, it was a Forge bug. Downgrading to 2655 fixed it.
