### ISSUE TITLE
[1.11+] Waila: NullPointerException Crash

### ISSUE THREAD

**Issue by artdude543** [MJRLegends/ExtraPlanets#284]
### ---Issue Report---

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

### Description of Issue
Reported on the SevTech tracker and Waila is telling us to report to the mod causing said issue 😄 (Linked our issue below)

User crafted a decontamination chamber to help me reduce their radiation.

**Crash log/Log (if applicable):** https://pastebin.com/vBufSaQF

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** 0.3.2

**Where did this bug happen:** Going to assume Single Player.

### Additional Information
Relation Issue: https://github.com/Darkosto/SevTech-Ages/issues/1909

**Comment by artdude543** [comment]
Thank you!

**Comment by MJRLegends** [comment]
Will be probably be releasing updates in the next day or so

**Comment by MJRLegends** [comment]
Updates have been upload to CurseForge :D
