### ISSUE TITLE
How does land on gas planets?

### ISSUE THREAD

**Issue by syrun97** [MJRLegends/ExtraPlanets#285]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue
[Description of the issue]
gas planet does not have surface area to land. because of that, you cant land on gas planet.
### Steps to Reproduce Issue
1. [First step]shoot a rocket to gas planets.
2. [Second step]LOL IM ON THE GAS PLANET THAT HAVE NO DIRTS TO LAND!

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
"Lateest" to "Oldest"
**Where did this bug happen:** [Single Player or Server]
is this intended?
### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Hey have a surface
