### ISSUE TITLE
High atmospheric pressure on the moon

### ISSUE THREAD

**Issue by 7eggert** [MJRLegends/ExtraPlanets#286]
### ---Issue Report---
**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

### Description of Issue
1) *High* pressure damage when not wearing space suit
2) while in base

### Steps to Reproduce Issue
1. Be without full space suit on a sealed mini-base (airlocks) on the moon -- before installing extra Planets, i could breath / the oxygen tank still doesn't empty while being there. The oxygen tanks don't empty while in that base.

2. The *high* atmospheric pressure of the moon will damage you (didn't happen without extra planets), inside and outside the sealed room

**Where did this bug happen:** [Single Player]

ExtraPlanets-1.10.2-1.0.5.jar
Galacticraft-Planets-1.10.2-4.0.1.174.jar
GalacticraftCore-1.10.2-4.0.1.174.jar
MicdoodleCore-1.10.2-4.0.1.174.jar
MJRLegendsLib-1.10.2-1.1.0.jar

**Comment by MJRLegends** [comment]
You need to put the ambient thermal controller in the oxygen sealers for it to work

**Comment by MJRLegends** [comment]
And then you need to wear a space suit for outside

**Comment by 7eggert** [comment]
Thanks, not intuitive for pressure, acceptable for radiation damage.

Still: HIGH pressure?
===

**Comment by MJRLegends** [comment]
Thats doesnt matter as long as your not taking damage your good the radation system you need to reduce which you can find the info in chat when going to a planet or moon and on the space suit tool tip

**Comment by ultramarines40** [comment]
this might be a tad bit late for this but i have the same problem and even when i use that thermal controller in the oxygen sealer it just does not work.

**Comment by MJRLegends** [comment]
Can more issues please make a new issue report
