### ISSUE TITLE
[1.8+] Basic Densifier Crash issue with any Fluid cables

### ISSUE THREAD

**Issue by billyma6** [MJRLegends/ExtraPlanets#288]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

### Description of Issue
When I connect a Thermal Foundation tank to the Basic Densifier using Thermal Dynamics Super Luminar Fluiduct, when the tank is set to output to the pipe and into the machine, it crashes once the liquid begins flowing.

### Steps to Reproduce Issue
1. Set down a Basic Densifier and give it power; I used a creative battery.
2. Place a Super Luminar Fluiduct to the left side of the machine, where the circle is on the side.
3. Place a tank full of fluid like Liquid Chocolate on top of that pipe.
4. Use the crescent hammer from Thermal Foundation to configure the tank to output to the bottom Fluiduct.

**Crash log/Log (if applicable):** https://pastebin.com/T63VKSUV
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

**Screenshots (if applicable):**

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** 0.3.2 and 0.3.3 for Minecraft 1.12.2

**Where did this bug happen:** Single Player

### Additional Information
After this crashed my game, it prevented me from going back onto that world. It appears at first glance to be something related to how the Basic Densifier machine refuses to accept fluids from any side at all.

**Comment by MJRLegends** [comment]
Thanks will take a look at this, i think i know the issue

**Comment by MJRLegends** [comment]
Seems its a issue with all fluid cables not just Thermal Dynamics but will be fixed in next update for MC 1.8+

**Comment by MJRLegends** [comment]
Updates are uploading as we speak
