### ISSUE TITLE
1.12.2 Newest mod version.

### ISSUE THREAD

**Issue by KrauzeBartek** [MJRLegends/ExtraPlanets#289]
Crash when I try land on any plant(any rocket tier)

---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.174.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.9.7-1.12.2-anarchy.jar)
Contact their authors BEFORE contacting forge

// Hey, that tickles! Hehehe!

Time: 4/22/18 12:44 AM
Description: Unexpected error

java.lang.ArrayIndexOutOfBoundsException: 58
	at CustomColors.getWorldSkyColor(CustomColors.java:1526)
	at net.minecraft.client.renderer.EntityRenderer.func_78466_h(EntityRenderer.java:2278)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1639)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1614)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1385)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at CustomColors.getWorldSkyColor(CustomColors.java:1526)
	at net.minecraft.client.renderer.EntityRenderer.func_78466_h(EntityRenderer.java:2278)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1639)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1614)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [GCEntityClientPlayerMP['Bartek'/90, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Chunk stats: MultiplayerChunkCache: 0, 0
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 1 total; [GCEntityClientPlayerMP['Bartek'/90, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2737)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:426)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_161, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3328167688 bytes (3173 MB) / 3936354304 bytes (3754 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms2048m -Xmn128m -XX:PermSize=128m -XX:MaxPermSize=128m -XX:+UnlockExperimentalVMOptions -XX:+AggressiveOpts -XX:+UseG1GC -XX:+OptimizeStringConcat
	IntCache: cache: 0, tcache: 0, allocated: 1, tallocated: 10
	FML: MCP 9.42 Powered by Forge 14.23.3.2669 Optifine OptiFine_1.12.2_HD_U_D1 22 mods loaded, 22 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                  | Version                  | Source                                    | Signature                                |
	|:--------- |:------------------- |:------------------------ |:----------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft           | 1.12.2                   | minecraft.jar                             | None                                     |
	| UCHIJAAAA | mcp                 | 9.42                     | minecraft.jar                             | None                                     |
	| UCHIJAAAA | FML                 | 8.0.99.99                | forge-1.12.2-14.23.3.2669.jar             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge               | 14.23.3.2669             | forge-1.12.2-14.23.3.2669.jar             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | micdoodlecore       |                          | minecraft.jar                             | None                                     |
	| UCHIJAAAA | foamfixcore         | 7.7.4                    | minecraft.jar                             | None                                     |
	| UCHIJAAAA | custommainmenu      | 2.0.8                    | CustomMainMenu-MC1.12.2-2.0.8.jar         | None                                     |
	| UCHIJAAAA | galacticraftcore    | 4.0.1.174                | GalacticraftCore-1.12.2-4.0.1.174.jar     | None                                     |
	| UCHIJAAAA | galacticraftplanets | 4.0.1.174                | Galacticraft-Planets-1.12.2-4.0.1.174.jar | None                                     |
	| UCHIJAAAA | mjrlegendslib       | 1.12.2-1.1.3             | MJRLegendsLib-1.12.2-1.1.3.jar            | b02331787272ec3515ebe63ecdeea0d746653468 |
	| UCHIJAAAA | extraplanets        | 1.12.2-0.3.3             | ExtraPlanets-1.12.2-0.3.3.jar             | b02331787272ec3515ebe63ecdeea0d746653468 |
	| UCHIJAAAA | foamfix             | 0.9.7-1.12.2             | foamfix-0.9.7-1.12.2-anarchy.jar          | None                                     |
	| UCHIJAAAA | waila               | 1.8.24                   | Hwyla-1.8.24-B39_1.12.jar                 | None                                     |
	| UCHIJAAAA | inventorytweaks     | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                  | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCHIJAAAA | jei                 | 4.9.0.163                | jei_1.12.2-4.9.0.163.jar                  | None                                     |
	| UCHIJAAAA | journeymap          | 1.12.2-5.5.2             | journeymap-1.12.2-5.5.2.jar               | None                                     |
	| UCHIJAAAA | metalchests         | v1.2.2.g3d3d54b          | MetalChests-v1.2.2.g3d3d54b.jar           | None                                     |
	| UCHIJAAAA | moreplanets         | 2.0.14                   | More-Planets-1.12.2-2.0.14-GC156.jar      | b3468b224a74e296555ad7efeb35f482e6f445de |
	| UCHIJAAAA | resourceloader      | 1.5.3                    | ResourceLoader-MC1.12.1-1.5.3.jar         | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| UCHIJAAAA | treechopper         | 1.2.4                    | TreeChopper-1.12.2-1.2.4.jar              | None                                     |
	| UCHIJAAAA | wailaharvestability | 1.1.12                   | WailaHarvestability-mc1.12-1.1.12.jar     | None                                     |
	| UCHIJAAAA | wearablebackpacks   | 3.1.2                    | WearableBackpacks-1.12.2-3.1.2.jar        | None                                     |

	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.174.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  lumien.resourceloader.asm.ClassTransformer
Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.9.7-1.12.2-anarchy.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 391.35' Renderer: 'GeForce GTX 960M/PCIe/SSE2'
	Launched Version: 1.12.2-forge1.12.2-14.23.3.2669
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 960M/PCIe/SSE2 GL version 4.6.0 NVIDIA 391.35, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_D1
	OptiFine Build: 20180323-135452
	Render Distance Chunks: 8
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 391.35
	OpenGlRenderer: GeForce GTX 960M/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by MJRLegends** [comment]
Yeah right you have ignored the template, and you havent bothered to look at closed issues all which is asked and easy for you to do.

 Optfine isnt supported remove it please

**Comment by MJRLegends** [comment]
In future please use the template or i will have to just close your issues and ignore them as its not fair if i dont have the correct information. And you just ignore information
