### ISSUE TITLE
[Suggestion]A Better Electric Compressor

### ISSUE THREAD

**Issue by SihenZhang** [MJRLegends/ExtraPlanets#290]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

### Description of Issue
I am ALWAYS tired of making compressed material and heavy-duty plate and I have to make a lot so that I can make higher tier rocket. Although there is Electric Compressor which may be helpful, it is still SLOW and hard to automate. Since you made better oxygen compressor, could you please make a better electric compressor? I'll appreciate it if you can do that. 

### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** 1.12

**Where did this bug happen:** [Single Player or Server]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Do note you can automate the compressors so no need
and I've made galacticraft tweaker which you can edit recipes yourself to what you want them to be

**Comment by MJRLegends** [comment]
I will probably add it at some point maybe...
