### ISSUE TITLE
[1.12.2] Dimensions issue with Dimension Advancements from Triumph

### ISSUE THREAD

**Issue by MJRLegends** [MJRLegends/ExtraPlanets#291]
### Description of Issue
When trying to make Dimension Advancements from Triumph with EP dimensions it doesnt trigger the Advancement 

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
v0.3.3
**Where did this bug happen:** [Single Player or Server]
Both

**Comment by justinrusso** [comment]
For the sake of properly documenting it:

When creating the Advancement, we used capitalized names such as `Saturn` and the Triumph script did not error. 

We then tried using lowercase `saturn` as it seemed like it may be that based on your code. This causes the script to error which results in the advancement triggering based on ANY dimension change - not specifically the `saturn` dimension.

**Comment by MJRLegends** [comment]
Updates are uploading as we speak
