### ISSUE TITLE
[1.10.2] NullPointerException Crash Upon Key Press

### ISSUE THREAD

**Issue by Artinaix** [MJRLegends/ExtraPlanets#292]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** 
Yes

### Description of Issue
I seem to crash when I press the "o" key when making a waypoint in journey map (however it most likely will happen anywhere)

### Steps to Reproduce Issue
1. Press the "o" key

**Crash log/Log (if applicable):** 
[Here's the crash log](https://pastebin.com/mLsRjVsE)

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** 
ExtraPlanets-1.10.2-1.0.5

**Where did this bug happen:** [Single Player or Server]
Singleplayer

**Comment by MJRLegends** [comment]
Updates will be out soon :D to fix this thanks

**Comment by MJRLegends** [comment]
Updates are uploading will be showing soon
