### ISSUE TITLE
The basic solar evaporation chamber won't make potassium.

### ISSUE THREAD

**Issue by drewkeating** [MJRLegends/ExtraPlanets#293]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes
Yes

### Description of Issue
The basic solar evaporation chamber won't make potassium. It's powered, and has a stack of potash shards. The status is Idle. It's been running that way for many minecraft days and nights.

### Steps to Reproduce Issue
1. Insert at least 12 potash shards into a powered basic solar evaporation chamber
2. wait for status to say evaporating, or potassium to be made that never comes.

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

**Screenshots (if applicable):** 
https://imgur.com/a/u65n1id

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
ExtraPlanets-1.12.2-0.3.3 in the Modern Skyblock 3 pack (v3.3.1.4)

**Where did this bug happen:** [Single Player or Server]
Single Player

### Additional Information
[Any other information that may be able to help me with the problem]
All of the other machines for making anti-rad are working (Basic block smasher, Basic chemical Injector, Basic crystallizer, and Basic Purifier.

**Comment by MJRLegends** [comment]
Does it have sky access and is it day time when you use it, you can see this in the GUI with the sun icon

**Comment by drewkeating** [comment]
Thank you. That was it. The only way I've found to pipe things into it are vanilla hoppers, even galacticraft pipes in item mode don't work. The hopper was fine, but the basic block smasher on top of the hopper was blocking it's path to the sky. Thanks again. it's working fine now.

**Comment by MJRLegends** [comment]
Please open another issue for any other issues
