### ISSUE TITLE
Crash when trying to land on kepler 22b

### ISSUE THREAD

**Issue by levilips123** [MJRLegends/ExtraPlanets#294]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** 
yes
### Description of Issue
exactly what the title says
### Steps to Reproduce Issue
1. Take tier 10 rocket
2. fly into space
3. try to land on kepler 22b
**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** ExtraPlanets-1.12.2-0.3.3

**Where did this bug happen:** singleplayer

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
You need to post the crash log, will reopne when you have supplied it
