### ISSUE TITLE
[1.8+] Modern skyblock 3, Tier 10 electric rocket

### ISSUE THREAD

**Issue by Elvi81** [MJRLegends/ExtraPlanets#295]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No] Yes

### Description of Issue
Nothing happens when you press space on this rocket even if it's fully charged and pressing space on all the other tier rockets work just fine.

### Steps to Reproduce Issue
1. Enter rocket, press space, nothing.
2. Enter Tier 1-10 fuel rocket, press space, launch.

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** 0.3.3

**Where did this bug happen:** [Single Player or Server] Server

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Please report to GC as tier 1 to 3 don't work too

**Comment by Elvi81** [comment]
What are you on about? GC tier 1 thru 3 rockets work just fine on my server and it's only tier 10 electric that does not launch.

**Comment by MJRLegends** [comment]
Had you put power in it?

**Comment by Elvi81** [comment]
It was fully powered.

**Comment by MJRLegends** [comment]
Updates will be out soon :D to fix this thanks

**Comment by MJRLegends** [comment]
Updates are uploading will be showing soon
