### ISSUE TITLE
[1.7+] Tier 4 Oxygen Setup Kit recipe issue

### ISSUE THREAD

**Issue by IChris2698I** [MJRLegends/ExtraPlanets#299]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

### Description of Issue
Tier 4 Oxygen Kit recipe should not include a parachute. Tier 4 Full Kit Without Oxygen recipe *should* include a parachute.

https://github.com/MJRLegends/ExtraPlanets/blob/18af3af73075e185f8ae3d1b9374b552b8134146/src/main/java/com/mjr/extraplanets/recipes/ExtraPlanets_Recipes.java#L1063-L1066

### Steps to Reproduce Issue
1. View recipes in JEI
2. Cheat in items and test what they give when used

**Crash log/Log (if applicable):** Not applicable.

**Screenshots (if applicable):** Probably not needed?

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** 1.12.2-0.3.2

**Where did this bug happen:** Server

### Additional Information
Should just be a couple changes on lines 1063 and 1065. I realize it'll be awhile before I get the fix in my SevTech instance, and it's not a big issue anyway :)

```java
		GameRegistry.addRecipe(new ItemStack(ExtraPlanets_Items.tier4EquipmentKit, 1, 3), new Object[] { "MGF", "TPT", "   ", 'M', new ItemStack(GCItems.oxMask), 'G', new ItemStack(GCItems.oxygenGear), 'F', new ItemStack(GCItems.basicItem, 1, 19),
				'T', new ItemStack(GCItems.oxTankHeavy), 'P', new ItemStack(GCItems.parachute) });
		GameRegistry.addRecipe(new ItemStack(ExtraPlanets_Items.tier4EquipmentKit, 1, 4), new Object[] { "M G", "T T", "   ", 'M', new ItemStack(GCItems.oxMask), 'G', new ItemStack(GCItems.oxygenGear), 'T', new ItemStack(GCItems.oxTankHeavy) });
```

**Comment by MJRLegends** [comment]
Thanks should be easy enough to fix

**Comment by MJRLegends** [comment]
Updates are rolling out as we speak
