### ISSUE TITLE
Tier4 Rocket - not able to load fuel

### ISSUE THREAD

**Issue by cluckinator** [MJRLegends/ExtraPlanets#3]
I just constructed the tier 4 rocket in the NASA workbench and placed it on the launch pad I used for tiers 1-3 with a Galacticraft core fuel loader, but the fuel will not load into the rocket. I hover over the fuel gauge and it says 'Fuel tank. Requires fuel loader to fill' and shows 0 of 2000 fuel. I don't see any messages on the console and the fuel level stays at 0.0%. is there a special fuel required or another tier of fuel loader that I can't see?

**Comment by MJRLegends** [comment]
What galacticraft version you using

**Comment by cluckinator** [comment]
That version has resolved the fuel loading issue for me. Thank you!
