### ISSUE TITLE
[1.10+] Crash When Opening The Galaxy Map

### ISSUE THREAD

**Issue by EmosewaPixel** [MJRLegends/ExtraPlanets#300]
### Description of Issue
With the latest version of GC (-4.0.1.176), a crash occurs when opening the Galaxy Map.

### Steps to Reproduce Issue
1. Open the galaxy map

**Crash log/Log (if applicable):**
https://pastebin.com/mqan9aa7

**Version of Mod using:** 0.3.6

**Where did this bug happen:** Single Player

**Additional Information**
 The same goes for Planet Progression
 Source: https://github.com/EmosewaPixel/Modern-Skyblock-3/issues/508

**Comment by MJRLegends** [comment]
I think this is going to require a GC change to fix, so will be making a pull request for them for this issue

**Comment by devcompl** [comment]
BTW in case you didnt see my comment on the source issue, the main problem I think is the change in FTBUtilities 5.0.2.11 in [this](https://github.com/LatvianModder/FTBUtilities/commit/b0bbabc90a04f6f557657047f2c7ea55877da046#diff-b3941c1d66d237989187e3d5502d1a4cL43) commit. I tested 5.0.2.10 and newest ExtraPlanets + Planet Progression work fine.

**Comment by MJRLegends** [comment]
Updated are rolling out as we speak
