### ISSUE TITLE
Open Module Manager control key disrupts other guis

### ISSUE THREAD

**Issue by FaustyTheRager** [MJRLegends/ExtraPlanets#301]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

### Description of Issue
Whenever I press the key to open the module manager or press a key to rebind the controls for it, the gui is immediately opened for it and all other guis and menus are closed.

### Steps to Reproduce Issue
1. Enter any gui
2. Press the open module manager key

**Crash log/Log (if applicable):** N/A
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

**Screenshots (if applicable):** 
N/A
**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
1.12.2-0.3.3
**Where did this bug happen:** [Single Player or Server]
Server
### Additional Information
N/A

**Comment by MJRLegends** [comment]
Please test with latest version of ExtraPlanets

**Comment by MJRLegends** [comment]
Ok yeah this is already fixed in latest version with commit https://github.com/MJRLegends/ExtraPlanets/commit/aa33dd7525f8366180d92854a06156466121ebba
