### ISSUE TITLE
Sensor Glasses Do Not Work While Installed As a Module

### ISSUE THREAD

**Issue by FaustyTheRager** [MJRLegends/ExtraPlanets#303]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

### Description of Issue
Sensor glasses showed nothing when installed as a module and showed much when they were used as a helmet.

### Steps to Reproduce Issue
1. Install sensor glasses
2. Look for ore

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

**Screenshots (if applicable):** 
Unavailable because of a separate issue: #302 
**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** 1.12.2-0.3.3

**Where did this bug happen:** Server

### Additional Information
I am playing the SevTech: Ages modpack.

**Comment by MJRLegends** [comment]
Yeah this is intended they are not fully added yet as a working module.

They will be working in the next ExtraPlanets update
