### ISSUE TITLE
[1.7.10] Kepler 22b Crash

### ISSUE THREAD

**Issue by bballboy2002** [MJRLegends/ExtraPlanets#304]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):**
Yes, there is a similar closed issue affecting 1.12.2, no crash log was included

### Description of Issue
Crash when trying to load Kepler 22b

### Steps to Reproduce Issue
1. Rocket, /dimensiontp, whatever
2. Go to Kepler 22b

**Crash log/Log (if applicable):** 
Initially tried to load: https://pastebin.com/2YHe8ShV

~~Reloaded the world, stayed on for a few minutes, then crashed again (might be completely unrelated): https://pastebin.com/rPnDwhSM~~ GC Issue

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** 1.7.10-2.0.1

**Where did this bug happen:** Singleplayer

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Ok thanks your first crash is to do with my mod but the second crash is a GC one so please report that one over at GC issue tracker

**Comment by MJRLegends** [comment]
Ok this seems to be because you've disabled the fire bomb in the config, should be a easy fix
