### ISSUE TITLE
"Module Manager" window opens any time you type H

### ISSUE THREAD

**Issue by justinrusso** [MJRLegends/ExtraPlanets#305]
## Issue / Bug
If you are wearing any of the Extra Planets spacesuit pieces and press H the Module Manager window always opens except if you are typing in chat.  If searching in JEI or any of the storage mod search windows for instance it will always close whatever inventory/GUI and open the Module Manager.

## Expected Behavior
Module Manager to only open if there is no active GUI/Inventory already on screen when pressing H

## Possible Solution
Remap to a key/symbol that isn't normally typed in search boxes etc.  Unmapping the key totally won't work as you need to use the Module Manager to add upgrades to the suits.

## Steps to Reproduce Issue
1. Wear any piece (or combination of pieces) of the Extra Planets spacesuit
2. Open any search/GUI such as inventory->TMI seearch
3. type an item name with an H in it such as "fish"

## Versions
**Version of Mod using:** 0.3.3

## Additional Information
**Where did this bug happen:** Single Player

Reference https://github.com/DarkPacks/SevTech-Ages/issues/2326

**Comment by MJRLegends** [comment]
Already fixed in the latest update
