### ISSUE TITLE
[1.10+] No Fall Damage module causes disconnect

### ISSUE THREAD

**Issue by Giovanni-NL** [MJRLegends/ExtraPlanets#306]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** 
Yes

### Description of Issue
Client continuously loses connection after installing module in space suit and wearing it.

### Steps to Reproduce Issue
1. Install the "No fall damage module" in the Tier 2 space suit.
2. Walk around, in any dimension.

**Crash log/Log (if applicable):** 
https://pastebin.com/7hbaPWBx

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** 
This is using modpack Sevtech Ages version 3.0.7
Extra Planets version: ExtraPlanets-1.12.2-0.3.3.jar

**Where did this bug happen:** [Single Player or Server]
Multiplayer server

### Additional Information
none

**Comment by MJRLegends** [comment]
Updated are rolling out as we speak
