### ISSUE TITLE
Crash on Galactic Map

### ISSUE THREAD

**Issue by ItsWolfPT** [MJRLegends/ExtraPlanets#307]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** No

### Description of Issue
Crash on Galactic Map, sometimes it happen, on Planet Selection Transition or Idle. And also Pluto name is bugged too.

### Steps to Reproduce Issue
1. Just grab a lauchpad and rocket and fly. 
Well there no more steps for reproduce it. It's random, can happen any time. But if you stay too much time(a few seconds idle) with out selecting a planet it might crash too. 

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
https://pastebin.com/zu3tVw09

**Screenshots (if applicable):** 
http://prntscr.com/jjh3hu  - Pluto Name 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** 
1.12.2-0.3.6
**Where did this bug happen:** 
Single Player
### Additional Information
I am using MultiMC, and also this is an heavy modpack.

**Comment by MJRLegends** [comment]
This isnt a ExtraPlanets issue

```
    at xaero.pvp.interfaces.BPVPInterfaceLoader.getMouseOver(BPVPInterfaceLoader.java:275)
    at xaero.pvp.interfaces.BPVPInterfaceLoader$5.drawInterface(BPVPInterfaceLoader.java:214)
    at xaero.common.interfaces.InterfaceHandler.drawInterfaces(InterfaceHandler.java:54)
```
Also the pluto name is just a mc thing nothing can be done about that
