### ISSUE TITLE
the BUG of Evolved Magma Cube Boss

### ISSUE THREAD

**Issue by driiiiiiift** [MJRLegends/ExtraPlanets#31]
There was something wrong on the Venus Dungeon When I went on the Venus Dungeon to find the BOSS on the Venus.
Here is my mod list:
ExtraPlanets-1.0-Pre 3.6.9
GalacticraftCore-1.7-3.0.12.463
Galacticraft-Planets-1.7-3.0.12.463
MicdoodleCore-1.7-3.0.12.463

The problem is the Evolved Magma Cube Boss wont spawn.
The Evolved Magma Cube Boss will spawn in a second then it will remove.
Here is the SERVER LOG when the Evolved Magma Cube Boss disappear.

[23:56:49 WARN]: Entity being removed for bounding box restrictions
[23:56:49 WARN]: BB Size: 1,452 > 1,000 avg edge: 10.007
[23:56:49 WARN]: Motion: (0, -0.022, 0)
[23:56:49 WARN]: Calculated bounding box: box[4532.5, 27.978439997944832, -2009.
5 -> 4542.5, 38.0, -1999.5]
[23:56:49 WARN]: Entity bounding box: null
[23:56:49 WARN]: Entity: EntityEvolvedMagmaCubeBoss['Evolved Magma Cube Boss'/72
5, l='DIM-14', x=4537.50, y=28.00, z=-2004.50]
[23:56:49 WARN]: Entity NBT: {Size:9,Attributes:[0:{Base:200.0d,Name:"generic.ma
xHealth",},1:{Base:0.0d,Name:"generic.knockbackResistance",},2:{Base:0.100000001
49011612d,Name:"generic.movementSpeed",},3:{Base:16.0d,Name:"generic.followRange
",},4:{Base:2.0d,Name:"generic.attackDamage",},],Invulnerable:0b,PortalCooldown:
0,AbsorptionAmount:0.0f,FallDistance:0.0f,DeathTime:0s,WorldUUIDMost:-8254881757
949377615L,DropChances:[0:0.085f,1:0.085f,2:0.085f,3:0.085f,4:0.085f,],roomCoord
sY:25.0d,roomCoordsZ:-2014.0d,PersistenceRequired:0b,Spigot.ticksLived:2,HealF:1
99.0f,Motion:[0:0.0d,1:-0.021560002055168184d,2:0.0d,],Leashed:0b,UUIDLeast:-366
7544984758000016L,Health:199s,Bukkit.updateLevel:2,roomCoordsX:4528.0d,Air:300s,
OnGround:0b,Dimension:-14,Rotation:[0:1.944835f,1:0.0f,],roomSizeZ:18.0d,roomSiz
eY:9.0d,roomSizeX:18.0d,UUIDMost:8147482243101512996L,Equipment:[0:{},1:{},2:{},
3:{},4:{},],CustomName:"",Pos:[0:4537.5d,1:28.0d,2:-2004.5d,],Fire:0s,CanPickUpL
oot:0b,HurtTime:8s,AttackTime:0s,WorldUUIDLeast:-7488097564132926402L,CustomName
Visible:0b,}

I installed that on KCauldron 6XXX...i dont know the detail.

BTW...maybe is my playing mistakes...
but i think thats a bugy....
i can successfuly spawn that on offline mode....
Please resolve that...

THX！

**Comment by aetherpirate** [comment]
I have the same issue, and my console also has the Entity being removed for bounding box restrictions message

**Comment by driiiiiiift** [comment]
Both u install the same version mods as me?

**Comment by MJRLegends** [comment]
Will look when i get time

**Comment by driiiiiiift** [comment]
Seems like a URGENT because all the players cant get the map of next global...

**Comment by MJRLegends** [comment]
"Map of next global " ??? Whats that???

**Comment by MJRLegends** [comment]
Your this is due to KCauldron as its doesnt happen with forge

**Comment by MJRLegends** [comment]
@driiiiiiift @aetherpirate 

Your issue is with KCauldron mainly cauldron part of it
Go to the cauldron.yml and change this keep trying to increase the value to see if it works.....
![](https://i.gyazo.com/d764e582570d92365dce897ee1334c3a.png)

**Comment by aetherpirate** [comment]
I had the same issue and tried this, it sorta works. The Giant Magma Cube Boss now spawns and stays, but  it doesn't move or attack, and all blows from any weapon I tried do 1HP damage. It did eventually die and drop the key, so progression isn't broken anymore.

**Comment by driiiiiiift** [comment]
same issue as u.the boss cant attack.but it stilling cut down itselfs HP in every seconds. eventhough i didnt touch or attack it.

**Comment by MJRLegends** [comment]
@aetherpirate @driiiiiiift if it works with just forge then its cauldron/kcauldron/thermos fault?

**Comment by driiiiiiift** [comment]
So...no way can fix the problem?
I like this mod.

**Comment by MJRLegends** [comment]
Does it work with forge?

**Comment by driiiiiiift** [comment]
on the client(forge) it runs very well.(single mode)
on the server will happend thats problem.
