### ISSUE TITLE
[1.12.2] Game crashes when opening the Galaxy Map

### ISSUE THREAD

**Issue by mzx987** [MJRLegends/ExtraPlanets#311]
### ---Issue Report---
**Have you checked Closed Issues?** Yes. There is a duplicate that was supposedly fixed in issue #300

### Description of Issue
With Galacticraft v4.0.1.177 installed, as well as the latest version of Extra Planets (see below), simply opening the Galaxy Map causes the screen to go white. Shortly after, the game crashes.

### Steps to Reproduce Issue
1. Simply open the Galaxy Map

**Crash log/Log:**
https://pastebin.com/34jpwFrs

**Version of Mod using:** Extra Planets v0.3.7

**Where did this bug happen:**
This bug occurs in both single player and multiplayer. 

### Additional Information
Not quite relevant, but this was tested with and without Foam Fix installed.

**Comment by MJRLegends** [comment]
Update you linked the already closed issue but your still using the same version not the latest

**Comment by MJRLegends** [comment]
Already posted https://github.com/MJRLegends/ExtraPlanets/issues/310

So 

**Have you checked Closed Issues?** No

:P
