### ISSUE TITLE
[1.7.10] Crash on Client Start

### ISSUE THREAD

**Issue by TwoTailedFox** [MJRLegends/ExtraPlanets#312]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

### Description of Issue
Crash on startup of Minecraft instance

### Steps to Reproduce Issue
Include the following mods for 1.7.10

CodeChickenCore-1.7.10-1.0.7.47-universal
ExtraPlanets-1.7.10-2.0.2
GalacticraftCore-1.7-3.0.12.504
Galacticraft-Planets-1.7-3.0.12.504
gregtech-5.09.32pre4
industrialcraft-2-2.2.827-experimental
MicdoodleCore-1.7-3.0.12.504
NotEnoughItems-1.7.10-1.0.5.120-universal
PowerConverters-1.7.10_3.2.2-jenkins.70
GT-PlusPlus-1.7.0-prerelease-20-hotfix
MekanismTools-1.7.10-9.1.1.1031
Mekanism-1.7.10-9.1.1.1031
MekanismGenerators-1.7.10-9.1.1.1031

Start server as normal, crash will present itself.

**Crash log/Log (if applicable):** https://pastebin.com/55kZuCfv

**Screenshots (if applicable):** N/A

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** 2.0.2

**Where did this bug happen:** Single Player Client Start-up

### Additional Information
The issue is only present with 2.0.2. <2.0.1 unaffected.

**Comment by MJRLegends** [comment]
Update has been submitted to curseforge to fix this :D will be showing when curse staff approve it
