### ISSUE TITLE
[1.7.10] Crash with multiple mods

### ISSUE THREAD

**Issue by TwoTailedFox** [MJRLegends/ExtraPlanets#313]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

### Description of Issue
This one is a little different to the previous crash, with several mods fingering this mod as the cause of the crash. This happens when placing these mods in a custom mod pack, the only action being a deletion of More Planets 1.4.4-GC502, and the inclusion of both Extra Planets 2.0.3 and Galaxy Space 1.2.2. Reversing this by deleting Extra Planets and Galaxy Space, and replacing with More Planets 1.4.4-GC502 resolves the issue.

### Steps to Reproduce Issue
Install following mods:
https://pastebin.com/dAFGDPyS
2. Start client.

**Crash log/Log (if applicable):** https://pastebin.com/Y7A2gg6c

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [2.0.3, however, this seems to affect multiple versions]

**Where did this bug happen:** [Single Player]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Please can you post a copy of your config, (using www.pastebin.com )

**Comment by TwoTailedFox** [comment]
https://pastebin.com/ineA9kA6 is my current ExtraPlanets.cfg

**Comment by MJRLegends** [comment]
Ok its because you have the More Planets Compatibility option on but you dont have More Planets in your mods folder

**Comment by TwoTailedFox** [comment]
Hello.

I added More Planets 1.4.4-GC502 back into the mods folder, but this crash persists.

**Comment by MJRLegends** [comment]
Please post new crash log with that change

**Comment by MJRLegends** [comment]
As im using More Planets right now with ExtraPlanets and seems good to me

**Comment by MJRLegends** [comment]
Dont worry found the issue sorry, will be fixed in next update

**Comment by MJRLegends** [comment]
Ok sorry to mess you around, please regenerate your config for ExtraPlanets and enable both Basic and Advanced More Planets compact and you will be good the option isnt enabling correctly as you have a old config.

**Comment by MJRLegends** [comment]
Also please use v2.0.4 version before you do the config regeneration

**Comment by TwoTailedFox** [comment]
I'll download it as soon as it appears on Curse. Thanks for your help so far :)

**Comment by MJRLegends** [comment]
But i can 100% say that ExtraPlanets, More Planets, Mekanism work with the More Planet config options on so seems to just be a config issue
