### ISSUE TITLE
[1.7.10] Crash when leaving planet

### ISSUE THREAD

**Issue by jack2423** [MJRLegends/ExtraPlanets#314]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

### Description of Issue
When you leave a planet in a rocket from the extra planets mod the game crashes on the star map

### Steps to Reproduce Issue
1. place your rocket
2. fly to space

**Crash log/Log (if applicable):** https://pastebin.com/fdZMs1tK

**Version of Mod using ():** ExtraPlanets-1.7.10-2.0.3

**Where did this bug happen:** Single Player

### Additional Information
[Config: https://pastebin.com/MvjQhnLf]

**Comment by MJRLegends** [comment]
Please post a copy of your config, (using pastebin.com )

**Comment by jack2423** [comment]
config: https://pastebin.com/MvjQhnLf

**Comment by MJRLegends** [comment]
Thanks please can you try without FarScape and PixelGalaxy

**Comment by jack2423** [comment]
I tried and it still crashes.

**Comment by MJRLegends** [comment]
Please post new crash log with them removed

**Comment by jack2423** [comment]
https://pastebin.com/BtpEMCrR

**Comment by MJRLegends** [comment]
Please can you disable all the Space Stations in the ExtraPlanets config and try

**Comment by jack2423** [comment]
I don't see a option to disable the spacestations only to disable the planets spacestations rockets all in one.

**Comment by MJRLegends** [comment]
These are the ones, they are in the ExtraPlanets.cfh file

```
##########################################################################################################
# space stations
#--------------------------------------------------------------------------------------------------------#
# Setting this option to false will remove the space station from the planet (Note: Will be auto disbled when disabling a planet, so you dont need to disable them when disabling a planets)
##########################################################################################################

"space stations" {
    # Setting this option to false will disable & remove the Ceres Space Station
    B:"Ceres SpaceStation"=true

    # Setting this option to false will disable & remove the Eris Space Station
    B:"Eris SpaceStation"=true

    # Setting this option to false will disable & remove the Jupiter Space Station
    B:"Jupiter SpaceStation"=true

    # Setting this option to false will disable & remove the Kepler22b Space Station
    B:"Kepler22b SpaceStation"=true

    # Setting this option to false will disable & remove the Mars Space Station
    B:"Mars SpaceStation"=true

    # Setting this option to false will disable & remove the Mercury Space Station
    B:"Mercury SpaceStation"=true

    # Setting this option to false will disable & remove the Neptune Space Station
    B:"Neptune SpaceStation"=true

    # Setting this option to false will disable & remove the Pluto Space Station
    B:"Pluto SpaceStation"=true

    # Setting this option to false will disable & remove the Saturn Space Station
    B:"Saturn SpaceStation"=true

    # Setting this option to false will disable & remove the Uranus Space Station
    B:"Uranus SpaceStation"=true

    # Setting this option to false will disable & remove the Venus Space Station
    B:"Venus SpaceStation"=true
}
```

**Comment by jack2423** [comment]
Still a crash 
Report:https://pastebin.com/atfBBBLm

**Comment by MJRLegends** [comment]
Ok Please try remove ExtraPlanets and test

**Comment by jack2423** [comment]
That works, I feel like the problem is with the extraplanets rockets because i can launch a normal rocket with extra planets

**Comment by MJRLegends** [comment]
Naa i wanna see if its ExtraPlanets or GC, so please remove ExtraPlanets and test

**Comment by jack2423** [comment]
I did that and it worked

**Comment by MJRLegends** [comment]
Ok Please delete ExtraPlanets & Galacticraft configs and try with ExtraPlanets

**Comment by MJRLegends** [comment]
And does the crash happen when using a GC rocket?

**Comment by jack2423** [comment]
No only with extraplanet rockets

**Comment by jack2423** [comment]
It still crashes after deleting both GC and extraplanets config
Report:https://pastebin.com/sgYeRdCW

**Comment by MJRLegends** [comment]
@jack2423 sorry for the delay, does it happen on a new world?
