### ISSUE TITLE
[1.8+] Space suit Texture Overlapping issue with Thermal Padding

### ISSUE THREAD

**Issue by ElSaam** [MJRLegends/ExtraPlanets#315]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

### Description of Issue
No texture between legs in space suit leggings

### Steps to Reproduce Issue
1. equip space suit leggings
2. walk and check between legs

**Screenshots
![inked2018-05-28_23 44 49_li](https://user-images.githubusercontent.com/16359905/40629297-d93ad6f0-62d2-11e8-9e2e-e09609609eef.jpg)
:** 

**Version of Mod using: 1.12.2-0.3.8 **

**Where did this bug happen:** Server

### Additional Information
Tier 1 used, not sure about others.

**Comment by MJRLegends** [comment]
Are you using any other mods?

**Comment by ElSaam** [comment]
![capture](https://user-images.githubusercontent.com/16359905/40629685-c7ba4bd8-62d5-11e8-853d-15c19e536099.PNG)
Those are all of them

**Comment by ElSaam** [comment]
Tried with optifine and still occurs. Looks like it only happens while wearing thermal padding leggings.

**Comment by MJRLegends** [comment]
Updates will be released some time this week

**Comment by MJRLegends** [comment]
Updates are coming out as we speak
