### ISSUE TITLE
[1.8+] Space Suit Power drain

### ISSUE THREAD

**Issue by Grim187** [MJRLegends/ExtraPlanets#316]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** yes

### Description of Issue
Tier 3 space suit drains rapidly (30 seconds or less) on jupiter but reports full when you mouse over it and sometimes sticks that way making it look like you have full armor when its 1 hit it also refills instantly without taking power in the energy storage module.

### Steps to Reproduce Issue
1. put on Tier 3 space suit
2. goto jupiter for 30 seconds or more
3. mouse over armor to make armor health bar disapear
4. return to overworld and put in a energy storage module.

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** 1.12.2-0.3.8

**Where did this bug happen:** Server

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by Grim187** [comment]
I forgot about the shield controller and wasn't expecting jupiter to be corrosive.
so the issue is more with damage value and instant charging without taking power.

**Comment by MJRLegends** [comment]
Already a known issue dont worry

**Comment by MJRLegends** [comment]
I having a very hard time fixing this, but i will find a way dont worry

**Comment by MJRLegends** [comment]
Updates will be released some time this week

**Comment by MJRLegends** [comment]
Updates are coming out as we speak
