### ISSUE TITLE
[1.12.2] Tier 6 Schematic in a Tier 5 chest

### ISSUE THREAD

**Issue by Grim187** [MJRLegends/ExtraPlanets#317]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** yes

### Description of Issue
I just defeated the fire bat boss on jupiter and opened the tier 5 chest to find a tier 6 rocket schematic.

### Steps to Reproduce Issue
1. goto jupiter and defeat the fire bat to obtain the key for the tier 5 chest
2. open the tier 5 chest to find a tier 6 rocket schematic

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** 1.12.2-0.3.8

**Where did this bug happen:** Server

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Turn off the more planets compact option if your not using More Planets, if you are using that mod then yeah this is intended.

Thats the only way that this is posable to happen

**Comment by MJRLegends** [comment]
After looking more in to this. Its not even possible at all

**Comment by MJRLegends** [comment]
```
			if (Config.MORE_PLANETS_COMPATIBILITY)
				GalacticraftRegistry.addDungeonLoot(4, new ItemStack(ExtraPlanets_Items.TIER_5_SCHEMATIC, 1, 0));
			else
				GalacticraftRegistry.addDungeonLoot(5, new ItemStack(ExtraPlanets_Items.TIER_5_SCHEMATIC, 1, 0));
```
```

		List<ItemStack> stackList;
		if (Config.MORE_PLANETS_COMPATIBILITY)
			stackList = GalacticraftRegistry.getDungeonLoot(4);
		else
			stackList = GalacticraftRegistry.getDungeonLoot(5);
		return stackList.get(rand.nextInt(stackList.size())).copy();
```

**Comment by Grim187** [comment]
I think it was a more planets schematic, I will try to recreate tomorrow.
I have more planets compatibility=false

**Comment by MJRLegends** [comment]
You need to enable it and follow the instructions in the comment for that option too that will fix your issue
