### ISSUE TITLE
[1.8+] Rocket Launch Pad issue

### ISSUE THREAD

**Issue by artdude543** [MJRLegends/ExtraPlanets#318]
Hello, I come to thee to post a dupe issue, which was posted on the SevTech: Ages tracker. I did see a similar issue posted last year on the tracker. But I thought to post a new one as the linked issue contains a decent amount of data and videos on the various dupe issues.

Minecraft version: 1.12.2
ExtraPlanets: 0.3.3
Galacticraft version: 4.0.1.176

All details and video can be found here: DarkPacks/SevTech-Ages#2750

**Comment by MJRLegends** [comment]
@artdude543 Please get them to test with new version as im unable to reproduce it from my first tests for this issue

**Comment by MJRLegends** [comment]
Im able to reproduce it, i will see what i can do it fix this

**Comment by MJRLegends** [comment]
Updates will be released some time this week

**Comment by artdude543** [comment]
Thank you for the fix! 🤗

**Comment by MJRLegends** [comment]
@artdude543 No problem im not happy with the clips tho and the fact the streamer decided to show it on a stream and acted in way like he wanted people to use the bug. But yolo :P.

**Comment by artdude543** [comment]
Yeah; not a fan of the way it was done either. But at least someone reported it I guess. Otherwise would be hidden with all the clips on Twitch xD

**Comment by MJRLegends** [comment]
Updates are coming out as we speak
