### ISSUE TITLE
[1.8+] Inability to charge Space Suits in non GC blocks

### ISSUE THREAD

**Issue by sfxworks** [MJRLegends/ExtraPlanets#319]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [**Yes** or No]

### Description of Issue
Standing on a charge pad via mechanism or using batteries from actually editions fail to charge the space suit.

### Steps to Reproduce Issue
1. Use any means of charging, such as a [charge pad](http://wiki.aidancbrady.com/wiki/Chargepad)
2. Notice the lack of charge

**Screenshots (if applicable):** 

![image](https://user-images.githubusercontent.com/5921035/41019711-cfd2df02-692d-11e8-8623-25f75e2490ce.png)
![image](https://user-images.githubusercontent.com/5921035/41019721-e5920372-692d-11e8-938f-ebcc29118010.png)

ExtraPlanets-1.12.2-0.3.8

**Where did this bug happen:** [Single Player or Server]
Server 

Additional Information:

Other users are having this issue as well. See https://www.reddit.com/r/feedthebeast/comments/8l1jbv/sevtech_question_regarding_extra_planets_tier_1/

**Comment by ZyorTaelon** [comment]
I've also tried a https://teamcofh.com/docs/thermal-expansion/flux-capacitor/ on all possible settings, both with the space suit equiped and in my inventory. No charge.

The https://teamcofh.com/docs/thermal-expansion/energetic-infuser/ with the https://teamcofh.com/docs/thermal-expansion/augment-parabolic-flux-coupling/ also didn't work.

**Comment by MJRLegends** [comment]
You can use the Energy Storage Module to charge it

**Comment by MJRLegends** [comment]
I've added a tool tip for the next version to explain that you need to use GC Blocks to charge it 

See below for a image of this
![](https://i.gyazo.com/5f2d53038c410f3c07097fab31dbe99f.png)

Im unable to fix the support for other power charging systems support atm but Galacticraft supports all power types so shouldn't be a issue overall

**Comment by Fireztonez** [comment]
For the tooltips I know, this is why I say I have to look for report to Galacticraft ;)

**Comment by MJRLegends** [comment]
Im adding RF, Mekanism, IC2 support to the Tier 1 - 4 Space suit, this should cover most popular mods

**Comment by MJRLegends** [comment]
Im going to add Forge Energy support for MC 1.10.2+ versions too, so Ender IO & 
Actually Additions can be used to charge the Tier 1 - 4 Space Suit

**Comment by MJRLegends** [comment]
Updates are rolling out as we speak for MC 1.8+

**Comment by Fireztonez** [comment]
Perfect, thank's for that update!
