### ISSUE TITLE
Titanium ingot unlocalized name duplicate

### ISSUE THREAD

**Issue by Wyrrrd** [MJRLegends/ExtraPlanets#32]
### ---Issue Report---

**Have you checked Closed Issues:** Yes
### Description of Issue
I am trying to change the name and behaviour of ExtraPlanets' Titanium Ingot with Minetweaker in Minecraft 1.7.10.
Strangely the QuantumFlux Ingot responds to every name change I apply to the EP ingot, while the EP ingot always takes the ore dictionary entry from the QF ingot.

### Steps to Reproduce Issue
1. Install critical mods:
  - Galacticraft 3.0.12
  - ExtraPlanets 1.0 Pre 3.6.6
  - QuantumFlux 1.3.4
  - Minetweaker 3.0.10B
2. See yourself

**Version of Mod using:** 1.0 Pre 3.6.6

### Additional Information
I am not sure where this is coming from (my suggestion is, they have the same unlocalized name), so I am filing issues on QF and Minetweaker, too.

[QuantumFlux Issue](https://github.com/joekaiser/QuantumFlux/issues/111)

Thanks in advance,
Wyrrrd

![unbenannt](https://cloud.githubusercontent.com/assets/11527443/18447132/a0a67846-7925-11e6-80cc-7dcea20c8675.png)

**Comment by MJRLegends** [comment]
Don't think this is a bug of my addon, as im just making a item and called titanium ingot and then adding ore dictionary for it so its a problem related to the other mods.

**Comment by Wyrrrd** [comment]
Well, if you could change your titanium oregen config option to removing the ingot too, I would be very happy already :)

**Comment by MJRLegends** [comment]
Wait Titanium is a Galacticraft item so this isnt my issue

**Comment by Wyrrrd** [comment]
Oh. My fault...

**Comment by MJRLegends** [comment]
Haha gg
