### ISSUE TITLE
Basic Purifier

### ISSUE THREAD

**Issue by MisterSmileyFace** [MJRLegends/ExtraPlanets#320]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes
### Description of Issue
[Description of the issue]
I can not get Ender IO conduits to push in or pull out any item or fluid into the Basic Purifier

### Steps to Reproduce Issue
1. [First step]
Build a basic purifier in Space Astronomy 2
2. [Second step]
Try to use Ender IO conduits to insert buckets (Full or empty) or to pump in and out the liquids.

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION**
Space Astronomy 2 - 1.51
Extra Planets 1.10.2-1.1.0

**Where did this bug happen:** [Single Player or Server]
My own hosted Server

### Additional Information
[Any other information that may be able to help me with the problem]
I think I have this same issue with other machines as well but found ways to get around them.

**Comment by MJRLegends** [comment]
Does any Galacticraft machine work?

**Comment by MisterSmileyFace** [comment]
The advanced Oxygen Compressor allows air to be pumped into it. (Extraplanets)
The electronic Compress allows items to but piped into it. (Galacticraft Core)
The refinery allows fluids to be pumped into it. (Galacticraft Core)
If you need me to test more I can. 

Also while troubleshooting this myself I stumbled across anther bug.
If you put any Mek tank with fluids into the fluid purifier, it only gives you 1 bucket full and changes the item into the pink and black block and renames it Bucket 325:11 and becomes useless.

**Comment by MisterSmileyFace** [comment]
Another Update, Just tried to pump air out of the Oxygen sealer like I have already setup in other bases and it will no longer suck it out. I also think that the issue might have happened when I most recently upgraded to 1.51 Space Astronomy 2.

**Comment by MisterSmileyFace** [comment]
![2018-06-12_22 01 54](https://user-images.githubusercontent.com/40185656/41328185-5e08215c-6e8c-11e8-8bfe-61ab582f367e.png)
![2018-06-12_22 02 16](https://user-images.githubusercontent.com/40185656/41328188-600aa95c-6e8c-11e8-8b29-1ee6893da5cf.png)

**Comment by MJRLegends** [comment]
Since you said about the Oxygen sealer not working please report this to Galacticraft as i've not updated my machines recently. And since the Oxygen sealer isnt a ExtraPlanets block it seems to be a non ExtraPlanets issue here. My machines extend Galacticraft code so my machines can be affected by there changes

**Comment by MJRLegends** [comment]
Please make sure you mention its happening with Galacticraft machines not just ExtraPlanets ones

**Comment by MisterSmileyFace** [comment]
Do you know where I would go to do that?

**Comment by MJRLegends** [comment]
https://github.com/micdoodle8/Galacticraft/issues

**Comment by MisterSmileyFace** [comment]
Ok, so the oxygen was simple, a spec of hydrogen got in the pipe and that is why it wouldn't pump out air, so we are back to the orginal issue. I can not pump in infected water into the basic purifier. It pulls it out of the tank and into the pipe but will not enter the Basic Purifier.
