### ISSUE TITLE
Spawning always on the moon when creating a world

### ISSUE THREAD

**Issue by Geistica** [MJRLegends/ExtraPlanets#322]
### ---Issue Report---

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** 
yes

### Description of Issue
So basically I spawn all the time on the moon and if I try to go off of it I land back on it.

### Steps to Reproduce Issue
1. Create new world
2. spawn

Version of Mod using 
ExtraPlanets-1.7.10-2.0.4.jar

**Where did this bug happen:**
Singleplayer

### Additional Information
I have all galactic craft addons installed and some more mods. But they don't seem to be the problem. Someone said that you can edit it in the config but I couldn't find it so I ended up writing here.

**Comment by MJRLegends** [comment]
Nothing to do with me sorry

**Comment by Geistica** [comment]
What do you mean? it is cause even Galactic craft devs said it is something with your mod and not with the others cause I removed the addons and the other mods and it didn't work. Only until I removed this addon.

**Comment by MJRLegends** [comment]
Nope its not a feature or anything my mod touches.

**Comment by MJRLegends** [comment]
You've probably messed the configs up and caused it to all break but its not something my mod touches. Nothing i can do for something thats broken for just you
