### ISSUE TITLE
Basic Purifier #2

### ISSUE THREAD

**Issue by MisterSmileyFace** [MJRLegends/ExtraPlanets#323]
---Issue Report---
(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)

Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING): [Yes or No]
Yes

Description of Issue
[Description of the issue]
I can not get Ender IO conduits or Mek pipes to push in or pull out any item or fluid into the Basic Purifier. The fluid will enter the pipe and then sit in the pipe and not enter the basic purifier.

Steps to Reproduce Issue
[First step]
Build a basic purifier in Space Astronomy 2
[Second step]
Try to use Ender IO conduits to insert buckets (Full or empty) or to pump in and out the liquids. The same is for Mek pipes.
Crash log/Log (if applicable): [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

How do i locate a crash log on Minecraft on Curse/Twitch? see https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
How do i locate a crash log on Minecraft on FTB? see http://imgur.com/a/IbWNC

Screenshots (if applicable):

Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'): [VERSION**
Space Astronomy 2 - 1.51
Extra Planets 1.10.2-1.1.0

Where did this bug happen: [Single Player or Server]
My own hosted Server

Additional Information
[Any other information that may be able to help me with the problem]
I checked with GC on this issue, with the previous ticket the issue with air was a spec of hydrogen got in the pipes and that is why it would not pump out. That issue was resolved and everything is working correctly. Right now the ONLY block that is having this issue is the Basic Purifier.

**Comment by MisterSmileyFace** [comment]
FINALLY figured it out!!!! I am only leaving this in case you might want to mention or if anyone else has the issue. Despite the fact the Infected Water level indicator is on the left side of the GUI, you can ONLY pump infected water in through the right side of the machine.

**Comment by MJRLegends** [comment]
Yeah thats by design
