### ISSUE TITLE
[1.12.2] Map GUI broken

### ISSUE THREAD

**Issue by block508** [MJRLegends/ExtraPlanets#324]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue
When I click on the map and/or launch to space to get to the moon or some extra planets, the description/buttons to get there aren’t there. It’s just a blank blue box.

### Steps to Reproduce Issue
1. Open Map
2. Click on Moon or extra planet stuff

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]

**Where did this bug happen** Server

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by block508** [comment]
Btw I’m using 0.4.0

**Comment by block508** [comment]
And haven’t seen any issue about it

**Comment by MJRLegends** [comment]
You have dimension ids conflicts probably, test with just MJRLegendsLib, Galacticraft and ExtraPlanets and get back to me if that doesnt work

**Comment by MJRLegends** [comment]
All good for me 

![](https://i.gyazo.com/afe6388a672902a26b465012ef7dca32.png)
![](https://i.gyazo.com/10a18a39c4bd4085d63601b917eb2915.png)
![](https://i.gyazo.com/1560bcdcff0463dcbb079701e5ae2b41.png)

**Comment by block508** [comment]
Alright
