### ISSUE TITLE
Space suits Break

### ISSUE THREAD

**Issue by Lach01298** [MJRLegends/ExtraPlanets#325]
Are space suits suppose to break when there out of power? I think they shouldn't since space suit are really expensive. The amount of tin and steel (mainly from the pressure layers) is a lot (haven't counted but seem to be more than a rocket!). so when it runs out of power then takes one hit and breaks that's a lot of effort wasted. I think a better option is they can't break and that if they run out of power they stop protecting you from radiation, pressure and damage.

I would also make spacesuits (first tier) cheaper in steel and tin.

**Comment by MJRLegends** [comment]
Please update your version, and if not fill out the template to report a bug
