### ISSUE TITLE
[1.12.2] Space Suit breaking at 0 power when damage happens to the player

### ISSUE THREAD

**Issue by Lach01298** [MJRLegends/ExtraPlanets#326]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** 
yes

### Description of Issue
space suits break/disappear when they take damage with no power

### Steps to Reproduce Issue
1. Make space suit and wear
2. Do not charge
3. Take damage from mob e.g. zombie
4. Space suit disappears/breaks

**Crash log/Log (if applicable):** 

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** 
1.12.2-0.4.0

**Where did this bug happen:** 
single player
### Additional Information
Are space suits suppose to break when there out of power? I think they shouldn't since space suit are really expensive. The amount of tin and steel (mainly from the pressure layers) is a lot (haven't counted but seem to be more than a rocket!). So when it runs out of power then takes one hit and breaks that's a lot of effort wasted. I think a better option is they can't break and that if they run out of power they stop protecting you from radiation, pressure and damage.

**Comment by MJRLegends** [comment]
Thanks will take  look and get back to you soon

**Comment by MJRLegends** [comment]
Going to be taking a look at this in the next few hours sorry for the delay

**Comment by MJRLegends** [comment]
Is there anymore information you can provide towards reproducing this issue as im having trouble with this one. 

Could be a mod interacting with the space suit? maybe test with just Galacticraft, MJRLegendsLib & ExtraPlanets?

**Comment by MJRLegends** [comment]
Will reopen if any more information gets provided

**Comment by CrankySupertoon01** [comment]
https://www.youtube.com/watch?v=x-mQ5OT9PyM

**Comment by MJRLegends** [comment]
@CrankySupertoon01 that video is a old version

**Comment by MJRLegends** [comment]
Should of been fixed many versions ago like around v0.3.7 for mc 1.12.2
