### ISSUE TITLE
Already Decorating

### ISSUE THREAD

**Issue by Deadlock783** [MJRLegends/ExtraPlanets#327]
### ---Issue Report---

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

### Description of Issue
Already Decorating

### Steps to Reproduce Issue
1. Installed 1.7.10 latest mods (All 3 GalactiCraft Mods and Extra Planets)
2. Started server
3. Changed cauldron.yml (load-chunk-on-request) to false
4. Was in a dungeon and whatever block generated crashed the server

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

https://pastebin.com/ffxrA7QQ

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
GalactiCraftCore - 1.7-3.0.12.504.jar
GalactiCraft-Planets - 1.7-3.0.12.504.jar
MicdoodleCore - 1.7-3.0.12.504
ExtraPlanets - 1.7.10-2.0.4.jar
**Where did this bug happen:** [Single Player or Server]
server
### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Changing the option "load chunk on request" to false in cauldron.yml

**Comment by Deadlock783** [comment]
Uhm already tried that and it doesn't work

**Comment by Deadlock783** [comment]
I did already say that in the post up above

**Comment by spannerman79** [comment]
For reference, look at the crash log and see if there is a section that says;
```
-- Requested block coordinates --
Details:
    Found chunk: true
    Location: World: (168,73,-353), Chunk: (at 8,4,15 in 10,-23; contains blocks 160,0,-368 to 175,255,-353), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
```
In this case, whatever that was at `168,73,-353` caused the server crash.

Use MCEdit/MCEdit Unified on the DIM that it happened on, and go to those co-ords to find out what block it is which will help with what to do next.

Sorry for the necro, but when I saw this issue its the first thing I do when using Cauldron based build and I get an error like this.
