### ISSUE TITLE
Crash when config changed

### ISSUE THREAD

**Issue by CKTheUltimate** [MJRLegends/ExtraPlanets#33]
I have discovered a bug,when I changed the galactic raft default silicon ore to minechem element_Si,it crashes the game.Here is the crash report,hope that you can fix it.

http://pastebin.com/7wvZQ2w2 (Changed to pastebin by MJRLegends)

**Comment by MJRLegends** [comment]
@CKTheUltimate can you send me a copy of your galacticraft main config please and my addon config, use www.pastebin.com and then post the url here

**Comment by MJRLegends** [comment]
Also next time fill out the template and dont just delete it because then i would have the information i needed from you filling out the template

**Comment by MJRLegends** [comment]
Update out (1.0-Pre 3.6.10), see https://minecraft.curseforge.com/projects/extraplanets/files
