### ISSUE TITLE
Black Terrain if using your mod with shaders!

### ISSUE THREAD

**Issue by MrProton657** [MJRLegends/ExtraPlanets#330]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes
### Description of Issue
[Description of the issue]

### Steps to Reproduce Issue
1. [First step] use your mod with shaders on the overworld.
With your mod I get a blackscreen with shader in the overworld, can you please fix it somehow?

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

**Screenshots (if applicable):** 
# https://imgur.com/a/In0Jtji
**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
2.0.4
**Where did this bug happen:** [Single Player or Server]
Single Player
### Additional Information
[Any other information that may be able to help me with the problem]
With your mod I get a blackscreen with shader in the overworld, can you please fix it somehow? If you could I would we very grateful to you, because I like your mod and I want to use it in my private modpack!

**Comment by MJRLegends** [comment]
Sorry shaders isnt support
