### ISSUE TITLE
ExtraPlanets Won't Launch Minecraft

### ISSUE THREAD

**Issue by LemonHeadOnGit** [MJRLegends/ExtraPlanets#331]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues: Yes

### Description of Issue
[Everytime I launch Minecraft the game crashes before the title screen even appears]

### Steps to Reproduce Issue
1. [Install All required mods + JEI and Optifine]
2. [Launch Minecraft]

**Crash log/Log (if applicable): https://pastebin.com/GsxtWqgS

**Version of Mod using: 1.12.2

**Where did this bug happen: Single Player / Client

### Additional Information
I am using a MacBook Pro Late 2011

**Comment by MJRLegends** [comment]
You've downloaded the mod from the wrong site

**Comment by MJRLegends** [comment]
Checkout http://stopmodreposts.org/ as people shouldnt be allowed to repost mods on scam sites its illegal posting, And please download the browser plugins found near the bottom of http://stopmodreposts.org/get-involved/ to make sure your not helping these people!! #StopModReposts
