### ISSUE TITLE
Glowstone, and other nether textures missing

### ISSUE THREAD

**Issue by NightHawk5755** [MJRLegends/ExtraPlanets#332]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue
[Description of the issue]

### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]

**Where did this bug happen:** [Single Player or Server]

### Additional Information
[Any other information that may be able to help me with the problem]

I'm using singleplayer, and I am using version 1.12.2, 0.4.0
When I loaded up the mod, I noticed that the textures for nether blocks are missing...

to reproduce, just load up the mod...
with galactricaft, version 4.0.1.181
![2018-07-14_18 34 57](https://user-images.githubusercontent.com/41243962/42729151-af092710-8794-11e8-8643-9bf2e6b63647.png)

**Comment by MJRLegends** [comment]
Sorry my mod doesnt touch this textures so i cant take credit for this issue

**Comment by NightHawk5755** [comment]
ok, thanks

**Comment by NightHawk5755** [comment]
figured it out, user error

**Comment by MJRLegends** [comment]
No problem :D
