### ISSUE TITLE
Dimensions dont load

### ISSUE THREAD

**Issue by Skaptic** [MJRLegends/ExtraPlanets#333]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

### Description of Issue
When executing /dimensiontp, it takes 3min to load the entire screen.
Also, when trying to go to Venus and to the Moon, it just loads 30min and still doesnt load the dimension (it only says "Taking one small step"). The problem is, that it loads on all planets except on Venus and the Moon and I cant wait 1000 years for it to load (it never did actually). 
And is there a reason why I have 4 fps on every space station ?

### Steps to Reproduce Issue
1. Execute /dimensiontp
2. Go to Venus or Moon

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** 0.4.0 for 1.12.2

**Where did this bug happen:** Singleplayer

### Additional Information
The problem is not the performance of my device. I added 4 GB of RAM to Minecraft and I have a fast processor (Intel i7 4510U with 2 GHz) and a GeForce GTX 840M. 
I have the right version of MJRLegendsLib, Galacticraft and Extra Planets.

**Comment by MJRLegends** [comment]
Venus and the moon are not my dimensions

**Comment by MJRLegends** [comment]
Your issue isnt a issue with my mod sorry

**Comment by Skaptic** [comment]
The bug only happens if Extra Planets is installed.

**Comment by MJRLegends** [comment]
That still doesnt mean its my mod, you could have dimension id conflicts or something else causing the issue
