### ISSUE TITLE
[1.7+] Crash when disabling Nuclear bomb in the config

### ISSUE THREAD

**Issue by MasterEnderman** [MJRLegends/ExtraPlanets#335]
### Description of Issue
The Game crashes when i fly to Saturn.

### Steps to Reproduce Issue
1. place tier 5 rocket
2. fly to saturn
3. crash

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
https://paste.dimdev.org/bowoxozeci.mccrash

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
Forge: 14.23.4.2739
MicdoodleCore: 4.0.1.181
GalacticraftCore: 4.0.1.181
GalacticraftPlanets: 4.0.1.181
MJRLegendsLib: 1.1.4
ExtraPlanets: 0.4.0
Planet Progression: 0.2.5

**Where did this bug happen:** [Single Player or Server]
Singleplayer

**Comment by MJRLegends** [comment]
This crash is happening because you have disabled the nuclear bomb, please re-enable this or turn off the nuclear pile world gen in the config.

I will fix this in the next update so people dont have to do the above

**Comment by MasterEnderman** [comment]
alright thanks for the quick answer 👍

**Comment by MJRLegends** [comment]
Updates fixing this issue have been released
