### ISSUE TITLE
[1.7+] Crash with Fire/Nuclear Bomb when changing some config options

### ISSUE THREAD

**Issue by TwoTailedFox** [MJRLegends/ExtraPlanets#336]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

### Description of Issue
This occurs when traversing across the overworld.

### Steps to Reproduce Issue
This seems to occur when the game is attempting to generate new chunks, this didn't start occurring until I got to the edge of the currently-generated terrain. If I sit in already-loaded chunks, this error doesn't occur. I've only experienced this in the Overworld, similar exploration in the Nether has not yet yielded this error.

**Crash log/Log (if applicable):** https://pastebin.com/hWASBUgV

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [2.0.5]

**Where did this bug happen:** [Single Player]

### Additional Information
Mod List: https://pastebin.com/LtUPtEu3

**Comment by MJRLegends** [comment]
Please post a copy of your config file

**Comment by TwoTailedFox** [comment]
Config file: https://pastebin.com/jjxVGRHP

**Comment by MJRLegends** [comment]
Ok i think i know why. For the mean time you can disable nuclear bomb in the config to fix it.

**Comment by MJRLegends** [comment]
Please do let me know if you see anymore issues, progression issues as i see you have a lot of the addons and have most of my compact options on

**Comment by TwoTailedFox** [comment]
Disabling the Nuclear Bomb does not prevent the error from occurring, but disabling Keplar22b entirely does.

**Comment by MJRLegends** [comment]
Try disabling able the firebomb config option too aswell as the Nuclear Bomb one. You have a lot of compact options on so a lot is being changed so its hard to think about

**Comment by TwoTailedFox** [comment]
I can confirm that disabling both of these fixes the problem.

**Comment by MJRLegends** [comment]
Updates are rolling out for 1.8+ version as we speak will be showing on curseforge very soon

MC1.7 will come later on
