### ISSUE TITLE
[1.11+]broken texture in advanced and utimate oxygen compressor

### ISSUE THREAD

**Issue by tonimark** [MJRLegends/ExtraPlanets#337]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
yes
### Description of Issue
the issue as I open the advanced or ultimate oxygen compressor GUI everything is different  with a blank texture error 

### Steps to Reproduce Issue
1. just open the GUI of ultimate or advanced compressor and you will see

**Screenshots (if applicable):** 
![2018-08-05_00 37 41](https://user-images.githubusercontent.com/17166550/43680701-a4759c56-9848-11e8-86f9-66d1099a9441.png)

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
0.4.1
**Where did this bug happen:** [Single Player or Server]
signe-player

**Comment by tonimark** [comment]
additional information sorry if its the decompressor in image but on oxygen compressor is exactly the same

**Comment by MJRLegends** [comment]
Updates are rolling out as we speak will be showing on curseforge very soon
