### ISSUE TITLE
[suggestion/idea](1.12.2)add wire plug support for decontamination unit

### ISSUE THREAD

**Issue by tonimark** [MJRLegends/ExtraPlanets#338]
add wire plug support for decontamination unit it's very sad that I see that there aren't any wire plug input for decontamination unit and I always have to charge it via galacticraft batteries and no any other rf source capacitor. its better idea to add a plug for energy input via wire so i can make bases easier on other planets :)

**Comment by MJRLegends** [comment]
sorry but i wont be adding this, thanks for the suggestion though

**Comment by tonimark** [comment]
and how to recharge the decontamination unit without only galacticraft batteries :/
these batteries have low current and needs some time

**Comment by MJRLegends** [comment]
Use the battery it suggestions you to use
