### ISSUE TITLE
Startup Crash - Oct 2016

### ISSUE THREAD

**Issue by Gamalyelg** [MJRLegends/ExtraPlanets#34]
### ---Issue Report---
**Have you checked Closed Issues: Yes

### Description of Issue
Startup crash

### Steps to Reproduce Issue
1. Just startup

**Crash log/Log (if applicable): [http://pastebin.com/FyXePzin](url)

**Version of Mod using: [ExtraPlanets-1.0-Pre 3.6.11]

### Additional Information
I tried a couple of times, but didn't change anything in config. Furthermore, just by removing ExtraPlanets everything works fine. However, I do love your mod so freaking much, please help me :(

**Comment by MJRLegends** [comment]
Why are you using a year old version of galacticraft, you are using build #375 and the new/latest build is #463

**Comment by Gamalyelg** [comment]
Just because "Green builds are recommended for download" ... following the meta (I'm noob, bro... chill)

**Comment by MJRLegends** [comment]
It says use LATEST version not recommended on my addon pages....

**Comment by Gamalyelg** [comment]
You are such a charm :)

Thx anyway =P

**Comment by MJRLegends** [comment]
Haha No problem :D
