### ISSUE TITLE
[1.8+]can't launch any electrical rockets

### ISSUE THREAD

**Issue by tonimark** [MJRLegends/ExtraPlanets#340]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

### Description of Issue
I just spam or hold the spacebar but I can't launch any electrical rocket although i have all equipment and the rocket fully charged

### Steps to Reproduce Issue
1. build a powered rocket launch pad
2. attempt to launch it, see it won't

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):0.4.1

**Where did this bug happen:** signe-player

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by Ax1007** [comment]
Same problem, fully powered, placed the landing pad in a dozen different places. Wont launch at all.

**Comment by epeeforteyt** [comment]
Hello, I also have the same problem on my side - impossible to launch this rocket !

**Comment by MJRLegends** [comment]
Sorry for the delay i will be looking at this soon

**Comment by epeeforteyt** [comment]
thx =)

**Comment by MJRLegends** [comment]
Updates are rolling out as we speak will be showing on curseforge very soon
