### ISSUE TITLE
Add Support for other armour to be used a space suit style armor

### ISSUE THREAD

**Issue by MJRLegends** [MJRLegends/ExtraPlanets#341]
**Here is the list of the current suggestions for armours to be used as space suits:**
 Blood Magic Living Armor - https://github.com/MJRLegends/ExtraPlanets/issues/287
Radiation Shielding from Modular Powersuits Mod - https://github.com/MJRLegends/ExtraPlanets/issues/282

**If you got any more examples post below the mod name, armour name, reason you think it should be considered a space suit. And it might get added in the future**

**Comment by JonoColwell** [comment]
Could add some modifiers to Construct's armory.

**Comment by MJRLegends** [comment]
Will be added in the next update for MC 1.8.9 - MC 1.12.2

**Comment by MJRLegends** [comment]
Updates rolling out as we speak

**Comment by israpps** [comment]
i tried to add the stellar alloy armor of enderIO endergy and I still get damage and rad

**Comment by israpps** [comment]
is this right??
    # Format: 'modID:item:tier' | example: minecraft:iron_chestplate:4
    S:"List of armour items to be considered as a space suit" <
        enderio:item_stellar_alloy_boots:4
        enderio:item_stellar_alloy_leggings:4
        enderio:item_stellar_alloy_chestplate:4
        enderio:item_stellar_alloy_helmet:4

**Comment by MJRLegends** [comment]
Please make a new issue report
