### ISSUE TITLE
planets cant be view 

### ISSUE THREAD

**Issue by M6444** [MJRLegends/ExtraPlanets#343]
I have no idea if its a problem with this mod or something else i could be just dumb i know i have everything needed, each part of the actual Galacticraft mod and i have the most recent version of this mod 1.12.2-0.4.2.
  i can not view any other planets on the Galaxy map, i only see the overworld i cant go to or view any other planet

![2018-08-17_01 33 10](https://user-images.githubusercontent.com/42199213/44256480-22880d80-a1be-11e8-9a72-cf6c5b47bf44.png)

### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue
[Description of the issue]

### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]

**Where did this bug happen:** [Single Player or Server]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Ypu havent filled out the template

**Comment by MJRLegends** [comment]
Also it's not a bug its a feature and a mod called Planet Progression you to do stuff to research them
