### ISSUE TITLE
Forge loading stops at stage 2/7 and crashes

### ISSUE THREAD

**Issue by DragonTamr34** [MJRLegends/ExtraPlanets#344]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

### Description of Issue
I have a variety of mods loaded including galacticraft and extraplanets. With only galacticraft the game loads fine. With extraplanets added it stops at stage 2/7 and crashes.

### Steps to Reproduce Issue
1. Install galacticraft, mcdoodle core, galacticraft core, extraplanets, mjrlib, and other various mods.
2. Launch the launcher and click play, it will load to 2/7 and hang for a second before crashing.

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
https://pastebin.com/Wf7PmaVP
**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
1.12.2-0.4.2 extraplanets, galacticraft core/planets/mcdoodlecore 1.12.2-4.0.1.1.8.1, mjrlegends lib 1.12.2-1.1.5
**Where did this bug happen:** [Single Player or Server]       Single Player instance

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
This isnt a bug. You just reached the block limit
