### ISSUE TITLE
[1.12.2]electrical rockets ignores launch controller

### ISSUE THREAD

**Issue by tonimark** [MJRLegends/ExtraPlanets#346]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue
I set up automated launch pads between overworld and Eris but when I launch an electrical rocket (with of course having to remove launch pad off) the rocket removes the launch pad and pops the map instead of landing to the target planet

### Steps to Reproduce Issue
1. build up an electrical launch pad with a controller and activate it
2. build another launch pad with an active controller and ensure that both controllers are synchronized
3.launch the electrical rocket, you will see that the rocket ignores the launch controller
**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
there is no a log

**Screenshots (if applicable):** 
no screenshots
**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]

**Where did this bug happen:** [Single Player or Server]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Yeah its meant to as its not a fuelled rocket to get it working i would have to make a new launch controller block which i dont think i wanna do atm sorry
