### ISSUE TITLE
Moon temperature too low

### ISSUE THREAD

**Issue by Mugiwaxar** [MJRLegends/ExtraPlanets#348]
**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):**
Yes, related to [347](https://github.com/MJRLegends/ExtraPlanets/issues/347)

### Description of Issue ###
I'm realy sorry to open a new issue, but you have closed my first post too quickly
Then:
Yes, I have a space suit, I have the thermal protection T1 and a oxygen setup.
I really think everythings is ok, but when I am on the moon, I die...
The chat say:
"[main/INFO] [minecraft/GuiNewChat]: [CHAT] Mugiwaxar forgot thermal protection"
It's appening since I added this mod

Please, I really love this mod, don't close the issue so quickly!
I don't want to remove it!

### Steps to Reproduce Issue ###
1. Go to the moon
2. Die

**Crash log/Log (if applicable):**
Any

**Screenshots (if applicable):** 
![screenshot](https://user-images.githubusercontent.com/4124999/44965634-e3381b80-af36-11e8-95fd-57395ee39204.png)

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
 0.4.3

**Where did this bug happen:**
Tested on Multiplayer and Singleplayer

### Additional Information ###
Pack mod: FTB Revelation
Other Space mod: More-planet

**Comment by MJRLegends** [comment]
Its a Galacticraft issue then. Also dont open new issues in future you just comment ok your old issue

**Comment by MJRLegends** [comment]
I dont chnage or do anything with thermal padding on the moon

**Comment by MJRLegends** [comment]
**Cause:** mocreatures uses -17 id for its dimension which is the uranus dimension in ExtraPlanets and thats causing weird issues. ID Conflicts in the past have never caused a issue like this. So i dont claim this issue with ExtraPlanets being at fault.

**Solution:** Change Dimension ID in config
