### ISSUE TITLE
Client Low FPS/Crash on Space Stations

### ISSUE THREAD

**Issue by sfxworks** [MJRLegends/ExtraPlanets#349]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes

### Description of Issue
When a user makes a space station they get 0.5 FPS or crash upon joining. 

### Steps to Reproduce Issue
1. Make a Venus or Mars Space station on Lapito's Galacticraft
2. Performance / Crashes. 

We have no crash log to report since its either a system freeze or low fps event.

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
1.12.2-0.4.0

**Where did this bug happen:** [Single Player or Server]
Server

### Additional Information

Server information:

Minecraft: 1.12.2
SpongeAPI: 7.1.0-SNAPSHOT-7105dfc
SpongeForge: 1.12.2-2705-7.1.0-BETA-3361
Minecraft Forge: 14.23.4.2705
Java version: 

openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)
Operating System: CentOS Linux release 7.5.1804 (Core)

Plugins/Mods:

Plugins (27): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, Aliases, BattleLog, CarrotShop, CatClearLag, Holograms, LangSwitch, LuckPerms, MMCReboot, MMCRestrict, MMCTickets, Nucleus, Plan, ProjectCore, ProjectPortals, ProjectWorlds, ServerListPlus, SleepVote, Total Economy, Universe Guard 2, VillagerShops, Web-API, WorldEdit, spark

Mods (97): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, AE2 Stuff, Actually Additions, Advanced Solar Panels, Ambience, Applied Energistics 2, AutoRegLib, BC Builders, BC Energy, BC Factory, BC Robotics, BC Silicon, BC Transport, BD Lib, Baubles, Blood Debug, Brandon's Core, BuildCraft, BuildCraft Compat, BuildCraft Lib, CoFH Core, CoFH World, CodeChicken Lib, ComputerCraft, CustomNPCs, DiscordIntegration, Draconic Evolution, Ender IO, Ender IO Applied Energistics Conduits, Ender IO Base, Ender IO Conduits, Ender IO Integration with Forestry, Ender IO Integration with Tinkers' Construct, Ender IO Integration with Tinkers' Construct, Ender IO Machines, Ender IO Open Computers Conduits, Ender IO Powertools, Ender IO Refined Storage Conduits, EnderCore, EnderStorage, Ex Compressum, Ex Nihilo Creatio, Extra Cells 2, Extra Planets, Extreme Reactors, Faction Mod, Galacticraft Core, Galacticraft Planets, ICBM-Classic, Immersive Engineering, IndustrialCraft 2, Inventory Tweaks, Iron Chest, It's the little things, JourneyMap, Just Enough Items, MJRLegendsLib, Malisis Advert, MalisisCore, Mantle, Mekanism, MekanismGenerators, MekanismTools, Micdoodle8 Core, NoMoreRecipeConflict, NuclearCraft, OMLib, Open Glider, Open Modular Turrets, OpenBlocks, OpenModsLib, OpenModsLib Core, PlusTiC, Quark, Random Things, Reborn Core, Redstone Arsenal, Redstone Flux, SG Craft, Simply Jetpacks 2, Smooth Font Core, Steve's Carts 2, TESLA, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Tinkers' Construct, VanillaFix, What Are We Looking At, Wireless Crafting Terminal 2, Zero CORE, p455w0rd's Library

**Comment by MJRLegends** [comment]
With a java profiler sample or a crash log i cant do anything as your not just using my mods so could be anything causing it like a million different things. If you need help getting a java profile sample let me know. I will reopen this when theres information to go off

**Comment by sfxworks** [comment]
Please provide me with a client side java-profiler. I only know of sponge & spark but that is server-side.

**Comment by MJRLegends** [comment]
This one should do the job. Put it on your client https://refinedstorage.raoulvdberge.com/wiki/profiling

**Comment by sfxworks** [comment]
Here are the rendered NPS files. 

https://mcserverhosting-distribution.nyc3.digitaloceanspaces.com/distribution/marssample.nps
https://mcserverhosting-distribution.nyc3.digitaloceanspaces.com/distribution/marssample1.nps

**Comment by MJRLegends** [comment]
@sfxworks Any news on the java-profiling, did you manage to make the files?

**Comment by sfxworks** [comment]
We're working on getting that over to you. Sorry for the delay.

**Comment by FatherFin** [comment]
@MJRLegends I am sorry for not getting back with you as soon as possible. After extensive profiling on different space stations as well as trying our best to replicate the issue, it has been found out that it is a client-sided issue for users who don't allow enough ram. We are experiencing server crashes upon joining Jupiter but, that's for a different issue. 

Thanks for everything!
~Fin
