### ISSUE TITLE
[1.8+] Pressure Damage underwater in Sealed Area.

### ISSUE THREAD

**Issue by UnduGT** [MJRLegends/ExtraPlanets#350]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

### Description of Issue
I wanted to create a Squid Farm in my Space Station. So I had a Room that is completely Sealed and has the Ambient Thermal Controller so I don't get any Damage. But if I go in the water pool I created I get damage. I know that it makes sense If I don't have Air underwater but the Pressure Damage?

### Steps to Reproduce Issue
1. Create Room in Space or Planet
2. Seal and add the Ambient Thermal Controller
3. Build a Water Pool

**Crash log/Log (if applicable):** --

**Screenshots (if applicable):** --

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** ExtraPlanets-1.12.2-0.4.3, MJRLegendsLib-1.12.2-1.1.5

**Where did this bug happen:** [Server]

### Additional Information
--

**Comment by MJRLegends** [comment]
Think i know the issue. Thanks will fix this

**Comment by MJRLegends** [comment]
Just noticed when your in water, oxygen from oxygen sealers dont work either. I might revert this change if thats the case

**Comment by MJRLegends** [comment]
Updates are rolling out as we speak for MC 1.8+
