### ISSUE TITLE
This mod

### ISSUE THREAD

**Issue by CrankySupertoon01** [MJRLegends/ExtraPlanets#351]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes

### Description of Issue
Mod is 100% broken. See https://www.youtube.com/watch?v=x-mQ5OT9PyM.

### Steps to Reproduce Issue
1. watch video

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

**Screenshots (if applicable):** 
https://www.youtube.com/watch?v=x-mQ5OT9PyM

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
0.9.3?

**Where did this bug happen:** [Single Player or Server]
SP

### Additional Information
https://www.youtube.com/watch?v=x-mQ5OT9PyM

**Comment by MJRLegends** [comment]
Not a valid issue report
