### ISSUE TITLE
Turkish Translate tr_TR.lang

### ISSUE THREAD

**Issue by kralrindo** [MJRLegends/ExtraPlanets#354]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

### Description of Issue
language translate

### Steps to Reproduce Issue
1.-

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [1.12.2-0.4.3]

### Additional Information
hi 
I've done the translation before
I  have now translated again
1.12.2 0.4.3 turkish language file
http://www.mediafire.com/file/rlrxzqcb510zcck/tr_TR.lang/file

I have a question
where is the true / false language line
I could not translate

**Comment by MJRLegends** [comment]
Thanks will be added for all version from MC 1.7 to MC 1.12.2 for the next updates
