### ISSUE TITLE
1.12.2 Rendering screen crash when opening galaxy map

### ISSUE THREAD

**Issue by Brunoshe** [MJRLegends/ExtraPlanets#355]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):**
yes but didnt helped

### Description of Issue
When i open galaxy map with extra planets mod installed, even if i disable extra planets galaxy map it crashes

### Steps to Reproduce Issue
1. Enter any world
2. Open galaxy map

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
https://pastebin.com/fpeuGhrV

**Screenshots (if applicable):** 
http://prntscr.com/kxus5v

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** 
ExtraPlanets-1.12.2-0.4.3

**Where did this bug happen:** [Single Player or Server]
Single player

### Additional Information
forge version 1.12.2-14-23.4.2718

**Comment by MJRLegends** [comment]
this is a galaxy space issue https://github.com/BlesseNtumble/GalaxySpace/issues/253

**Comment by Brunoshe** [comment]
Nothing happens, continues crashing..................... U-U

**Comment by MJRLegends** [comment]
Remove AsmodeusCore and Galaxy Space and it will work, provided you dont have any other issues like dimension id conflicts or other mods doing weird things

**Comment by MJRLegends** [comment]
@Brunoshe should be fixed as of latest versions. It was some GC and Galaxy Space issues which are all sorted out
