### ISSUE TITLE
1.12.2 Bug

### ISSUE THREAD

**Issue by wiqg** [MJRLegends/ExtraPlanets#356]
So , recently i've downloaded galacticraft and played it for a while until i got interested in some addons for it . I downloaded Extra planets and Galaxy Space , but they both crash . Not exactly crash but , everytime i start the game and i type /dimensiontp nothing happens , i cant type in chat , right click something or anything , just walk around .I cant even quit the game , i have to close it with task manager...

**Comment by MJRLegends** [comment]
Fill out the template dont delete it

**Comment by MJRLegends** [comment]
And already posted https://github.com/MJRLegends/ExtraPlanets/issues/355

**Comment by MJRLegends** [comment]
for future reference seems the solution is 

> disable GalaxyMap in configs/AsmodeusCore/core.conf
> 
> #Enable/Disable New Galaxy Map.
> B:enableNewGalaxyMap=true
>
