### ISSUE TITLE
Ambient Temperature Controller not working due to Warp Drive Air Generator being used in the same area.

### ISSUE THREAD

**Issue by ultramarines40** [MJRLegends/ExtraPlanets#357]
---**Issue Report**---

**Have you checked Closed Issues  [Yes]

**Description of Issue**
1. When creating a base on the moon and the oxygen sealer is working fine and no pressure difference
2.  When adding a Ambient Thermal Controller to a oxygen sealer nothing happens 

### Steps to Reproduce Issue
1. Creating a base and setting up all the machines to get a working atmosphere inside base
2. insert the Ambient Temperature Controller and the pressure inside the base does not work

**Where did this bug happen:** [Both on a single player and on a server]

GalacticraftCore-1.12.2-4.0.1.181.jar
Galacticraft-Planets-1.12.2-4.0.1.181.jar
MJRLegendsLib-1.12.2-1.1.5.jar

along with quite a few other mods i don't want to put them all here cause there is alot

**Comment by MJRLegends** [comment]
What ExtraPlanets version?

**Comment by MJRLegends** [comment]
Do you take pressure damage when Ambient Thermal Controller in the oxygen sealer without space suit on?
Do you have Ambient Thermal Controller in all oxygen sealers?

**Comment by ultramarines40** [comment]
i just got 1 sealer and yes well i didnt have one in my one on the server but the one on my single player has one and it works hmmm is it a glitch or something?

**Comment by MJRLegends** [comment]
Do you take pressure damage when Ambient Thermal Controller in the oxygen sealer without space suit on?

**Comment by MJRLegends** [comment]
Im not seeing anything, wrong. I tested on a server and single player world i can reproduce the issue. Please can you send me a copy of your world and provide me information to which planet/moon/station and the coords of your base is?

**Comment by MJRLegends** [comment]
Or if your playing on a server, you can provide me the ip address. I'd recommenced private messaging me the ip address though. Curseforge would be a good place for that

**Comment by MJRLegends** [comment]
Please see my messages above @ultramarines40

**Comment by Nyabloody** [comment]
I got the same issue on my server. Ambient Temperature Controller is not working and provide zero protection against pressure. If you are willing, I could share you the ip and the modpack to test it? I think your pressure system has some issues since the server config is also not working for that and when playing as an android I'm still taking pressure damage without a space suit.

**Comment by MJRLegends** [comment]
@Korvynus Please can you send me a copy of your world and provide me information to which planet/moon/station and the coords of your base is?

without theses its pointless reporting as i cant produce it so i need someone to invest in helping for this issue

**Comment by Nyabloody** [comment]
@MJRLegends  It's hosted on a dedicated server and the world folder is around 1,5GB. I can't take that decision alone also. But like I said I can provide you everything to login so you can test directly on the server. Preferably in pm since the server is private.

**Comment by MJRLegends** [comment]
I would need a world with the issue for debugging without it i can never get to the bottom of a few getting this issue sorry

**Comment by Nyabloody** [comment]
Ok actually for me it's a conflict between Oxygen Sealer (GC) and Air Generator from WarpDrive. Everything else work except the android from MatterOverdrive still suffering from pressure while it should not. Do you still need a world to debug for the android issue?

**Comment by MJRLegends** [comment]
Nope we will talk about that issue over on that issue report as this one has been resolved now
