### ISSUE TITLE
Compressor not placing items correctly

### ISSUE THREAD

**Issue by xob** [MJRLegends/ExtraPlanets#358]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

### Description of Issue
The Electric Compressor is impossible to fully automate when creating higher-tier heavy-duty plates.

Using a hopper to create Tier 4 Heavy-Duty Plates, the items do not go in the correct slots in the correct amount, resulting in an incomplete last craft. This then breaks the whole crafting operation, as it cannot complete Tier 4 plates.

Mods installed:
Minecraft 1.12.2
forge-14.23.5.2769
ExtraPlanets-1.12.2-0.4.3
Glacticraft-Planets-1.12.2-4.0.1.181
GlacticraftCore-1.12.2-4.0.1.181
jei_1.12.2-4.13.1.220
MicdoodleCore-1.12.2-4.0.1.181
MJRLegendsLib-1.12.2-1.1.6

### Steps to Reproduce Issue
1. Place a compressor or electric compressor (they both have the issue)
2. Give it fuel or power
3. Place a hopper on top
4. Put ingredients for more than 2 Tier 4 Heavy-Duty Plates in the hopper
5. Watch as the compressor fails to craft the last plate

**Screenshots (if applicable):** I assume a video will do? https://youtu.be/eehcRnReJjs

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** 0.4.3

**Where did this bug happen:** Single Player, untested on server.

### Additional Information
I am unsure if the problem lies in the Galacticraft code or in the ExtraPlanets code, but seeing as the problem only happens with higher-tier heavy-duty plates (tiers 1 to 3 are absolutely fine), I reported the problem here.

**Comment by MJRLegends** [comment]
The Electric compressors and ingot compressor are not blocks added by ExtraPlanets

**Comment by MJRLegends** [comment]
I cant fix sorry
