### ISSUE TITLE
[1.7+] Disabling tools in config leads to NPE on Initialization

### ISSUE THREAD

**Issue by nexfwall** [MJRLegends/ExtraPlanets#360]
### ---Issue Report---

**Have you checked Closed Issues:** Yes, by title at least.

### Description of Issue
Disabling tools in config leads to crash on Initialization phase.

### Steps to Reproduce Issue
1. Disable some of the tools in config. It's unknown if it's some certain one or all the tools affected.
2. Launch Minecraft again
3. ???
4. Crash

**Crash log/Log:** https://pastebin.com/SVEnRK15

**Version of Mod using:** 1.12.2-0.4.3

**Where did this bug happen:** Initialization of client

### Additional Information
I disabled Mercury, Palladium and Uranium tools personally before encountered this.

**Comment by MJRLegends** [comment]
ahh ok i know why, its a easy fix. To fix it for the mean time if you enable Palladium tools it will stop the crashing in till i release a update

**Comment by MJRLegends** [comment]
Updates are rolling out as we speak for MC 1.8+, MC 1.7.10 will be very soon
