### ISSUE TITLE
Graphic bug in galaxy map

### ISSUE THREAD

**Issue by KrauzeBartek** [MJRLegends/ExtraPlanets#362]
Hi. I have some graphic bug. I don't know you describe this bug, so I've sent a img.

https://imgur.com/a/bnVXewd

ExtraPlanets-1.12.2-0.4.3

GalacticraftCore-1.12.2-4.0.1.181

OptiFine_1.12.2_HD_U_E2

Forge 14.23.5.2770

**Comment by MJRLegends** [comment]
Please fill out the template dont delete it

**Comment by MJRLegends** [comment]
Will reopen when dome so
