### ISSUE TITLE
[1.8+] Serverside crash when right-clicking decontamination unit

### ISSUE THREAD

**Issue by dsmall3303** [MJRLegends/ExtraPlanets#363]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes

### Description of Issue
Upon right-clicking a decontamination unit, it will throw an "Error executing task" exception.

### Steps to Reproduce Issue
1. Place Decontamination Unit
2. Right-click on Decontaminaiton Unit

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

VanillaFix was used to capture the issue
https://paste.dimdev.org/rinanaxami.mccrash

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** 1.12.2-0.4.3            

**Where did this bug happen:** [Single Player or Server]
Single player

### Additional Information
[Any other information that may be able to help me with the problem]
Happens both when the machine is crafted and is placed with creative mode

**Comment by MJRLegends** [comment]
i think i know why its happening, shouldnt be to hard to fix

**Comment by MJRLegends** [comment]
Updates are rolling out as we speak to fix this
