### ISSUE TITLE
[1.10.2] Crash from Missing Class

### ISSUE THREAD

**Issue by TheLittleArtist** [MJRLegends/ExtraPlanets#364]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
yes
### Description of Issue
[Description of the issue]
Crash during loading of Extra Planets
### Steps to Reproduce Issue
1. Attempt to boot custom modpack through curse
2. crashes during 2/7 of Forge loading, during Extra Planets loading

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC
https://pastebin.com/qaPjZGRw
**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
EP 1.10.2-1.1.6
**Where did this bug happen:** [Single Player or Server]
Loading
### Additional Information
[Any other information that may be able to help me with the problem]
MJRLegendsLib 1.10.2-1.1.3
GC Core 4.0.1.181
GC Planets 4.0.1.181
MicDoodleCore 4.0.1.181

I can confirm i can see it load GC & EP during stage 1/7 and stage 2/7

**Comment by MJRLegends** [comment]
Have you disabled anything in the ExtraPlanets config?

**Comment by TheLittleArtist** [comment]
I have not.

**Comment by MJRLegends** [comment]
Please try downloading the mod again, as im unable to reproduce this issue

**Comment by TheLittleArtist** [comment]
So i redownloaded and it didnt work, but i then added extraplanets to an instance i had already played galacticraft content on, and it worked fine. 
Booted my new instance without EP and then closed it without starting a world, then readding EP worked. Using the original download I had.

**Comment by MJRLegends** [comment]
Updates are rolling out as we speak, sorry again for taking so long for me to notice it was a actual bug. I messed up there.
