### ISSUE TITLE
Crash when I open the map

### ISSUE THREAD

**Issue by Mugiwaxar** [MJRLegends/ExtraPlanets#366]
### ---Issue Report---

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** 
YES

### Description of Issue
The game crash when I open the galaxy map

### Steps to Reproduce Issue
1: Start the game
2: Open The map

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
[PastBin](https://pastebin.com/zc4uBUMH)

**Screenshots (if applicable):** 
No

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
ExtraPlanet: 1.12.2-0.4.2
Forge: 1.12.2-14.23.5.2772
GalactiCraft: 1.12.2-4.0.1.181
GalaxySpace: 2.0.2+STABLE

**Where did this bug happen:** [Single Player or Server]
Single and multi

### Additional Information
Only crash on combinaison with GalaxySpace

**Comment by MJRLegends** [comment]
Already posted https://github.com/MJRLegends/ExtraPlanets/issues/355

**Comment by MJRLegends** [comment]
The issue reason and the solution is on the issue i linked
