### ISSUE TITLE
Saturn Boss being despawned (1.7.10)

### ISSUE THREAD

**Issue by Breadabix** [MJRLegends/ExtraPlanets#367]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes

### Description of Issue
On the modpack I am playing the saturn ghast boss if being despawned, and this is produced in the server console. 
[Saturn Boss removal.txt](https://github.com/MJRLegends/ExtraPlanets/files/2544078/Saturn.Boss.removal.txt)

### Steps to Reproduce Issue
1. Download and install this modpack on Curse: https://www.dropbox.com/s/tf1iske42zx9yen/Modpack%20Download.rar?dl=0
2. Go to saturn and find a dungeon.

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):**
ExtraPlanets-1.7.10-2.0.5.jar

**Where did this bug happen:** [Single Player or Server]
Singleplayer and Server

### Additional Information
[Mod List.xlsx](https://github.com/MJRLegends/ExtraPlanets/files/2544255/Mod.List.xlsx)

**Comment by MJRLegends** [comment]
Ahh ok i thought you meant something else sorry my mistake but yeah its a Kcauldron thing you need to get the server owner to set the following in cauldron.yml
https://camo.githubusercontent.com/f57395487c65a7945321aeb55735de0a18617778/68747470733a2f2f692e6779617a6f2e636f6d2f64373634653538323537306439323336356463653839376565313333346333612e706e67

**Comment by MJRLegends** [comment]
Known issue https://github.com/MJRLegends/ExtraPlanets/issues/31

**Comment by Breadabix** [comment]
Easy enough considering im running the server :). Thanks

**Comment by Breadabix** [comment]
Can confirm this has fixed it server side, although in singleplayer this is still occuring and as far as I can find I can not change the entity bounding box size for singleplayer.

**Comment by Breadabix** [comment]
I dont know what mod might be affecting it, and I definitely havent got kcauldron running in singleplayer

**Comment by MJRLegends** [comment]
The Saturn boss has been in the 1.7 version for over a year and this is the first im here of it in single player, so cant imagine it being a issue. with kcauldron on multiplayer its a known thing for sure

**Comment by Breadabix** [comment]
I cant find any log that says the same as the server log, however the behavior is exactly the same so Im pretty certain its being caused by the same thing as the server, Ill do more testing tomorrow to try and figure out if a specific mod is to blame.

**Comment by MJRLegends** [comment]
you sure your not just on peaceful difficult ?

**Comment by Breadabix** [comment]
100% sure im not, mobs are spawning from the spawners in the dungeons

**Comment by Breadabix** [comment]
OK so I have deleted config files from mods that have been removed from the pack and now it works.

**Comment by MJRLegends** [comment]
Glad you fixed it
