### ISSUE TITLE
[1.7] Kepler22b Copper/Tin ore

### ISSUE THREAD

**Issue by Breadabix** [MJRLegends/ExtraPlanets#368]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes, couldnt find anything.

### Description of Issue
Kepler22b Copper and Tin ore have the wrong names, so Tin ore, while looking like tin and producing tin ingots is called Copper ore, and vice versa.

### Steps to Reproduce Issue
1. Use latest version of ExtraPlanets & Galacticraft 1.7.10
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

**Screenshots (if applicable):** 
This is actually Tin ore: https://gyazo.com/2bba544ec20f4191137f2812ce4207b7
This is actually Copper ore: https://gyazo.com/777a3fa14aa457c3c85b3901ecc11e65

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
ExtraPlanets-1.7.10-2.0.5.jar

**Where did this bug happen:** [Single Player or Server]
Singleplayer and Server

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Thanks yeah i see the issue, i know what is wrong too, stuff seems to of got messed up when i back ported a lot from MC 1.8.9+ to MC 1.7.10

**Comment by MJRLegends** [comment]
Update will be out in the next couple of days to fix this sorry for the delay

**Comment by Breadabix** [comment]
Thanks

**Comment by MJRLegends** [comment]
Update is being uploaded as we speak
