### ISSUE TITLE
Flans mod conflict / crash. Crash log needed!

### ISSUE THREAD

**Issue by ItzKarlPvP** [MJRLegends/ExtraPlanets#369]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

### Description of Issue
Flans mod conflict/crash with extra planets

### Steps to Reproduce Issue
1. install flans mod , extra planets and galacticraft 
2. try to launch minecraft

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [ExtraPlanets-1.12.2-0.4.3]

**Where did this bug happen:** [Single Player]
SinglePlayer

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Please post a crash log. You cant report a crash issue without the log to go with it.

**Comment by saipul1982** [comment]
Oke.....

**Comment by MJRLegends** [comment]
@saipul1982 do you have a crash log for this

**Comment by Krotain** [comment]
[crash-2019-01-08_14.43.52-client.txt](https://github.com/MJRLegends/ExtraPlanets/files/2738207/crash-2019-01-08_14.43.52-client.txt)
I am running ftb revelations plus some extra mods including flans mod and was thinking of adding this mod

**Comment by MJRLegends** [comment]
Thank you

**Comment by MJRLegends** [comment]
@Krotain plz can you try without ExtraPlanets and tell me if it still crashes?

**Comment by Krotain** [comment]
Works fine with galacticraft and mods like moreplanets and the progression mod it's only extraplanets that I've tried that crashes with flans

**Comment by BluePyros** [comment]
I've encountered this as well.  The content pack that the crash log calls out, Apocalypse, got baked into the latest releases of Flans, and it doesn't even work far as I can tell.  Removing it from the .jar resolves the issue and everything works fine afterwards, so something in that specific content package and only that package isn't playing nice.

**Comment by MJRLegends** [comment]
Seems to be a flans mod or Galacticraft issue, confirmed by https://github.com/BlesseNtumble/GalaxySpace/issues/275

**Comment by DarkMatterXCIX** [comment]
Any update on this at all? im actually excited for a fix

**Comment by MJRLegends** [comment]
Nothing i can do sorry its not my mods fault..
