### ISSUE TITLE
Crash on launch with Reika's Mods.

### ISSUE THREAD

**Issue by MaDmaxwell311** [MJRLegends/ExtraPlanets#37]
### ---Issue Report---

**Have you checked Closed Issues (if applicable):** Yes 
### Description of Issue
Crash on launch of both server and client with @ReikaKalseki 's mods.
### Steps to Reproduce Issue
1. launch either server or client with mods installed

**Crash log/Log (if applicable):** https://gist.github.com/MaDmaxwell311/1459d033214382f9e43d8795bc919dea

**Version of Mod using:** 1.0-Pre 3.7.0

### Additional Information
These crashes only occur with 1.0-Pre 3.7.0, there is no crash with 1.0-Pre 3.1.6.13

**Comment by MJRLegends** [comment]
Its a dragon api issue, im not doing anything apart from registering blocks and items and ore dictionary stuff which is all vaild

**Comment by MaDmaxwell311** [comment]
So report this to Reika?

**Comment by MJRLegends** [comment]
Yeah the crash log shows all dragon api not forge or my mod so my mod isnt doing anything invalid

**Comment by MaDmaxwell311** [comment]
Alright will do.
