### ISSUE TITLE
Invalid Fingerprint Detected / Texture has visual artifacts

### ISSUE THREAD

**Issue by realTIMematrix** [MJRLegends/ExtraPlanets#370]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes
### Description of Issue
Minecraft Game Output shows errors

### Steps to Reproduce Issue
1. Start Minecraft 1.12.2 with Forge 14.23.5.2768
2. Watch Game Output

**Crash log/Log (if applicable):** 
Texture extraplanets:textures/items/geiger_counter.png with size 24x24 will have visual artifacts at mip level 4, it can only support level 3. Please report to the mod author that the texture should be some multiple of 16x16.

The mod extraplanets is expecting signature b02331787272ec3515ebe63ecdeea0d746653468 for source ExtraPlanets-1.12.2-0.4.5.jar, however there is no signature matching that description
extraplanets: Invalid fingerprint detected! The file ExtraPlanets-1.12.2-0.4.5.jar may have been tampered with. This version will NOT be supported!

Fully Log: https://pastebin.com/Q3LPn8g6 

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** 0.4.5

**Where did this bug happen:** Single Player

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
They are both fine, dont worry. Thanks for the report though. I might reupload the jars though to fix the sign issue

**Comment by MJRLegends** [comment]
New jars have been uploaded will be showing soon :D
