### ISSUE TITLE
Spongeforge Planets Menu Bug?

### ISSUE THREAD

**Issue by NightScale5755** [MJRLegends/ExtraPlanets#373]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes

### Description of Issue
[Description of the issue]
Whenever I go to the Galaxy Map, with Galacticraft, Extra Planets, and Spongeforge installed. I get the menu, but all the planet info is blank. I don't why, but it doesn't happen without Extra Planets.

### Steps to Reproduce Issue
1. [First step]
Install Spongeforge, Galacticraft, and Extra Planets
2. [Second step]
Open the Galaxy Map.

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
Extra Planets: 1.12.2-0.4.5
MJRLegendsLIB: 1.12.2-1.1.6

**Where did this bug happen:** [Single Player or Server]
Server

### Additional Information
[Any other information that may be able to help me with the problem]
I can select the planets, but the info panels are blank. I cannot even travel to them.

**Comment by MJRLegends** [comment]
Please post your log files

**Comment by MJRLegends** [comment]
You probably have dimension id conflicts and it probably says this in your log files

**Comment by MJRLegends** [comment]
Since im 99% sure its id conflicts and you just need to check the logs to find out what on and then change it via config

**Comment by MJRLegends** [comment]
#324

**Comment by NightScale5755** [comment]
ok, so here you go:
![2018-11-15_21 59 53](https://user-images.githubusercontent.com/43540281/48597128-c601cf00-e921-11e8-8743-4de307b79bbd.png)
[latest.log](https://github.com/MJRLegends/ExtraPlanets/files/2587928/latest.log)

**Comment by NightScale5755** [comment]
in the mean time, I'll look at Dimension IDs

**Comment by NightScale5755** [comment]
only issue is that it only does this when I'm on my server, not singleplayer...

**Comment by MJRLegends** [comment]
Please post your server and client log files

**Comment by MJRLegends** [comment]
I need 

fml-client-latest.log
debug.log
fml-junk-earlystartup.log

for the client too please

**Comment by NightScale5755** [comment]
ok

**Comment by NightScale5755** [comment]
[debug.log](https://github.com/MJRLegends/ExtraPlanets/files/2587969/debug.log)
ummm. the other two logs don't show up

**Comment by NightScale5755** [comment]
[debug.log](https://github.com/MJRLegends/ExtraPlanets/files/2587975/debug.log)
server.

**Comment by MJRLegends** [comment]
Ok your error is java.lang.IllegalArgumentException: Could not get provider type for dimension -19, does not exist

meaning something is wrong with the -19 dimension. There conflict of id or spongeforge still has the bug where it makes dimensions nethers. which you will need to report to them. If not your server files are not matching client or are messed up

**Comment by NightScale5755** [comment]
ok. will do.

**Comment by MJRLegends** [comment]
The fact it works in single player points towards your server files having a issue or a spongeforge thing. You can always try a normal forge to see if its spongeforge. If it is spongeforge im out with helping as i've reported the bug it thinks dimensions are nether sometimes/most of the time but got no where so i gave up

**Comment by NightScale5755** [comment]
Well, I'm going to try reIDing Dimension -19, see if that works

**Comment by NightScale5755** [comment]
more than likely it's sponge, so I'm going to stop commenting this thread now...

**Comment by MJRLegends** [comment]
Here is the spongeforge issue report for mc 1.10.2 but the problem was in 1.12.2 to but not sure if it still exists https://github.com/SpongePowered/SpongeForge/issues/1429
