### ISSUE TITLE
Planet rocket tiers (Question) 

### ISSUE THREAD

**Issue by RiptideC27** [MJRLegends/ExtraPlanets#375]
Is there any way that you can change the required rocket tier need to get to certain planets?
(Example Kepler 22b needs a tier 2 rocket to get to it instead of a tier 10)

**Comment by MJRLegends** [comment]
Nope sorry allowing for that would mess up all the progression elements

**Comment by MJRLegends** [comment]
Might be something to add in the future though i will have a think about it and how i can make it work

**Comment by RiptideC27** [comment]
Thanks for the answer. I would love to have this in the future for modpack but I do see how it can mess with the progression of the mod.
