### ISSUE TITLE
Venus Bug/Glitch

### ISSUE THREAD

**Issue by jillv46** [MJRLegends/ExtraPlanets#376]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes
### Description of Issue
When I go to Venus I die instantly from high pressure even though I have the suit on. I tried every tier suit and thermal padding and I still keep dying.

### Steps to Reproduce Issue
1. Use a rocket to leave the overworld or any planet/moon etc that you are currently on.
2. Select Venus and click launch. And if in survival right as the terrain loads you die. And then the game freezes. Once you reload the game you die and die over and over again.

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** Version 1.12.2-0.4.5

**Where did this bug happen:** [Single Player or Server] Singleplayer

### Additional Information
[Any other information that may be able to help me with the problem] No extra info

**Comment by MJRLegends** [comment]
High pressure, your issue from our discord convo is with galaxy space.
