### ISSUE TITLE
Bug/Glitch with the Ultimate Fuel Loader

### ISSUE THREAD

**Issue by jillv46** [MJRLegends/ExtraPlanets#378]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes
### Description of Issue
Well idk if it’s a glitch or not but when I put fuel into the Ultimate Fuel Loader and it gets full it still takes the fuel out of the bucket and makes it empty. Any ideas why that’s happening?

### Steps to Reproduce Issue
1. Place down a Ultimate Fuel Loader and fill it up with fuel.
2. After it’s full put another fuel bucket in and it will take it/empty the fuel bucket even though it’s full

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.] No crash
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

**Screenshots (if applicable):** I don’t have any screenshots

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** 1.12.2-0.4.5

**Where did this bug happen:** [Single Player or Server] Singleplayer

### Additional Information
[Any other information that may be able to help me with the problem] I don’t have any other information

**Comment by MJRLegends** [comment]
Seems to be a bug with the Galacticraft Fuel loader too

**Comment by MJRLegends** [comment]
Seems to be a bug with the Galacticraft Fuel loader too. Will see if theres anything i can do from my side for the advanced and ultimate versions. But this will need reporting to GC mod devs too @jillv46

**Comment by MJRLegends** [comment]
Please report this to GC devs as the issue on there side, once they fix it, ExtraPlanets versions of this machine will be fixed too
