### ISSUE TITLE
[1.7.10] Keybind description in MC's Control config

### ISSUE THREAD

**Issue by spannerman79** [MJRLegends/ExtraPlanets#380]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

### Description of Issue
In minecraft controls, under Galacticraft the name is `keybind.vehicleInv.name`.  I searched GC's commits and this bit of text wasn't added by it, but by ExtraPlanets.

### Steps to Reproduce Issue
1. Obtain latest (Build #504) GC's mods ( https://ci.micdoodle8.com/job/Galacticraft-1.7/lastBuild/ ) and your latest release from curseforge ( https://minecraft.curseforge.com/projects/extraplanets/files/2639651 )
2. Game Menu -> Options -> Controls -> scroll down to Galacticraft section.

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

**Screenshots (if applicable):** 
![issue](https://user-images.githubusercontent.com/7542384/50258336-5a94ab00-0453-11e9-9e14-f20230cc0f49.PNG)

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** ExtraPlanets-1.7.10-2.0.6.jar

**Where did this bug happen:** Single player & Server

### Additional Information
Possibly https://github.com/MJRLegends/ExtraPlanets/blob/02c49918205692c08af23858cf455ccde92a515c/src/main/resources/assets/extraplanets/lang/en_US.lang#L562 wasn't added to 1.7.10, or its in fact suppose to be `keybind.vehicleInv.name=Open Powered Vehicle Inventory`.  Usually I would just do a PR as I have done before a couple of times, but as I can't see a [1.7 branch](https://github.com/MJRLegends/ExtraPlanets/branches) I am unsure which branch to submit the PR to.

**Comment by MJRLegends** [comment]
Thanks the keybind in the code needs changing to keybind.vehicle_inv.name its a easy fix thanks

**Comment by MJRLegends** [comment]
Updates are rolling out as we speak
