### ISSUE TITLE
Sleeping Recovers less than 5%

### ISSUE THREAD

**Issue by christianacuna** [MJRLegends/ExtraPlanets#382]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue
Sleeping regularly has "diminishing returns" it sometimes recovers 3% or just 1%

### Steps to Reproduce Issue
1. [First step]
Sleep on a bed
2. [Second step]
The next day Sleep on the same bed and it will recover less % than it says normally.

**Screenshots (if applicable):** 
https://cdn.discordapp.com/attachments/509966711248781313/525872840197537822/unknown.png
**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
1.12.2-0.4.5
**Where did this bug happen:** [Single Player or Server]
Server
### Additional Information
If I wait 2 or 3 days before i sleep again it will take the 5% out, and no I haven't visit any planets between sleeps.

**Comment by MJRLegends** [comment]
Its 5 % of your current radiation level not straight 5%
