### ISSUE TITLE
Issues overworld generation

### ISSUE THREAD

**Issue by KrauzeBartek** [MJRLegends/ExtraPlanets#383]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

### Description of Issue
Ceres and Saturn biome generate in overworld

### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

**Screenshots (if applicable):** 
![2019-01-05_17 50 17](https://user-images.githubusercontent.com/29304275/50726814-77e39d80-1112-11e9-91fe-d3c8a46e9bfc.png)
![2019-01-05_17 50 32](https://user-images.githubusercontent.com/29304275/50726816-7ca85180-1112-11e9-9cf0-2791ea52f36e.png)

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
ExtraPlanets 1.7.10 2.0.7

**Where did this bug happen:** [Single Player or Server]
Both

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
This is due to biome conflicts with another mod that has biomes in the overworld you will need to change the ids in the config
