### ISSUE TITLE
Crash from Missing Class

### ISSUE THREAD

**Issue by janagyjr** [MJRLegends/ExtraPlanets#384]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

Yes

### Description of Issue
[Description of the issue]

ExtraPlanets is crashing Minecraft upon loading stage 2/7

### Steps to Reproduce Issue
1. Create custom modpack
2. Install Galacticraft
3. Install ExtraPlanets
4. ????
5. Crash

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

https://gist.github.com/janagyjr/f8785b8e9dc22a72c4a5d3f632d91299

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]

1.1.8

**Where did this bug happen:** [Single Player or Server]

single-player

### Additional Information
Using forge 12.18.3.2511, Galacticraft 185 for 1.10.2 (same issue using 181). Checked closed tickets and thought it might be related to #364 but deleting/readding did not fix the issue. Already have launched successfully with just Galacticraft and retried with EP added. I was streaming modpack dev, you can check at https://www.twitch.tv/tcgjoe around the 5h 30m from the stream on 5 January 2019 to end (where you'll see me submitting this crash report). Nothing was configured, just trying to put together a workable collection of mods for a new pack at the moment.

**Comment by MJRLegends** [comment]
Redownload from https://minecraft.curseforge.com/projects/extraplanets/files/2651040/download

**Comment by janagyjr** [comment]
Is there anything else I can provide information wise?

**Comment by MJRLegends** [comment]
Are you still getting this issue?

**Comment by MJRLegends** [comment]
Please post any new comments over on #387, just so we have one place for this issue

**Comment by MJRLegends** [comment]
Updates are rolling out as we speak, sorry again for taking so long for me to notice it was a actual bug. I messed up there.
