### ISSUE TITLE
Crash on server startup

### ISSUE THREAD

**Issue by Krotain** [MJRLegends/ExtraPlanets#385]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

### Description of Issue
Loads fine on the client side but when I tried to run a server it crashes

### Steps to Reproduce Issue
Install galacticraft and extra planets (along with libs) on a forge server
Launch forge server

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

This crash is occurs when only using galacticraft and extra planets https://pastebin.com/zHAJ2Qhi
This crash occurs when using all my other mods https://pastebin.com/eYuxRKg7
(They appear to be the same)

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** 

extraplanets 1.12.2-0.4.6
mjrlegendslib 1.12.2-1.1.7
Galacticraft versions 181 and 186 have the same results
Forge version 2768

**Where did this bug happen:** Server

### Additional Information
[Any other information that may be able to help me with the problem]

I think this has something to do with the mod looking for client side forge code on the server but I have very limited knowledge with this stuff.

**Comment by MJRLegends** [comment]
Where did you download ExtraPlanets from?

**Comment by MJRLegends** [comment]
Because from your log i can tell you have not downloaded them from curse forge which is the only official place to get them.

**Comment by Krotain** [comment]
I downloaded the mods from these sites https://micdoodle8.com/mods/galacticraft/downloads https://minecraft.curseforge.com/projects/extraplanets
Are these not the correct places to download the mods from?

**Comment by Krotain** [comment]
I noticed that the mods were updated very recently so I tried the previous versions of the mods and found that if I use 1.1.6 of the lib and 0.4.5 of the extra planets mods it all works fine

**Comment by MJRLegends** [comment]
Yeah plz
