### ISSUE TITLE
[1.12.2] Server crash on load

### ISSUE THREAD

**Issue by shroomdog27** [MJRLegends/ExtraPlanets#386]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No] Yes

### Description of Issue
The server will crash upon attempting to load with ExtraPlanets installed

### Steps to Reproduce Issue
1. Install a forge 1.12.2-14.23.5.2781 server.
2. Install GalacticraftCore-1.12.2-4.0.1.181.
3. Install Galacticraft-Planets-1.12.2-4.0.1.181.
4. Install MicdoodleCore-1.12.2-4.0.1.181.
5. Install MJRLegendsLib-1.12.2-1.1.7.
6. Install ExtraPlanets-1.12.2-0.4.6
7. Start server.
8. Watch server crash and produce crash report below.

**Crash log/Log (if applicable):** https://pastebin.com/BRvku4t9
**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** ExtraPlanets-1.12.2-0.4.6

**Where did this bug happen:** Server

### Additional Information
I initially had this problem while building a modpack, but while trying to run a server for it the game crashed. It still works in singleplayer. To see if it was a mod conflict with one of the other mods, I tried it with just ExtraPlanets and Galacticraft alone, and it still happened.

**Comment by MJRLegends** [comment]
Already been fixed. Update MJRLegenssLib.

**Comment by shroomdog27** [comment]
Ah, I didn't notice there was an update for that. Thank you!
