### ISSUE TITLE
Crash from Missing Class

### ISSUE THREAD

**Issue by joshthebossxl** [MJRLegends/ExtraPlanets#387]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes

### Description of Issue
I have installed these mods only as a start of a singleplayer world, it cannot find the java classes for three items I think 
[crash-2019-01-12_19.43.49-client.txt](https://github.com/MJRLegends/ExtraPlanets/files/2752439/crash-2019-01-12_19.43.49-client.txt)
     ) Java cannot find the class in the mod  

### Steps to Reproduce Issue
1. install forge version forge-1.8.9-11.15.1.1875-installer.jar
2. install ExtraPlanets-1.8.9-1.5.1
3.  install GalacticraftCore-1.8.9-4.0.1.188
4.  install Galacticraft-Planets-1.8.9-4.0.1.188
5.  install MicdoodleCore-1.8.9-4.0.1.188
6.  install MJRLegendsLib-1.8.9-1.1.1
7. No ram amounts changed from the default

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]

**Where did this bug happen:** [Single Player]

### Additional Information
[This should be the only java class that's missing ]

**Comment by MJRLegends** [comment]
Where did you download your mods from

**Comment by joshthebossxl** [comment]
1 ( forge version forge-1.8.9-11.15.1.1875-installer.jar) I downloaded this file from the official forge website.
2 (ExtraPlanets-1.8.9-1.5.1) CurseForge
3 4 5 (https://micdoodle8.com/mods/galacticraft/downloads) version 188 (Not latest)
6 (MJRLegendsLib-1.8.9-1.1.1) CurseForge

**Comment by MJRLegends** [comment]
Download the mods again

**Comment by MJRLegends** [comment]
Normally people who get these issues are downloading not from curseforge

**Comment by janagyjr** [comment]
I no longer am getting the issue, but I use the Twitch launcher to build my packs so they should be coming from CurseForge. Directly downloading from the link you provided in my issue solved it thus far (but I'm not done building the pack). I'll be keeping an eye on this in case it happens again as I add more mods.

**Comment by MJRLegends** [comment]
Ok the issue seems in the following versions from my testing:

MC 1.8.9
v1.5.1
v1.5.0
v1.4.9

MC 1.10.2
v1.1.6
v1.1.7
v1.1.8

Rip :(

Seems very odd as the class that is says doesnt exist, actually exists in the jar file. I will try and work it out and fix for next version i guess..

**Comment by MJRLegends** [comment]
Think i might of found the issue. It seems to happen when IC2 isnt in the pack as i missed a , @Optional.Interface line for a IC2 api class

**Comment by MJRLegends** [comment]
Updates will be rolling out in the next 10 mins once i defo confirm this is the issue. Sorry it took so long for me to notice it was a actual bug

**Comment by MJRLegends** [comment]
Can confirm this was the issue, im just fixing a few more issues then will be uploading updates

**Comment by MJRLegends** [comment]
Updates are rolling out as we speak, sorry again for taking so long for me to notice it was a actual bug. I messed up there.
