### ISSUE TITLE
Duplicate orange medium oxygen tank and missing lime medium oxygen tank

### ISSUE THREAD

**Issue by DelviousCrafts** [MJRLegends/ExtraPlanets#389]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** YES

### Description of Issue
There is no lime medium oxygen tank and and recipe using lime wool is a duplicate orange medium oxygen tank which is crafted in Galacticraft standard using orange wool.

### Steps to Reproduce Issue
1. attempt to craft lime medium oxygen tank using lime wool or search for lime oxygen tank in NEI

**Crash log/Log (if applicable):** N/A does not produce crash
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

**Screenshots (if applicable):** 
![2019-01-13_15 44 17](https://user-images.githubusercontent.com/46658624/51091708-7ab24400-174b-11e9-889f-49f0169e2307.png)

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** 1.12.2-0.4.6

**Where did this bug happen:** Single Player

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Thank you will take a look :D

**Comment by MJRLegends** [comment]
Updates are rolling out as we speak
