### ISSUE TITLE
Compressed Zinc not used at all

### ISSUE THREAD

**Issue by Suinkai** [MJRLegends/ExtraPlanets#390]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

### Description of Issue
Probably a bug, Tier 8 Heavy-Duty Plate and Zinc Battery crafts with zinc ingots instead of compressed zinc

### Steps to Reproduce Issue
1. Attempt to see uses of compressed zinc in JEI gives no results.
2. Trying to compress tier 7 heavy-duty plates with compressed zinc doesn't do anything

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

**Screenshots (if applicable):**
![zinc](https://user-images.githubusercontent.com/22036266/51337701-1dd6c680-1a88-11e9-9401-71a53d83c158.png)
![zinc 2](https://user-images.githubusercontent.com/22036266/51337702-1dd6c680-1a88-11e9-9b28-8b7915f6dd9f.png)

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** 1.12.2-0.4.5

**Where did this bug happen:** Single Player

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Updates rolling out as we speak
