### ISSUE TITLE
Venus Rover Crash in Multiplayer

### ISSUE THREAD

**Issue by Morgoth16** [MJRLegends/ExtraPlanets#395]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

### Description of Issue
When I enter the Venus dungeon and wait for the boss to spawn, I instantly crash but the server stays open.

### Steps to Reproduce Issue
1. Walk into the Venus dungeon
2. Crash

**Crash log/Log (if applicable):** https://pastebin.com/uDbAnP14

**Screenshots (if applicable):** N/A

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** ExtraPlanets-1.7.10-2.0.7.jar

**Where did this bug happen:** Server

### Additional Information
This is my mods list, perhaps it's conflicting with something?
Advanced-Genetics-Mod-1.7.10
BuildCraft-Mod-1.7.10
Carpenters-Blocks-Mod-1.7.10
Chisel-Mod-1.7.10
CodeChickenCore-1.7.10-Latest
CodeChickenLib-1.7.10-1.1.3.138-universal
ExtraPlanets-1.7.10-2.0.7
GalacticraftCore-1.7-3.0.12.504
Galacticraft-Planets-1.7-3.0.12.504
JourneyMap-Mod-1.7.10-Unlimited
Macro-Keybind-Mod-1.7.10.litemod
Mantle-Mod-1.7.10
MicdoodleCore-1.7-3.0.12.504
Not-Enough-Items-1.7.10-Latest
Optifine_1.7.10_HD_U_E7
TabbyChat-Mod-by-Killjoy1221-1.7.10.litemod
TConstruct-Mod-1.7.10
Vein-Miner-Mod-1.7.10
Waila-Mod-1.7.10

**Comment by MJRLegends** [comment]
ExtraPlanets issue not Galacticraft

**Comment by MJRLegends** [comment]
Will take a look later

**Comment by MJRLegends** [comment]
Please do and try the following
1. Remove optifine and try as its not a supported mods
2. Remove all mods but ExtraPlanets and its required mods and try
3. Post a copy of your client and server config files.

**Comment by rdlenk** [comment]
Same issue with the 1.12.2 version on Mercury. Only seems to affect multiplayer as I can spawn the Magma boss and Venus rover in a single player game but it crashes instantly when using a server. The crash is specific to the client as well, the server only logs the disconnect and some Netty garbage about the connection being forcibly closed by the remote host.


### ---Issue Report---

### Description of Issue
When entering the Mercury dungeon boss spawn area the client crashes but the server stays online and other players are not affected.

### Steps to Reproduce Issue
Walk into the Mercury dungeon and spawn the boss

### Details
**Client Crash Log:** https://pastebin.com/k9jD5Rx0

**Version:** ExtraPlanets-1.12.2-0.4.9.jar, GalacticraftCore-1.12.2-4.0.2.190.jar

**Where did this bug happen:** Client

### Error Details
Description: Ticking entity
java.lang.ClassCastException: java.lang.Float cannot be cast to java.lang.Integer
Entity Type: extraplanets:extraplanets.entityvenusrover (com.mjr.extraplanets.entities.vehicles.EntityVenusRover)

### Troubleshooting Steps
1. Tried editing region to remove the entity
2. Disabled custom bosses on both client and server
3. Deleted DIM-13 (Mercury) to force it to recreate

**Comment by rdlenk** [comment]
As a follow up here, I tried re-enabling the fire and nuclear bombs in the ExtraPlanets config. I also re-enabled custom bosses and then deleted the Mercury dimension again. For whatever reason, this worked and the correct boss spawned and didn't crash out the client.

**Comment by MJRLegends** [comment]
Please can you make a different issue report for yours as this isnt the same issue.

**Comment by MJRLegends** [comment]
@Morgoth16 i believe your issue is the client and server configs are mismatched

@rdlenk i've moved your issue to its own issue report for you https://github.com/MJRLegends/ExtraPlanets/issues/409
