### ISSUE TITLE
Smelting recipe for Lucraft Ores conflicts with Extra Planet

### ISSUE THREAD

**Issue by Velocihater** [MJRLegends/ExtraPlanets#396]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
YES
### Description of Issue
If you smelt any ore from lucraft that's also in extra planets, the lucraft ore will turn into the extra planets ingot instead of the lucraft ingot (for example uranium)

### Steps to Reproduce Issue
1. smelt uranium ore from lucraft in a furnace
2.  check the ingot. it should be from extraplanets

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
ExtraPlanets-1.8.9-1.5.2.jar
**Where did this bug happen:** [Single Player or Server]
single player
### Additional Information
none

**Comment by MJRLegends** [comment]
You will need to fix this via CraftTweaker mod or Lucraft will need to make a fix

**Comment by Velocihater** [comment]
How do I fix this with crafttweaker? And since this is your mod tampering with Lucraft, how are they supposed to fix it?
