### ISSUE TITLE
Moons no longer load properly and you can't fly to them

### ISSUE THREAD

**Issue by Veteranspy** [MJRLegends/ExtraPlanets#397]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

### Description of Issue
Unable to load Overworld's moon, and upon warping to dimension configured it overwrites OW data

### Steps to Reproduce Issue
1. Attempt to travel to the moon, the GUI for travel disappears and breaks.
2. Warp to the dimension configured for the moon. Blocks generate correctly but it overwrites the OW data causing conflicting data.

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

**Screenshots (if applicable):** 
![image](https://user-images.githubusercontent.com/47379087/52325597-37926c00-29ab-11e9-845a-de5a18d6e8e4.png)
Image taken on OW

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
GC 190, Extra Planets 0.4.7
**Where did this bug happen:** [Single Player or Server]
Server
### Additional Information
[Any other information that may be able to help me with the problem]
Attempted troubleshooting by downgrading version of GC, removing Extra Planets seems to be the only fix at this time.
Mod list:
Actually Additions r144
Advanced Solar Panels 4.2.0
Applied energistics rv6 stable 4
Betterbuilderswands 0.11.1.245+69d0d70
BrandonsCore - 2.4.9.195
Buildcraft - 7.99.18
CodeChickenLib 3.2.2.353
CoFH Core 4.6.1.22
CoFH world 1.3.0.6
Custom Mob Spawner 1.12.2
Draconic evolution 2.3.18.329
Endercore .5.43
Enderio 5.0.38
excompressum 3.0.26
exnihilocreatio 0.2.4
extraplanets 0.4.7
extrautils2 1.9.6
GC 190
GC planets 190
gregtech 1.0.124
hwyla 1.12.2
ieclochecompat 2.1.7 dev 454
immersiveengineering 0.12.88
IC2 2.8.96-112
inventorytweaks 1.63
JEI 4.12.1.217
journeymap 1.12.2
llibrary 1.7.17
magicalcrops 1.0.2
mantle 1.3.3.39
mcjtylib 3.0.6
mekanism 9.4.13.349
micdoodlecore - 4.0.2.190
mjrlegendslib 1.1.8
Mo-creatures 1.12.2
mtlib 3.0.5
NEI 2.4.2.240
Nuclearcraft 2.12e
plustic 6.5.4.2
redstoneflux 2.1.0.6
rftools 7.56
rftoolsdim 5.61
solarfluxreborn 4.32r
tconstruct 2.12.0.113
thermal Cultivation 0.3.1.8
theymaldynamics 2.5.3.16
Thermal expansion 5.5.2.39
thermalfoundation 2.6.1.22
thermalinnovation 0.3.1.8
tinyprogressions 3.3.31
tombstone 3.3.0
veinminer .38.2.647+b31535a

**Comment by MJRLegends** [comment]
Already posted #392

**Comment by Veteranspy** [comment]
Thank you for showing me that. I apologize for the duplicate, didn't see that one listed whenever I was looking in the related. Cheers!

**Comment by MJRLegends** [comment]
No problem
