### ISSUE TITLE
Wrong block icons on deimos ores

### ISSUE THREAD

**Issue by Tau-Rah-Tar** [MJRLegends/ExtraPlanets#399]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues:** Yes

### Description of Issue

Deimos ores uses Ceres ore models in assets\extraplanets\models\item\deimos_ore_copper(iron, tin).json so in inventory this blocks looks like it's Ceres analogs.

### Steps to Reproduce Issue
1. Launch minecraft
2. Look at any deimos ore block in inventory.

**Crash log/Log:** Not crushing

**Screenshots:** 
![image](https://user-images.githubusercontent.com/7080418/52596397-453f6a00-2e61-11e9-8980-1e7f96d16244.png)
![image](https://user-images.githubusercontent.com/7080418/52597218-699c4600-2e63-11e9-80af-aa8fb51f7f7d.png)

**Version of Mod using:** [1.12.2-0.4.7]

**Where did this bug happen:** In client

### Additional Information
GitHub shows, that this mistake presents in all branches except master, where are no such files.

**Comment by MJRLegends** [comment]
Thanks

**Comment by MJRLegends** [comment]
Updates rolling out as we speak
