### ISSUE TITLE
Mincraft version 1.7.10 forge  10.13.4.1614

### ISSUE THREAD

**Issue by selriam** [MJRLegends/ExtraPlanets#40]
With the mod problem with industrialcraft 2 if I mod mod in modpack I can the macerator recipe as iron under other ores no longer use a bugfix the versions that I use
ExtraPlanets-1.0-Pre 3.7.0.jar, industrialcraft-2-2.2.826-experimental

**Comment by MJRLegends** [comment]
I dont understand sorry??

**Comment by selriam** [comment]
If I use your new version of your mod the recipes at industrailcraft with crushers no longer like iron and other matteralien

**Comment by MJRLegends** [comment]
Weird i will have a look
