### ISSUE TITLE
[1.7.10] ExtraPlanets worlds do not unload

### ISSUE THREAD

**Issue by kmecpp** [MJRLegends/ExtraPlanets#400]
### ---Issue Report---

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

### Description of Issue
Running Thermos server. ExtraPlanets worlds refuse to unload even if `keep-world-loaded` is false in cauldron.yml

Can there be a config option to enable world unloading? This is very configurable in Galacticraft

### Steps to Reproduce Issue
1. Install the mod

**Crash log/Log (if applicable):** N/A

**Screenshots (if applicable):**

![image](https://user-images.githubusercontent.com/6520738/53142283-53783f00-3561-11e9-98a6-b85a3727bcfd.png)

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [1.7.10-2.0.7]

**Where did this bug happen:** [Server]

**Comment by MJRLegends** [comment]
Version: 1.2.12 whats the version for as its not a ExtraPlanets version?

**Comment by kmecpp** [comment]
My bad. Don't know where I got that. Correct version is 1.7.10-2.0.7

**Comment by MJRLegends** [comment]
Also you havent told me if your using thermos or kcauldron or something else. And just being there loaded doesnt affect much. They say 0 for chunks and entities and tiles so its causing you no tick time.

Your issue report is kinda missing 3/4 of the details i need. You haven't included your config spigot.yml or nothing...

**Comment by MJRLegends** [comment]
Also -28 and -29 and -30 are on your list there thats Galacticraft dimensions and they handle my dimension registering and that so this seems like to me not my issue

**Comment by kmecpp** [comment]
All of the other dimensions on their ARE ExtraPlanets worlds. The screenshot is basically irrelevant I just included it to show that all of the extra planets worlds won't unload. I can delete it if you want me to. Also the worlds still do take up tick time. While not a lot, it is significant.

![image](https://user-images.githubusercontent.com/6520738/53142706-eebde400-3562-11e9-8849-6e9f3018c7ff.png)

**Comment by MJRLegends** [comment]
Can you unload the nether or the end using your method?

**Comment by MJRLegends** [comment]
And do Galacticraft dimensions unload using your method?

**Comment by kmecpp** [comment]
There is no method. I would just expect worlds to unload if there are no players and nothing on them as that's how Galacticraft works by default.

Another issue is that I cannot manually unload them if I use a plugin like multiverse

Correction in my original post I meant cauldron.yml not spigot.yml and the only reason why I mentioned that was because for some reason `keep-world-loaded` was set to true by default for Extra Planets worlds while is isn't for any other type of world. However even after changing it to false the worlds still don't unload automatically

**Comment by MJRLegends** [comment]
nothing i can do for you for a 4 nearly 5 year old minecraft, with dead plugins and discontinued thermos... sorry.

I cant fix something i dont have control over

**Comment by MJRLegends** [comment]
Also there is no reason at all you need to unload the worlds

**Comment by MJRLegends** [comment]
Unless you can find a issue when just using forge, i can do nothing for you

**Comment by MJRLegends** [comment]
Unless you can find a issue when just using forge not thermos, i can do nothing for you
```
[05:06:08] [Client thread/INFO] [STDOUT]: [com.mjr.extraplanets.handlers.MainHandler:onPlayer:34]: Load: Mercury
[05:06:08] [Client thread/INFO] [STDOUT]: [com.mjr.extraplanets.handlers.MainHandler:onPlayer:39]: UnLoad: Overworld
[05:06:08] [Server thread/INFO] [Galacticraft]: Server attempting to transfer player Player979 to dimension -13
[05:06:16] [Server thread/INFO]: [Player979: §7[Player979 was sent into the atmosphere]]
[05:06:16] [Client thread/INFO]: [CHAT] §7[Player979 was sent into the atmosphere]
[05:06:36] [Server thread/INFO] [Galacticraft]: Found matching world (0) for name: Overworld
[05:06:36] [Client thread/INFO] [STDOUT]: [com.mjr.extraplanets.handlers.MainHandler:onPlayer:34]: Load: Overworld
[05:06:36] [Client thread/INFO] [STDOUT]: [com.mjr.extraplanets.handlers.MainHandler:onPlayer:39]: UnLoad: Mercury
```
