### ISSUE TITLE
[1.7.10] Planet Selection GUI breaks when clicking on asteroids dimension

### ISSUE THREAD

**Issue by kmecpp** [MJRLegends/ExtraPlanets#401]
### ---Issue Report---

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

### Description of Issue

ExtraPlanets breaks asteroids dimension info on planet selection GUI

### Steps to Reproduce Issue
1. Use /dimensiontp
2. Click on the asteroid

**Crash log/Log (if applicable):** N/A

**Screenshots (if applicable):**

![image](https://user-images.githubusercontent.com/6520738/53142520-3a23c280-3562-11e9-9ab1-79fe6e4a59e1.png)

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [1.7.10-2.0.7]

**Where did this bug happen:** [Server]

**Comment by MJRLegends** [comment]
This is due to a dimension conflict

**Comment by kmecpp** [comment]
What would you like so see in the logs? There are no errors? The dimension ID for asteroids is -30 and no ExtraPlanets dimension conflicts with that.

https://hastebin.com/emocicevil.coffeescript

**Comment by MJRLegends** [comment]
post your server and client logs, i dont need the config..

**Comment by MJRLegends** [comment]
as works for me https://i.gyazo.com/a8163bc1cce30ff9a628696aebaa7f53.png
