### ISSUE TITLE
Enhancement Req:  Spacesuit module GUI interaction with JEI/NEI

### ISSUE THREAD

**Issue by burshaz** [MJRLegends/ExtraPlanets#402]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue
Can the module GUI dynamically move the JEI/NEI GUI like Thermal Expansion machines do?  So JEI/NEI doesn't overlay on top of the module GUI.

### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
1.12.2-0.4.6

**Where did this bug happen:** [Single Player or Server]
Single Player

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Updates released for MC 1.12.2, 1.11.2, 1.10.2. 

MC 1.8.9 will come later as got more work to do for that version :D

**Comment by MJRLegends** [comment]
Update released for MC 1.8.9
