### ISSUE TITLE
Cant go to the moon

### ISSUE THREAD

**Issue by ArielzaK** [MJRLegends/ExtraPlanets#403]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue
Tier 1, 2, 3, and 4 rockets cant fly to the moon. When I get to the celestial screen and select moon, the launch button is red and does nothing when clicked. However, I can launch to the moon using a tier 10 rocket. I haven't tried tiers 5-9. 

### Steps to Reproduce Issue
1. Launch to space in a tier 1-4 rocket.
2. View "moon" on the celestial screen.
3. Launch button is red and doesn't work.

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

**Screenshots (if applicable):** 
![screenshot](https://user-images.githubusercontent.com/48036582/53465834-5dd48600-3a04-11e9-85c3-88ba5aed3623.png)

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** 0.4.8

**Where did this bug happen:** Single Player and Lan

### Additional Information
This problem is occuring on both single player and lan worlds. Also, the person I was playing lan with is having the same problem also in lan and single player worlds.

**Comment by MJRLegends** [comment]
Please can you post your log files?

**Comment by ArielzaK** [comment]
> Please can you post your log files?

How do i do that?

**Comment by MJRLegends** [comment]
Which launcher you using?

**Comment by Kubadab045** [comment]
The same here. I cannot launch to moon with lower tier than 4. But when I go to moon with higher tier, Im landing at phobos. Maybe colliding ID?

**Comment by timeherald** [comment]
I am getting the same problem. There isn't an error report. Just a red button before tier 4, and a crash, with resulting re-login at phobos.

**Comment by MJRLegends** [comment]
Ok will take a look asap for this

**Comment by MJRLegends** [comment]
Turns out this is already a known issue and the conflicting mods has been found a solution is over in the comments of https://github.com/MJRLegends/ExtraPlanets/issues/392 any more issues let me know
