### ISSUE TITLE
Can't Remove Tier 4 Rocket from Nasa Workbench with new crafttweaker script.

### ISSUE THREAD

**Issue by Freebi85** [MJRLegends/ExtraPlanets#404]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes
### Description of Issue
Can't Remove Tier 4 Rocket from Nasa Workbench with new crafttweaker script.

### Steps to Reproduce Issue
1. Remove Tier 4 Rocket via Crafttweaker

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
ExtraPlanets-1.12.2-0.4.8
**Where did this bug happen:** [Single Player or Server]
Singleplayer
### Additional Information
Minecraft 1.12
Forge .2807

**Comment by MJRLegends** [comment]
Please post your crafttweaker.log
Please post the script your using?

**Comment by Freebi85** [comment]
Sorry forgotten^^

mods.ExtraPlanets.removeNASATier4RocketRecipe();

**Comment by MJRLegends** [comment]
Please post your crafttweaker.log

**Comment by MJRLegends** [comment]
Will update to fix later found the issue

**Comment by MJRLegends** [comment]
Updates are being released as we speak

**Comment by Freebi85** [comment]
Thx man your super fast <3

**Comment by MJRLegends** [comment]
Did it fix the issue yea?

**Comment by Freebi85** [comment]
Im afraid the issue is still there :/

**Comment by MJRLegends** [comment]
Ok please post your crafttweaker log

**Comment by Freebi85** [comment]
mods.ExtraPlanets.removeNASATier4RocketRecipe();

That's all so far. I was just trying to remove the recipe.

**Comment by MJRLegends** [comment]
Thats not your log file, thats your script. This is your log file im asking for 
![90ec262378c6e4250f9339db25e1c5c2](https://user-images.githubusercontent.com/8526321/53689021-83cf9280-3d44-11e9-8167-17e3e9735a05.png)

**Comment by MJRLegends** [comment]
As for me it works fine...

**Comment by Freebi85** [comment]
Yes there seems to have been a problem with the download. Now everything is working thank you. Sorry for the trouble.
