### ISSUE TITLE
Dumping a bucket of liquid nitrogen on an IC2 reactor causes a crash that persists

### ISSUE THREAD

**Issue by AquaticFish** [MJRLegends/ExtraPlanets#405]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** 
Yes

### Description of Issue
Dumping a bucket of ExtraPlanet's "Liquid Nitrogen Ice" onto an IC2 liquid cooled reactor causes a fatal crash in a server that persists

### Steps to Reproduce Issue
1. Make a basic IC2 liquid cooled reactor hull
2. Dump a bucket of "Liquid Nitrogen Ice" on the top

**Crash log/Log (if applicable):**
https://pastebin.com/raw/eKKYfQgK

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** 
ExtraPlanets-1.12.2-0.4.7

**Where did this bug happen:**
Server

### Additional Information
---

**Comment by MJRLegends** [comment]
Updates are being released as we speak
