### ISSUE TITLE
Disabling Radiation causes Wafer Textures to fail

### ISSUE THREAD

**Issue by IcedReaper** [MJRLegends/ExtraPlanets#406]
### Description of Issue
When I disable the Radiation and the Radiation on the Planets and Moons the Textures and Models for the Wafer cannot be loaded.

### Steps to Reproduce Issue
1. Disable Radiation in the config.
2. Launch the game
3. Check JEI.

**Screenshots (if applicable):** 
https://imgur.com/a/WhSLwQr

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):**
0.4.9

**Where did this bug happen:**
Single Player

### Additional Information
First I thought it could be a mod conflict, so I started the game only with Galacicraft, Extra Planets and JEI. It worked. I then created a new modpack profile in the twitch launcher, copied all mods from my modpack in and started it; I let the mods create their default configs - And it worked.
I then compared the configs from my modpack with the default one and one difference was the Radiation. I disabled the Radiation in the test profile, started it and the textures were missing too.
The related Items aren't available and every other Texture works; just not the wafer.

**Comment by MJRLegends** [comment]
How odd, yea it seems the item texture registering line got inside a if statement for radiation items. Should be fixed in next updates

**Comment by MJRLegends** [comment]
Shouldn't cause any issues for you in the mean time apart from visually no texutresm

**Comment by IcedReaper** [comment]
Thank you. 👍

**Comment by MJRLegends** [comment]
Updates have been released

**Comment by IcedReaper** [comment]
Hi @MJRLegends, 
sorry for the inconvenience, but I just checked the version released today and I just wanted to report that the version 0.5.0 havn't fixed the problem.

https://imgur.com/a/kdyJRBM

Thanks in advance.
IcedReaper

**Comment by MJRLegends** [comment]
Haha i may of forgot to push the commits sorry i will be in the next update. xD

**Comment by MJRLegends** [comment]
Updates are rolling out, as we speak

**Comment by IcedReaper** [comment]
Thanks @MJRLegends. The Problem is fixed. :)

**Comment by MJRLegends** [comment]
No problem
