### ISSUE TITLE
Crash When Shift Clicking Into GUI

### ISSUE THREAD

**Issue by Darkosto** [MJRLegends/ExtraPlanets#407]
### ---Issue Report---

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes

### Description of Issue
When shift clicking Atomic Batteries into Vehicle 

### Steps to Reproduce Issue
1. Build powered launch pad multiblock
2. Line up 5-10 Vehicle Chargers to power the launch pad
3. Shift click Atomic batteries into the GUI of the charger
4. Should get crash
5. Profit

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
https://pastebin.com/kGBFikiG
https://pastebin.com/K866gW8R

**Screenshots (if applicable):** https://clips.twitch.tv/SmokyHelpfulNarwhalM4xHeh

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** 0.4.9

**Where did this bug happen:**  Single Player

**Comment by MJRLegends** [comment]
Updates have been released
