### ISSUE TITLE
#37 Is not fixed.

### ISSUE THREAD

**Issue by MaDmaxwell311** [MJRLegends/ExtraPlanets#41]
### ---Issue Report---

**Have you checked Closed Issues (if applicable):** [Yes or No]
### Description of Issue
Issue #37 is still not fixed.

### Steps to Reproduce Issue
Refer to issue #37

**Crash log/Log (if applicable):** https://gist.github.com/MaDmaxwell311/b4a4a33ca66d300dda0504b820a0329f

**Version of Mod using:** 1.0-Pre 3.7.1.jar
### Additional Information
@ReikaKalseki may need to know about this as well.

**Comment by MJRLegends** [comment]
@MaDmaxwell311 no idea, seems to work fine with all other mods apart from Dragon API and RotaryCraft, i even get a different crash to you with http://pastebin.com/TiRrRvYZ

**Comment by MJRLegends** [comment]
@MaDmaxwell311 try and try off OreDictionary in the config of Extra Planets and let me know if it works then

**Comment by MaDmaxwell311** [comment]
Yes, turning off the OreDictionary in the config fixed the crashing, I can now load the pack just fine, as far as I can tell. I have not tested this fully, as in with a client connecting to a server, but right now I do not have the system resources, on my laptop. Shall I close this issue then?

**Comment by MJRLegends** [comment]
Can you test the new version i released earlier please with that option back on

**Comment by MaDmaxwell311** [comment]
No crash on version: 1.0-Pre 3.7.2 with 
"dimension settings" {
    B:"Add planet/moons ores to the ore dictionary"=true
}

So, it looks like this issue has been fixed.

**Comment by MJRLegends** [comment]
Thats good to hear :)
