### ISSUE TITLE
Game Crash When Rocket Launches

### ISSUE THREAD

**Issue by LadyAzureus** [MJRLegends/ExtraPlanets#414]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** 
Yes

### Description of Issue
Every time I launch the rocket, the game crashes.

### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

[crash-2019-03-23_17.37.48-client.txt](https://github.com/MJRLegends/ExtraPlanets/files/2999938/crash-2019-03-23_17.37.48-client.txt)

**Screenshots (if applicable):** 
![5F9E730A-92E9-45E5-8A24-F0F8FA37DD40](https://user-images.githubusercontent.com/48870898/54873412-fd323200-4d92-11e9-8dd3-6b25cd146cbb.png)

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
GalacticraftCore-1.12.2-4.0.2.190
ExtraPlanets-1.12.2-0.5.0
MJRLegendsLib-1.12.2-1.1.8

**Where did this bug happen:** [Single Player or Server]
Single Player

### Additional Information
I have tried different versions of each mod to see if the issue is with compatibility, but I'm not sure which combination to use. I have the latest of each mod since I just downloaded it. I can't open the galaxy map, so I think that might be the issue. I think that when I launch, the game can't open the galaxy map and so it crashes.

**Comment by MJRLegends** [comment]
The crash log tells you what you need to do its a on purpose one

**Comment by MJRLegends** [comment]
Also please use www.pastebin.com to post your crash logs it just makes things easy than my desktop filling up with crash files

**Comment by LadyAzureus** [comment]
Thank you! I had no idea that the crash report said what to do. I feel like an idiot XD

**Comment by MJRLegends** [comment]
No problem
