### ISSUE TITLE
Crystallizer Transforms Any Liquid Carrier Into Empty Bucket

### ISSUE THREAD

**Issue by EnderofGames** [MJRLegends/ExtraPlanets#415]
### ---Issue Report---

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yup 

### Description of Issue
The input slot of the basic crystallizer accepts any block or item (possibly the bug at hand) but only reacts when the item in the input slot is Liquid Crystal Water. If the item contains Liquid Crystal Water and is not a bucket, though, it will transform into an empty bucket. 

Tested with IC2 Universal Fluid Cells, TR Fluid Cells, and EnderIO Fluid Tanks. Does not accept the liquid from Thermal Expansion's Florbs, so no issue is present. If the cell is partially filled (or over filled, in the case of EnderIO Fluid Tanks) it will still input exactly 1000mb of Liquid Crystal Water. 

### Steps to Reproduce Issue
1. Fill non-bucket fluid container with Liquid Crystal Water.
2. Put the container from step 1 into a basic crystallizer. 

**Crash log/Log (if applicable):** <not applicable>

**Screenshots (if applicable):** 

![2019-03-24_14 48 14](https://user-images.githubusercontent.com/17417666/54885959-f9141c00-4e47-11e9-8647-295ea7c83b7b.png)
![2019-03-24_14 48 18](https://user-images.githubusercontent.com/17417666/54885960-f9141c00-4e47-11e9-95d3-3880840e8aec.png)
![2019-03-24_14 48 20](https://user-images.githubusercontent.com/17417666/54885958-f9141c00-4e47-11e9-83d4-81ee4d2b3a6c.png)

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** 

ExtraPlanets-1.12.2-0.5.0
Micdoodle and Galacticraft versions 189 and 190 (exhibits this behaviour in both versions)

**Where did this bug happen:** 

Both single player and on server 

### Additional Information
The last line of the tool tip says "Each Liquid Crystallized Water Bucket will give 1000" which appears to end prematurely. A simple change would be "1000mbs" or "will input 1000mb into the machine".

**Comment by MJRLegends** [comment]
Updates are rolling out, as we speak
