### ISSUE TITLE
Hybrid Solar Panel GUI Claims To Be "Ultimate Solar Panel" After Dimension Change

### ISSUE THREAD

**Issue by EnderofGames** [MJRLegends/ExtraPlanets#416]
### ---Issue Report---
**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** yeah dude

### Description of Issue
The GUI of Hybrid Solar Panels state "Ultimate Solar Panel" after changing dimensions. This appears to be graphical only, and will not affect other players on servers who have not changed dimensions. 

### Steps to Reproduce Issue
1. Place a Hybrid Solar Panel
2. Travel to another dimension and return
3. Right click on the solar panel block to see GUI

**Crash log/Log (if applicable):** <not applicable>

**Screenshots (if applicable):** 
Just placed: 
![2019-03-24_15 51 51](https://user-images.githubusercontent.com/17417666/54886575-fd900300-4e4e-11e9-8f52-ab843346233e.png)
Left through nether portal and promptly returned:
![2019-03-24_15 53 22](https://user-images.githubusercontent.com/17417666/54886576-fd900300-4e4e-11e9-99a6-8646779250b0.png)

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** 

ExtraPlanets-1.12.2-0.5.0
Micdoodle and Galacticraft versions 189 and 190 (exhibits this behaviour in both versions)

**Where did this bug happen:** 

Both single player and on server

### Additional Information
---

**Comment by MJRLegends** [comment]
Updates are rolling out, as we speak
