### ISSUE TITLE
Crash after updating to 1.12.2-0.5.1

### ISSUE THREAD

**Issue by BrisingrAerowing** [MJRLegends/ExtraPlanets#418]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

### Description of Issue
Crash on startup.

### Steps to Reproduce Issue
1. Load MC with 1.12.2-0.5.1
2. Crash

**Crash log/Log (if applicable):** [Crash  Log](https://paste.dimdev.org/ujeyoziqah.mccrash)

**Screenshots (if applicable):** N/A

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** 1.12.2-0.5.1

**Where did this bug happen:** [Single Player or Server] SP

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Update will be release in the next few hours

**Comment by BrisingrAerowing** [comment]
Sounds good.
