### ISSUE TITLE
Can't launch to the moon, but can launch everywhere else

### ISSUE THREAD

**Issue by grandmen123** [MJRLegends/ExtraPlanets#419]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

### Description of Issue
Can't launch to the moon, can launch everywhere else, have tried version mix and match between this and galacticraft. Two different outcomes between single player and multiplayer:
- Singleplayer I can see the moon description but launch button is red (even though I tried using both tier 1 and tier 2.
- In multiplayer I've landed in another dimension Oberon, or dimension -1509, instead of -28

This is happening on a modpack with the following mods:
https://gyazo.com/5e376a7c7d6b46534e8807143a737211
Modpack link: https://www.technicpack.net/modpack/xcraft-modded-v2.1257917

Would prefer this to be resolved on the multiplayer side although I believe it's also important for singleplayer.
No real crash logs, since it doesn't actually crash, nor the server, nor the singleplayer.

Have tried resetting configs, copying server configs into singleplayer and vice versa, both for galacticraft and extraplanets.

### Steps to Reproduce Issue
1. Download the modpack
2. Launch a creative world/server
3. Get the Tier 1 space gear/oxygen gear/parachute
4. Get a creative fueled tier 1 rocket and launch pad
5. Launch to the space map
6. Click moon and try launching (this is where it should fail)

For the server the same goes just the server doesn't have mods like optifine etc, but I believe this is pretty obvious

**Screenshots (if applicable):** 
Singleplayer:  https://gyazo.com/dd3d66b75a9357577eeaaf3f6c3ba26e
Multiplayer:  https://gyazo.com/0311c67dcadccf2ea455e4e2de265f68

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):**
Versions on the mods:
Galacticraft: 4.0.2.210
ExtraPlanets: 0.5.2

**Where did this bug happen:** 
Both, in singleplayer I can see the moon details but the launch button is red, in multiplayer I end up in a different dimension.

### Additional Information
Have reported to Galacticraft GITHUB as well https://github.com/micdoodle8/Galacticraft/issues/3663

**Comment by grandmen123** [comment]
https://pastebin.com/hQRaf0mC - Loading of dimensions

Notice how dimension -28 (the moon) loads just before dimension -1509 (the one I'm being teleported to)

**Comment by MJRLegends** [comment]
Please send me a copy of your log files(debug and latest) and copies of your ExtraPlanets and Galacticraft configs. Also please can you give just running ExtraPlanets and Galacticraft together with out the other mods

**Comment by grandmen123** [comment]
Debug and latest (right after it restarted not sure if you want me to try and actually go there?)
[latest (1).log](https://github.com/MJRLegends/ExtraPlanets/files/3050879/latest.1.log)
[debug (1).log](https://github.com/MJRLegends/ExtraPlanets/files/3050877/debug.1.log)

**Configs**
Galacticraft:
- chunkloading.conf: https://pastebin.com/srdPETka
- core.conf: https://pastebin.com/TDptrkm8
- miccore.conf: https://pastebin.com/wdPFmfV5
- planets.conf: https://pastebin.com/drVHdVXY
- power-GC3.conf: https://pastebin.com/qtFbYBXW
Extraplanets: https://pastebin.com/EHuUqcrS


I've only tested it in singleplayer but it does seem to be working properly, I tried launching myself to the moon and to Uranos and both worked properly.

The configs and logs above are from the server though, which is my main concern.

**Comment by MJRLegends** [comment]
im seeing 

`[19:46:25] [Server thread/ERROR] [Galacticraft]: Tried to register dimension for body: planet.Uranus hit conflict with ID -17`

in the logs, whats the bet theres mods conflicting dimension ids

**Comment by MJRLegends** [comment]
Please can you test with just ExtraPlanets and Galacticraft and post logs for when you just run with them two mods.

We need to find the mod that is causing the error for -17 in the last message of mine

**Comment by MJRLegends** [comment]
Also could be the same issue as #392

**Comment by grandmen123** [comment]
Found the mod conflicting with the dimension -17, it was the MoCreatures Wyvern Dimension, I moved it to dimension -17000, hopefully, this doesn't conflict with any other dimensions.

I'm gonna test again with this done

**Comment by grandmen123** [comment]
Fixed it, all I had to do was switch the MoCreatures Wyvern Dimension ID.

Thank you!

**Comment by MJRLegends** [comment]
No problem

**Comment by Spongebobfan907** [comment]
im having the same issue

> Found the mod conflicting with the dimension -17, it was the MoCreatures Wyvern Dimension, I moved it to dimension -17000, hopefully, this doesn't conflict with any other dimensions.
> 
> I'm gonna test again with this done

you could just change the Wyvern Lair or Uranus dimension to 17 instead of -17 but that works too
