### ISSUE TITLE
Galactic map issue

### ISSUE THREAD

**Issue by Byomakuta** [MJRLegends/ExtraPlanets#420]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** 
Yes

### Description of Issue
Whenever i use the EP Custom Galaxy Map Config in true, it crrash whit GS, but is i turn it false, all Systems from other galaxies collide and squash each other in the center, making it a blended version of the solar system.

### Steps to Reproduce Issue
True-True and True-False scenario
1. Having EP Custom Galaxy Map Config in true.
2. Having GS Custom Map Config in true or false.
3. Booting MC
4. IN-Game press M key
5. Crash

False-True and False-False scenario
1. Having EP Custom Galaxy Map Config in false
2. Having GS Custom Map Config in true or false
3. Booting MC
4. IN-Game press M key
5. Everything is blended

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/Minecraft/crash-log/

[true-true_scenario.txt](https://github.com/MJRLegends/ExtraPlanets/files/3075618/true-true_scenario.txt)

[true-false_scenario.txt](https://github.com/MJRLegends/ExtraPlanets/files/3075619/true-false_scenario.txt)

**Screenshots (if applicable):** 
False-True and False-False scenario
![2019-04-11_22 03 10](https://user-images.githubusercontent.com/25575028/56073036-fbdd9f00-5d6b-11e9-99cb-3a3cc1d25b1d.png)

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
EP - 1.12.2-0.5.2
GS - 1.12.2-2.0.7

**Where did this bug happen:** [Single Player or Server]
Single Player

### Additional Information
it worked before in an older version, but there has been various updates from the last time i checked so i cant give previous version reference unfortunately

**Comment by MJRLegends** [comment]
Try using the Galacy Space compact option in the ExtraPlanets config too

**Comment by Byomakuta** [comment]
finally tried, no results, while  he tried to show the map this time, it crashed 3 sec after, it turrned out i actually had the compatibility in True since the beginning so i didnt touch it again, and i placed the EP config as said in the wiki, i failed 

[after_trying_using_wiki_and_reconfig_the_config.txt](https://github.com/MJRLegends/ExtraPlanets/files/3077008/after_trying_using_wiki_and_reconfig_the_config.txt)

as extra info: the moment it tried to show the map, the system where still blended as screenshot above

**Comment by MJRLegends** [comment]
Will look at this very soon sorry for the delay

**Comment by MJRLegends** [comment]
Cant reproduce your issue atm, please post ExtraPlanets, AsmodeusCore and GalaxySpace configs

**Comment by Byomakuta** [comment]
Here i post the 3 config files requested

[ep_config.txt](https://github.com/MJRLegends/ExtraPlanets/files/3087328/ep_config.txt)
[asmodeus_config.txt](https://github.com/MJRLegends/ExtraPlanets/files/3087329/asmodeus_config.txt)
[gs_core_config.txt](https://github.com/MJRLegends/ExtraPlanets/files/3087330/gs_core_config.txt)

**Comment by Stiller90** [comment]
I actually experienced this too, it was on the 0.2.4 edition of extraplanets. I also had the other 3 mods for galacticraft, all were 4.0.1.140 edition. It was where all the solar systems, our's and the extra solar systems combined together.

**Comment by MJRLegends** [comment]
Updates are rolling out within the next hour
