### ISSUE TITLE
missing tooltip for rocket schematics

### ISSUE THREAD

**Issue by ToserBan** [MJRLegends/ExtraPlanets#421]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
yes
### Description of Issue
[No tooltip for rocket schematics and where to find them. I searched in Venus dungeons for the rocket 4 schematic, before i read an older thread at github, that says it could be found in mercury dungeons. Would be nice to have a tooltip]

### Steps to Reproduce Issue
1. []
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/Minecraft/crash-log/

**Screenshots (if applicable):** 
![schematic4](https://user-images.githubusercontent.com/22052809/56084829-82ac7d80-5e39-11e9-8b45-a64de6b0a9b1.png)

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
1.12.2.0.5.0
**Where did this bug happen:** [Single Player or Server]
single
### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Its in the Mercury dungeon. And sorry i wont be adding there locations but you can find them here https://docs.mjrlegends.com/Space%20Astronomy%201%20&%202/dungeons/ under ``Space Astronomy 2 (ExtraPlanets)`` section
