### ISSUE TITLE
Hide Pluto and Eris' Moons

### ISSUE THREAD

**Issue by Dr-Ergmern** [MJRLegends/ExtraPlanets#422]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** 
Yes

**Description of Issue**

It's not really an issue with code but more of an oversight, but since you can remove all of the other planetary moons from the config and make them disappear from the galaxy map, it makes it look odd and out of place that both Pluto and Eris still show their moons on the galaxy map. I was wondering if you could add it into the config for them to be removed from the galaxy map similar to how you've done it for other celestial bodies.

**Version of Mod:**
EP - 1.12.2-0.5.2

**Comment by MJRLegends** [comment]
How come your wanting to remove them

**Comment by Dr-Ergmern** [comment]
> How come your wanting to remove them

If I've got the rest of the moons disabled, then I'd obviously want those ones not visible in the galaxy map as well.

**Comment by MJRLegends** [comment]
Doesnt really answer my question to why your removing them

**Comment by Dr-Ergmern** [comment]
> Doesnt really answer my question to why your removing them

The reason I have the rest of the moons disabled is because most servers "can't keep up" and the extra dimensions in the forms of the planetary moons are adding extra weight to the server hence why I disabled them in the config file. The extra moons showing on the outer planets just appears out of place since the rest of the planets (bar the overworld) no longer show their moons orbiting them on the galaxy map.

**Comment by MJRLegends** [comment]
I've added you the following config option will be in MC 1.7.10 - MC 1.12.2 version in the next updates: 

```
#Setting this option to false will remove all unreachable moons added by ExtraPlanets, from showing on the Celestaial Selection Screen!
    B:"Unreachable moons on the Celestaial Selection Screen"=true
```

**Comment by MJRLegends** [comment]
Another part of your issue here will be covered by me fixing #425

**Comment by MJRLegends** [comment]
Updates are rolling out within the next hour
