### ISSUE TITLE
Saturn Slime Ore is reconised like like Saturn Surface Rock by HWYLA

### ISSUE THREAD

**Issue by Fireztonez** [MJRLegends/ExtraPlanets#423]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue
HWYLA show the wrong tooltip for the Saturn Slime Ores, I think there probably have something wrong in the code about that.

**Screenshots (if applicable):** 
![slime-ore-surface_rock](https://user-images.githubusercontent.com/19277301/56466244-038ceb80-63dd-11e9-8f27-152e9474dc4a.png)

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
Extra Planets: 0.5.2
Galacticraft Core: 4.0.2.210
Galacticraft Planets: 4.0.2.210
Galacticraft Tweaker: 1.0.3
Forge: 14.23.5.2824
HWYLA: 1.8.26

**Where did this bug happen:** Single Player, but for sur this is the same in multiplayer...

### Additional Information
If you need other information, let me know...

Fireztonez

**Comment by MJRLegends** [comment]
Updates are rolling out as we speak to fix this
