### ISSUE TITLE
Сant find dungeons and bosses on the planet Mercury.

### ISSUE THREAD

**Issue by ResponsibleBear** [MJRLegends/ExtraPlanets#424]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
**Yeap.**

### Description of Issue
**Сant find dungeons and bosses on the planet Mercury. 
From here follow that I can not find a scheme for the rocket №5. What to do?**

### Steps to Reproduce Issue
**1. Create the world
2. Explore it.**

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
ExtraPlanets-1.7.10-2.1.0.jar 

**Where did this bug happen:** [Single Player or Server]
Single and Server.

**Comment by MJRLegends** [comment]
They exist, just harder to find due to the terrain

**Comment by MJRLegends** [comment]
Ahh sorry i missed that you were on Mc 1.7.10 in this case its Venus you want not Mercury. MC 1.8.9 ans above are Mercury
