### ISSUE TITLE
shutdown server in single [1.12.2]

### ISSUE THREAD

**Issue by ProDash1998** [MJRLegends/ExtraPlanets#427]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues : YES

### Steps to Reproduce Issue
1. Use to test 6-10 interstellar space
2.  launch  space
3. Fly to space
$. crash in map

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> Have only "server shutdown " and "A fatal error ...."  0 crash 
lastes.log https://pastebin.com/Bz7i3b5D
debug.log https://pastebin.pl/view/6541c7e1 

**Screenshots (if applicable):** 
https://youtu.be/ttgXJM4CR6s

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
AsmodeusCore-1.12.2-0.0.7
GalacticraftCore-1.12.2-4.0.2.210
Galacticraft-Planets-1.12.2-4.0.2.210
GalaxySpace-1.12.2-2.0.7
MicdoodleCore-1.12.2-4.0.2.210
ExtraPlanets-1.12.2-0.5.2
MJRLegendsLib-1.12.2-1.1.8
**Where did this bug happen:** [Single Player or Server]
Singleplayer

**Comment by MJRLegends** [comment]
java.lang.RuntimeException: Please disable the following option: enableNewGalaxyMap in configs/AsmodeusCore/core.conf

**Comment by MJRLegends** [comment]
See https://docs.mjrlegends.com/ExtraPlanets/1.12.2compact/ for more help
