### ISSUE TITLE
Server stuck in startup mode

### ISSUE THREAD

**Issue by grandmen123** [MJRLegends/ExtraPlanets#428]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

### Description of Issue
Server gets stuck in startup mode or crashes before finishing, never allowing the player to join.
I'm running a 1.7.10 modpack, and if I remove ExtraPlanets this stops happening, the server is running on 3 GBs and has started before, however I added TreeCapitator and it seemed to no longer function, unless I remove ExtraPlanets.

### Steps to Reproduce Issue
1. Setup the server with these mods
2. Run it
3. Attempt to join and see this happen OR See the server crash

**Crash log/Log (if applicable):** 
Latest.log: https://pastebin.com/6rSz1i3Y
fml-server.log: (had to upload it to dropbox it was too big for pastebin) https://www.dropbox.com/s/9usn49iar4rn7x8/fml-server-1.log?dl=1

**Screenshots (if applicable):** 
Stuck in startup (I tried joining approximately 30 minutes after the server started and multicraft said it was up): https://gyazo.com/b7b783902b7529fbad753173cd042600

Modpack mods: https://gyazo.com/0209393446775aa68373090a9eab4b8c

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** 
- GalacticCraft 1.7.10-3.0.12.504
- ExtraPlanets 1.7.10-2.1.0

**Where did this bug happen:** Server

### Additional Information
I've been trying to figure out why this is happening? I believe it is RAM but since it has started before so I'm not sure what to do, I've also tried removing treecapitator and it doesn't seem to want to work. Here is the modpack link: https://www.technicpack.net/modpack/xcraft-modded-v2.1257917

**Comment by grandmen123** [comment]
As a side note, if you download the modpack on the latest version it won't have ExtraPlanets, since I had to remove it for my mates and I to play, but every other mod is there, you will need to add ExtraPlanets to your mods.

Apologies for this complication

**Comment by MJRLegends** [comment]
This is nothing to do with ExtraPlanets

**Comment by MJRLegends** [comment]
your error is ```
java.lang.IllegalArgumentException: Duplicate id value for 23!
	at net.minecraft.entity.DataWatcher.func_75682_a(SourceFile:64) ~[te.class:?]
	at com.tihyo.legends.entities.ExtendedLiving.<init>(ExtendedLiving.java:22) ~[ExtendedLiving.class:?]
	at com.tihyo.legends.entities.ExtendedLiving.register(ExtendedLiving.java:31) ~[ExtendedLiving.class:?]
	at com.tihyo.legends.handlers.ExtendedPlayerEventHandler.onEntityConstructing(ExtendedPlayerEventHandler.java:39) ~[ExtendedPlayerEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_296_ExtendedPlayerEventHandler_onEntityConstructing_EntityConstructing.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
```

Doesnt even mention ExtraPlanets

**Comment by grandmen123** [comment]
Missed that my apologies I spent 10h putting and removing mods and ExtraPlanets just happened to be in there every time it crashed.

Thanks for the help though!

**Comment by grandmen123** [comment]
Even with the error removed the server still gets stuck loading dimensions and doesn't finish initiating the server.
This is a snipped of the logs https://pastebin.com/6S7g5LD7

I just get timed out, and the server never surpasses ping stage...

Is this a RAM issue? Or something else?

**Comment by MJRLegends** [comment]
Idk i dont see a ExtraPlanets issue here sorry

**Comment by grandmen123** [comment]
Me neither, hence the issue, I can't pin it down to anything, except perhaps lack of ram? I'll contact the host, thank you either way.
