### ISSUE TITLE
Dimension tp not working on some planets

### ISSUE THREAD

**Issue by Darksilence43** [MJRLegends/ExtraPlanets#429]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No] Yes

### Description of Issue
[Description of the issue]
I can't dimensiontp to kepler
### Steps to Reproduce Issue
1. [First step]
Do /dimensiontp
2. [Second step]
Try anything to tp to kepler
Cant tp to kepler without it being in a menu to tp to and cant tp to any of the names that are red if those are out yet
**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/Minecraft/crash-log/
no crash
**Screenshots (if applicable):** 
https://imgur.com/a/QNiZR17
**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
1.7.10-2.0.7
**Where did this bug happen:** [Single Player or Server]
server
### Additional Information
[Any other information that may be able to help me with the problem]
nope

**Comment by MJRLegends** [comment]
This is normally due to dimension id conflicts, nothing on the mods side
