### ISSUE TITLE
[1.7.10] Spawing other a parts of planets biomes in Overworld

### ISSUE THREAD

**Issue by kolbka96** [MJRLegends/ExtraPlanets#430]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):**
Yes

### Description of Issue
Spawing other a parts of planets biomes in Overworld.

### Steps to Reproduce Issue
1. Start a new game(create world) with seed(seed was randon for me): -220360383878106409
2. For example go to the coordinates: x: 609 z: -1445 y: 68 (i get here Saturn biome).

**Crash log/Log (if applicable):** 
No crash log, because this issue don't crash a game.

**Screenshots (if applicable):** 
![2019-05-26_22 49 38](https://user-images.githubusercontent.com/15887188/58382068-bff35600-8008-11e9-8389-df6bcff6f7e8.png)
![2019-05-26_22 50 07](https://user-images.githubusercontent.com/15887188/58382069-c1bd1980-8008-11e9-8870-9c57cfadb87e.png)
![2019-05-26_22 50 18](https://user-images.githubusercontent.com/15887188/58382072-c386dd00-8008-11e9-85b1-629a780f020e.png)
![2019-05-26_22 50 54](https://user-images.githubusercontent.com/15887188/58382074-c4b80a00-8008-11e9-8723-68096ddf839c.png)

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** 
Minecraft 1.7.10
Forge: 10.13.4.1614
ExtraPlanets-1.7.10-2.1.0
GalacticraftCore-1.7-3.0.12.504
Galacticraft-Planets-1.7-3.0.12.504
MicdoodleCore-1.7-3.0.12.504

**Where did this bug happen:** 
Single Player and Server (both)

### Additional Information
This issue i was get on my server, i was play with my comrade and when we going to North, we get that biome. We also meets Uranus biome like islands.
After we finished the game, I decided to find out where this error came from. Firstly i delete all other mods and try start a game ONLY with GC and ExtraPlanets, i still getting other parts of planets biomes in Overworld. I'm not sure about what is: bug or not a bug? Because i not tested this with other world seed, i just get random world seed on server and start play. But it seems to me that this will happen with other world generation.

**Comment by MJRLegends** [comment]
Biome id conflicts change them in the config
