### ISSUE TITLE
ExtraPlanets crashing the server

### ISSUE THREAD

**Issue by spongeblast** [MJRLegends/ExtraPlanets#434]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No] Yes

### Description of Issue
When loading up on single client is fine, but, when adding mods to server they crash. With my basis of crash logs I understand that the problem was extraplanets but is there any way to fix it

### Steps to Reproduce Issue
1. Put all the mods into server mods folder, including extraplanets
2. Server closes with extraplanets installed

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them] https://pastebin.com/KetZHWNz
> *How do i locate a crash log* see https://docs.mjrlegends.com/Minecraft/crash-log/

**Screenshots (if applicable):** 
Not applicable.

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
ExtraPlanets 1.12.2-0.5.2
MJRlegendslib 1.12.2-1.1.7

**Where did this bug happen:** [Single Player or Server]
Server

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by spongeblast** [comment]
Technic Launcher api link is http://api.technicpack.net/modpack/deepspace

**Comment by MJRLegends** [comment]
You have download half your mods for a site that isnt a official site and just steals download get your mods from curseforge or mod devs sites only.

**Comment by spongeblast** [comment]
I'll redownload all the mods from curseforge but is there any way to fix the problem?

**Comment by MJRLegends** [comment]
No you did not i can tell from your crash log theres a few you didnt download from curseforge. That is your issue here.

**Comment by MJRLegends** [comment]
Make sure all your mods are up to date as well
