### ISSUE TITLE
Crashes on opening of map

### ISSUE THREAD

**Issue by cloud44049** [MJRLegends/ExtraPlanets#436]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

### Description of Issue
When I launch into space everything is fine until the map opens up and it tells me the internal server has crashed and it takes me to the server list. I am playing singleplayer/

### Steps to Reproduce Issue
1. Launch into space
2. Wait

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do I locate a crash log* see https://docs.mjrlegends.com/Minecraft/crash-log/
https://drive.google.com/file/d/116Sjq4WPONYO9ttiy8teSjf1Rr9BbXkM/view?usp=sharing
**Screenshots (if applicable):** 
No screenshots sorry! But the error says shutting down internal server
**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
GalacticraftCore-1.12.2-4.0.2.210
ExtraPlanets-1.12.2-0.5.2
MJRLegendsLib-1.12.2-1.1.8
**Where did this bug happen:** [Single Player or Server]
Single Player
### Additional Information
[Any other information that may be able to help me with the problem]
Sorry! no extra information.

**Comment by MJRLegends** [comment]
```
[19:03:11] [Netty Local Client IO #0/ERROR]: There was a critical exception handling a packet on channel asmodeuscore
java.lang.RuntimeException: Please disable the following option: enableNewGalaxyMap in configs/AsmodeusCore/core.conf
```

**Comment by l33tdaniel** [comment]
For whatever reason, I still get a crash report even after disabling enableNewGalaxyMap in configs/AsmodeusCore/core.conf

I have the exact same error as the user above.

**Comment by MJRLegends** [comment]
Yea thats a Asmodeuscore issue their config wasnt saving correctly, contact them for deals on best way to fix
