### ISSUE TITLE
Conflict with EasyCrafting mod

### ISSUE THREAD

**Issue by strangelf47829** [MJRLegends/ExtraPlanets#438]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No] Yes

### Description of Issue
if i load a world (fresh or old doesn't matter) the game kicks me to the main menu

### Steps to Reproduce Issue
1. just start a new game
2. thats it

**Crash log/Log (if applicable):** No crash log

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION] 2.11 - 2.0.9

**Where did this bug happen:** [Single Player or Server] single player

### Additional Information
[Any other information that may be able to help me with the problem] i updated to forge 1614 for 1.7.10 and deleted the extra planets mod and the problem stopped, so it is extra planets. i used the extra planets 2.11 and then downgraded to 2.09 but problem persisted, also latest galacticraft 3 (build 504) version, then downgraded to forge 1558 and problem still persisted.

**Comment by MJRLegends** [comment]
Please supply your logs files

**Comment by strangelf47829** [comment]
> Please supply your logs files

I tried to look at the crash report to see if i could see the problem, i think it has something to do with incompatibility with a mod called easy crafting throwing an array out of bounds exception when trying to load something.i uninstalled the easy crafting mod and your mod worked. im pretty sure it was something with easy crafting and it was outdated anyways.



[logs.zip](https://github.com/MJRLegends/ExtraPlanets/files/3309611/logs.zip)

**Comment by MJRLegends** [comment]
Seems to be a conflict with EasyCrafting mod, you can remove the EasyCrafting mod for the time being if you want everything to work

**Comment by MJRLegends** [comment]
Update has been released
