### ISSUE TITLE
Lag when on space stations from this mod

### ISSUE THREAD

**Issue by Aang23** [MJRLegends/ExtraPlanets#439]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

### Description of Issue
Going onto Galacticraft's default Overworld space station is fine, my client keeps up at 60 FPS without any issues. But, when going on, let's say, a Mercury space station, it'll go down to almost 20, no matter how powerful the computer it's running on is.

### Steps to Reproduce Issue
1. Create a new creative world
2. do /dimensiontp
3. Create a space station anywhere but not the Overworld
4. Lag...

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/Minecraft/crash-log/

**Screenshots (if applicable):** 
https://ibb.co/7WMpcj7
https://ibb.co/kHNt1SL

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** 1.12.2-0.5.3

**Where did this bug happen:** SinglePlayer & Server

### Additional Information
Considering the hardware I got... This seems odd. This issue is something I have for more than a year, and when reusing this mod I discovered it was still present.
Forge 2838, 15G allocated, OpenJDK 8 212.
If you need me to profile the client, just ask.

**Comment by MJRLegends** [comment]
Please provide a profile see https://docs.mjrlegends.com/General%20Minecraft/profiling/

**Comment by Aang23** [comment]
Done. http://www.altillimity.com/lag.nps

**Comment by Aang23** [comment]
if this helps, here's a video of the issue : https://www.youtube.com/watch?v=OFUuCb83M4I&feature=youtu.be

**Comment by MJRLegends** [comment]
@Aang23 Might be able to help you will this, will take a look later

**Comment by MJRLegends** [comment]
Updates have been released, you should see an improvement, do note you probably wont see same fps as overworld space station but should at least be close. Let me know if you still see the issue @Aang23
