### ISSUE TITLE
Some graphical glitches with rocket launches

### ISSUE THREAD

**Issue by tethlah** [MJRLegends/ExtraPlanets#44]
Description of Issue:
When launching using T7-9 rockets, the screen gets severely shaky and flashy to watch. 
When launching using a T10 rocket, the screen get mildly shaky and flashy to watch.
All other tiers seem to launch without any issues.

Version of Mod using: 3.7.2

**Comment by MJRLegends** [comment]
have you got any images and are you using optifine?

**Comment by tethlah** [comment]
No I'm not using optifine, but I am using fastcraft.  A screenshot isn't going to illustrate an issue that exists in movement....

**Comment by MJRLegends** [comment]
This is a client side issue as there is no difference in the render for each rocket...

**Comment by tethlah** [comment]
Weird because it's happening on multiple clients to the same effect.  (4 tested so far).

**Comment by MJRLegends** [comment]
Will look in to this more now and get back to you

**Comment by MJRLegends** [comment]
@tethlah i have found the issue, it seems when i set the fuel tank size above 3000 it makes it shake like a dog running around with a toy lol.... seems its a galacticraft related bug but i think i can fix it for v3.7.4

**Comment by tethlah** [comment]
Awesome.  I'm loving the addon so far, in case you can't tell I pretty rigorously stress test everything before including it in the pack.  But I love the scenery.  I'm going to be interested in comparing the pressure/gravity comparisons with real life mass estimates.

Keep up the great work!

**Comment by MJRLegends** [comment]
@tethlah Nice thank you and yeah feel free to post any more bugs, also Kepler22b is in WIP atm

**Comment by MJRLegends** [comment]
Seems its not the rocket fuel tank its not something to do with the tier being 7 or 8 or 9 as the amount rumble is calculate in the galacticraft classes using the tier

**Comment by MJRLegends** [comment]
I think i can make a work around though for it to work

**Comment by MJRLegends** [comment]
Fixed in v3.7.4
