### ISSUE TITLE
Error when setting up MorePlanets Compatibility

### ISSUE THREAD

**Issue by geobr1990** [MJRLegends/ExtraPlanets#440]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

### Description of Issue
Server is displaying an error on startup about setting up MorePlanets Compatibility.

### Steps to Reproduce Issue
1. Add Galacticraft, MJRLegendsLib, ExtraPlanets, SteveKunG's Lib and More Planets mods to server.
2. Start server

**Crash log/Log (if applicable):** https://pastebin.com/NMCGX6k9

**Screenshots (if applicable):** N/A

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** MJRLegendsLib 1.1.8
Extra Planets 0.5.3
More Planets 2.1.5
SteveKunG's Lib 1.0.5
Galacticraft 4.0.2.211

**Where did this bug happen:** Server

### Additional Information
Minecraft 1.12.2, Forge 14.23.5.2836

**Comment by MJRLegends** [comment]
Thanks for the report, this error shouldn't cause you any issues. You still should be able to play as normal. Its because a block doesnt exist in the More Planets version your using, due to there is two different versions of More Planets for MC 1.12.2

**Comment by geobr1990** [comment]
Yes I've not seen any apparent issues while playing; everything seems to be working as intended. Just wanted to make you aware of the error message if you weren't already :)

**Comment by MJRLegends** [comment]
Updates have been released
