### ISSUE TITLE
Space Suits will not accept Enchantments? (JEI use references)

### ISSUE THREAD

**Issue by Danekjovax** [MJRLegends/ExtraPlanets#441]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

### Description of Issue
All of the Space Suit components seem to be enchantable (looking through JEI), though when placed in an anvil do not accept any enchantment.  Screenshots attached.

### Steps to Reproduce Issue
1. Have any tier of a spacesuit component.
2. Place item into anvil (via its GUI) and observe the "X".

**Crash log/Log (if applicable):** [N/A]

**Screenshots (if applicable):** 
![2019-06-23_08 19 30](https://user-images.githubusercontent.com/10191173/59976315-b1a94300-9590-11e9-869e-9d8f9c8049e2.png)
![2019-06-23_08 19 33](https://user-images.githubusercontent.com/10191173/59976316-b1a94300-9590-11e9-840f-e7864f753714.png)
![2019-06-23_08 19 48](https://user-images.githubusercontent.com/10191173/59976317-b1a94300-9590-11e9-92ea-294524d0795d.png)

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [0.5.3]
* being played inside of v5.2 of Dungeons Dragons & Space Shuttles and ticket originated here (https://github.com/Freebi85/Dungeons-Dragons-Space-Shuttles/issues/193)

**Where did this bug happen:** [both Single Player/Server]

### Additional Information
If this is an intended feature, please allow the functionality.  If it wasn't intended (JEI being a troll), then please remove all references allowing enchantments so this confusion doesn't happen to others.  Thank you for your time.

**Comment by MJRLegends** [comment]
That are not meant to accept them, JEI is showing wrong information

**Comment by MJRLegends** [comment]
They have custom modules system which can be accessed via a key(see controls menu)

**Comment by Danekjovax** [comment]
I'll forward this to JEI's devs.  I'll also look into the modules and see what I can use of those.  Thanks.
