### ISSUE TITLE
Won't allow me to travel to uranus

### ISSUE THREAD

**Issue by blarb21** [MJRLegends/ExtraPlanets#442]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

### Description of Issue
I Cannot Travel to Uranus, But i can travel to it's moons.

### Steps to Reproduce Issue
1. Install Galacticraft Core, Galacticraft Planets, MicdoodleCore, Extra Planets, and MJRLegendslib.
2. Just try to go to uranus.

**Crash log/Log (if applicable):** N/A
> *How do i locate a crash log* see https://docs.mjrlegends.com/Minecraft/crash-log/

**Screenshots (if applicable):**  N/A

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** 1.12.2-0.5.3

**Where did this bug happen:** Single Player

**Comment by mcDandy** [comment]
Why would you land on gas giant? There is no place to land.

**Comment by MJRLegends** [comment]
@blarb21 please post your log files

**Comment by geobr1990** [comment]
I have no problem going to Uranus. Been there a couple of times.

**Comment by MJRLegends** [comment]
@geobr1990 Yea these issues always seem to resolve to dimension id conflicts with other dimensions/mods and its just a matter of looking at the logs which tells you which dimension id has the issue. And then changing the configs to stop the conflict
