### ISSUE TITLE
Can't Get Mod Working

### ISSUE THREAD

**Issue by Chezcaek** [MJRLegends/ExtraPlanets#443]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues:** Yes

### Description of Issue
I have tried everything I can think of to get this mod working. I made sure it was the same version as Galacticraft and its dependencies. I've tried using this mod in multiple different custom modpacks and it never worked.

### Steps to Reproduce Issue
1. Download Mod

**Crash log/Log (if applicable):** No crash log.

**Screenshots (if applicable):** No screenshots.

**Version of Mod using:** 4.0.2.211, Galacticraft version is also 4.0.2.211.

**Where did this bug happen:** Everywhere I've tried to use the mod.

### Additional Information
I also have More Planets mod, but I don't think that's important. It didn't work without it anyway.

**Comment by MJRLegends** [comment]
You couldnt of provide less information about your issue if you tried. Please post your log files

**Comment by Chezcaek** [comment]
> You couldnt of provide less information about your issue if you tried. Please post your log files

How do I find that?
Also, forge won't even load it.

**Comment by MJRLegends** [comment]
Cant help you then sorry, this isnt a mod issue then if you cant even run forge.
