### ISSUE TITLE
Anti-Rads not honoring config setting?

### ISSUE THREAD

**Issue by geobr1990** [MJRLegends/ExtraPlanets#445]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

### Description of Issue
Anti-Rads do not reduce the proper amount of radiation.

### Steps to Reproduce Issue
1. Adjust config and set "Amount of Radiation reduced by Anti Rad Drinks"=5
2. Go to a planet and begin accumulating radiation.
3. Drink an Anti-Rad drink.

**Crash log/Log (if applicable):**

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):**1.12.2-0.5.3

**Where did this bug happen:** Server

### Additional Information
Minecraft 1.12.2, Forge 2836. I was on Pluto last night with a very high radiation level. Drinking an Anti-Rad drink lowered my radiation level considerably more than the 5% as set in the config.

I can grab the logs from the server later today if needed.

**Comment by MJRLegends** [comment]
Its 5% of your current amount not a straight 5%

**Comment by MJRLegends** [comment]
Im going to leave this open as i might change how the messages and config option is described

**Comment by geobr1990** [comment]
Thanks for the explanation!

**Comment by TripTripIssueTeller** [comment]
abc abc abc

**Comment by MJRLegends** [comment]
Updates have been released
