### ISSUE TITLE
Server 1.12.2 crashes when opened.

### ISSUE THREAD

**Issue by ElEricua** [MJRLegends/ExtraPlanets#446]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

### Description of Issue
Server crashes when opened.

### Steps to Reproduce Issue
1. Have a server with forge-1.12.2-14.23.5.2808-universal.jar
2. Have on the mods folder: ExtraPlanets-1.12.2-0.5.3.jar

**Crash log/Log (if applicable):** I think the crash log is the following:
https://pastebin.com/PpHHVSNf

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** 1.12.2

**Where did this bug happen:** Server

### Additional Information
Minecraft 1.12.2, Forge 2808. The server crashes before doing something. Sorry if there was another post saying the same thing as me but I couldn`t find it.

**Comment by MJRLegends** [comment]
Ahh your using the dev version of ExtraPlanets plz download the normal version

**Comment by ElEricua** [comment]
Thanks, and please continue updating the mod, its one of my favorites.

**Comment by ElEricua** [comment]
Sorry but it gives me again the same error, do I have to download it from
these link
https://www.curseforge.com/minecraft/mc-mods/extraplanets/files/2723471 and
download ExtraPlanets-1.12.2-0.5.3.jar? Beacause I did it and it appears
the same error.

**Comment by ElEricua** [comment]
I think this might help: https://pastebin.com/ZUfD9KTP

**Comment by MJRLegends** [comment]
Well thats because you been downloading mods like mjrlegends lib from unofficial sites. I'd recommend redownloading all your mods from curseforge or mod devs sites only nothing else

**Comment by ElEricua** [comment]
Ouu, now I understand, you where always saying that I had to download
mjrlegends lib from curseforge and not ExtraPlanets mod. Love you and
thanks for the patience.

**Comment by TripTripIssueTeller** [comment]
abc
