### ISSUE TITLE
Issues with Sky Providers for Moons/Space Stations/Kepler22b

### ISSUE THREAD

**Issue by KevinUnknown** [MJRLegends/ExtraPlanets#448]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or no]

### Description of Issue
[Description of the issue]
1st issue. Planets from moons. even with optifine zoom in ability i can't see much details of the planet, so lets say i am on europa(1 of jupiters moons), in real life i could see jupiter take  up about a quarter of the sky but in extra planets i cant even see it
2nd issue. same sun  size from every space station, so we can see the same size sun on every space station
3rd issue(its not that big) in information tab it says that kepler 22b doesnt have any moons but in night sky theres a moon
### Steps to Reproduce Issue
1. Launch minecraft with galacticraft and extraplanets
2. go to any of the space stations or moons added by extraplanets

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/Minecraft/crash-log/

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
1.12.2, extraplanets 0.5.3
**Where did this bug happen:** [Single Player or Server]
both
### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by TripTripIssueTeller** [comment]
abc abc

**Comment by DavidThatGamed** [comment]
cool idea man

**Comment by MJRLegends** [comment]
Updates are being released
