### ISSUE TITLE
Crash issue with Galaxy Map

### ISSUE THREAD

**Issue by Schookers** [MJRLegends/ExtraPlanets#449]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue
[Description of the issue]
When i lauched into space the server crushed. After that im joining server,trying to fly back to Earth and game crushes. How i can fix it?
### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them] [crash-2019-07-15_18.15.34-client.txt](https://github.com/MJRLegends/ExtraPlanets/files/3392985/crash-2019-07-15_18.15.34-client.txt)

> *How do i locate a crash log* see https://docs.mjrlegends.com/Minecraft/crash-log/

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
ExtraPlanets-1.12.2-0.5.2
**Where did this bug happen:** [Single Player or Server]
Server
### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by Recorpse** [comment]
I've been having the same issue. my game says "shutting down internal server" every time I use this and try to get into space. it happens when the map should open.

**Comment by MJRLegends** [comment]
Update to latest version and then report if it fixes the issue

**Comment by Recorpse** [comment]
still doesn't work. I was on the latest version the entire time anyway.

**Comment by MJRLegends** [comment]
@Recorpse Ok Please post your log files, and every config file for any galacticraft addons you have

**Comment by TripTripIssueTeller** [comment]
abc

**Comment by Recorpse** [comment]
d

**Comment by Recorpse** [comment]
doesn't matter I just removed the mod. pretty simple.

**Comment by MJRLegends** [comment]
@Recorpse please provide the other info i need to fix the issue

**Comment by MJRLegends** [comment]
Found the issue, its with PlanetProgressions. And it will be fixed in next version of PlanetProgressions that is out today

**Comment by ChrisTong1018** [comment]
I have this problem, too. What should I do?
Minecraft: 1.12.2
Forge: 14.23.5.2847
Galacticraft: 4.0.2.243
ExtraPlanets: 0.6.2
Thanks :)

**Comment by MJRLegends** [comment]
Please post your logs, mod list and any Galacticraft addon configs including ExtraPlanets
