### ISSUE TITLE
Buildings on Kepler 22b have no texture.

### ISSUE THREAD

**Issue by tethlah** [MJRLegends/ExtraPlanets#45]
Description of Issue:
Some of the buildings on Kepler 22b load with the stone buildings, however some of them load with the following block that has no texture:

tile.kepler22b.null.name
2730:15

Version of Mod using: 3.7.2

**Comment by MJRLegends** [comment]
This is because there was changes from 3.7.1 to 3.7.2 with block changes so you need to regen your dimension

**Comment by tethlah** [comment]
I never had 3.7.1, I just downloaded this mod for the first time a few hours ago, so the dim has never been loaded prior to the 3.7.2 I got tonight.

**Comment by MJRLegends** [comment]
Update is out give it 15 mins to show on curse
