### ISSUE TITLE
QUESTION: Spacesuit Compatability

### ISSUE THREAD

**Issue by ThrowawayIssueTeller** [MJRLegends/ExtraPlanets#450]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
n/a
### Description of Issue
[Description of the issue]
QUESTION: How would I go about adding compatability with another mods suit of armor/spacesuit, as in terms of pressure.
### Steps to Reproduce Issue
1. [First step]
2. [Second step]
n/a
**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
n/a
> *How do i locate a crash log* see https://docs.mjrlegends.com/Minecraft/crash-log/

**Screenshots (if applicable):** 
n/a
**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
1.12.2-0.5.3
**Where did this bug happen:** [Single Player or Server]
n/a
### Additional Information
[Any other information that may be able to help me with the problem]
n/a

**Comment by MJRLegends** [comment]
In ExtraPlanets config, there is the following option,

```
    # Format: 'modID:item:tier' | example: minecraft:iron_chestplate:4
    S:"List of armour items to be considered as a space suit" <
     >
```

**Comment by ThrowawayIssueTeller** [comment]
Thank you

**Comment by TripTripIssueTeller** [comment]
abc
