### ISSUE TITLE
Crash with new version of Galacticcraft core

### ISSUE THREAD

**Issue by BedrockLegends** [MJRLegends/ExtraPlanets#451]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue
[Description of the issue]
Updated Gc and crashed
### Steps to Reproduce Issue
1. [First step] Launch a pack with new GV version and then crash
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/Minecraft/crash-log/
https://paste.dimdev.org/qopaduvesi.mccrash
**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]

**Where did this bug happen:** [Single Player or Server] Single Player and server

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by BedrockLegends** [comment]
Thanks for the quick answer back

**Comment by MJRLegends** [comment]
Will try and fix in the next 24 hours

**Comment by BedrockLegends** [comment]
That is fine, No rush

**Comment by HeroNextDoor** [comment]
Any update on this yet @MJRLegends ?

**Comment by TripTripIssueTeller** [comment]
abc

**Comment by MJRLegends** [comment]
Still havent had time to fully get the changes done yet but will very soon

**Comment by MJRLegends** [comment]
Update is being released right this moment :D sorry for the delay

**Comment by HeroNextDoor** [comment]
@MJRLegends thank you so much for your time and dedication! Its really appreciated 🥇
