### ISSUE TITLE
Crash on Start up 1.12.2

### ISSUE THREAD

**Issue by RealDaku** [MJRLegends/ExtraPlanets#453]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes i have
https://pastebin.com/16TfRS2D

So every time i start the game i usually get 8-12 seconds of loading then it crashes once it gets to the extra planets mod. I have the latest version of everything even, i triple checked before i made this post and everything is up to date. It says its an exception issue but i don't know what that means.

**Comment by TripTripIssueTeller** [comment]
Does this occur with just Extra Planets and Galacticraft and their dependencies?

**Comment by MJRLegends** [comment]
@RealDaku You have download your mods from a unofficial source, meaning they will all be broke, download fro curseforge or mod devs website only.

We dont support 9minecraft no one does, the owner of that site is stealing money off mod devs and fucking them over.

Theres a whole group for this kinda of thing https://stopmodreposts.org/ they even have browser plugins to tell you when you are visiting a stealing site

**Comment by RealDaku** [comment]
> @RealDaku You have download your mods from a unofficial source, meaning they will all be broke, download fro curseforge or mod devs website only.
> 
> We dont support 9minecraft no one does, the owner of that site is stealing money off mod devs and fucking them over.
> 
> Theres a whole group for this kinda of thing https://stopmodreposts.org/ they even have browser plugins to tell you when you are visiting a stealing site

Thank you, it solved the exception problem and i downloaded from curseforge and reinstalled the mods. But now i have a new problem https://pastebin.com/8XAa4uyw It's to do with the blocks i think.

**Comment by MJRLegends** [comment]
See #451
