### ISSUE TITLE
ExtraPlanets do not unload on a Forge client/server.

### ISSUE THREAD

**Issue by Oakiepal** [MJRLegends/ExtraPlanets#457]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

### Description of Issue
ExtraPlanets dimensions will not unload regardless of server configuration of it not being in the `Static Loaded Dimensions` list in config/Galacticraft/core.yml. Every time a server is started, all ExtraPlanets are loaded up and are never unloaded. This same bug also occurs on the client-side. This issue makes servers harder to manage and it's harder to see what is loaded. It also clutters up other commands.

### Steps to Reproduce Issue
SERVER:
1. Run a Forge Server with ExtraPlanets and dependencies (eg. Galacticraft)
2. Join the server and issue the command /forge tps.

CLIENT:
1. Run a Forge Client with ExtraPlanets and dependencies (eg. Galacticraft)
2. Create/Open an existing world and issue /forge tps.

**Crash log/Log (if applicable):** [N/A]

**Screenshots (if applicable):** 
SERVER:
![image](https://user-images.githubusercontent.com/45017441/61820871-e9bbd400-ae23-11e9-8bce-02af91e5cbac.png)
CLIENT:
![image](https://user-images.githubusercontent.com/45017441/61820955-1cfe6300-ae24-11e9-8642-f89c681f1416.png)

All of the following planets are ExtraPlanets, with the exception of the Vanilla and GC Planets.

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [ExtraPlanets-1.7.10-2.1.1]

**Where did this bug happen:** [Both]

### Additional Information
Although this issue is quite similar to the issue that @kmecpp opened, #400, this report shows that this issue is not a bug exclusive to a server running on KCauldron/Thermos and does occur on a normal forge environment.

**Comment by MJRLegends** [comment]
Yea that's normal no harm in that
