### ISSUE TITLE
Crash issue

### ISSUE THREAD

**Issue by jakebacker** [MJRLegends/ExtraPlanets#458]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

### Description of Issue
After placing the Basic Contamination Unit, loading it causes the client to disconnect and the server to produce many errors such as
```
[16:46:57] [Server thread/ERROR] [FML]: A TileEntity type com.mjr.extraplanets.tileEntities.blocks.TileEntityBasicDecontaminationUnitFake has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.NullPointerException: null
```

### Steps to Reproduce Issue
1. On a server, place the Basic Decontamination Unit
2. User disconnects
(I don't really know the specifics, but it happened twice after restoring a backup)

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/Minecraft/crash-log/

[Crash Log](https://paste.ubuntu.com/p/zqxJpfP3Db/)

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** 1.12.2-0.5.4

**Where did this bug happen:** Server

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Update rolling out as we speak to fix this
