### ISSUE TITLE
Leaves not showing correct name when inspecting them.

### ISSUE THREAD

**Issue by tethlah** [MJRLegends/ExtraPlanets#46]
Description of Issue:
When using Waila to inspect leaves on Kepler 22b, leaves that are NOT on the outside facing of the tree (IE: leaves that are against the tree trunk with leaves outside of them making them the innermost leaf block) do not show the proper name of the leaf block.

IE:  tile.kepler22bMapleLeaves.null.name

Version of Mod using: 3.7.2

**Comment by MJRLegends** [comment]
Will look in to this more now and get back to you

**Comment by MJRLegends** [comment]
Fixed in v3.7.4
