### ISSUE TITLE
[Space Suit Compatability]

### ISSUE THREAD

**Issue by Triplapeeck-Dev** [MJRLegends/ExtraPlanets#460]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes
### Description of Issue
[Description of the issue]
When I try and add more than 1 item to the space suit compatibly list, none of the items listed work as a space suit
### Steps to Reproduce Issue
1. [First step] Add more than 1 item to the space suit compatibility 
2. [Second step] Try and wear, radiation continues to go up as if you weren't wearing a space suit. You also die of pressure.

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/Minecraft/crash-log/
n/a
**Screenshots (if applicable):** 
If you request it, I can create a video of this happening
**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
1.12.2-0.5.4
**Where did this bug happen:** [Single Player or Server]
Single Player
### Additional Information
[Any other information that may be able to help me with the problem]
Tested with just Galacticraft 218 + Extra Planets (wasn't when I first encountered this) It still occurs
Related config:
 # Format: 'modID:item:tier' | example: minecraft:iron_chestplate:4
    S:"List of armour items to be considered as a space suit" <
        minecraft:iron_chestplate:4
        minecraft:iron_helmet:4
        minecraft:iron_leggings:4
        minecraft:iron_boots:4
     >

**Comment by Triplapeeck-Dev** [comment]
Not an issue for me anymore. Found a workaround.

**Comment by MJRLegends** [comment]
What was the workaround?

**Comment by Triplapeeck-Dev** [comment]
My issue that was the reason I needed to add armor was that I have AR and Galacticraft + addons in the same pack. I have GC air override on, causing AR to use its air instead, and while it is possible to add a seal to any set of armor to allow breathing, that seal by default is just for 30 minutes of air. I forgot that there is another way to add more oxygen storage for all armor in AR. I can now just use the Extra Planets suits with an airtight seal and an extra AR oxygen tank added to the chestplate for a larger amount of time.

**Comment by MJRLegends** [comment]
Yeah Galacticraft/ExtraPlanets are not compatible with advanced rocketry each other use one or the other

**Comment by Triplapeeck-Dev** [comment]
I'm aware. AR is very modular, so with enough work, you can use AR's rocket and oxygen systems, while still enforcing GC progression.
