### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by Rumspringa90** [MJRLegends/ExtraPlanets#461]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue
i have translated version 2.1.2 from MC1.7.10 into German
[de_DE.zip](https://github.com/MJRLegends/ExtraPlanets/files/3451851/de_DE.zip)

### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/Minecraft/crash-log/

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** MC1.7.10 ExtraPlanets 2.1.2

**Where did this bug happen:** [Single Player or Server]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Thank you
