### ISSUE TITLE
Space station register crash issue

### ISSUE THREAD

**Issue by ROMVoid95** [MJRLegends/ExtraPlanets#462]
### ---Issue Report---

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** I have

### Description of Issue
With the newest build version of Galacticraft (**226**) that fixed the versioning issues with add-ons. I had gone to test each add-on for compatibility with the new version. once alone with GC, then with other add-on's included. This crash report occurred when ExtraPlanets was the only add-on and when not. There's an easy fix to this but figured it should either be a default config value or have a built in workaround so others don't experience this on first run.

**java.lang.RuntimeException: Two space station types registered with the same home planet ID: -31**

### Steps to Reproduce Issue
1. Download Galacticraft-4.0.2.226 files
2. Install ExtraPlanets-1.12.2-0.5.5
3. Start the game.
4. See crash-log when prompted

**Crash log/Log (if applicable):** 
[Crash-Log Link](https://hasteb.in/nasikuza.yaml)
Its on https://hateb.in because http://hastebin.com went down, and this is such a cleaner format to read.

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** 
MJRLegendsLib-1.12.2-1.1.8
ExtraPlanets-1.12.2-0.5.5

GalacticraftCore-1.12.2-4.0.2.226
Galacticraft-Planets-1.12.2-4.0.2.226
MicdoodleCore-1.12.2-4.0.2.226

**Where did this bug happen:** Singleplayer start-up. Have not tested this on a server with or without existing worlds

### Additional Information
To fix this crash and prevent on next start-up is to edit **extraplanets.cfg**
Section: space stations
Line: 993
Replace **false** with **true**
```cfg
    # Setting this option to false will disable & remove the Venus Space Station
    B:"Venus SpaceStation"=true
```

**Comment by MJRLegends** [comment]
This isnt a bug just just the compact options that are available 

If you ever need help with making ExtraPlanets work with other Galacticraft addons check out these

MC 1.7.10 Compatibility Support: https://docs.mjrlegends.com/ExtraPlanets/1.7.10compact/
MC 1.12.2 Compatibility Support: https://docs.mjrlegends.com/ExtraPlanets/1.12.2compact/
MC 1.8.9 - 1.11.2 Compatibility Support: https://docs.mjrlegends.com/ExtraPlanets/1.8-1.11compact/
