### ISSUE TITLE
1.7.10 Server startup crash

### ISSUE THREAD

**Issue by VariaSTX** [MJRLegends/ExtraPlanets#463]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

### Description of Issue
Exeption in Server tick loop
cpw.mods.fml.common.LoaderException: java.lang.ClassNotFoundException: com.mjr.extraplanets.ExtraPlanets

### Steps to Reproduce Issue
1. make a modded server with: extra planets, more planets and galacticraft
2. Start server

Crash Log:
[crash-2019-08-09_19.44.56-server.txt](https://github.com/MJRLegends/ExtraPlanets/files/3487503/crash-2019-08-09_19.44.56-server.txt)

Version of mods: [ExtraPlanets-1.7.10-2.1.2, ExtraPlanets-1.7.10-2.1.2-api, Galacticraftcore-3.0.12.504, Galacticraft-Planets-3.0.12.504 and Micdoodlecore-3.0.12.504]

This bug happened on a server

**Comment by MJRLegends** [comment]
Yea you have the api jar not even the normal jar for ExtraPlanets lol

**Comment by VariaSTX** [comment]
I've already tried without the api installed and it still doesnt work and i do have te normal jar for extraplanets

**Comment by MJRLegends** [comment]
You have the api jar. And it works fine once you get the correct jar file.

**Comment by MJRLegends** [comment]
Delete everything to do with ExtraPlanets you have and download https://www.curseforge.com/minecraft/mc-mods/extraplanets/download/2746525

**Comment by VariaSTX** [comment]
wel guess what i already have the correct jar file since the beginning and if not it would be strange if i could use the exact same file but working in singleplayer

**Comment by VariaSTX** [comment]
and i did download it from curseforge

**Comment by MJRLegends** [comment]
Your loss dude. You can see in your crash log that you have the api version of the jar. The normal jar works fine for the other 5452 people so just you dude. Nothing more i can do if your not listening and going to look in your mods folder you will see the ExtraPlanets has the words api in it. Thats the wrong jar file
