### ISSUE TITLE
1.7.10 server crash on startup

### ISSUE THREAD

**Issue by VariaSTX** [MJRLegends/ExtraPlanets#464]
---Issue Report---

(Note: this is the second coming of my original post.)

Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING): [Yes]
Description of Issue
I spent well over an hour working on this problem and i am extremely agitated beacose the developers are not listening beacose i see no api in the jar file unless i'm blind even in te crash report i see no api with the NORMAL .jar file (UE	ExtraPlanets{1.7.10-2.1.2} [Extra Planets] (ExtraPlanets-1.7.10-2.1.2.jar)) wich has a UE (Unloaded and Errored) next to it so i see no reason to just ignore this as a UsED aN INcoRreCT jAr fiLE problem so please have a good look into this.

Exeption in Server tick loop
cpw.mods.fml.common.LoaderException: java.lang.ClassNotFoundException: com.mjr.extraplanets.ExtraPlanets
Steps to Reproduce Issue

    make a modded server with: extra planets, more planets and galacticraft
    Start server

Crash Log:
[crash-2019-08-09_19.44.56-server.txt](https://github.com/MJRLegends/ExtraPlanets/files/3487662/crash-2019-08-09_19.44.56-server.txt)

Version of mods: [ExtraPlanets-1.7.10-2.1.2, Galacticraftcore-3.0.12.504, Galacticraft-Planets-3.0.12.504 and Micdoodlecore-3.0.12.504]

This bug happened on a server

**Comment by MJRLegends** [comment]
Does it work if ExtraPlanets is removed

**Comment by VariaSTX** [comment]
yes

**Comment by MJRLegends** [comment]
Ahh ok yea just use java 8 rather than 7

**Comment by VariaSTX** [comment]
Finally, it works now. thank you for a good awnser
