### ISSUE TITLE
Basic Crystallizer doesn't work with pipes from other mods

### ISSUE THREAD

**Issue by idkw** [MJRLegends/ExtraPlanets#466]
### Description of Issue

I can't insert or take items out from the Basic Crystallizer with pipes from Thermal Dynamics or A2 cables.

### Steps to Reproduce Issue

Put a Basic Crystallizer with a hopper below : works for extracting items
Put a Basic Crystallizer with some other mod's pipe : doesn't work for extracting items

Works :
![image](https://user-images.githubusercontent.com/7012331/63129365-9ae30380-bfb7-11e9-804a-23b4f5a5cd0c.png)

Doesn't work :
![image](https://user-images.githubusercontent.com/7012331/63129368-9dddf400-bfb7-11e9-92ce-472357534b42.png)

**Versions**

ExtraPlanets-1.12.2-0.5.5.jar
GalacticraftCore-1.12.2-4.0.2.230.jar

**Where did this bug happen:**

Server and single player

### Additional Information

For all other machines, the pipes work but not the Basic Crystallizer.

Only the hopper work

The issue happens too when putting items in from above.

Thanks

**Comment by MJRLegends** [comment]
Update has been released to fix this
