### ISSUE TITLE
MPS Support?

### ISSUE THREAD

**Issue by Dalethium** [MJRLegends/ExtraPlanets#469]
Modular power suits has an "Air tight" seal thing for galacticraft I think, perhaps you could allow certain upgrades from MPS to allow pressure protection aswell? 

Perhaps if it's air tight and has energy shield/diamond armor on?

Thanks!

**Comment by MJRLegends** [comment]
Should be in next MC 1.12.2 update see https://github.com/MJRLegends/ExtraPlanets/commit/2f6c12f1fb1eaa1de6394695d05ed198f7398e1e

for the other mc versions i will see, i might add it for them too

**Comment by Dalethium** [comment]
Sweet, thanks so much!
