### ISSUE TITLE
Some grass tiles not showing name when inspecting them.

### ISSUE THREAD

**Issue by tethlah** [MJRLegends/ExtraPlanets#47]
Description of Issue:
The following grass blocks do not display a proper name when you inspect them, instead they display the tile entity:

tile.kepler22b_yellowGrass.name
tile.kepler22b_redGrass.name
tile.kepler22b_blueGrass.name
time.kepler22b_purpleGrass.name

Version of Mod using: 3.7.2

**Comment by MJRLegends** [comment]
What language do you use?

**Comment by tethlah** [comment]
English

**Comment by MJRLegends** [comment]
English US or UK?

**Comment by tethlah** [comment]
US

**Comment by MJRLegends** [comment]
Update is out give it 15 mins to show on curse
