### ISSUE TITLE
Crash on loading

### ISSUE THREAD

**Issue by jinkhya** [MJRLegends/ExtraPlanets#470]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue
Crash on loading a custom pack

### Steps to Reproduce Issue
Not sure it's reproducible since it's a custom pack but I'll give you the crash log.

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/Minecraft/crash-log/
https://pastebin.com/ca34bwzf

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
1.12.2-0.5.6
forge 2838

**Where did this bug happen:** [Single Player or Server]
While loading the pack on step 4/7
### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Update your Galacticraft its very out of date
