### ISSUE TITLE
JEI GUI Overlaps Module GUI and Space Suit Not Found in Creative GUI

### ISSUE THREAD

**Issue by Yataro-Ibuza** [MJRLegends/ExtraPlanets#472]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

### Description of Issue
**-JEI OVERLAPS:** When you have installed JEI and you open the Module Manager the JEI start to Overlaps the Module Manager, this do not Crash the game, but the description is barely visible for the JEI Overlapping.

**- Space Suit no found:** In Creative when i use the GUI search of Minecraft and try to search from there i only find the "Un-Prepared" Tier, but he don´t found the "Space Suit", but if i search the same en JEI they are all the Space Suit Tier, included the Un-Prepared one

### Steps to Reproduce Issue
1. Open Launcher and wait until is complete
2. Create a new World in Creative and go there
3. When the world generates, open the creative Inventory

### For JEI OVERLAPS
4. Go to "Extra Planet" Section
5. Equip any Tier Space Suit.
6. Close the Creative Inventory
7. Enter to "Module Manager"
8. IF you have JEI installed the JEI GUI start to Overlap the Module Manager GUI.

### For SPACE SUIT TIER NO FOUND
4. Go to the "Search" creative Tap
5. Then insert in the Search Bar "Space Suit"
6. It only Shows the "Un-Prepared Space Suit Tier X" (Where X is any Tier)
7. Now go to the JEI GUI in the Search Bar.
8. Insert "Space Suit" Again
9. He shows all the Space Suit included the "Un-Prepared" ones 

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> No Log available because the game do not Crash or Something

**Screenshots (if applicable):** 
**_For JEI OVERLAP_**
![JEI OVERLAP](https://user-images.githubusercontent.com/54340068/64045869-45facd80-cb1f-11e9-8dd7-f64d1c31ad89.png)

**_For SPACE SUIT NOT FOUND IN Minecraft_**
![SPACE SUIT NO FOUND](https://user-images.githubusercontent.com/54340068/64045876-498e5480-cb1f-11e9-8280-4d39a8185a6f.png)

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** Mods Used:

- OptiFine_1.12.2_HD_U_E3

- jei_1.12.2-4.15.0.268

- MJRLegendsLib-1.12.2-1.1.8

- MicdoodleCore-1.12.2-4.0.2.231

- GalacticraftCore-1.12.2-4.0.2.231

- Galacticraft-Planets-1.12.2-4.0.2.231

- ExtraPlanets-1.12.2-0.5.4

**Where did this bug happen:** Single Player (I don´t know if happens in a server)

### Additional Information
Unfortunatetly, i don´t have more further information...

**Comment by MJRLegends** [comment]
Updates released for MC 1.12.2, 1.11.2, 1.10.2. 

MC 1.8.9 will come later as got more work to do for that version :D

**Comment by MJRLegends** [comment]
Update released for MC 1.8.9
