### ISSUE TITLE
[1.12.2] Space suit boots tier 2 have effects of grav boots tier 2

### ISSUE THREAD

**Issue by Tayaress51** [MJRLegends/ExtraPlanets#475]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** No

### Description of Issue

I played on an ancient version of the mod and differents gravities of planets don't act on me. So I took the latest version and I have the same problem. In creative I tried to resolve that and I find that I jump a block with space suit boots tier 2  and more than a block with space suit grav boots tier 2.  I tried with the others tier and there is no problem, this is just for tier 2

### Steps to Reproduce Issue
1. equip space suit boots tier 2 on a planet ( Asteroids for exemple) an jump => one block
2. equip space suit grav boots tier 2 on the same planet => more than a block

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/Minecraft/crash-log/

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):**  0.5.6 (but the same problem with 0.4.7)

**Where did this bug happen:**  Single Player

### Additional Information
In french, gravity is "gravité" and not "garvité". little mistake.

**Comment by MJRLegends** [comment]
Thanks fixed in the next MC 1.8.9, 1.10.2, 1.11.2, 1.12.2 updates

**Comment by MJRLegends** [comment]
Updates released for MC 1.12.2, 1.11.2, 1.10.2. 

MC 1.8.9 will come later as got more work to do for that version :D

**Comment by MJRLegends** [comment]
Update released for MC 1.8.9
