### ISSUE TITLE
<"Enable Radiation"=false> Cause rocket's recipe can't be found in JEI

### ISSUE THREAD

**Issue by Flactine** [MJRLegends/ExtraPlanets#476]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

### Description of Issue
In ExtraPlanets.cfg, if set "Enable Radiation"=false , then all ExtraPlanets' rockets(Tier 4-10 and Electrical) recipes can't be found in JEI. But original Galacticraft's rockets(Tier 1-3) recipes can be found in JEI.
But the rocket is still craftable.

### Steps to Reproduce Issue
1. Not edit ExtraPlanets.cfg, can check ExtraPlanets Rocket's recipes by press R.
2. Quit Game, Edit ExtraPlanets.cfg:
"Enable Radiation"=false
Start Game, Then can't check all ExtraPlanets Rocket's recipes. But Rockets are still craftable.

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
ExtraPlanets-1.12.2-0.5.6

**Where did this bug happen:** [Single Player or Server]
Single Player

### Additional Information
JEI's version is 
jei_1.12.2-4.15.0.268

**Comment by MJRLegends** [comment]
Updates released for MC 1.12.2, 1.11.2, 1.10.2. 

MC 1.8.9 will come later as got more work to do for that version :D

**Comment by MJRLegends** [comment]
Update released for MC 1.8.9
