### ISSUE TITLE
Crash when flying to all EP planets

### ISSUE THREAD

**Issue by TheTerrorByte** [MJRLegends/ExtraPlanets#477]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

### Description of Issue
When I get to space and select an EP planet (mercury, jupiter, etc), the game crashes before loading the planet. I eventually get placed on my desired planet after restarting the game, however, attempting to fly to another EP planet crashes again. This does not occur when travelling to the standard galacticraft planets or any other dimension.

### Steps to Reproduce Issue
1. Launch a rocket or use /dimensiontp
2. Select any planet added by EP
3. The game should crash now

**Crash log/Log (if applicable):** https://pastebin.com/V2hbKaP3

**Screenshots (if applicable):** N/A

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** 

ExtraPlanets-1.12.2-0.5.6
MJRLegendsLib-1.12.2-1.1.8
GalacticraftCore-1.12.2-4.0.2.237
Galacticraft-Planets-1.12.2-4.0.2.237
MicdoodleCore-1.12.2-4.0.2.237

**Where did this bug happen:** Singleplayer

### Additional Information
nope :)

**Comment by MJRLegends** [comment]
Please use Galacticraft 236 for now, an api in Galacticraft change needs a update in my mod to make it work again

**Comment by MJRLegends** [comment]
https://github.com/MJRLegends/ExtraPlanets/commit/20a6fd6e625e7cd28ab834cd57c183e972e8b563

**Comment by MJRLegends** [comment]
Update released
