### ISSUE TITLE
Space suits cannot be crafted in 0.5.7 for mc 1.12.2

### ISSUE THREAD

**Issue by mcBegins2Snow** [MJRLegends/ExtraPlanets#479]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes
### Description of Issue
Space suits cannot be crafted in **0.5.7**'s Extra Planets, but in **0.5.6**(previous version), they can be crafted normally.

### Steps to Reproduce Issue
1. Find a space suit in jei;
2. Press "R" to show its recipe;
3. Recipe not found.
4. Try to craft a Tier 1 Space Suit Helmet, failed.

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
No crash

**Screenshots (if applicable):** 
![2019-09-24_19 50 40](https://user-images.githubusercontent.com/37864486/65509259-a3a6ed80-df04-11e9-8b10-a5a5be0aad3b.png)

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]

1. ExtraPlanets-1.12.2-0.5.7
2. MJRLegendsLib-1.12.2-1.1.9
3. GalacticraftCore-1.12.2-4.0.2.237
4. Galacticraft-Planets-1.12.2-4.0.2.237
5. MicdoodleCore-1.12.2-4.0.2.237
6. jei_1.12.2-4.15.0.289

**Where did this bug happen:** [Single Player or Server]
Single Player
### Additional Information
[Any other information that may be able to help me with the problem]
Nothing

**Comment by MJRLegends** [comment]
Update has been released, will be showing once approved on curseforge

**Comment by MJRLegends** [comment]
Update is now available https://www.curseforge.com/minecraft/mc-mods/extraplanets/files/2793936

**Comment by velocityraptor-real** [comment]
Do you have a good wiki for the crafting recipes?
Or do I have to install too many items?
