### ISSUE TITLE
[1.7.10] Oberon High Hills Biome spawning in the overworld

### ISSUE THREAD

**Issue by Sinmis077** [MJRLegends/ExtraPlanets#480]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes
### Description of Issue
The oberon high hills/mountain biome its spawning in places of extreme hills , and mountain biomes (vanilla ones)

### Steps to Reproduce Issue
1. Make a new world with no changes to config
2. fly far away (in creative mode) [At least 1k blocks from spawn] where are mountains (any mountain can do)
**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/Minecraft/crash-log/

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** 2.1.2

**Where did this bug happen:** singleplayer

### Additional Information
[Any other information that may be able to help me with the problem] : it may be caused because of biome id overriding

**Comment by Sinmis077** [comment]
https://cdn.discordapp.com/attachments/627157620913995797/627225322093412352/unknown.png
this is the screenshot

**Comment by MJRLegends** [comment]
Biome conflicts change biome ids via config
