### ISSUE TITLE
Game crash on Space Map

### ISSUE THREAD

**Issue by StevenGeiloo** [MJRLegends/ExtraPlanets#482]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

### Description of Issue
Game screen background will be white and crash after a few seconds when AsmodeusCore is installed

### Steps to Reproduce Issue
1. Open Space Map with M or fly with a rocket when AsmodeusCore is installed

**Crash log/Log (if applicable):** https://pastebin.com/4GyYKmQJ

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** 1.12.2-0.5.8

**Where did this bug happen:** Single Player

**Comment by MJRLegends** [comment]
AsmodeusCore isnt compatibility to latest Galacticraft probably the reason. report to them
