### ISSUE TITLE
Game crash whenever i go to another planet than earth

### ISSUE THREAD

**Issue by MrRyaan** [MJRLegends/ExtraPlanets#483]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

****Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]**
Yes

### Description of Issue
The game crashes whenever i try to go to another planet. Game crash is in attatchments

### Steps to Reproduce Issue
1. Get this addon mod
2. Try to go to anothe planet

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]

[crash-2019-10-02_13.41.54-server.txt](https://github.com/MJRLegends/ExtraPlanets/files/3680929/crash-2019-10-02_13.41.54-server.txt)
[crash-2019-10-02_13.37.44-server.txt](https://github.com/MJRLegends/ExtraPlanets/files/3680931/crash-2019-10-02_13.37.44-server.txt)

**Screenshots (if applicable):** 
\none 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]

 version: 1.12.2 

**Where did this bug happen:** [Single Player or Server]

single player

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
You have download your mods from a unofficial source, meaning they will all be broke, download fro curseforge or mod devs website only.

We dont support 9minecraft no one does, the owner of that site is stealing money off mod devs and fucking them over.

Theres a whole group for this kinda of thing https://stopmodreposts.org/ they even have browser plugins to tell you when you are visiting a stealing site
