### ISSUE TITLE
Crash on loading world, Invalid dimension planet.venus

### ISSUE THREAD

**Issue by Lgk2** [MJRLegends/ExtraPlanets#484]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
No

### Description of Issue
[Description of the issue]
I get a crash on loading in my singleplayer world.

### Steps to Reproduce Issue
1. [First step] Load in the game, this works fine.
2. [Second step] Load a world and the game instantly crashes.

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/Minecraft/crash-log/
https://pastebin.com/rTJsjDNc

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
GalacticraftCore 1.12.2-4.0.2.237
Galacticraft-Planets 1.12.2-4.0.2.237
Extraplanets: 1.12.2-0.5.8

**Where did this bug happen:** [Single Player or Server]
Single Player

**Extra info**
When i disabled extraplanets the game didn't crash on load anymore so it's probably not caused by galacticraft.

**Comment by MJRLegends** [comment]
**The crash you have provided is a Galacticraft issue with their advancements.**

```
java.lang.IllegalArgumentException: Invalid dimension planet.venus
    at net.minecraft.world.DimensionType.func_193417_a(DimensionType.java:104)
    at net.minecraft.advancements.critereon.ChangeDimensionTrigger.func_192166_a(SourceFile:58
```
**My mod doesnt have or touch any advancements sorry :P**
