### ISSUE TITLE
Vanilla Magma Block's name has been changed by Extra Planets mod

### ISSUE THREAD

**Issue by mcBegins2Snow** [MJRLegends/ExtraPlanets#487]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** 
Yes

### Description of Issue
Vanilla Magma Block(minecraft:magma)'s name has been changed to "Liquid Magma" when installed the Extra Planets mod. Without this mod, this thing cannot be happened.

### Steps to Reproduce Issue
1. Open my inventory;
2. Search a Magma Block(minecraft:magma) on JEI.

**Crash log/Log (if applicable):** No crash

**Screenshots (if applicable):** 
![2019-10-09_19 18 55](https://user-images.githubusercontent.com/37864486/66477557-fbc81d00-eaca-11e9-9caf-c98fe1d544ad.png)

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]

1. ExtraPlanets-1.12.2-0.5.8
2. MJRLegendsLib-1.12.2-1.1.9
3. GalacticraftCore-1.12.2-4.0.2.237
4. Galacticraft-Planets-1.12.2-4.0.2.237
5. MicdoodleCore-1.12.2-4.0.2.237
6. jei_1.12.2-4.15.0.289

**Where did this bug happen:** Single Player

### Additional Information
In https://github.com/MJRLegends/ExtraPlanets/blob/master/src/main/resources/assets/extraplanets/lang/en_US.lang#L1435
`tile.magma.name=Liquid Magma`

**Comment by MJRLegends** [comment]
Update for MC 1.12.2 has been released others will come later

**Comment by mcBegins2Snow** [comment]
If solved this issue, please allow me to update zh_cn.lang again.

**Comment by MJRLegends** [comment]
Switch the branch your using on my repo to something other than master or dev_1.8.9 and you are able to get new files

**Comment by MJRLegends** [comment]
Updates for MC 1.11.2 & 1.10.2 have been released
