### ISSUE TITLE
Crash when loading world [1.7.10]

### ISSUE THREAD

**Issue by isinfinity** [MJRLegends/ExtraPlanets#488]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
No
### Description of Issue
[Description of the issue]
When I install extra planets and open a save, the game crashes
### Steps to Reproduce Issue
1. [First step]Load in the game, this works fine
2. [Second step]Load a world and the game instantly crashes.

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/Minecraft/crash-log/
https://pastebin.com/YFRV669r
**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
ExtraPlanets-1.7.10-2.1.2
GalacticraftCore-1.7-3.0.12.504
Galacticraft-Planets-1.7-3.0.12.504
**Where did this bug happen:** [Single Player or Server]
Singleplayer
### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
No idea could be anything the crash log doesn't directly say ExtraPlanets. If you can get it to crash with just the base mods like Galacticraft and ExtraPlanets. Or them mods and another one of another one is causing my mod to fail i will be able to look at it then

**Comment by MJRLegends** [comment]
Please try with Tihyoa legends mod on its own

**Comment by isinfinity** [comment]
oh wait, it's Legends mod, antiidconflict and your mod

**Comment by isinfinity** [comment]
I think I know what's wrong. There is an inherent incompatibility between Legends mod and Antiidconflict. While disabling the 'crash if conflict' stop the crash. It still affected other mods, including yours. Sorry for wasting your time. I just have to uninstall antiidconflict, shame.

**Comment by MJRLegends** [comment]
No problem
