### ISSUE TITLE
[1.7.10]ExtraPlanets crashes in the startup of the game

### ISSUE THREAD

**Issue by shiroo557** [MJRLegends/ExtraPlanets#489]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No] Yes.

### Description of Issue
[Description of the issue]
It is probably a incompatibility error but i couldnt manage to find out wich one caused the crash but if i remove EP it starts up normally. 
### Steps to Reproduce Issue
1. [First step]
install all my current mods
(should be listet in the crash but i have like 267 mods so i cant copy them in pastebin)
2. [Second step]
add EP
**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
https://pastebin.com/W51AMAdZ
> *How do i locate a crash log* see https://docs.mjrlegends.com/Minecraft/crash-log/

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
ExtraPlanets-1.7.10-2.1.2
**Where did this bug happen:** [Single Player or Server]
Single Player
### Additional Information
[Any other information that may be able to help me with the problem]
I can use the other mods( Galacticraft core, galacticraft planets and mcdoodlecore but when i add it it crashes in phase 5 (initialising mods 3 ) in the forge launcher

**Comment by MJRLegends** [comment]
i see nothing saying ExtraPlanets and your crash log so cant help you sorry. Your issue is with thaumcraft compact support in moofluids

```
    at com.robrit.moofluids.common.plugins.thaumcraft.AspectRegistry.registerEntityAspects(AspectRegistry.java:45)
    at com.robrit.moofluids.common.plugins.thaumcraft.ThaumcraftPlugin.init(ThaumcraftPlugin.java:25)
```
