### ISSUE TITLE
Tier 7, 8, 9, and 10 Rocket issues

### ISSUE THREAD

**Issue by Cazadorsniper** [MJRLegends/ExtraPlanets#49]
### ---Issue Report---

Have you checked Closed Issues (if applicable): Yes 
### Description of Issue:
Not sure why the Tier 7, Tier 8 and Tier 9 rockets will not launch or display their internal inventory (to check fuel). The Tier 10 Rocket is not craftable in the NASA Workbench.

### Steps to Reproduce Issue
1. Try to launch a tier 7, 8, or 9 rocket and see that nothing happens.
2. Try to craft a Tier 10 rocket in the NASA Workbench and the Rocket won't appear in order to craft.

Version of Mod using: ExtraPlanets-1.0-Pre 3.7.4

**Comment by MJRLegends** [comment]
Will get a fix out later for you :)

**Comment by MJRLegends** [comment]
Update should be out soon, just waiting on curse to approve it :D
