### ISSUE TITLE
[1.12.2] Crash upon landing on an EP planet

### ISSUE THREAD

**Issue by DanRocs298** [MJRLegends/ExtraPlanets#490]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes

### Description of Issue
[Description of the issue]
Whenever you launch into an EP planet (Mercury, Jupiter, etc), the game will crash.

### Steps to Reproduce Issue
1. Launch into an EP planet
2. Wait a minute or two and the game should crash

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/Minecraft/crash-log/
https://pastebin.com/viVBKEep

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
Currently running version 1.12.2-0.5.6

**Where did this bug happen:** [Single Player or Server]
Single Player

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Update to latest version, also never report bugs for older versions of a mod its just pointless as 9 times out of 10 its not a issue in newer versions

**Comment by DanRocs298** [comment]
My apologies
