### ISSUE TITLE
Jetpack space suit energy never empty

### ISSUE THREAD

**Issue by ToserBan** [MJRLegends/ExtraPlanets#493]
### ---Issue Report---

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
yes
### Description of Issue
Three little problems in one. First, when i fly with my space suit jetpack, the energy is almost empty after only 10 seconds. It should last much longer. Second, the last 1000 gJ of energy does never use up, which means i can fly infinite. I expect a behaviour like the jetpack from mekanism or similar. I can fly a couple of minutes and when the energy is used up, i cant fly any longer. Third problem, whenever i fly, the durability of the space suit drops, until it reaches 2/100. Expected behaviour: The durability is not affected by flying.

### Steps to Reproduce Issue
1. Install gc and extra planets, get yourself a jetpack space suit, charge it with RF and fly
2. Energy drops way too fast, but never uses up completely.

**Crash log/Log (if applicable):** 
no crash
> *How do i locate a crash log* see https://docs.mjrlegends.com/Minecraft/crash-log/

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
ExtraPlanets-1.12.2-0.5.6.jar
But i saw it in older versions too.
**Where did this bug happen:** [Single Player or Server]
SP
### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Btw your ExtraPlanets is out of date, best to always report bugs with latest version

**Comment by MJRLegends** [comment]
Will be fixed in next update

**Comment by MJRLegends** [comment]
Updates released for MC 1.12.2, 1.11.2, 1.10.2.

MC 1.8.9 will come later as got more work to do for that version :D

**Comment by MJRLegends** [comment]
Update released for MC 1.8.9

**Comment by xJon** [comment]
Any chance this caused this? https://github.com/MJRLegends/ExtraPlanets/issues/510
