### ISSUE TITLE
[Issue] ExtraPlanet Biomes in overworld

### ISSUE THREAD

**Issue by LordOfDeath35** [MJRLegends/ExtraPlanets#495]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]
### Description of Issue
[There are biomes from other planets in the overworld]

### Steps to Reproduce Issue
1. [Install the following Modpack: https://www.curseforge.com/minecraft/modpacks/freetime-modpack/files/2828042]
2. [Create a world and fly around for a bit]

**Crash log/Log (if applicable):** [No crashlog as the world works]
> *How do i locate a crash log* see https://docs.mjrlegends.com/Minecraft/crash-log/

**Screenshots (if applicable):** 
![Bug](https://user-images.githubusercontent.com/32539080/68993837-b098eb00-087c-11ea-9e1b-14fdb0997c61.png)

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [ExtraPlanets-1.7.10-2.1.2.jar]

**Where did this bug happen:** [Single Player and Server]

### Additional Information
[It is used in a modpack]

**Comment by MJRLegends** [comment]
Change biome ids in config
