### ISSUE TITLE
Modular Powersuits crash but not on client

### ISSUE THREAD

**Issue by craving-death** [MJRLegends/ExtraPlanets#499]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue
[Description of the issue]
Crash on pack loading
### Steps to Reproduce Issue
"LotzaModz" modpack on curseforge
**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/Minecraft/crash-log/
https://paste.dimdev.org/opusizekak.mccrash
**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
ExtraPlanets-1.12.2-0.5.8.jar
**Where did this bug happen:** [Single Player or Server]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
So you dont have module powersuites mods in that pack correct?

**Comment by craving-death** [comment]
> So you dont have module powersuites mods in that pack correct?

correct, my apology for the delayed response

**Comment by MJRLegends** [comment]
Update has been released
