### ISSUE TITLE
[1.7.10] moons not appearing on galaxy map

### ISSUE THREAD

**Issue by isinfinity** [MJRLegends/ExtraPlanets#506]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue
[Description of the issue]
Some moons, like io and Europa does not appear in the galaxy map.
### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/Minecraft/crash-log/

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
2.1.2
**Where did this bug happen:** [Single Player or Server]
Singleplayer
### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Cant help you sorry you have provided so little information.

Please post logs, mod list? Images??

**Comment by MJRLegends** [comment]
Will reopen when more info is posted

**Comment by isinfinity** [comment]
screenshots of galaxy map and modlist:
![modlist](https://user-images.githubusercontent.com/20225652/70796364-06f63c80-1ddd-11ea-8d53-15260a71d87b.png)
![2019-12-13_18 03 43](https://user-images.githubusercontent.com/20225652/70796394-1b3a3980-1ddd-11ea-95ce-cf1bca396e3e.png)

**Comment by MJRLegends** [comment]
And i need logs please

**Comment by isinfinity** [comment]
Here is the logs of the day when I took the screenshot: https://pastebin.com/SWVCYwyE
But I doubt you can find anything interesting in it.
