### ISSUE TITLE
[1.12.2] Tier 3 Rocket Launch Pad does not used proper oredict

### ISSUE THREAD

**Issue by BedrockLegends** [MJRLegends/ExtraPlanets#509]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes
### Description of Issue
[Description of the issue]
When you go and craft the Tier 3 Rocket Launch Pad, It only requires 1 type of zinc Ingot but with a modpack that has different types of zinc. It would be helpful to have the Zinc oredict, using ingotZinc

### Steps to Reproduce Issue
1. [First step] checks recipe
2. [Second step] sees its not oredict

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/Minecraft/crash-log/

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
1.12.2-0.6.0
**Where did this bug happen:** [Single Player or Server]
Single Player and Server
### Additional Information
[Any other information that may be able to help me with the problem]
Check recipes to make sure they use right Oredict

**Comment by MJRLegends** [comment]
Its like this to force progression.
