### ISSUE TITLE
[1.8+] Space suit tier 1 do not charge (ONLY 1.8.9 TO UPDATE FOR FIX)

### ISSUE THREAD

**Issue by Romz24** [MJRLegends/ExtraPlanets#510]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue
When trying to charge Space suit nothing happens

### Steps to Reproduce Issue
1. Need to craft Space suit tier 1
2. Put in any charger

**Screenshots (if applicable):** 
![ScreenShot00111](https://user-images.githubusercontent.com/2458113/71229394-629d5a00-22f6-11ea-82ee-abdc6003c445.jpg)

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** ExtraPlanets 1.12.2-0.6.0
![ScreenShot00112](https://user-images.githubusercontent.com/2458113/71229481-be67e300-22f6-11ea-9e26-c6eec43946e2.jpg)

**Where did this bug happen:** Single Player and Server

**Comment by xJon** [comment]
Neither do other tiers:
![Screenshot_1](https://user-images.githubusercontent.com/8945347/71320788-12bac080-24b9-11ea-9ccb-4d79fa2ca28a.png)
Reported for my modpack here: https://github.com/xJon/The-1.12.2-Pack/issues/53

**Comment by aadoz** [comment]
I am having the same issue, I somehow got my chest peice to charge in the energy storage module but I am unable to charge any other pieces. The power in the module drops by 200 MJ but nothing happens.

**Comment by xJon** [comment]
@MJRLegends Is there any ETA of the update? I'm just not sure whether to wait or release a modpack update. Thanks.

**Comment by MJRLegends** [comment]
I will have a sort fix which will fix this issue out in the release later today

**Comment by MJRLegends** [comment]
Managed to find the really issue here so we going for a full working fix, hopefully will be the last space suit power issue i have to ever fix :D

**Comment by MJRLegends** [comment]
Updates for MC 1.12.2, 1.11.2, 1.10.2. MC 1.8.9 update will come later

**Comment by MJRLegends** [comment]
Update for MC 1.8.9 have been released
