### ISSUE TITLE
[1.7.10] suggest using extraplanet's jupiter instead of moreplanet's when enabling compat section

### ISSUE THREAD

**Issue by isinfinity** [MJRLegends/ExtraPlanets#511]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue
Jupiter in more planets is not finished. Therefore, can you change the compat section to using extraplanets's jupiter?

### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/Minecraft/crash-log/

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
2.1.2
**Where did this bug happen:** [Single Player or Server]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
The following new config options have been added which will you be able to do this with, btw the old options still exist and work/been fixed, part from the more planets progression fixes has been removed in favour of these new options.

```
    # Will tweak ExtraPlanets Planets/Moons, to allow them to work along side Extended Planets version of the same planets/moons! Will rename ExtraPlanets versions of doubled Planets/Moons to have 2.0 on the end. Example: Jupiter 2.0
    B:"Enable New Extended Planets Compatibility (v1.3.1 Alpha)"=false

    # Will tweak ExtraPlanets Planets/Moons, to allow them to work along side Extended Planets version of the same planets/moons! Will rename ExtraPlanets versions of doubled Planets/Moons to have 2.0 on the end. Example: Jupiter 2.0
    B:"Enable New Extended Planets Compatibility (v1.4 Alpha)"=false

    # Will tweak ExtraPlanets Planets/Moons, to allow them to work along side GalaxySpace version of the same planets/moons! Will rename ExtraPlanets versions of doubled Planets/Moons to have 2.0 on the end. Example: Jupiter 2.0 & disable Custom Celestial Selection screen, NOTE: WILL CHANGE THE FOLLOWING DIMENSION IDS Iapetus & Titania TO -44 & -45
    B:"Enable New Galaxy Space Compatibility (v1.2.3 and above)"=false

    # Will tweak ExtraPlanets Planets/Moons, to allow them to work along side More Planets version of the same planets/moons! Will rename ExtraPlanets versions of doubled Planets/Moons to have 2.0 on the end. Example: Jupiter 2.0!
    B:"Enable New More Planets Compatibility"=true
```

**Comment by MJRLegends** [comment]
Update MC 1.7.10 has been released
