### ISSUE TITLE
[1.12.2] Crashing upon loading

### ISSUE THREAD

**Issue by Hyalus** [MJRLegends/ExtraPlanets#512]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue
[Description of the issue]

### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/Minecraft/crash-log/

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]

**Where did this bug happen:** [Single Player or Server]

### Additional Information
[Any other information that may be able to help me with the problem]

1. install the mods in question to a profile on the twitch launcher
2. click play and it won't load

Hello I created a melting pot modpack and when I launch I get the "An error during startup prevented Minecraft from starting. The following mods have been identified as potential causes: "Galacticraft Core, Extra Planets"".

![GETLINK](https://user-images.githubusercontent.com/7918557/71603680-ff989800-2b2b-11ea-9d00-88d584a0c423.JPG)

 I got this screen when loading the minecraft app (before the main menu), Also I run a server that has the same mods and it won't run.

I am using Galacticraft (Planets, core, & McDoodleCore) verison: 1.12.2-4.0.2.238
I am using ExtraPlanets version: 1.12.2-0.6.0
I am using MJRLegends Lib version: 1.12.2-1.1.9
I am using Galaxy Space version: 1.12.2-2.0.11

 

here is the pastebin/crash report link: https://paste.dimdev.org/wegulihopa.mccrash 

And I followed this guide to try to make Extra Planets, Galaxy Space, Galacticraft and (hopefully More Planets & More Planets Extra) play nice together.

 

Please get in contact with me if you need any other information even if you need to friend me on Twitch and PM me. Thank you in advance for the help.

**Comment by MJRLegends** [comment]
You missed step 3 on galaxy space here https://docs.mjrlegends.com/ExtraPlanets/1.12.2compact/

**Comment by MJRLegends** [comment]
Also next time actually fill out the template not just post it blank then type your own stuff as next time i will just delete it and ignore it

**Comment by Hyalus** [comment]
> Also next time actually fill out the template not just post it blank then type your own stuff as next time i will just delete your issue report and ignore it

oops sorry my dude and thank you for the quick response and being such an active mod author!
