### ISSUE TITLE
EnderIO Endergy Stellar amor as space suit isnt working

### ISSUE THREAD

**Issue by israpps** [MJRLegends/ExtraPlanets#516]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue
[Description of the issue]
I tried to add the Stellar alloy armor as a tier 4 space suit

is this right??
# Format: 'modID:item:tier' | example: minecraft:iron_chestplate:4
S:"List of armour items to be considered as a space suit" <
enderio:item_stellar_alloy_boots:4
enderio:item_stellar_alloy_leggings:4
enderio:item_stellar_alloy_chestplate:4
enderio:item_stellar_alloy_helmet:4

### Steps to Reproduce Issue
1. 
Add the four pieces of armor to the config
2. 
Restart Minecraft 
3. 
Go to the moon (i'm playing un survival so i don't know if it happens on every planet) with the Stellar amor equiped ( i don't know If this is important but the helmet is painted with EnderIO quite clear glass to look like oxigen mask)

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/Minecraft/crash-log/

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]

 gc 1.12.2-4.0.2.239 
 ExtraPlanets-1.12.2-0.6.0.jar

**Where did this bug happen:** [Single Player or Server]
Single

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Please try with ExtraPlanets v0.6.1 and post your log files too please

**Comment by MJRLegends** [comment]
Never mind i see the issue, i will fix for next update thanks

**Comment by MJRLegends** [comment]
Fix will be out in a few hours :D

**Comment by MJRLegends** [comment]
Updates for MC 1.8.9, 1.10.2, 1.11.2, 1.12.2 have been released
