### ISSUE TITLE
[1.12.2 - 0.6.2] Crash on startup

### ISSUE THREAD

**Issue by HydrogenC** [MJRLegends/ExtraPlanets#518]
---- Minecraft Crash Report ----
// My bad.

Time: 2020-01-15 20:36:07 CST
Description: Initializing game

net.minecraftforge.fml.common.LoaderException: extraplanets Failed load class: com.mjr.extraplanets.ExtraPlanets
    at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:544)
    at sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
    at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:595)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
    at net.minecraft.client.Minecraft.init(Minecraft.java:467)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3931)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: com.mjr.extraplanets.ExtraPlanets
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at net.minecraftforge.fml.common.ModClassLoader.loadClass(ModClassLoader.java:75)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:348)
    at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:539)
    ... 35 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 6
    at org.objectweb.asm.ClassReader.readShort(Unknown Source)
    at org.objectweb.asm.ClassReader.<init>(Unknown Source)
    at org.objectweb.asm.ClassReader.<init>(Unknown Source)
    at net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper.findAndMergeSuperMaps(FMLDeobfuscatingRemapper.java:425)
    at net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper.getMethodMap(FMLDeobfuscatingRemapper.java:402)
    at net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper.mapMethodName(FMLDeobfuscatingRemapper.java:349)
    at org.objectweb.asm.commons.RemappingMethodAdapter.doVisitMethodInsn(Unknown Source)
    at org.objectweb.asm.commons.RemappingMethodAdapter.visitMethodInsn(Unknown Source)
    at org.objectweb.asm.ClassReader.a(Unknown Source)
    at org.objectweb.asm.ClassReader.b(Unknown Source)
    at org.objectweb.asm.ClassReader.accept(Unknown Source)
    at org.objectweb.asm.ClassReader.accept(Unknown Source)
    at net.minecraftforge.fml.common.asm.transformers.DeobfuscationTransformer.transform(DeobfuscationTransformer.java:76)
    at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
    ... 41 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Mac OS X (x86_64) version 10.14.6
  Java Version: 1.8.0_221, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 3054001208 bytes (2912 MB) / 3640655872 bytes (3472 MB) up to 4412407808 bytes (4208 MB)
  JVM Flags: 10 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx4200m
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_F4 142 mods loaded, 142 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID                                | Version                      | Source                                                         | Signature                                |
       |:----- |:--------------------------------- |:---------------------------- |:-------------------------------------------------------------- |:---------------------------------------- |
       | LC    | minecraft                         | 1.12.2                       | minecraft.jar                                                  | None                                     |
       | LC    | mcp                               | 9.42                         | minecraft.jar                                                  | None                                     |
       | LC    | FML                               | 8.0.99.99                    | forge-1.12.2-14.23.5.2847.jar                                  | None                                     |
       | LC    | forge                             | 14.23.5.2847                 | forge-1.12.2-14.23.5.2847.jar                                  | None                                     |
       | LC    | micdoodlecore                     |                              | minecraft.jar                                                  | None                                     |
       | LC    | openmodscore                      | 0.12.2                       | minecraft.jar                                                  | None                                     |
       | LC    | foamfixcore                       | 7.7.4                        | minecraft.jar                                                  | None                                     |
       | LC    | obfuscate                         | 0.2.6                        | minecraft.jar                                                  | None                                     |
       | LC    | splan                             | 2.65                         | minecraft.jar                                                  | None                                     |
       | LC    | WarpDriveCore                     | 1.12.2-1.5.12.SNAPSHOT       | minecraft.jar                                                  | None                                     |
       | LC    | randompatches                     | 1.12.2-1.20.1.0              | randompatches-1.12.2-1.20.1.0.jar                              | None                                     |
       | LC    | actuallyadditions                 | 1.12.2-r151                  | ActuallyAdditions-1.12.2-r151-2.jar                            | None                                     |
       | LC    | forgelin                          | 1.8.4                        | Forgelin-1.8.4.jar                                             | None                                     |
       | LC    | alib                              | 1.0.12                       | alib-1.0.12.jar                                                | None                                     |
       | LC    | crafttweaker                      | 4.1.19                       | CraftTweaker2-1.12-4.1.19.jar                                  | None                                     |
       | LC    | alchemistry                       | 1.0.36                       | alchemistry-1.0.36.jar                                         | None                                     |
       | LC    | redstoneflux                      | 2.1.0                        | RedstoneFlux-1.12-2.1.0.6-universal.jar                        | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LC    | cofhcore                          | 4.6.3                        | CoFHCore-1.12.2-4.6.3.27-universal.jar                         | None                                     |
       | LC    | craftstudioapi                    | 1.0.0                        | CraftStudioAPI-universal-1.0.1.95-mc1.12-alpha.jar             | None                                     |
       | LC    | twilightforest                    | 3.10.1013                    | twilightforest-1.12.2-3.10.1013-universal.jar                  | None                                     |
       | LC    | animania                          | 1.7.3                        | animania-1.12.2-1.7.3.jar                                      | None                                     |
       | LC    | anvilpatch                        | 1.0.0                        | anvilpatch-1.0.0.jar                                           | None                                     |
       | LC    | bdlib                             | 1.14.3.12                    | bdlib-1.14.3.12-mc1.12.2.jar                                   | None                                     |
       | LC    | codechickenlib                    | 3.2.3.358                    | CodeChickenLib-1.12.2-3.2.3.358-universal.jar                  | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LC    | cofhworld                         | 1.3.1                        | CoFHWorld-1.12.2-1.3.1.7-universal.jar                         | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LC    | ctgui                             | 1.0.0                        | CraftTweaker2-1.12-4.1.19.jar                                  | None                                     |
       | LC    | endertweaker                      | 1.2.0                        | EnderTweaker-1.12.2-1.2.0.jar                                  | None                                     |
       | LC    | mtlib                             | 3.0.6                        | MTLib-3.0.6.jar                                                | None                                     |
       | LC    | modtweaker                        | 4.0.17                       | modtweaker-4.0.17.jar                                          | None                                     |
       | LC    | jei                               | 4.15.0.293                   | jei_1.12.2-4.15.0.293.jar                                      | None                                     |
       | LC    | crafttweakerjei                   | 2.0.3                        | CraftTweaker2-1.12-4.1.19.jar                                  | None                                     |
       | LC    | cucumber                          | 1.1.3                        | Cucumber-1.12.2-1.1.3.jar                                      | None                                     |
       | LC    | cyclicmagic                       | 1.19.19                      | Cyclic-1.12.2-1.19.19.jar                                      | None                                     |
       | LC    | endercore                         | 1.12.2-0.5.73                | EnderCore-1.12.2-0.5.73.jar                                    | None                                     |
       | LC    | thermalfoundation                 | 2.6.3                        | ThermalFoundation-1.12.2-2.6.3.27-universal.jar                | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LC    | thermalexpansion                  | 5.5.4                        | ThermalExpansion-1.12.2-5.5.4.43-universal.jar                 | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LC    | enderio                           | 5.1.55                       | EnderIO-1.12.2-5.1.55.jar                                      | None                                     |
       | LC    | enderiointegrationtic             | 5.1.55                       | EnderIO-1.12.2-5.1.55.jar                                      | None                                     |
       | LC    | enderiobase                       | 5.1.55                       | EnderIO-1.12.2-5.1.55.jar                                      | None                                     |
       | LC    | enderioconduits                   | 5.1.55                       | EnderIO-1.12.2-5.1.55.jar                                      | None                                     |
       | LC    | enderioconduitsappliedenergistics | 5.1.55                       | EnderIO-1.12.2-5.1.55.jar                                      | None                                     |
       | LC    | enderioconduitsopencomputers      | 5.1.55                       | EnderIO-1.12.2-5.1.55.jar                                      | None                                     |
       | LC    | refinedstorage                    | 1.6.15                       | refinedstorage-1.6.15.jar                                      | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
       | LC    | enderioconduitsrefinedstorage     | 5.1.55                       | EnderIO-1.12.2-5.1.55.jar                                      | None                                     |
       | LC    | enderiointegrationforestry        | 5.1.55                       | EnderIO-1.12.2-5.1.55.jar                                      | None                                     |
       | LC    | enderiointegrationticlate         | 5.1.55                       | EnderIO-1.12.2-5.1.55.jar                                      | None                                     |
       | LC    | ftblib                            | 5.4.4.5                      | FTBLib-5.4.4.5.jar                                             | None                                     |
       | LC    | enderiomachines                   | 5.1.55                       | EnderIO-1.12.2-5.1.55.jar                                      | None                                     |
       | LC    | enderiopowertools                 | 5.1.55                       | EnderIO-1.12.2-5.1.55.jar                                      | None                                     |
       | LC    | enderioendergy                    | 5.1.55                       | EnderIO-endergy-1.12.2-5.1.55.jar                              | None                                     |
       | LC    | enderstorage                      | 2.4.6.137                    | EnderStorage-1.12.2-2.4.6.137-universal.jar                    | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LC    | energyconverters                  | 1.3.6.24                     | energyconverters_1.12.2-1.3.6.24.jar                           | None                                     |
       | LC    | valkyrielib                       | 1.12.2-2.0.20.1              | valkyrielib-1.12.2-2.0.20.1.jar                                | None                                     |
       | LC    | environmentalmaterials            | @EM_VERSION@                 | environmentalmaterials-1.12.2-1.0.20.1.jar                     | None                                     |
       | LC    | environmentaltech                 | 1.12.2-2.0.20.1              | environmentaltech-1.12.2-2.0.20.1.jar                          | None                                     |
       | LC    | etlunar                           | 1.12.2-2.0.20.1              | etlunar-1.12.2-2.0.20.1.jar                                    | None                                     |
       | LC    | galacticraftcore                  | 4.0.2.243                    | GalacticraftCore-1.12.2-4.0.2.243.jar                          | None                                     |
       | LC    | galacticraftplanets               | 4.0.2.243                    | Galacticraft-Planets-1.12.2-4.0.2.243.jar                      | None                                     |
       | LC    | mjrlegendslib                     | 1.12.2-1.1.9                 | MJRLegendsLib-1.12.2-1.1.9.jar                                 | b02331787272ec3515ebe63ecdeea0d746653468 |
       | LE    | extraplanets                      | 1.12.2-0.6.2                 | ExtraPlanets-1.12.2-0.6.2.jar                                  | None                                     |
       | L     | zerocore                          | 1.12.2-0.1.2.8               | zerocore-1.12.2-0.1.2.8.jar                                    | None                                     |
       | L     | bigreactors                       | 1.12.2-0.4.5.67              | ExtremeReactors-1.12.2-0.4.5.67.jar                            | None                                     |
       | L     | fluxnetworks                      | 4.0.14                       | fluxnetworks-1.12.2-4.0.14-31.jar                              | None                                     |
       | L     | foamfix                           | 0.10.10-1.12.2               | foamfix-0.10.10-1.12.2.jar                                     | None                                     |
       | L     | forgemultipartcbe                 | 2.6.2.83                     | ForgeMultipart-1.12.2-2.6.2.83-universal.jar                   | None                                     |
       | L     | microblockcbe                     | 2.6.2.83                     | ForgeMultipart-1.12.2-2.6.2.83-universal.jar                   | None                                     |
       | L     | minecraftmultipartcbe             | 2.6.2.83                     | ForgeMultipart-1.12.2-2.6.2.83-universal.jar                   | None                                     |
       | L     | ftbutilities                      | 5.4.0.124                    | FTBUtilities-5.4.0.124.jar                                     | None                                     |
       | L     | mcmultipart                       | 2.5.3                        | MCMultiPart-2.5.3.jar                                          | None                                     |
       | L     | mekanism                          | 1.12.2-9.8.3.390             | Mekanism-1.12.2-9.8.3.390.jar                                  | None                                     |
       | L     | gasconduits                       | 1.12.2-1.2.1                 | GasConduits-1.12.2-1.2.2.jar                                   | None                                     |
       | L     | advgenerators                     | 0.9.20.12                    | generators-0.9.20.12-mc1.12.2.jar                              | None                                     |
       | L     | mts                               | 15.9.1                       | Immersive+Vehicles-1.12.2-15.9.1.jar                           | None                                     |
       | L     | immersiveengineering              | 0.12-92                      | ImmersiveEngineering-0.12-92.jar                               | None                                     |
       | L     | unuparts                          | 3.0.0                        | UNU+Parts+Pack+for+IE+[MTS]+[IR]+1.12.2-15.5.0-1.5.0-3.0.0.jar | None                                     |
       | L     | ivairlinerpack                    | 1.0.0                        | Golden+Airport+Pack+[Immersive-Vehicles]+0.2.2.jar             | None                                     |
       | L     | guideapi                          | 1.12-2.1.8-63                | Guide-API-1.12-2.1.8-63.jar                                    | None                                     |
       | L     | cgm                               | 0.15.3                       | guns-0.15.3-1.12.2.jar                                         | None                                     |
       | L     | waila                             | 1.8.26                       | Hwyla-1.8.26-B41_1.12.2.jar                                    | None                                     |
       | L     | immersivepetroleum                | 1.1.9                        | immersivepetroleum-1.12.2-1.1.9.jar                            | None                                     |
       | L     | immersive_energy                  | 0.3.3                        | Immersive+Energy-0.3.3.jar                                     | None                                     |
       | L     | immersivecables                   | 1.3.2                        | ImmersiveCables-1.12.2-1.3.2.jar                               | None                                     |
       | L     | inventorytweaks                   | 1.63+release.109.220f184     | InventoryTweaks-1.63.jar                                       | None                                     |
       | L     | ironchest                         | 1.12.2-7.0.67.844            | ironchest-1.12.2-7.0.72.847.jar                                | None                                     |
       | L     | iv_tcp                            | 1.0.0                        | IV_Trin_Civil_Pack_(extended)_2.5.0.jar                        | None                                     |
       | L     | iv_tpp                            | 2.0.0                        | IV_Trin_Part_Pack_2.8.0.jar                                    | None                                     |
       | L     | jaopca                            | 1.12.2-2.2.8.103             | JAOPCA-1.12.2-2.2.8.103.jar                                    | None                                     |
       | L     | oredictinit                       | 1.12.2-2.2.1.71              | JAOPCA-1.12.2-2.2.8.103.jar                                    | None                                     |
       | L     | journeymap                        | 1.12.2-5.5.6                 | journeymap-1.12.2-5.5.6.jar                                    | None                                     |
       | L     | jeid                              | 1.0.3-52                     | JustEnoughIDs-1.0.3-52.jar                                     | None                                     |
       | L     | justenoughreactors                | 1.1.3.61                     | JustEnoughReactors-1.12.2-1.1.3.61.jar                         | None                                     |
       | L     | malisiscore                       | 1.12.2-6.4.0                 | malisiscore-1.12.2-6.4.0.jar                                   | None                                     |
       | L     | malisisblocks                     | 1.12.2-6.1.0                 | malisisblocks-1.12.2-6.1.0.jar                                 | None                                     |
       | L     | malisisdoors                      | 1.12.2-7.3.0                 | malisisdoors-1.12.2-7.3.0.jar                                  | None                                     |
       | L     | mcjtylib_ng                       | 3.5.4                        | mcjtylib-1.12-3.5.4.jar                                        | None                                     |
       | L     | mekanismgenerators                | 1.12.2-9.8.3.390             | MekanismGenerators-1.12.2-9.8.3.390.jar                        | None                                     |
       | L     | mekanismtools                     | 1.12.2-9.8.3.390             | MekanismTools-1.12.2-9.8.3.390.jar                             | None                                     |
       | L     | minewatch                         | 3.13                         | Minewatch-1.12.X-3.13.jar                                      | None                                     |
       | L     | mousetweaks                       | 2.10                         | MouseTweaks-2.10-mc1.12.2.jar                                  | None                                     |
       | L     | mrtjpcore                         | 2.1.4.43                     | MrTJPCore-1.12.2-2.1.4.43-universal.jar                        | None                                     |
       | L     | mtsofficialpack                   | 13.0.0                       | MTS_Official_Pack_V13.jar                                      | None                                     |
       | L     | mysticalagriculture               | 1.7.5                        | MysticalAgriculture-1.12.2-1.7.5.jar                           | None                                     |
       | L     | mysticalagradditions              | 1.3.2                        | MysticalAgradditions-1.12.2-1.3.2.jar                          | None                                     |
       | L     | recipehandler                     | 0.13                         | NoMoreRecipeConflict-0.13(1.12.2).jar                          | None                                     |
       | L     | nuclearcraft                      | 2.18o                        | NuclearCraft-2.18o-1.12.2.jar                                  | None                                     |
       | L     | omlib                             | 3.1.3-246                    | omlib-1.12.2-3.1.3-246.jar                                     | None                                     |
       | L     | ompd                              | 3.1.0-61                     | ompd-1.12.2-3.1.0-61.jar                                       | None                                     |
       | L     | openmods                          | 0.12.2                       | OpenModsLib-1.12.2-0.12.2.jar                                  | None                                     |
       | L     | openblocks                        | 1.8.1                        | OpenBlocks-1.12.2-1.8.1.jar                                    | None                                     |
       | L     | openmodularturrets                | 3.1.4-356                    | openmodularturrets-1.12.2-3.1.4-356.jar                        | None                                     |
       | L     | oreexcavation                     | 1.4.143                      | OreExcavation-1.4.143.jar                                      | None                                     |
       | L     | overloaded                        | 0.0.58                       | Overloaded-1.12.2-0.0.58.jar                                   | None                                     |
       | L     | projecte                          | 1.12.2-PE1.4.1               | ProjectE-1.12.2-PE1.4.1.jar                                    | None                                     |
       | L     | quickleafdecay                    | 1.2.4                        | QuickLeafDecay-MC1.12.1-1.2.4.jar                              | None                                     |
       | L     | redstonearsenal                   | 2.6.3                        | RedstoneArsenal-1.12.2-2.6.3.18-universal.jar                  | None                                     |
       | L     | redstonepaste                     | 1.7.5                        | redstonepaste-mc1.12-1.7.5.jar                                 | None                                     |
       | L     | redstonerepository                | 1.3.2                        | RedstoneRepository-1.12.2-1.4.0-dev-universal.jar              | None                                     |
       | L     | refinedexchange                   | 2.1.1                        | refinedexchange-2.1.1.jar                                      | None                                     |
       | L     | refinedstorageaddons              | 0.4.4                        | refinedstorageaddons-0.4.4.jar                                 | None                                     |
       | L     | rsinfinitewireless                | 1.2                          | rsinfinitewireless-1.2.jar                                     | None                                     |
       | L     | silentlib                         | 3.0.13                       | SilentLib-1.12.2-3.0.13+167.jar                                | None                                     |
       | L     | scalinghealth                     | 1.3.37                       | ScalingHealth-1.12.2-1.3.42+147.jar                            | None                                     |
       | L     | thermaldynamics                   | 2.5.5                        | ThermalDynamics-1.12.2-2.5.5.21-universal.jar                  | None                                     |
       | L     | simplyjetpacks                    | 2.2.14.67                    | SimplyJetpacks2-1.12.2-2.2.14.67.jar                           | None                                     |
       | L     | stellarfluidconduits              | 1.12.2-1.0.0                 | stellarfluidconduit-1.12.2-1.0.2a.jar                          | None                                     |
       | L     | thermalcultivation                | 0.3.3                        | ThermalCultivation-1.12.2-0.3.3.12-universal.jar               | None                                     |
       | L     | thermalinnovation                 | 0.3.3                        | ThermalInnovation-1.12.2-0.3.3.12-universal.jar                | None                                     |
       | L     | timehud                           | 7.3.1                        | TimeHUD-1.12.2-7.3.1.jar                                       | None                                     |
       | L     | torcherino                        | 7.6                          | torcherino-7.6.jar                                             | None                                     |
       | L     | unucivil                          | 3.0.0                        | UNU+Civilian+Vehicles+[MTS]+[IR]+1.12.2-15.5.0-1.5.0-3.0.0.jar | None                                     |
       | L     | universalmodifiers                | 1.12.2-1.0.16.1              | valkyrielib-1.12.2-2.0.20.1.jar                                | None                                     |
       | L     | vanillafix                        | 1.1.1-138                    | VanillaFix-1.1.1-138.jar                                       | None                                     |
       | L     | viewemc                           | v8                           | ViewEMC-1.12.2-v8.jar                                          | None                                     |
       | L     | wanionlib                         | 1.12.2-2.4                   | WanionLib-1.12.2-2.4.jar                                       | None                                     |
       | L     | warpdrive                         | 1.12.2-1.5.12.SNAPSHOT       | WarpDrive-1.12.2-1.5.12.jar                                    | None                                     |
       | L     | wawla                             | 2.5.273                      | Wawla-1.12.2-2.5.273.jar                                       | None                                     |
       | L     | worldedit                         | 6.1.10-SNAPSHOT              | worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist.jar              | None                                     |
       | L     | worldeditcuife2                   | 2.1.2-mf-1.12.2-14.23.5.2768 | WorldEdit-CUI-Forge-Edition-2-2.1.2-mf-1.12.2-14.23.5.2768.jar | None                                     |
       | L     | phosphor-lighting                 | 1.12.2-0.2.6                 | phosphor-1.12.2-0.2.6+build50-universal.jar                    | None                                     |
       | L     | reauth                            | 3.6.0                        | reauth-3.6.0.jar                                               | None                                     |
       | L     | unidict                           | 1.12.2-2.9.3                 | UniDict-1.12.2-2.9.3.jar                                       | None                                     |
       | L     | wrapup                            | 1.12-1.1.3                   | WrapUp-1.12-1.1.3.jar                                          | None                                     |
  Loaded coremods (and transformers): MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.243.jar)
                                        micdoodle8.mods.miccore.MicdoodleTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.1.1-138.jar)
                                        
                                      ForgelinPlugin (Forgelin-1.8.4.jar)
                                        
                                      MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
                                        mekanism.coremod.KeybindingMigrationHelper
                                      RandomPatches (randompatches-1.12.2-1.20.1.0.jar)
                                        com.therandomlabs.randompatches.core.RPTransformer
                                      OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
                                        openmods.core.OpenModsClassTransformer
                                      JustEnoughIDs Extension Plugin (JustEnoughIDs-1.0.3-52.jar)
                                        org.dimdev.jeid.JEIDTransformer
                                      ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
                                        com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
                                      ServerPropertiesLAN (ServerPropertiesLAN-2.65.jar)
                                        JaideepSinghHeer.Minecraft.mod.SPLANtransformerPort
                                      EnderCorePlugin (EnderCore-1.12.2-0.5.73-core.jar)
                                        com.enderio.core.common.transform.EnderCoreTransformer
                                        com.enderio.core.common.transform.SimpleMixinPatcher
                                      IELoadingPlugin (ImmersiveEngineering-core-0.12-92.jar)
                                        blusunrize.immersiveengineering.common.asm.IEClassTransformer
                                      NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
                                        net.fybertech.nwr.NWRTransformer
                                      MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
                                        
                                      Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
                                        invtweaks.forge.asm.ContainerTransformer
                                      PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50-universal.jar)
                                        
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.10-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      WarpDriveCore (WarpDrive-1.12.2-1.5.12.jar)
                                        cr0s.warpdrive.core.ClassTransformer
  GL info: ' Vendor: 'Intel Inc.' Version: '2.1 INTEL-12.10.14' Renderer: 'Intel(R) Iris(TM) Graphics 6100'
  OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:FINISHED],[horse_null_fix:FINISHED]
  Suspected Mods: Unknown
  Launched Version: HMCL 3.2.130
  LWJGL: 2.9.2
  OpenGL: Intel(R) Iris(TM) Graphics 6100 GL version 2.1 INTEL-12.10.14, Intel Inc.
  GL Caps: VboRegions not supported, missing: OpenGL 1.3, ARB_copy_buffer
           Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: 
  Current Language: 简体中文 (中国)
  Profiler Position: N/A (disabled)
  CPU: 4x Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz

**Comment by MJRLegends** [comment]
Fill out the issue template and repost thx
