### ISSUE TITLE
ExtraPlanents Worldgen crashing Project Ozone 2 Server

### ISSUE THREAD

**Issue by BlackenedHeaven** [MJRLegends/ExtraPlanets#52]
Hey was told by the galacticraft mod dev to get ahold of you about my issue. 
so the issue im having on my Project Ozone 2 server is that when ever someone goes to generate terrain on Uranus it will crash my server. This has happened twice now both when there were two people on Uranus moving in different directions and with only one person flying trying to find the dungeon. Im running the most recent version of both the modpack and the mod it self.
 
ive noticed this line in the crash report, seems to point towards igloos on Uranus. 
at com.mjr.**extraplanets**.worldGen.features.WorldGenIgloo.func_76484_a(WorldGenIgloo.java:91)
at com.mjr.**extraplanets**.planets.Uranus.worldgen.BiomeDecoratorUranus.decorate (BiomeDecoratorUranus.java:90)
 
Here is a link to my crash file: https://www.dropbox.com/s/uyfo9opogmdr9uv/crash-2016-11-29_06.04.37-server.txt?dl=0

**Comment by MJRLegends** [comment]
Use pastebin.com for the crash log

**Comment by BlackenedHeaven** [comment]
http://pastebin.com/emaV0u7c sorry about that. heres the pastebin link.

**Comment by BlackenedHeaven** [comment]
Just did a little more testing on this, the crash dosnt happen once i take opis and mobiuscore out of my pack. seems that is causing the crash to happen.

**Comment by MJRLegends** [comment]
Update for my addon (v1.0 Pre-3.7.6) is out
