### ISSUE TITLE
Missing the moon for Overworld in 1.12.2 

### ISSUE THREAD

**Issue by wivallius** [MJRLegends/ExtraPlanets#521]
Hi, 
Im currently running "The 1.12.2 Pack" and when I use my Tier 1 rocket to go to the moon the moon is not visible around "Overworld". I simply cant choose to go to the moon when in space.
I could build my Space Station but still after this and several restarts of the game the moon is still not visible.

Thankful for any help :)

**Comment by MJRLegends** [comment]
Yea you need to research them, its part of the mod called Planet Progressions which is in that pack your playing

**Comment by wivallius** [comment]
TY MJRLegends for your fast response, I will test tomorrow :)
