### ISSUE TITLE
Galacticraft bug

### ISSUE THREAD

**Issue by Nyone123** [MJRLegends/ExtraPlanets#524]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

### Description of Issue
Stucking on "taking one giant leap" screen. Before i was trying to do it on singleplayer and it was bugged too, when I found out that Galaxy Space is causing this error i deleted it from mods and config then everything was fine and on singleplayer i can go to the moon properly without this screen but then i did the same on my server (deleted GalaxySpace from mods and config) but on server this bug is still alive

### Steps to Reproduce Issue
1. [Launch minecraft]
2. [Just go to the moon]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]

There is no crash log

**Screenshots (if applicable):** 

https://imgur.com/a/6cPhulh

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]

ExtraPlanets-1.12.2-0.6.2
GalacticraftCore-1.12.2-4.0.2.244
Galacticraft-Planets-1.12.2-4.0.2.244
AsmodeusCore-1.12.2-0.0.12
MJRLegendsLib-1.12.2-1.1.9

**Where did this bug happen:** [Single Player or Server]
Server
### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Please can you try without AsmodeusCore

**Comment by Nyone123** [comment]
But on singleplayer i can do it with AsmodeusCore, i guess is something with logs or files idk in another folders like server trying to load some files from GalaxySpace but i removed it so minecraft dont know what to do

**Comment by MJRLegends** [comment]
Please just try without AsmodeusCore

**Comment by Nyone123** [comment]
Okay, gonna try

**Comment by Nyone123** [comment]
Okay evertyhing is fine now i guess, thank u very much

**Comment by Nyone123** [comment]
Whatever, sometimes is ok and i can land on moon properly and sometimes i still have this screen "taking one giant leap"
Also my thermal protection was ok when i could land on moon without this screen, but when i got the screen i can see on my server console i died coz of wrong thermal protection

**Comment by MJRLegends** [comment]
Ok i think this a non ExtraPlanets issue anyways, glad you got it working :P
