### ISSUE TITLE
Everytime i try to open the galaxy map the game crashes 1.12.2 PLS HELP!

### ISSUE THREAD

**Issue by DavidThatGamed** [MJRLegends/ExtraPlanets#526]
### ---Issue Report--
galaxy map error
### Description of Issue
game crashes when i open the galaxy map, so i cant even go to space :(
### Steps to Reproduce Issue
1. my modpack needs to be downloaded to reproduce the problem, the mods from it can be found in the crash-log i think.
2. start the game, create a new world and try to open the galaxy map

**Crash log/Log: https://paste.dimdev.org/kivayalana.mccrash

**Screenshots: cant

**Versions of Mods: ExtraPlanets: 0.6.2, GC Core and Planets: 4.0.2.239, MJRLegendsLib: 1.1.9

**Where did this bug happen: Single Player

### Additional Information
the crash log starts by saying disable NewGalaxyMap in asmodeus core config, but there is no config for asmodeus core v0.0.12, and the crash said that extra planets, mjrlegendslib and gc core were causing this problem.

I really hope you can help, because i cant do anything

**Comment by MJRLegends** [comment]
the crash log tells you what the issue is already. 

`java.lang.RuntimeException: Please disable the following option: enableNewGalaxyMap in configs/AsmodeusCore/core.conf`

**Comment by MJRLegends** [comment]
If you need any more help follow https://docs.mjrlegends.com/ExtraPlanets/1.12.2compact/#galaxyspace-all-versions

**Comment by DavidThatGamed** [comment]
ive searched through similar issues and none of them were helping me

**Comment by DavidThatGamed** [comment]
oh yes it does say it but how do i find the config, it is not in the game itself, so how do i find the config then?

**Comment by DavidThatGamed** [comment]
ok ill try that

**Comment by DavidThatGamed** [comment]
oh lol sorry, just always when i try to open these paper looking icons it says "always use microsoft store for opening this kind of files?" and dont think that i should have clicked on "more" and select "notesbook" to change it. omg how dumb could i be? thanks for that, i normally figure out things pretty fast but not this time ;) thanks, bye

**Comment by DavidThatGamed** [comment]
https://paste.dimdev.org/oboxugihib.mccrash now it crashes help

**Comment by MJRLegends** [comment]
yea you didnt do step 3 https://docs.mjrlegends.com/ExtraPlanets/1.12.2compact/#step-3

**Comment by DavidThatGamed** [comment]
sorry i get so many errors, thanks!
