### ISSUE TITLE
well i need some help here with the config 

### ISSUE THREAD

**Issue by DavidThatGamed** [MJRLegends/ExtraPlanets#530]
### ---Issue Report---
pressure and radiation config

**Have you checked Closed Issues: none are like mine

### Description of Issue
im trying to add the nano armor and quantum armor from industrial craft 2 to count as a tier 4 space suit, i tried pultiple times but nothing worked

### Additional Information
so can u help me because, example: <ic2:quantum_helmet:4 ic2:nano_helmet:3> but what do i type in between the items, because no matter how i type it, it dosent save it in the config because its wrong i think so can u help me with that please, i cant find any other place where i can see how i do it

**Comment by MJRLegends** [comment]
Please join our discord for this kinda of help https://discord.mjrlegends.com
