### ISSUE TITLE
Invalid thermal protection on the Moon -115°C

### ISSUE THREAD

**Issue by lukashoracek** [MJRLegends/ExtraPlanets#531]
### ---Issue Report---
**Have you checked Closed Issues:** Yes, probably the same as https://github.com/MJRLegends/ExtraPlanets/issues/348. The #347 issue has been deleted.

### Description of Issue
So when I go to the Moon, I start dying because of invalid thermal protection. It says its -115°C on the Moon. With tier 4 thermal protection (didn't test lower) I didn't die.

### Steps to Reproduce Issue
1. Go to the Moon (with equipment that should be enough?)
2. Start dying on the Moon because of the cold

**Crash log/Log:** 
Server log: https://pastebin.com/raw/S8Gp9s6X
Mod list (from latest crash log): https://pastebin.com/raw/JxP0DGGK

**Screenshots:**
![](https://cdn.discordapp.com/attachments/304609303912775681/688386317217824878/unknown.png)

**I ALSO WORE THE SUIT BOOTS ON THE MOON!**
![](https://cdn.discordapp.com/attachments/304609303912775681/688373344520765441/unknown.png)

**Version of Mod using:** 1.12.2-0.6.2

**Where did this bug happen:** Tested on server only

**Comment by MJRLegends** [comment]
Try remove ExtraPlanets and see if it still happens

**Comment by lukashoracek** [comment]
**All tested in singleplayer**
World generated with ExtraPlanets, using ExtraPlanets: Same result as what I get in multiplayer and also because it got stuck on loading screen (at least i thought so) on first generation, restarted minecraft and the Moon generation was weird.

World generated without ExtraPlanets, with or without ExtraPlanets: It just works like how it would without ExtraPlanets

**Comment by MJRLegends** [comment]
So does it work ok without ExtraPlanets?

**Comment by lukashoracek** [comment]
Yes, it does.

**Comment by MJRLegends** [comment]
Ok try with just ExtraPlanets and Galacticraft and no other mods

**Comment by lukashoracek** [comment]
So it seems like some mod is modifying it as you said before. Now, how do I know which mod modifies it?

It is now 0°C, it was -115°C with all mods.
![image](https://user-images.githubusercontent.com/26440060/76688378-678b5480-662c-11ea-978e-eeb8f57b0648.png)

**Comment by MJRLegends** [comment]
You will have to keep adding mods back to see when it breaks

**Comment by MJRLegends** [comment]
If you find out which mod causes it please let me know I'd like to debug this more

**Comment by lukashoracek** [comment]
So I found out DrZhark's Mo'Creatures Mod is changing it, no idea why.

**Comment by MJRLegends** [comment]
Ahh they seem to mess up everything as theres another issue in which they mess with travelling to the moon too. Please let them know there mod is buggy

**Comment by MJRLegends** [comment]
**Cause:** mocreatures uses -17 id for its dimension which is the uranus dimension in ExtraPlanets and thats causing weird issues. ID Conflicts in the past have never caused a issue like this. So i dont claim this issue with ExtraPlanets being at fault.

**Solution:** Change Dimension ID in config
