### ISSUE TITLE
need help debugging a instability between extra planets and galaxy space.

### ISSUE THREAD

**Issue by LordDnds** [MJRLegends/ExtraPlanets#532]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues **
yes

### Description of Issue
When I use extraplanets and galaxyspace it errors

### Steps to Reproduce Issue
1.Have extraplanets 1.12.2-0.6.2
2.Have galaxyspace 1.12.2-2.0.11

**Crash log/Log (if applicable):**
[crash-2020-03-16_01.57.12-client.txt](https://github.com/MJRLegends/ExtraPlanets/files/4337142/crash-2020-03-16_01.57.12-client.txt)

**Version of Mod using**
mjrlegends 1.12.2 1.1.9

**Where did this bug happen:**
singleplayer

### Additional Information
I messed around with mod combos and theses were to the two causing problems.
also is says multiple stations with id -31 but the only place that id exists is in galacticraft its self, and changing this value that there multi of just gives the same error but with the new id.

galacticraft plugins in use
AsmodeusCore-1.12.2-0.0.12
ExtraPlanets-1.12.2-0.6.2
GalacticraftCore-1.12.2-4.0.2.244
Galacticraft-Planets-1.12.2-4.0.2.244
GalaxySpace-1.12.2-2.0.11
MicdoodleCore-1.12.2-4.0.2.244
MJRLegendsLib-1.12.2-1.1.9
More-Planets-1.12.2-2.1.10-GC238
MorePlanetsExtras-1.12.2-1.0
SteveKunG's-Lib-1.12.2-1.1.5
ZollernGalaxy-1.12.2-v2.0.12

**Comment by MJRLegends** [comment]
https://docs.mjrlegends.com/ExtraPlanets/1.12.2compact/#galaxyspace-all-versions
