### ISSUE TITLE
[1.12.2] Space Stations/Satellites cause what appears to be a memory leak

### ISSUE THREAD

**Issue by windows-95-420** [MJRLegends/ExtraPlanets#533]
### ---Issue Report---

**Have you checked Closed Issues: Yes

### Description of Issue
Going to a space station causes rapid memory usage climbing. Forge crashes after memory usage reaches 100%.

### Steps to Reproduce Issue
1. Go to a space station.
2. Wait.
**Crash log/Log: The document linked didnt show how to find it on the vanilla launcher. There are a lot of what look like crash logs.

**Version of Mod using: 1.12.2-0.6.2

**Where did this bug happen:** Singleplayer and server.

### Additional Information
All planets seem to work fine with no problems. Space stations seem to cause issues. I can include all mods that I am using.

**Comment by MJRLegends** [comment]
Please do (after you think memory usage has increased) https://docs.mjrlegends.com/General%20Minecraft/profiling/ and post file here,

**Comment by velocityraptor-real** [comment]
My memory also is leaking, even with 5GB dedicatet to the system

**Comment by velocityraptor-real** [comment]
[12:03:02] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 4243ms behind, skipping 84 tick(s)
keeps spamming this until the game finaly crashes

**Comment by MJRLegends** [comment]
Thats not a memory leak dude that just your world has laggy stuff in

**Comment by velocityraptor-real** [comment]
no: flushing a full memory makes system overload

**Comment by velocityraptor-real** [comment]
here is more information/instructions to reproduce the issue:
Build a station around pluto and spend time building it.
System works perfectly fine for a while because there is enough spare memory to fill
Hit F3 to look at memory
Memory is filling up slowly
Game starts lagging very hardly when memory is flushing above 80%
Game crashes

**Comment by MJRLegends** [comment]
@velocityraptor-real Thats all great information but it doesnt help me with nothing... Do the following if you want to help

Please do (after you think memory usage has increased) https://docs.mjrlegends.com/General%20Minecraft/profiling/ and post file here,

**Comment by windows-95-420** [comment]
I have not been home recently but i will post the logs you have told me to soon. I am using Java 8 update 241 if it helps.

**Comment by MJRLegends** [comment]
Please do the profiling above as i cant do anything more without it

**Comment by windows-95-420** [comment]
> Please do the profiling above as i cant do anything more without it

I have since reinstalled windows and deleted the mods i had, but i will do my best to recreate the pack and get the data you need within the next 2 weeks.

**Comment by MJRLegends** [comment]
Ok i will close for now if you ever post profiling i will reopen

**Comment by kphoenix137** [comment]
In reference to my issue #961, my most recent crash said:
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (malloc) failed to allocate 1055616 bytes for Chunk::new
My RAM allocation was 12GB.
