### ISSUE TITLE
Spelling error in EP Settings under Items

### ISSUE THREAD

**Issue by Stiller90** [MJRLegends/ExtraPlanets#535]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes, and there is no closed issue of this, neither is there an open issue.
### Description of Issue
[Description of the issue]
The word Diamond in the Extraplanets config settings under "items" is spelled as "Diamomd" when it should be "Diamond".
### Steps to Reproduce Issue
1. [First step] Basically, just load up the latest version of EP in 1.12.2 and open up the mod's config settings.
2. [Second step] There isn't really a second step to this.

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/General%20Minecraft/crash-log/

**Screenshots (if applicable):** 
https://cdn.discordapp.com/attachments/495688158458019843/692053678923972608/2020-03-24_12.50.19.png
**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
1.12.2-0.6.2
**Where did this bug happen:** [Single Player or Server]
Probably both since it is in the config section, but this was singleplayer.
### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Updates for MC 1.8.9, 1.10.2, 1.11.2, 1.12.2 have been released
