### ISSUE TITLE
Decontamination unit has only one orientation

### ISSUE THREAD

**Issue by siber-cat1** [MJRLegends/ExtraPlanets#536]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes, none found.

### Description of Issue
The basic decontamination unit (as of 0.6.2) is a rectangular structure, with only one side that can be entered. It only opens to the south, no matter which way the player was facing when it was placed.

### Steps to Reproduce Issue
Place basic decontamination unit facing any cardinal direction other than north.

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/General%20Minecraft/crash-log/

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
0.6.2

**Where did this bug happen:** [Single Player or Server]
Server

### Additional Information
[Any other information that may be able to help me with the problem]
Bug encountered while playing Dungeons, Dragons and Space Shuttles version 7.2a/b

**Comment by MJRLegends** [comment]
Thats intended yea

**Comment by siber-cat1** [comment]
Can I get an explanation as to why the multiblock only facing one direction is intended behavior?

**Comment by MJRLegends** [comment]
Yea, its because im unable to make it not one direction due to how its made
