### ISSUE TITLE
Decontamination Unit scale in first person offhand too big

### ISSUE THREAD

**Issue by siber-cat1** [MJRLegends/ExtraPlanets#537]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes

### Description of Issue
Selecting the basic decontamination unit on your hot bar draws (what I am guessing) the full scale model of the chamber, blocking all vision while trying to place it.

### Steps to Reproduce Issue
1. Put basic decon unit on your hot bar
2. Select the slot it is in

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/General%20Minecraft/crash-log/

**Screenshots (if applicable):** 
https://imgur.com/WzI5Cg1.png

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
0.6.2

**Where did this bug happen:** [Single Player or Server]
Server

### Additional Information
[Any other information that may be able to help me with the problem]
Bug encountered in the mod pack Dungeons, Dragons and Space Shuttles, version 7.2a/b

**Comment by MJRLegends** [comment]
Lol thx will take a look

**Comment by MJRLegends** [comment]
Updates for MC 1.10.2, 1.11.2, 1.12.2 have been released
