### ISSUE TITLE
Why isn't the radiation/pressure system implemented in 1.7?

### ISSUE THREAD

**Issue by ghost** [MJRLegends/ExtraPlanets#538]
Hi! I was just wandering why pressure/radiation isn't a thing in 1.7.10 . Is there something that 1.7 libs don't provide, that is needed for that system to work, or is it something else?
I really want that feature. Thought of implementing it myself, but i'd have to learn Java from scratch(wouldn't be too hard, because I am a competent c# programmer).
Could it be possible for it to be implemented in the future?
Thanks in advance!

**Comment by MJRLegends** [comment]
Because 1.7.10 so old why would i spend 50+ hours adding pressure and radiation system for it
