### ISSUE TITLE
Problem traveling to one planet within another

### ISSUE THREAD

**Issue by JuanJSAR** [MJRLegends/ExtraPlanets#539]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

### Description of Issue
[I have a problem trying to travel to the moon or some other planet within another.
When I use the command "/ dimensiontp" I can select the moon, but it stays loading indefinitely.
If I select another main planet it works correctly.]

### Steps to Reproduce Issue
1. [Launch minecraft]
2. [Try to go to any planet within another. Like the moon]

**Crash log/Log (if applicable):** [There is no crash log]

**Screenshots (if applicable):** 
https://i.imgur.com/k8UyPYi.png
https://i.imgur.com/92bYdeU.png
https://i.imgur.com/JcJnn7w.png
https://i.imgur.com/NSLR2PI.png

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** 
[1.12.2-forge1.12.2-14.23.5.2847
OptiFine_1.12.2_HD_U_E3
ExtraPlanets-1.12.2-0.6.3
GalacticraftCore-1.12.2-4.0.2.244
Galacticraft-Planets-1.12.2-4.0.2.244
MicdoodleCore-1.12.2-4.0.2.244]

**Where did this bug happen:** [Single Player]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
You got mo creatures mod installed?

**Comment by JuanJSAR** [comment]
Yes, I did not remember that I had it installed.
I removed it and the problem was fixed.
Do you know why? Couldn't you add compatibility?

**Comment by MJRLegends** [comment]
Its their issue sorry
