### ISSUE TITLE
[1.7.10] Kepler 22b Block Chiselable from Cobblestone

### ISSUE THREAD

**Issue by Wealthyturtle** [MJRLegends/ExtraPlanets#54]
### ---Issue Report---

**Have you checked Closed Issues (if applicable):** Yes
### Description of Issue
A Kepler 22b Block is Chiselable from Cobblestone.
Refer to Picture:
[http://i.imgur.com/5VN5E20.png](http://i.imgur.com/5VN5E20.png)

### Steps to Reproduce Issue
1. [First step] Install [Chisel - tterrag1098](https://mods.curse.com/mc-mods/minecraft/235279-chisel) (Version: 2.9.5.11)
2. [Second step] Go into NEI, and then Check the Uses of Cobblestone when Chiseling (Note: The Chisel Recipe being Shown in NEI May be Done by a NEI Addon, I'm Not Too Sure. Here's my Full Mod List: [https://minecraft.curseforge.com/projects/universal-interdimensional-escape](https://minecraft.curseforge.com/projects/universal-interdimensional-escape)

**Crash log/Log (if applicable):** N/A

**Version of Mod using:** 1.0-Pre-3.7.5
1.0-Pre-3.7.5

### Additional Information
None Unfortunately, I'm Clueless about this. (Also, You Should Probably Add en_US Localization for the Block)

**Comment by MJRLegends** [comment]
Not sure i can sort that without adding chisel support

**Comment by Wealthyturtle** [comment]
Did Another Mod Accidentally Add the Kepler 22b Block into the Chisel List?

**Comment by MJRLegends** [comment]
No chisel is detecting the ore dictionary on the block

**Comment by Wealthyturtle** [comment]
Yeah, in that case, you Probably Need to Add Chisel Support.

On the Side Note, Tier 10 Boosters, Rocket Engines, and Rocket Fins are Not Craftable (According to NEI)?

**Comment by MJRLegends** [comment]
"On the Side Note, Tier 10 Boosters, Rocket Engines, and Rocket Fins are Not Craftable (According to NEI)?" will be fixed in the next update

**Comment by MJRLegends** [comment]
Update for my addon (v1.0 Pre-3.7.6) is out

**Comment by MJRLegends** [comment]
@Wealthyturtle i will look in to the Chisel thing and see i can do anything for it

**Comment by Eufranio** [comment]
Remove the oreDict entry and put it in your own?

**Comment by MrEyeballs29** [comment]
Why not?
