### ISSUE TITLE
Galaxy Space Pluto compatibility issue.

### ISSUE THREAD

**Issue by DanielAntony201** [MJRLegends/ExtraPlanets#540]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

Yes, I don't think anyone adressed this issue.

### Description of Issue
[Description of the issue]

Seems like Pluto from GalaxySpace has some strange compatibility issues with Extra Planets. I can't remember what the Crash name specifically said but it said something about Kepler 22b biomes or something. I think it was trying to load Kepler 22b stuff into Pluto. I think it said this. I think I found it.

java.lang.ClassCastException: com.mjr.extraplanets.planets.Kepler22b.worldgen.biome.BiomeGenKepler22bDiamondPlains cannot be cast to galaxyspace.core.world.gen.GSBiomeGenBase

 Maybe it's a third party mod issue, but I couldn't figure out what was exactly causing it. That's why I need your help. I also hope you'll adress stuff if I manage to find other issues. Btw, I will be honest, I only use the last 3 compatibility options you put in. I just didn't want for blocks and items to be removed. Could that be the Issue? Let me know, please.

### Steps to Reproduce Issue
1. [First step]
Install GalaxySpace, use a tier 6(can also be from ExtraPlanets) rocket, launch into Pluto.
2. [Second step]
It will either crash immediately or after a few minutes of wondering through Pluto.
**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/General%20Minecraft/crash-log/

Here's the Crash Report.
https://pastebin.com/0RZMfYNP

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]

ExtraPlanets-1.7.10-2.1.3

**Where did this bug happen:** [Single Player or Server]

Singleplayer.

### Additional Information
[Any other information that may be able to help me with the problem]

I think I've told you everything in the first description. I hope the amount of mods aren't the cause of this issue. It's just that GalaxySpace Pluto is the only plan that had an issue, as far as I can tell. Other planets might have an issue too, but so far I've only deliberately checked Mercury, Mercury 2.0, Venus, Venus 2.0, Mars(But that was before GalaxySpace's installation(I think),The new Ceres(Can't remember the name, it wasn't even named correctly, I think), Eris, Kepler 22b, Proxima Centauri B. That's all the planets that I deliberately checked. I'll check the other ones, if you need me to. Because I really want to fix things. Modded minecraft is my favourite thing and it would be a bummer to know that I can't play it properly anymore. I hope you can figure out the Issue and I hope you haven't abandoned 1.7.10. It may be old, but it's still viable in my opinion.

**Comment by MJRLegends** [comment]
This is a Galaxyspace issue sorry i cant help you there

**Comment by DanielAntony201** [comment]
Should I adress the Galaxy Space Author for this?

**Comment by MJRLegends** [comment]
Ye as its their code on other dimensions than their own. They probably didnt think about other dimensions that would cause this code to fail

**Comment by DanielAntony201** [comment]
Hey, uh... can you help? There's one problem I want to ask you about. I want to know if the authors of that mod are lazy or if it's really unfixable. It's a rocket tier display issue.
![2020-04-17_17 54 22](https://user-images.githubusercontent.com/60870366/79632900-4cec5400-8173-11ea-9264-41179e8b3682.png)
![2020-04-17_17 54 41](https://user-images.githubusercontent.com/60870366/79632901-4eb61780-8173-11ea-9607-6ae5f8eb9ade.png)
![2020-04-17_17 54 48](https://user-images.githubusercontent.com/60870366/79632903-4f4eae00-8173-11ea-9a92-31321a60a1f8.png)
![2020-04-17_17 29 00](https://user-images.githubusercontent.com/60870366/79632905-4fe74480-8173-11ea-8322-66685259eb24.png)
![2020-04-17_17 29 03](https://user-images.githubusercontent.com/60870366/79632906-4fe74480-8173-11ea-8455-af8eb97f504e.png)
![2020-04-17_17 29 12](https://user-images.githubusercontent.com/60870366/79632908-507fdb00-8173-11ea-8041-5ac6a60c2588.png)
![2020-04-17_17 53 33](https://user-images.githubusercontent.com/60870366/79632909-51187180-8173-11ea-8eb4-93b7b184c3df.png)
![2020-04-17_17 53 38](https://user-images.githubusercontent.com/60870366/79632910-51187180-8173-11ea-9a11-d991e001414d.png)
![2020-04-17_17 54 08](https://user-images.githubusercontent.com/60870366/79632911-51b10800-8173-11ea-90bc-f6bcf27f3acf.png)

**Comment by DanielAntony201** [comment]
Can you help? it seemed like you're an experienced modder and that's why I'm asking for your help.
