### ISSUE TITLE
Game Crashes When Entering Electric Rocket

### ISSUE THREAD

**Issue by ghost** [MJRLegends/ExtraPlanets#541]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

### Description of Issue
Whenever I enter a tier 10 electric rocket, the game says "shutting down internal server..." and crashes. I have tested other rockets, and they all seem to work fine. I tried disabling all other mods except for galacticraft core, planets, crafttweaker, galacticraft tweaker and JEI as well as trying and older version of forge but the same crash happened.

### Steps to Reproduce Issue
1. Place down 5x5 square of powered rocket launch pads.
2. Place tier 10 electric rocket on launch pad.
3. Right click on rocket.

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/General%20Minecraft/crash-log/
https://pastebin.com/1CnuJXWZ
**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
1.12.2-0.6.3
**Where did this bug happen:** [Single Player or Server]
Single player and in creative mode.

**Comment by MJRLegends** [comment]
This is very strange crash please can you try with Galacticraft build 244

**Comment by ghost** [comment]
Using build 244 worked. Thank you.

**Comment by MJRLegends** [comment]
Ok i will need to find out what they changed and fix thx

**Comment by MJRLegends** [comment]
Ok i found the change that happened in GC build 250 & above. For time being use 250 & below in till update for ExtraPlanets v0.6.4 comes out later

**Comment by MJRLegends** [comment]
Update rolling out as we speak
