### ISSUE TITLE
Tier Infinite rocket

### ISSUE THREAD

**Issue by UniverseisaPixel** [MJRLegends/ExtraPlanets#543]
it can go to any planet (even non-2.0 gas giants, it makes its own small island) and to any galaxy, i really want to go to a star wars planet in minecraft.

**Comment by MJRLegends** [comment]
I dont be adding this sorry, ExtraPlanets has enough rockets already, plus as far as i know no other addon has more then a tier 10 planet so ExtraPlanets should already have 10 and below covered.
