### ISSUE TITLE
Can't modify settings in the game

### ISSUE THREAD

**Issue by MaxwellYe0815** [MJRLegends/ExtraPlanets#545]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING): Yes

### Description of Issue
I want to add conarm's armor to be considered as a spacesuit and modify some specific values of radiation. But mod settings cannot be changed in the game.
### Steps to Reproduce Issue
After the modification, I was prompted to restart the game. I closed the game (I tried to close it directly and the ‘Leave Game’ button), but when I opened it again, none of the settings were changed, as if someone clicked ‘Reset All Settings’.

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do I locate a crash log* see https://docs.mjrlegends.com/General%20Minecraft/crash-log/

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):Minecraft:1.12.2,ExtraPlanets:0.6.3,forge:1.12.2-14.23.5.2854

**Where did this bug happen: Single Player

### Additional Information
Strictly speaking, this is not a very serious bug, because I can directly modify the .cfg file, and such modification is effective.

**Comment by YlimazYe** [comment]
After reporting the bug, I saw the 0.6.4 update, which has been downloaded and replaced, Minecraft is opening, I will check if the problem still exists

**Comment by MJRLegends** [comment]
Please report to Galacticraft this also a issue with their ingame config changing for Galacticraft as well

**Comment by MJRLegends** [comment]
Should hopefully be fixed in MC 1.12.2 & 1.11.2, other versions will come later

**Comment by MJRLegends** [comment]
Updates are being released for MC 1.10.2. MC 1.8.9 wont be fixed for this
