### ISSUE TITLE
The server crash everytime i enter in Kepler 22B

### ISSUE THREAD

**Issue by PRROWIN** [MJRLegends/ExtraPlanets#547]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes, but I dont find a solution

### Description of Issue
[Description of the issue]
Everytime I enter to Kepler 22b, the server crash.
Sometimes I can move a few seconds, but it crash, whatever I do it always crash

### Steps to Reproduce Issue
1. [First step]
Go in my spaceship, tp or another way to enter
2. [Second step]
Enter to Kepler 22b

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.google.com/document/d/1qRq3RZa5yiZcflVF3plhh1C2OJWsTpDowXnes_tdLIE/edit?usp=sharing
**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
1.12.2-0.6.4

**Where did this bug happen:** [Single Player or Server] Server

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
They seem to show correctly for me?

**Comment by MJRLegends** [comment]
Thanks i will look at this

**Comment by MJRLegends** [comment]
Do you have discord account i can message you on over this?

**Comment by PRROWIN** [comment]
Yes, I have, is Erlm12#3056

**Comment by MJRLegends** [comment]
Added

**Comment by MJRLegends** [comment]
Temp fix:

ExtraPlanets config and set the following to false 
```
# Setting this option to false will disable & remove Big Trees from generating on Kepler22b
    B:"Generate Big Trees on Kepler22b"=false
```

**Comment by MJRLegends** [comment]
I've reported this to Galacticraft as its a problem with using vines in a world feature from biome decorator.

**Comment by MJRLegends** [comment]
https://github.com/micdoodle8/Galacticraft/issues/4018
