### ISSUE TITLE
Machines are not extracting remaining resources

### ISSUE THREAD

**Issue by kmccmk9** [MJRLegends/ExtraPlanets#548]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

### Description of Issue
I noticed the Smasher and Evaporation Chamber both exhibit the same issue. If you run them the items can be extracted automatically without issue. But, if there is no more "processing" happening within the machine, whatever is in the output slot will remain there unless the player manually grabs it. I've tested this with other mods for item transfer and vanilla item hopper.

### Steps to Reproduce Issue
1. Place a smasher on top of a item hopper
![image](https://user-images.githubusercontent.com/678335/81134960-67b91980-8f24-11ea-9802-37fcd6e3e296.png)
2. Insert 12 Potash into smasher and watch it run
![image](https://user-images.githubusercontent.com/678335/81135197-1b220e00-8f25-11ea-9087-97f9524f40fd.png)
![image](https://user-images.githubusercontent.com/678335/81135206-21b08580-8f25-11ea-8630-21978109335e.png)
3. When there is no remaining input Potash, but remaining output Potash Shards, the items are no longer extracted.
![image](https://user-images.githubusercontent.com/678335/81135009-90d9aa00-8f24-11ea-9acd-f7309901fa34.png)

NOTE: This can easily be reproduced with just inserting 1 Potash in an empty Smasher as well. 

It seems that once the process of smashing is done, it cannot pull the items out.

**Crash log/Log (if applicable):** [N/A]

**Screenshots (if applicable):** Added as part of the reproduction steps to help illustrate the issue.

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [1.12.2-0.6.2]

**Where did this bug happen:** [Server]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Update for MC 1.12.2 are rolling out now
