### ISSUE TITLE
Launch Pad Tier 2 not connecting to Launch Controller

### ISSUE THREAD

**Issue by MoonstreamJustNotInSpace** [MJRLegends/ExtraPlanets#551]
Just like the title says. I set up a launch controller, even attached a refueler to a Tier 2 Launch Pad. I can't launch it using a redstone signal (even after setting it) and the rocket always breaks the pad. Is there just a Tier 2 Controller I'm missing?

**Comment by MJRLegends** [comment]
This is a already open issue report #391
