### ISSUE TITLE
[Suggestion] Config Option to Disable Planets, But Not Their Moons

### ISSUE THREAD

**Issue by TwiliDiamondOcelot** [MJRLegends/ExtraPlanets#552]
Currently, you are able to disable travel to a planet, but in doing so will remove their moons and all related gear/items.

Say you want to disable "landing" on Jupiter, Saturn, Neptune, and Uranus, yet still travel to their  moons like Io, Titan, Triton, or Oberon. Right now, you can only disable planets, and all related moons, and not just a planet excluding it's moons.

For the dungeons, you could add a config to enable generation of a planet's dungeons on it's moons.

**Comment by MJRLegends** [comment]
I wont be adding sorry, things get very hacky trying to do this even more then adding addons.

Thank you for the suggestion tho
