### ISSUE TITLE
Weird Rocket Galacticraft API Crash with Tier 7 Rocket

### ISSUE THREAD

**Issue by DabbingEevee** [MJRLegends/ExtraPlanets#553]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
YES

### Description of Issue
attempting to land on Uranus 
### Steps to Reproduce Issue
go to uranus
get hit in the face with a crash

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/General%20Minecraft/crash-log/

[crash-2020-06-02_15.19.07-client.txt](https://github.com/MJRLegends/ExtraPlanets/files/4720036/crash-2020-06-02_15.19.07-client.txt)

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
ExtraPlanets-1.12.2-0.6.2
**Where did this bug happen:** [Single Player or Server]
Server
### Additional Information
https://www.dropbox.com/s/mk5zuw7824egc61/TSMP_1.4.1_1.zip?dl=0
modpack may be downloaded here

**Comment by MJRLegends** [comment]
Please post a crash log with latest version of the mod

**Comment by DabbingEevee** [comment]
[crash-2020-06-02_17.28.27-client.txt](https://github.com/MJRLegends/ExtraPlanets/files/4720311/crash-2020-06-02_17.28.27-client.txt)
ok i updated it

**Comment by MJRLegends** [comment]
I currently cant reproduce this issue, is there any more information you can give me like full logs and screenshots of the launch pad setup you used and any setups/cargo you added before launch

**Comment by ROMVoid95** [comment]
i had this same exact crash from when using Java 1.8.0_242, may not be the root cause but after reverting back to 241 at the time the crash never resurfaced. Also seen other issues with that java build and i cant see a reason whatever bugs in 242 couldn't extend to AdeptOpenJDK.

hope this info helps

**Comment by MJRLegends** [comment]
Does it happen with any other rockets

**Comment by MJRLegends** [comment]
Please report to Galacticraft as its their api code crashing..
