### ISSUE TITLE
Problems with defining armor as space suits

### ISSUE THREAD

**Issue by Erdragh** [MJRLegends/ExtraPlanets#554]
---Issue Report---

**Have you checked Closed Issues:** [Yes]

I have checked the one about the [EnderIO Endergy Stellar armor](https://github.com/MJRLegends/ExtraPlanets/issues/516), but I haven't installed that mod and I have looked through the forum for similar issues, but didn't find any solution.

### Description of Issue

I've just made a custom modpack for me and my friends with a lot of galacticraft addons, including extra planets. It also has a lot of other mods that are considered normal for tech modpacks, such as: enderIO and IC2. I went into the .cfg file for ExtraPlanets and edited the list for armor considered as space suits. Here it is:

S:"List of armour items to be considered as a space suit" <
        redstonearsenal:armor.helment_flux:3
        redstonearsenal:armor.plate_flux:3
        redstonearsenal:armor.legs_flux:3
        redstonearsenal:armor.boots_flux:3
        ic2:nano_boots:3
        ic2:nano_chestplate:3
        ic2:nano_helmet:3
        ic2:nano_leggins:3
        ic2:quantum_boots:4
        ic2:quantum_chestplate:4
        ic2:quantum_helmet:4
        ic2:quantum_leggins:4
        gravisuite:gravichestplate:4
        gravisuite:advancednanochestplate:3
        enderio:item_dark_steel_chestplate:3
        enderio:item_dark_steel_helmet:3
        enderio:item_dark_steel_leggins:3
        enderio:item_dark_steel_boots:3
        enderio:item_end_steel_chestplate:4
        enderio:item_end_steel_helmet:4
        enderio:item_end_steel_leggins:4
        enderio:item_end_steel_boots:4
        grimpack:anti_radiation_boots:1
        grimpack:anti_radiation_chest:1
        grimpack:anti_radiation_helmet:1
        grimpack:anti_radiation_legs:1
        advanced_solar_panels:ultimatesolarhelmet:4
        advanced_solar_panels:hybridsolarhelmet:4
        advanced_solar_panels:advancedsolarhelmet:3
     >

I tried the quantum suit, the dark and end steel armor, the nano suit and the flux infused armor. They all seem to not be working. I tested this on the moon: I went there in creative mode, suited up in the tier 4 space suit and went back into survival, to test if and how fast I would get radiation and/or pressure damage. With the space suit, pressure wasn't an issue and because of the radiation level of 3% on the moon I also didn't consume any radiation with the space suit. However I then went into creative mode again and suited myself up with the above mentioned armor sets. I died of pressure damage each time and also seemed to consume radiation (I drank multiple anti radiation drinks between the tests to make sure I started at 0).
After that I tried the anti radiation armor from grimpack and that seemed to work. I didn't get pressure damage and got as much radiation over time as I did with a tier 1 space suit on our survival server.

### Steps to Reproduce Issue

1. Install the mods that add the armor pieces in the list
2. Install Galacticraft together with ExtraPlanets
3. Edit the ExtraPlanets.cfg file and edit the list of armor pieces to be considered space suits to the above
4. Go onto any planet with a level of radiation other than 0%
5. Put on a valid oxygen setup and thermal protection
6. Put on an armor set that is in the list
7. Observe as it doesn't act like a space suit

**Screenshot:** 

https://imgur.com/a/rZVhjfO

**Version of Mod using:**

ExtraPlanets 0.6.4 for 1.12.2

**Where did this bug happen:** [Single Player]

I haven't changed the config files for the server yet, because I would have had to restart it. All testing was therefore made in a single player world.

### Additional Information

I speculate that the issue might be that the armor pieces that don't work are ones that require power, since the one that does work doesn't. However, I'm not a modder nor do I have experience with GalactiCraft addons so this is as said only speculation.

**Comment by MJRLegends** [comment]
Ok i've just tested this and it seems you just have some items names incorrectly entered in the config for example 

nano_leggins should be nano_leggings

Just for future thought i only check the registry name which is what you see in the item hidden tooltips feature such as the following

https://gyazo.com/24c3b2d38a503e95ccf88c7e591c7c2a
