### ISSUE TITLE
exposed to air blocks...

### ISSUE THREAD

**Issue by gunmaker** [MJRLegends/ExtraPlanets#555]
unkown blocks were generated Caused by: java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=basictypevenus, clazz=class micdoodle8.mods.galacticraft.planets.venus.blocks.BlockBasicVenus$EnumBlockBasicVenus, values=[ROCK_SOFT, ROCK_HARD, ROCK_MAGMA, ROCK_VOLCANIC_DEPOSIT, DUNGEON_BRICK_1, DUNGEON_BRICK_2, ORE_ALUMINUM, ORE_COPPER, ORE_GALENA, ORE_QUARTZ, ORE_SILICON, ORE_TIN, LEAD_BLOCK, ORE_SOLAR_DUST]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}

**Comment by MJRLegends** [comment]
Use the issue template

**Comment by gunmaker** [comment]
lol
