### ISSUE TITLE
Cargo Unloader Crash when placed next to Tier 2 or 3 Rocket Launch Pad without rocket

### ISSUE THREAD

**Issue by mape14** [MJRLegends/ExtraPlanets#556]
### ---Issue Report---
Cargo Unloader Crash when placed next to Tier 2 or 3 Rocket Launch Pad without a rocket.

On the other hand, Cargo Loader don't cause this problem.

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

### Description of Issue
Placing a Cargo Unloader next to a Tier 2 or Tier 3 Rocket Launch Pad without any rocket cause the game to crash. Also, if the Cargo Unloader is placed and the rocket lauch to the space, it crashes too. If the Cargo Unloader is placed in any other block that is not next to a Tier 2 or Tier 3 Rocket Launch Pad, the game does not crash. Also, in the Galacticraft Launch Pad, Cargo Unloader works perfectly.

### Steps to Reproduce Issue
1. Place a Tier 2 or Tier 3 Rocket Launch Pad 5x5 square.
2. Place a Cargo Unloader next to it.

**Crash log/Log (if applicable):** https://pastebin.com/fABKW5ZG
> *How do i locate a crash log* see https://docs.mjrlegends.com/General%20Minecraft/crash-log/

**Screenshots (if applicable):** -

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'): 1.12.2 - 0.6.4

**Where did this bug happen:** Single Player

### Additional Information
-

**Comment by MJRLegends** [comment]
Updates for MC 1.12.2 & 1.11.2 are rolling out now
