### ISSUE TITLE
Crashing with same space station and id.

### ISSUE THREAD

**Issue by TailowOfficial** [MJRLegends/ExtraPlanets#557]
[crash-2020-06-09_22.30.39-client.txt](https://github.com/MJRLegends/ExtraPlanets/files/4754809/crash-2020-06-09_22.30.39-client.txt)
So i get this error just when i try to start the game it's says that there is a double version of the space station and same id. This crash might be happening because i have other planet mods. The list over the mods is in the file. Please help i don't want to remove anything from my save.

**Comment by MJRLegends** [comment]
Use issue template for your issue report dont just delete it
