### ISSUE TITLE
Double Version Of A Space Station And Some Server Problems.

### ISSUE THREAD

**Issue by TailowMine** [MJRLegends/ExtraPlanets#559]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes I have
### Description of Issue
So basically when i try to start Minecraft my game crashes saying that i got two items with the name space station with the same id this might be because i have different planet mods added too though please help.

### Steps to Reproduce Issue
1. Install Extra Planets With Some Other Planet Mods For Example The Ones I Have More Planets, Extra Planets, Galaxy Space.
2. Launch Minecraft.

**Crash log/Log (if applicable):** 
[crash-2020-06-09_22.30.39-client.txt](https://github.com/MJRLegends/ExtraPlanets/files/4759505/crash-2020-06-09_22.30.39-client.txt)

**Screenshots (if applicable):** 
Sorry Don't Have Any
**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]

ExtraPlanets-1.12.2-0.6.4.jar
I use this one because i use twitch.
**Where did this bug happen:** [Single Player or Server]
Single Player When I Start Minecraft
### Additional Information
I don't have anymore information but i hope you can help.

**Comment by MJRLegends** [comment]
You just got to read and do what the crash log says

```
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Extra Planets (extraplanets)
Caused by: java.lang.RuntimeException: You have a double version of the same space station, station for planet ID: -31 You will most likely fix this by checking out compatibility guide over at https://docs.mjrlegends.com/ExtraPlanets/1.12.2compact/
	at
```
