### ISSUE TITLE
Crash while going in space

### ISSUE THREAD

**Issue by Atomivv** [MJRLegends/ExtraPlanets#561]
My game crash while going in space.
ISSUE:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.255.jar)
Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 6/17/20 12:07 PM
Description: Rendering screen

java.lang.NoSuchFieldError: ticksSinceSelectionF
	at com.mjr.extraplanets.client.gui.screen.CustomCelestialSelection.drawCustomButtons(CustomCelestialSelection.java:403)
	at com.mjr.extraplanets.client.gui.screen.CustomCelestialSelection.drawButtons(CustomCelestialSelection.java:445)
	at micdoodle8.mods.galacticraft.core.client.gui.screen.GuiCelestialSelection.func_73863_a(GuiCelestialSelection.java:1212)
	at com.mjr.extraplanets.client.gui.screen.CustomCelestialSelection.func_73863_a(CustomCelestialSelection.java:998)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:353)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.mjr.extraplanets.client.gui.screen.CustomCelestialSelection.drawCustomButtons(CustomCelestialSelection.java:403)
	at com.mjr.extraplanets.client.gui.screen.CustomCelestialSelection.drawButtons(CustomCelestialSelection.java:445)
	at micdoodle8.mods.galacticraft.core.client.gui.screen.GuiCelestialSelection.func_73863_a(GuiCelestialSelection.java:1212)
	at com.mjr.extraplanets.client.gui.screen.CustomCelestialSelection.func_73863_a(CustomCelestialSelection.java:998)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:353)

-- Screen render details --
Details:
	Screen name: com.mjr.extraplanets.client.gui.screen.CustomCelestialSelection
	Mouse location: Scaled: (341, 191). Absolute: (683, 384)
	Screen size: Scaled: (683, 384). Absolute: (1366, 768). Scale factor of 2

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [GCEntityClientPlayerMP['Atomiv'/1244, l='MpServer', x=-301.43, y=1203.10, z=245.00]]
	Chunk stats: MultiplayerChunkCache: 280, 280
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-248,64,192), Chunk: (at 8,4,0 in -16,12; contains blocks -256,0,192 to -241,255,207), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 3474 game time, 3474 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 35 total; [EntityItem['item.item.seeds'/5198, l='MpServer', x=-326.62, y=70.00, z=226.45], EntityItem['item.item.seeds'/6263, l='MpServer', x=-282.02, y=64.00, z=224.05], GCEntityClientPlayerMP['Atomiv'/1244, l='MpServer', x=-301.43, y=1203.10, z=245.00], EntityCelestialFake[''/13745, l='MpServer', x=-301.50, y=1203.45, z=245.50], EntityItem['item.item.seeds'/4724, l='MpServer', x=-252.13, y=63.00, z=249.34], EntityItem['item.item.seeds'/5802, l='MpServer', x=-256.94, y=63.00, z=256.44], EntityItem['item.item.seeds'/5804, l='MpServer', x=-274.77, y=63.00, z=206.13], EntitySheep['Sheep'/731, l='MpServer', x=-379.50, y=69.00, z=191.50], EntitySheep['Sheep'/732, l='MpServer', x=-374.57, y=70.00, z=195.28], EntitySheep['Sheep'/733, l='MpServer', x=-377.45, y=69.00, z=190.21], EntitySheep['Sheep'/740, l='MpServer', x=-375.50, y=66.00, z=219.50], EntitySheep['Sheep'/741, l='MpServer', x=-371.50, y=68.00, z=217.50], EntitySheep['Sheep'/742, l='MpServer', x=-372.50, y=67.00, z=220.50], EntitySheep['Sheep'/743, l='MpServer', x=-370.50, y=68.00, z=218.50], EntitySheep['Sheep'/744, l='MpServer', x=-378.58, y=64.00, z=266.13], EntitySheep['Sheep'/745, l='MpServer', x=-375.31, y=64.00, z=263.01], EntitySheep['Sheep'/746, l='MpServer', x=-371.50, y=64.00, z=261.50], EntitySheep['Sheep'/747, l='MpServer', x=-378.12, y=64.00, z=267.18], EntitySheep['Sheep'/756, l='MpServer', x=-351.50, y=71.00, z=223.50], EntitySheep['Sheep'/757, l='MpServer', x=-353.50, y=71.00, z=221.50], EntitySheep['Sheep'/758, l='MpServer', x=-352.50, y=71.00, z=222.50], EntitySheep['Sheep'/759, l='MpServer', x=-353.50, y=71.00, z=226.50], EntitySheep['Sheep'/760, l='MpServer', x=-345.50, y=71.00, z=235.50], EntitySheep['Sheep'/761, l='MpServer', x=-345.50, y=71.00, z=237.50], EntitySheep['Sheep'/762, l='MpServer', x=-346.50, y=71.00, z=237.50], EntitySheep['Sheep'/763, l='MpServer', x=-346.50, y=71.00, z=239.50], EntitySheep['Sheep'/782, l='MpServer', x=-301.50, y=67.00, z=165.50], EntitySheep['Sheep'/795, l='MpServer', x=-284.50, y=67.00, z=283.50], EntitySheep['Sheep'/796, l='MpServer', x=-283.50, y=67.00, z=283.50], EntitySheep['Sheep'/797, l='MpServer', x=-285.50, y=67.00, z=285.50], EntitySheep['Sheep'/798, l='MpServer', x=-284.50, y=67.00, z=287.50], EntitySheep['Sheep'/809, l='MpServer', x=-278.50, y=63.00, z=178.45], EntitySheep['Sheep'/810, l='MpServer', x=-279.49, y=63.00, z=180.80], EntitySheep['Sheep'/811, l='MpServer', x=-268.73, y=66.00, z=185.50], EntitySheep['Sheep'/812, l='MpServer', x=-278.50, y=63.00, z=179.43]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2748)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:418)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2887423312 bytes (2753 MB) / 4764729344 bytes (4544 MB) up to 6442450944 bytes (6144 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 48
	FML: MCP 9.42 Powered by Forge 14.23.1.2555 11 mods loaded, 11 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State           | ID                  | Version      | Source                                    | Signature                                |
	|:--------------- |:------------------- |:------------ |:----------------------------------------- |:---------------------------------------- |
	| UCHIJAAAAAAAAAA | minecraft           | 1.12.2       | minecraft.jar                             | None                                     |
	| UCHIJAAAAAAAAAA | mcp                 | 9.42         | minecraft.jar                             | None                                     |
	| UCHIJAAAAAAAAAA | FML                 | 8.0.99.99    | forge-1.12.2-14.23.1.2555.jar             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAAAAAAAA | forge               | 14.23.1.2555 | forge-1.12.2-14.23.1.2555.jar             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAAAAAAAA | micdoodlecore       |              | minecraft.jar                             | None                                     |
	| UCHIJAAAAAAAAAA | mercurius_updater   | 1.0          | MercuriusUpdater-1.12.2.jar               | None                                     |
	| UCHIJAAAAAAAAAA | galacticraftcore    | 4.0.2.255    | GalacticraftCore-1.12.2-4.0.2.255.jar     | None                                     |
	| UCHIJAAAAAAAAAA | galacticraftplanets | 4.0.2.255    | Galacticraft-Planets-1.12.2-4.0.2.255.jar | None                                     |
	| UCHIJAAAAAAAAAA | asmodeuscore        | 0.0.16       | AsmodeusCore-1.12.2-0.0.16.jar            | None                                     |
	| UCHIJAAAAAAAAAA | mjrlegendslib       | 1.12.2-1.1.9 | MJRLegendsLib-1.12.2-1.1.9.jar            | b02331787272ec3515ebe63ecdeea0d746653468 |
	| UCHIJAAAAAAAAAA | extraplanets        | 1.12.2-0.6.4 | ExtraPlanets-1.12.2-0.6.4.jar             | b02331787272ec3515ebe63ecdeea0d746653468 |

	Loaded coremods (and transformers): 
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.255.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 389.12' Renderer: 'GeForce 820M/PCIe/SSE2'
	Launched Version: 1.12.2-forge1.12.2-14.23.1.2555
	LWJGL: 2.9.4
	OpenGL: GeForce 820M/PCIe/SSE2 GL version 4.6.0 NVIDIA 389.12, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Faithful-1.12
	Current Language: English (United Kingdom)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz

**Comment by MJRLegends** [comment]
Try update Galacticraft to latest

**Comment by Atomivv** [comment]
which forge version should i use?

**Comment by MJRLegends** [comment]
Any

**Comment by Atomivv** [comment]
ok, now the game doesn't crash but it shutting down and close theworld

**Comment by Atomivv** [comment]
sorry for my bad english

**Comment by MJRLegends** [comment]
Ok send me full log file or crash log if one is generated

**Comment by Atomivv** [comment]
[latest.log](https://github.com/MJRLegends/ExtraPlanets/files/4792007/latest.log)

**Comment by Atomivv** [comment]
And when i crashed it saw this:
[crash-2020-06-17_12.22.07-client.txt](https://github.com/MJRLegends/ExtraPlanets/files/4792023/crash-2020-06-17_12.22.07-client.txt)

**Comment by MJRLegends** [comment]
From your log file it seems like the game is working as it says you got in a rocket and that. Seems your orginal crash issue is fixed

Im seeing no other errors here

**Comment by MJRLegends** [comment]
If you still get issues try without asmodeuscore which in the core mod for Galaxyspace mod

**Comment by Atomivv** [comment]
Now work! Thanks you!

**Comment by MJRLegends** [comment]
No problem
