### ISSUE TITLE
1.12.2 Oberon replaces Overworld's Moon

### ISSUE THREAD

**Issue by TopCraft** [MJRLegends/ExtraPlanets#562]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue
[Description of the issue]

I can't launch to overworld's moon with tier 1 rocket, the launch button was red. So I tried using /dimensiontp and the launch button was green and I successfully launched to the moon... but. It wasn't the overworld's moon but the Oberon moon from Extra planets. There seems to be an ID conflict or something... and I died because I didn't have the required suit. Please help!

### Steps to Reproduce Issue
1. [First step] Launch to Space
2. [Second step] Attempt to launch to Overworld's Moon

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them] I launched back to overworld successfully so there was no crash.
> *How do i locate a crash log* see https://docs.mjrlegends.com/General%20Minecraft/crash-log/

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION] (In additional information)

**Where did this bug happen:** [Single Player or Server] Single Player

### Additional Information
[Any other information that may be able to help me with the problem]

These are the other space mods and the required mods that must come with it that I have in my modpack

AsmodeusCore-1.12.2-0.0.15.jar
Galacticraft-Planets-1.12.2-4.0.2.280
GalacticraftCore-1.12.2-4.0.2.280
GalaxySpace-1.12.2-2.0.13.jar
More-Planets-1.12.2-2.0.24-GC251.jar
ExtraPlanets-1.12.2-0.6.4.jar
MJRLegendsLib-1.12.2-1.1.9
MicdoodleCore-1.12.2-4.0.2.280
SteveKunG's-Lib-1.12.2-1.1.6.jar

[Modlist.docx](https://github.com/MJRLegends/ExtraPlanets/files/4801877/Modlist.docx)

**Comment by MJRLegends** [comment]
Please post your Galacticraft and ExtraPlanets configs files please

**Comment by MJRLegends** [comment]
And a full log file after going to this moon

**Comment by TopCraft** [comment]
[file.zip](https://github.com/MJRLegends/ExtraPlanets/files/4802397/file.zip)

There is another issue after I launch into space (before the planet selection) or /dimensiontp, the game just freezes. I can still move around but I can't interact or do any commands. Probably "waiting for server" problem. I exit to main menu and loaded back and it worked, brought me right into the planet selection and I can select planets from there. I think this is not ExtraPlanet's problem but I'm just saying, the log is pretty long.

**Comment by MJRLegends** [comment]
Remove DrZharks MoCreatures it causes conflicts as their mod has issues :P
