### ISSUE TITLE
Extraplanets Launch pads not working with launch controller

### ISSUE THREAD

**Issue by DeadReaper451** [MJRLegends/ExtraPlanets#563]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

### Description of Issue
When trying to set up a launch controller for tier 2 and 3 launch pads, the pad breaks, when the regular one that comes with galacticraft doesn't

### Steps to Reproduce Issue
1. set up any extraplanets launch pad
2. add a launch controller and power it
3. Launch pad breaks on liftoff.
NOTE: even when another launch pad is set up on another planet with controller, it will still break

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/General%20Minecraft/crash-log/

**Screenshots (if applicable):** 
[](url)
**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
1.12.2 0.6.4
**Where did this bug happen:** [Single Player or Server]
Single Player
### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
https://github.com/MJRLegends/ExtraPlanets/issues/391
