### ISSUE TITLE
Vic's Modern Warfare 2.0 causing rendering issue with Space Suit and Thermal Paddings

### ISSUE THREAD

**Issue by SinzHyper** [MJRLegends/ExtraPlanets#564]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes
### Description of Issue
[Description of the issue]
When I put on any tier space suit or thermal padding on my body it does not show up. It gives me armor protection but I only see my normal skin not the suit. The only way for me to see what the suit looks like is to put it on an armor stand.
### Steps to Reproduce Issue
1. [First step] I dont really know how to recreate it because it might be just a local issue but if not,
2. [Second step] Download all the mods I have.
try and put suit or padding on.
My Mod List.
[Minecraft mod links.txt](https://github.com/MJRLegends/ExtraPlanets/files/4893392/Minecraft.mod.links.txt)

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/General%20Minecraft/crash-log/

**Screenshots (if applicable):** 
![image](https://user-images.githubusercontent.com/67345574/86970815-e436c700-c124-11ea-932d-95445be91094.png)
![image](https://user-images.githubusercontent.com/67345574/86971552-388e7680-c126-11ea-977e-6c58cc2efed9.png)

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
1.12.2
**Where did this bug happen:** [Single Player or Server]
Single Player
### Additional Information
[Any other information that may be able to help me with the problem]
I tried installing the same mods on my other computer and had the same issue when I put on the space suit or thermal padding

**Comment by MJRLegends** [comment]
1.12.2 isnt a mod version....

**Comment by SinzHyper** [comment]
Sorry thought you meant game version. Mod version is 0.6.4

**Comment by MJRLegends** [comment]
Can you send me a picture of all your jar files in your mods folder

**Comment by SinzHyper** [comment]
![image](https://user-images.githubusercontent.com/67345574/87007041-761af000-c176-11ea-9fe6-1474f8e9bce2.png)

**Comment by MJRLegends** [comment]
Two of your mods were downloaded from illegal sources which could be causing your issue

ASM mod and Dynamic lighting 

Please try with just Galacticraft and MJRLegendsLib and ExtraPlanets and see if your issue happens

**Comment by SinzHyper** [comment]
So I tried taking out every but the mods you said and it worked fine. I put back all my other mods except ASM and Dynamic Lighting and I still had the issue. Any Ideas?

**Comment by MJRLegends** [comment]
Ok please keep removing mods ans try locate the one mod causing the ussue as we need to find the one mod causing the render issue

**Comment by SinzHyper** [comment]
I have found the issue. It is the Vic's Modern Warfare 2.0 mod that is causing issues with rendering and has also made my game crash numerous times.

**Comment by MJRLegends** [comment]
Ok does the rendering issue happen with Galacticrafts thermal padding and oxygen gear/mask?

**Comment by SinzHyper** [comment]
There is no issue with the Galacticrafts padding or oxygen gear/mask. There is how ever an issue with the thermal padding from extra planets and Galacticcraft. When I take off the Galacticraft thermal padding is does not appear to be removed from my player, and when I put on the padding from Extra Planets, it does not appear on my player's body.
![image](https://user-images.githubusercontent.com/67345574/87092158-d1d58f80-c1ef-11ea-899e-329d4c706291.png)

**Comment by MJRLegends** [comment]
ok since the rendering issue doesnt happen if Vic's Modern Warfare 2.0 is not installed, please report to Vic's Modern Warfare 2.0 as its only there mod causing any issues with ExtraPlanets render that has be noticed so far. So probably a use case they havent thought about with their code causing something to get messed up
