### ISSUE TITLE
Anti-Rad description

### ISSUE THREAD

**Issue by Romz24** [MJRLegends/ExtraPlanets#568]
### Description of Issue
Description of this item is not displayed correctly.

**Screenshots (if applicable):**
![image](https://user-images.githubusercontent.com/2458113/87418507-75e97d00-c5da-11ea-9d37-a411748d4206.png)

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):**
1.12.2-0.6.5

**Comment by MJRLegends** [comment]
Thanks looks like this has been a bug for about a year with no bug reports on it..

**Comment by MJRLegends** [comment]
Updates are being released
