### ISSUE TITLE
Basic purifier incorrect working

### ISSUE THREAD

**Issue by vsergeenko777** [MJRLegends/ExtraPlanets#569]
### Description of Issue
Basic purifier does not work correctly if you put only 6 iodized salt. To start purifying, you need to put 7 pieces, although only 6 are required.
![extra-planets-bug](https://user-images.githubusercontent.com/14260215/87622848-0dfb7980-c735-11ea-86f3-797ea521eb02.gif)

I found this error in [code](https://github.com/MJRLegends/ExtraPlanets/blob/a2537bc98b0d4057dfa561352498d5bf2c9a6d53/src/main/java/com/mjr/extraplanets/tileEntities/machines/TileEntityBasicPurifier.java#L144):
```java
else if (this.getInventory().get(4).getCount() <= 6)
```
Fix:
```java
else if (this.getInventory().get(4).getCount() < 6)
```

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):**
1.12.2-0.6.5

**Comment by MJRLegends** [comment]
Updates are being released
