### ISSUE TITLE
Random crash while in Kepler 22b Space Station Dimension

### ISSUE THREAD

**Issue by kphoenix137** [MJRLegends/ExtraPlanets#571]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

### Description of Issue
Game crashes at random intervals while located in the Kepler 22b Space Station dimension. Tested with GC Space Stations and couldn't replicate the issue. From what I can see in the crash log, the term SkyProvider keeps showing up and is consistent between crash logs. Any mods that show up in these crash logs come and go from log to log and are not consistent.

### Steps to Reproduce Issue
1. Enter Kepler 22b Space Station Dimension
2. Wait

**Crash log/Log (if applicable):** Client crash log- https://pastebin.com/jN6sX5ZF -------- Client crash shown on server console: https://pastebin.com/LnEcWUQj

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** ExtraPlanets-1.12.2-0.5.3.jar

**Where did this bug happen:** Replicated both in SSP and SMP

### Additional Information
Also, if it helps, when placing thrusters on the space station, the sky remains static with a very rapid jitter when I am stationary/on solid ground, and the the sky rotates when I am not stationary/on solid ground, backwards to what I observed during the same session on the GC Overworld Space Station. I am led to believe something is going on with the skybox that is causing the game to crash. I tried my hardest to track down the source of the problem, but I've never seen a crash log like the one here, and it doesn't seem to offer anything helpful as to what went wrong. I would also like to point out that I was playing with a friend in the same server, and they experienced the same crash that I did, but not at the same time. I'm using an AMD RX 5700 XT, and they are using Intel Integrated Graphics.

**Comment by MJRLegends** [comment]
Not a minecraft related crash sorry can't help you. Its a operating system level java crash, try updating your drivers and or java to latest java 8

**Comment by kphoenix137** [comment]
Why would it only occur while in an ExtraPlanets Space Station? I haven't experienced this crash in any other dimension at all, or even other modpacks. I think it would be safe to deduce that if I only crash in the controlled environment where ExtraPlanets mod is the only common denominator... something about ExtraPlanets is causing my system to implode. My friend and I playing both experienced a crash, and with 100% different computer setups. In fact, I am confident that if you attempted to reproduce this, you could within 0-10 min of normal gameplay in this dimension. Download the modpack Planetary and in SSP creative mod, use the command to unlock all celestial bodies, then launch yourself to space and create and go to the kepler 22b space station, and just attempt to play like normal. The game will guarentee to crash within 10 min or less. I've already made sure my Java and drivers are 100% up to date.

**Comment by kphoenix137** [comment]
To elaborate more, I'm currently using Forge with only the 3 GC mods installed, along with MJRLegendsLib 1.1.9 and EP 0.5.3, and I'm on the Pluto Space Station that has thrusters on it, and the sky is jittering HARD while standing on the station. If i jump up the space station rotates and the sky begins rotating with it, so it looks like I'm the one who is orbiting the station.
