### ISSUE TITLE
[1.12.2] Game crashing when opening the Galaxy Map

### ISSUE THREAD

**Issue by Draco26** [MJRLegends/ExtraPlanets#572]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes i have.

### Description of Issue
I have Galacticraft installed (latest version), MJR libs (latest version) and Extra planets (latest version), and when i'm in game and i'm trying to open the galaxy map, the game just crash.

### Steps to Reproduce Issue
1. Open the Galaxy Map

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/General%20Minecraft/crash-log/
https://pastebin.com/sD7tuYbM

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
ExtraPlanets-1.12.2-0.6.5

**Where did this bug happen:** [Single Player or Server]
Single Player on a brand new world.

### Additional Information
[Any other information that may be able to help me with the problem]
I have a bunch of other mods, but I'm sure Extra planet is the problem because i removed Extra planets from my mods folder, and when i open the galaxy map, no problem ! Maybe a compatibility problem with another mods (?).

**Comment by MJRLegends** [comment]
The crash log tells you how to fix

java.lang.RuntimeException: Please disable the following option: enableNewGalaxyMap in configs/AsmodeusCore/core.conf

**Comment by Ottoerich** [comment]
How do you change it on server?

**Comment by MJRLegends** [comment]
Same way as client

**Comment by Ottoerich** [comment]
I can not find the config for it, what do I do?

**Comment by MJRLegends** [comment]
You don't have the mod this issue report is for then
