### ISSUE TITLE
Crash with api jar

### ISSUE THREAD

**Issue by Robasaur** [MJRLegends/ExtraPlanets#573]
name | about | title | labels | assignees
-- | -- | -- | -- | --
Bug report | Create a report to help us improve |   | needs investigating | MJRLegends

### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

### Description of Issue
User Crashing upon entering Mercury, I've seen a similar thread posted but not the same error log so was wondering if it is a minecraft problem or a EP problem. This is in our server and in singleplayer on a custom modpack, no edited files just latest compat's for 1.12.2.

### Steps to Reproduce Issue
1. Load modpack
2. Loading into venus
2.5 stuck on a loading screen
3. Server times user out to an "internal server error"

**Crash log/Log (if applicable):** https://pastebin.com/rvbMwysF

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** MC 1.12.2-0.6.5

**Where did this bug happen:** [Single Player or Server] Both

### Additional Information
The error log says Minecraft.Worldgen but also has a line regarding EP itself, so no idea overall just wanted to understand it better.

**Comment by MJRLegends** [comment]
Please can you send a image of your mods folder

**Comment by MJRLegends** [comment]
Also a full server and client log if possible

**Comment by Robasaur** [comment]
[LogClient.txt](https://github.com/MJRLegends/ExtraPlanets/files/4976211/LogClient.txt)
[LogServer.txt](https://github.com/MJRLegends/ExtraPlanets/files/4976212/LogServer.txt)
![mods1](https://user-images.githubusercontent.com/68344049/88464263-301d9600-ceb1-11ea-882d-305063f1e32a.JPG)
![mods2](https://user-images.githubusercontent.com/68344049/88464265-314ec300-ceb1-11ea-8b9d-bfcb53f501b7.JPG)
![mods3](https://user-images.githubusercontent.com/68344049/88464266-314ec300-ceb1-11ea-9531-9459b806a7c0.JPG)
![mods4](https://user-images.githubusercontent.com/68344049/88464267-31e75980-ceb1-11ea-9b41-9e3e481ce4dc.JPG)

**Comment by MJRLegends** [comment]
The logs are not the full logs including starting of client and server

**Comment by MJRLegends** [comment]
Also you dont have Galacticraft Planets but ExtraPlanets needs it and should be firing missing mods on start up for it?

**Comment by Robasaur** [comment]
Okay I may have accidentally removed GP from that modlist, but its in the server and the modpack itself (server and clients that play). 
We did some testing and when removing the Extraplanets API, it started working properly (able to go to venus etc).
 Thanks for the help, struggling to replicate rn as I'm working remotely from my laptop that can't really run the modpack without crashing.

**Comment by MJRLegends** [comment]
Yea you dont need to use the ExtraPlanets api jar thats for developers not players :D
