### ISSUE TITLE
venus planet update request

### ISSUE THREAD

**Issue by jessiejames133** [MJRLegends/ExtraPlanets#578]
the Venus planet only works for 1.7.10 as it says in the description of the mod, but I am using this for 1.12.2 and the issue is I cannot use this mod for that version because it crashes the game. I have to physically go into the configuration and set the Venus planet to false in order to use this mod for 1.12.2. it took me three days to figure out this stupid issue. my request is can you update the Venus planet to 1.12.2 so for other people who actually want to use this mod don't have to go through the trouble of disabling the Venus planet I would really appreciate it so I don't have to disable the planet. please and thank you if you do.

**Comment by MJRLegends** [comment]
Venus doesnt exist in ExtraPlanets in anything above 1.8 minecraft as Galacticraft adds venus

**Comment by MJRLegends** [comment]
A venus config option doesn't even exist in ExtraPlanets in anything above 1.8 minecraft so i have no idea what you mean tbh.

**Comment by MJRLegends** [comment]
Sounds like to me you were trying to use a 1.7.10 mod on 1.12.2

**Comment by jessiejames133** [comment]
> A venus config option doesn't even exist in ExtraPlanets in anything above 1.8 minecraft so i have no idea what you mean tbh.

i went to the config in minecraft within itself changed extra planets to a notepad which then gave me what was in it and i set venus to false. what im trying to say is i shouldnt have to do that in order to use a mod

**Comment by jessiejames133** [comment]
> Sounds like to me you were trying to use a 1.7.10 mod on 1.12.2

i was using 1.12.2 i used the lastest mod and still gave me a issue unless i turned off venus

**Comment by jessiejames133** [comment]
> A venus config option doesn't even exist in ExtraPlanets in anything above 1.8 minecraft so i have no idea what you mean tbh.

![config](https://user-images.githubusercontent.com/69190675/89351039-2ea55800-d67f-11ea-8ba7-6e1797cc21df.PNG)
![notepad](https://user-images.githubusercontent.com/69190675/89351044-3107b200-d67f-11ea-9e8a-06362f4a01b3.PNG)
![to work](https://user-images.githubusercontent.com/69190675/89351045-32d17580-d67f-11ea-970b-9faf7f815abc.PNG)
