### ISSUE TITLE
Crash with api jar

### ISSUE THREAD

**Issue by Zerominion** [MJRLegends/ExtraPlanets#579]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
This is my first issue reporting

### Description of Issue
[Description of the issue]
I'm using Galacticraft mod + Extraplenets along with other mods but when i try to launch for the first time Tier4~10 spaceship MC crashes then when i come back into the game the spaceship started to launch. Whenever i enter into Extraplanet mod planets it crashes e.g Phobos(Mars moon) and Ceres.

### Steps to Reproduce Issue
1. [First step] Launch Tier4~10 Spaceship(creative) in Creative mode without any gears or suits in Single player
2. [Second step] Entering certain planets like Phobos(Mars moon) and Ceres caused Screen Freeze.

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/General%20Minecraft/crash-log/

https://pastebin.com/nk1VsCGk this is the Crash log

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
Galacticraft versions: GalacticraftCore-1.12.2-4.0.2.280, Galacticraft-Planets-1.12.2-4.0.2.280, MicdoodleCore-1.12.2-4.0.2.280

Extraplanets versions: ExtraPlanets-1.12.2-0.6.4, ExtraPlanets-1.12.2-0.6.4-api

**Where did this bug happen:** [Single Player or Server]
Both on Single player and Server

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Please can you try with just Galacticraft 3 mods, ExtraPlanets and MJRLegendsLib

**Comment by MJRLegends** [comment]
Remove API jar will fix it
