### ISSUE TITLE
crashing

### ISSUE THREAD

**Issue by Firedoodle1** [MJRLegends/ExtraPlanets#581]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No] yes

### Description of Issue
[Description of the issue]
when i launch a rocket and it try's to load the planet screen it crashes 

### Steps to Reproduce Issue
1. [First step] launch rocket
2. [Second step]crashes

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]

https://pastebin.com/Nhnj0afm

> *How do i locate a crash log* see https://docs.mjrlegends.com/General%20Minecraft/crash-log/

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION] 1.12.2-0.6.5

**Where did this bug happen:** [Single Player or Server] both

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Update Galacticraft
