### ISSUE TITLE
Mod Crashes When Minecraft Trys To load it.

### ISSUE THREAD

**Issue by QuantumSD** [MJRLegends/ExtraPlanets#582]
Hi, I have seen this mod on curse and I really liked it. But unfortunately, it doesn't load it just crashes.
Here is the crash report:
[crash-2020-08-09_17.35.17-client.txt](https://github.com/MJRLegends/ExtraPlanets/files/5048074/crash-2020-08-09_17.35.17-client.txt)

**Comment by MJRLegends** [comment]
Use the issue template when reporting an issue
