### ISSUE TITLE
Suns smaller than should be on Moons

### ISSUE THREAD

**Issue by galacticrafthuman** [MJRLegends/ExtraPlanets#583]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue
so when you go on any moons added by extraplanets, the sun is incredibly small, but the sun should be the same size as you can see it on the planet it orbits
 
### Steps to Reproduce Issue
1.go to any extraplanets moon
2. look at the sun

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/General%20Minecraft/crash-log/

**Screenshots (if applicable):** 

![](https://cdn.discordapp.com/attachments/304609303912775681/742423847998849114/2020-08-10_19.46.57.png)

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]

ExtraPlanets-1.12.2-0.6.5
--

**Where did this bug happen:** [Single Player or Server]
single player but it can happen on servers too
### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Will be fixed in next update, it will scale same as the parent planet of that moon

**Comment by MJRLegends** [comment]
Updates are being released
