### ISSUE TITLE
wrong sound types for blocks

### ISSUE THREAD

**Issue by galacticrafthuman** [MJRLegends/ExtraPlanets#586]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue
[Description of the issue]
Sounds for these blocks are stone sounds, but they shouldnt me
kepler 22b green, yellow, purple blue and brown maple saplings
kepler 22b red and blue tall grass, red and blue medium grass, red and blue short grass
kepler 22b grass, infected grass, yellow grass, blue grass, purple grass red grass
emerald, coal, iron, diamond and gold grit
red sand, orange sand
mercury, ceres, jupiter pluto saturn, eris, triton, phobos, lapetus, deimos, io, europa, callisto, ganymede, titania, rhea, oberon and titan gravel
### Steps to Reproduce Issue
1. [First step]launch mc with extraplanets
2. [Second step] break or place any of these blocks

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/General%20Minecraft/crash-log/

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
0.6.8 1.12.2
**Where did this bug happen:** [Single Player or Server]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
I've fixed
- kepler 22b green, yellow, purple blue and brown maple saplings
- kepler 22b red and blue tall grass, red and blue medium grass, red and blue short grass
- kepler 22b grass, infected grass, yellow grass, blue grass, purple grass red grass
- red sand, orange sand

These will need a MJRLegendsLib Update to fix
- emerald, coal, iron, diamond and gold grit
- mercury, ceres, jupiter pluto saturn, eris, triton, phobos, lapetus, deimos, io, europa, callisto, ganymede, titania, rhea, oberon and titan gravel

**Comment by MJRLegends** [comment]
Updates have been released for MJRLegendsLib and Updates for ExtraPlanets are coming out now
