### ISSUE TITLE
Space suit Jetpack Bug while landing on the Planets

### ISSUE THREAD

**Issue by Zerominion** [MJRLegends/ExtraPlanets#587]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes

### Description of Issue
[Description of the issue]
When we are landing on the planets, we have to press Space bar to slow down but if you are wearing a Space Suit with Jetpack Attached on it. That Jetpack consumes the energy at the same time when you try to slow down the Spaceship on landing.

### Steps to Reproduce Issue
1. [First step] Wear "Space suit Jetpack Armor" and go to any other planets
2. [Second step] Press Space bar to slow down the Spaceship but it will consume Space Suit Jetpack energy at the same time.

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/General%20Minecraft/crash-log/
No Crash

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
Tested Version: Extra Planets 0.6.4 and 0.6.9 both versions had the same problem

**Where did this bug happen:** [Single Player or Server]
single player and server both

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
MC 1.12.2 Updated released, MC 1.11.2 & 1.10.2 & 1.8.9 updates are delayed due a issue, i trying to work something out

**Comment by MJRLegends** [comment]
All updates have been released

**Comment by Zerominion** [comment]
got it thank u
