### ISSUE TITLE
kepler 22b dirt sound issue

### ISSUE THREAD

**Issue by galacticrafthuman** [MJRLegends/ExtraPlanets#588]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue
[Description of the issue]
kepler 22b dirt sounds like stone
### Steps to Reproduce Issue
1. [First step]launch mc with gc and extrplanets
2. [Second step]break or place kepler 22b dirt

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/General%20Minecraft/crash-log/

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
0.6.9
**Where did this bug happen:** [Single Player or Server]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
MC 1.12.2 Updated released, MC 1.11.2 & 1.10.2 & 1.8.9 updates are delayed due a issue, i trying to work something out

**Comment by MJRLegends** [comment]
MC 1.11.2 & 1.10.2 updates out, and i cant fix for MC 1.8.9 due to no way in minecraft code to do that
