### ISSUE TITLE
[1.7.10] Biomes in Overworld caused by extra biomes xl mod

### ISSUE THREAD

**Issue by Blake-HWW** [MJRLegends/ExtraPlanets#589]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

### Description of Issue
Seems to be some biome confliction, I have noticed it in both Saturn Biome and Neptune Biome

### Steps to Reproduce Issue
1. Make a world
2. Look at planet biomes on earth

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/General%20Minecraft/crash-log/

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** 1.7.10

**Where did this bug happen:** Server

### Additional Information
[Any other information that may be able to help me with the problem]

Modlist:
It’s the little things
AE2 Stuff
Another One Bites the Dust
AE2
Big Reactors
Carpenters Blocks
Custom NPCs
Dense Ores
Enchanting Plus - might be removed.
EnderIO
Ender Storage
Extra Planets
Extra Utilities
ExtrabiomesXL
ExtraCells2
Galacticraft
Gilbys Voice Chat
ICBM-Classic
Iron Chest
Mekanism
Mine Factory Reloaded
Modular Powersuits
Not Enough Items
Open Modular Turrets
Open Blocks
Open Computers
Physica Modular Forcefield/Nuclear Physics
Project Red - Bass/Compat/Integration/Lighting
Secret Rooms
Solar Flux
Thermal Dynamics/Expansion/Foundation
Voltz Engine
Wireless Crafting Terminal

**Comment by MJRLegends** [comment]
Ok please give me the following details\files

- Log files
- mod versions, screenshot of mods folder maybe?
- image of biomes, screenshot of f3 screen when in biomes
- copy of file for Galacticraft and ExtraPlanets config

**Comment by Blake-HWW** [comment]
![image](https://user-images.githubusercontent.com/61499814/90079264-5344a400-dcff-11ea-8976-cff4681ee10a.png)

[configs.zip](https://github.com/MJRLegends/ExtraPlanets/files/5066471/configs.zip)

**Comment by Blake-HWW** [comment]
Not sure what log files, and I deleted the world with the planets on earth.

**Comment by Blake-HWW** [comment]
![image](https://user-images.githubusercontent.com/61499814/90079630-5ab87d00-dd00-11ea-9da4-ef5a0582dcb8.png)

**Comment by MJRLegends** [comment]
How come you said Saturn Biome and Neptune Biome but show kepler22b biome?

**Comment by Blake-HWW** [comment]
As I was walking through the new world that was generated and I saw this.

**Comment by MJRLegends** [comment]
Ok do you have Not enough items installed?

**Comment by Blake-HWW** [comment]
Yes I do.
I assume this is what you want.
[biome.zip](https://github.com/MJRLegends/ExtraPlanets/files/5066483/biome.zip)

**Comment by MJRLegends** [comment]
can you remove ExtraPlanets and get me that biome dump again

**Comment by Blake-HWW** [comment]
[biome.zip](https://github.com/MJRLegends/ExtraPlanets/files/5066492/biome.zip)

**Comment by MJRLegends** [comment]
Ok please can you add ExtraPlanets back and remove everything except Galacticraft and ExtraPlanets and see if you get a biome in overworld

**Comment by Blake-HWW** [comment]
Yeah doing it now, but its not guaranteed I find a biome so it doesnt really rule anything out unless I find one

**Comment by MJRLegends** [comment]
also i'd suggest taking note of a seed that you know where a biome is incorrectly spawned and remaking a world with same seed and go to coords, could help you here

**Comment by Blake-HWW** [comment]
No it wasnt even the same biome that was surrounding it but I assume that is due to the removal of ExtrabiomesXL

**Comment by MJRLegends** [comment]
ok, what we really need to find out is if you get a wrong biome with just Galacticraft and ExtraPlanets..

as if that comes back no then i will be asking you to slowly add mods back intill you find a mod that causes a ignore biome.

Im 90% sure another mod not Galacticraft and ExtraPlanets is causing this. Your biome ids look fine and i have confirmed all my default ids are not used in vanilla

**Comment by Blake-HWW** [comment]
Thats what I just did I ran the modpack with just Galacticraft and Extraplanets and did the seed thing you suggested.

**Comment by Blake-HWW** [comment]
I have all the IDs written in a google sheet and non of the conflict

**Comment by Blake-HWW** [comment]
them*

**Comment by MJRLegends** [comment]
Yea please follow my troubleshooting steps above and get back to me with if you find one with just Galacticraft and ExtraPlanets 

Or if you find a mod that causes them to exist

**Comment by Blake-HWW** [comment]
You've already told me to do that step, and its done.

**Comment by MJRLegends** [comment]
Talked via discord, they confirmed it happened with extra biomes

so told to report to extra biomes as incorrect biome was only found with that mod installed and not just only ExtraPlanets and Galacticraft.
