### ISSUE TITLE
Hide Radiation chat notification if Extra Planets radiation system is disabled

### ISSUE THREAD

**Issue by knoxhack** [MJRLegends/ExtraPlanets#593]
I want to be able to hide the Radiation chat notification you get at world join if Extra Planets radiation system is disabled
![2020-08-15_13 55 35](https://user-images.githubusercontent.com/9358725/90318528-0e875b80-deff-11ea-9b71-18fab71c0c1a.png)

**Comment by MJRLegends** [comment]
You cant sorry its there as valuable information that you cant get else where sorry. If i add a config option i risk the fast someone could turn it off in a mod pack causing players not to get this information.

Sorry it only happens when you first arrive in that dimension so its not to bad

**Comment by knoxhack** [comment]
Ok. I still don't get it though.  But why still show that information if the radiation system is disabled? All that information is about radiation and since radiation is disabled it becomes useless spam information.

**Comment by MJRLegends** [comment]
Because it has info for pressure too
