### ISSUE TITLE
Kepler 22b Logs giving wrong colours when broke, Planks > Pressure Plates Crafting issue

### ISSUE THREAD

**Issue by Zerominion** [MJRLegends/ExtraPlanets#595]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
YES

### Description of Issue
[Description of the issue]
Kepler 22b planet's Tree logs are not obtained as it's colors and 4 Wooden planks does not crating the "Crafting Table" but it crafts "Pressure plates" 

Dirt block under the trees are Regular Earth dirt not Kepler dirt.

### Steps to Reproduce Issue
1. [First step]
Chop down the Yellow tree gives u Blue tree log in inventory.
2. [Second step]
Make wooden planks from the logs and try making "Crating Table" with 4 planks it will give u "Pressure plate"

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
No Crash
> *How do i locate a crash log* see https://docs.mjrlegends.com/General%20Minecraft/crash-log/

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
ExtraPlanets-1.12.2-0.7.0
MJRLegendsLib-1.12.2-1.2.0

**Where did this bug happen:** [Single Player or Server]
Server

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
I've just tested all the maple trees and they seem to give the correct logs to me, any ideas how you got different colours?

**Comment by MJRLegends** [comment]
Also thank i will fix the pressure plate crafting recipe issue

**Comment by MJRLegends** [comment]
MC 1.12.2 Updated released
