### ISSUE TITLE
[1.12.2] Holding Weapons incorrectly 

### ISSUE THREAD

**Issue by Zerominion** [MJRLegends/ExtraPlanets#596]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
No

### Description of Issue
[Description of the issue]
Holding the Swords like we can throw it as darts

### Steps to Reproduce Issue
1. [First step]
Hold the Weapons for example, Blue diamond Sword, Red gem, and blue gem.
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/General%20Minecraft/crash-log/

**Screenshots (if applicable):** 
![Sword](https://user-images.githubusercontent.com/69224487/90951175-339f3100-e40d-11ea-93a3-5835214c5d3d.png)

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
ExtraPlanets-1.12.2-0.7.0
MJRLegendsLib-1.12.2-1.2.0

**Where did this bug happen:** [Single Player or Server]
Both Single and server

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
MC 1.12.2 Update have released, MC 1.11.2 & 1.10.2 updates are delayed due a issue, i trying to work something out

**Comment by MJRLegends** [comment]
MC 1.11.2 & 1.10.2 Updates have released
