### ISSUE TITLE
Game crash when entering Tier 10 Electric rocket in Tekxit 3

### ISSUE THREAD

**Issue by sa6osasa** [MJRLegends/ExtraPlanets#599]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes

### Description of Issue
[Description of the issue]
The game crashes every time I enter a tier 10 electric rocket

### Steps to Reproduce Issue
1. [First step]
Download Tekxit 3
2. [Second step]
Spawn in and enter a Tier 10 electric rocket

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]

https://pastebin.ubuntu.com/p/V4Q5PhMd2W/

> *How do i locate a crash log* see https://docs.mjrlegends.com/General%20Minecraft/crash-log/

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION] 
1.12.2

**Where did this bug happen:** [Single Player or Server]
Tested in both a local server and singleplayer, happens in both

### Additional Information
[Any other information that may be able to help me with the problem]

The crash happens immediately after entering the rocket

**Comment by MJRLegends** [comment]
You have downloaded ExtraPlanets and probably others from an illegal sits you will get no support download from curseforge only not 9minecraft

**Comment by sa6osasa** [comment]
Thank you so much, that fixed the problem! <3

I am sorry for downloading illegaly, I am new to Forge and modding in general. I am looking forward to seeing this mod become even better than it already is!
