### ISSUE TITLE
Already decorating!

### ISSUE THREAD

**Issue by Eufranio** [MJRLegends/ExtraPlanets#60]
A player of my server went to Venus and the server crashed. Not sure if that's the right place to ask, but...

**Crash:** https://hastebin.com/panusazuma.sql

**Version of Mod using:** 1.0-3.7.4, Forge 1614, running Thermos B58

**Comment by MJRLegends** [comment]
Use the latest version for 1.7.10

**Comment by MJRLegends** [comment]
ExtraPlanets-1.0-Pre 3.8

**Comment by Eufranio** [comment]
Hmm, okay, thanks!

**Comment by KopiisCze** [comment]
I'm using ExtraPlanets-1.0-Pre 3.8 and server still crashing..

**Comment by MJRLegends** [comment]
Are you both using thermos or kcauldron or plain forge?

**Comment by KopiisCze** [comment]
Thermos b58

**Comment by MJRLegends** [comment]
Try this: 
Changing the option "load chunk on request" to false in cauldron.yml

I came across this with More Planets addon and the official servers for my Space Astronomy mod pack,  that also use thermos

**Comment by KopiisCze** [comment]
Thank you, it's working, but now I have problem with boss on Venus. He despawn myself when I enter to dungeon.

**Comment by MJRLegends** [comment]
Also a thermos problem change "entity-bounding-box-max-size" in cauldron.yml

**Comment by Eufranio** [comment]
Same crash, with latest: https://hastebin.com/ezacufapor.sql

**Comment by MJRLegends** [comment]
@Eufranio Try this:
Changing the option "load chunk on request" to false in cauldron.yml
