### ISSUE TITLE
Unknown crash.

### ISSUE THREAD

**Issue by MagmaSlime123** [MJRLegends/ExtraPlanets#601]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**
...

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes.

### Description of Issue
Unknown Crash.

### Steps to Reproduce Issue
Start the game.

**Crash log/Log (if applicable):**
https://pastebin.com/tTNgXhVE
Apparently, the crash did mention a duplicate Space station, but I'm not sure how to remove it. Tried removing this mod's and Gal's config folders and the world folder itself, but still crashing.

**Screenshots (if applicable):** 
N/A

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
ExtraPlanets 1.12.2-0.7.0
MJRLegendsLib 1.12.2-1.2.0

**Where did this bug happen:** [Single Player or Server]
Singleplayer.

### Additional Information
If you need other info then comment below.

**Comment by MJRLegends** [comment]
Just read the crash log it tells you the issue

Caused by: java.lang.RuntimeException: You have a double version of the same space station, station for planet ID: -31 You will most likely fix this by checking out compatibility guide over at https://docs.mjrlegends.com/ExtraPlanets/1.12.2compact/

**Comment by MagmaSlime123** [comment]
How can I fix this. I don't have any space station... The game thinks I do though.

**Comment by MJRLegends** [comment]
Follow the 5 steps for Galaxyspace on the link provided in the crash log
