### ISSUE TITLE
Increased biome sizes for kepler 22b planet and a config to remove the candyland biome

### ISSUE THREAD

**Issue by galacticrafthuman** [MJRLegends/ExtraPlanets#602]
increased biome sizes cuz then its gonna be like the planet made out of not SMALL different color zones but BIG color zones which would make it look nicer
Also if possible, a config to remove the candyland biome from kepler 22b as me and im sure alot of people arent fan of candy planets, i know you have said u wont do it but idk how it would crash world saves as the config to disable the biome would be off by default

**Comment by MJRLegends** [comment]
I might play around with biome sizes

As for biome config option it wont be added you can already remove the usable features of biomes in config so it becomes a visual thing without them sorry
