### ISSUE TITLE
DrZharks MoCreatures Mod causing planets and moons not to be accessible 

### ISSUE THREAD

**Issue by 3hr1ss1** [MJRLegends/ExtraPlanets#603]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
yes

### Description of Issue
I tried to fly to moon with an tier 1 rocket and, as I clicked on the moon the tier 1 sign was red and i was unable to click launch

**Screenshots (if applicable):** 
![Screenshot (6)](https://user-images.githubusercontent.com/71387208/94012384-0990b400-fda9-11ea-8810-77fdbdc4d0b3.png)

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** ExtraPlanets-1.12.2-0.7.0.jar

**Where did this bug happen:** [Single Player or Server] Single Player

### Additional Information
I tried without extra planets and it worked.

**Comment by 3hr1ss1** [comment]
I also already changed the moon id

**Comment by MJRLegends** [comment]
DrZharks MoCreatures Mod issue not ExtraPlanets remove the mod or report it to them
