### ISSUE TITLE
Crafttweaker Rocket Recipes adds recipes for rocket parts

### ISSUE THREAD

**Issue by brachy84** [MJRLegends/ExtraPlanets#604]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue
Crafttweaker Rocket Recipes adds recipes for rocket parts.

### Steps to Reproduce Issue
Make script that adds a rocket recipe.

**Screenshots (if applicable):** 
![2020-10-03_10 17 20](https://user-images.githubusercontent.com/45517902/94986768-b1ed0800-0561-11eb-8671-bda58bdda25a.png)

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** 1.12.2-0.7.0

**Where did this bug happen:** Single Player

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Plz can you send me your script file

**Comment by brachy84** [comment]
Here you go.
https://pastebin.com/9iZuw7z8
Also there order the items has to be is weird

**Comment by MJRLegends** [comment]
Yea dont worry i know the issue it will be fixed in next update

**Comment by MJRLegends** [comment]
MC 1.12.2 Updated released
