### ISSUE TITLE
CANT GET TO URANUS 

### ISSUE THREAD

**Issue by theradpickle** [MJRLegends/ExtraPlanets#606]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue
[im in creative with a tier ten rocket but when i get into space Uranus is still red even though it says tier 6]

### Steps to Reproduce Issue
1. [launch rocket ]
2. [click Uranus ]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/General%20Minecraft/crash-log/

**Screenshot 
![image](https://user-images.githubusercontent.com/68872904/95417637-883a3500-0903-11eb-820d-f26df161f6b3.png)

**Version of Mod using 1.12.2-0.7.0

**Where did this bug happen:** Single Player 
### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
#603
