### ISSUE TITLE
I cannot get this to work with galaxy space

### ISSUE THREAD

**Issue by Jmooroof** [MJRLegends/ExtraPlanets#608]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):**Yes

### Description of Issue
[Description of the issue]
I could not get this to work with galaxy space. I changed a config setting that makes it work with galaxy space. Minecraft crashed when loading up the mod. The crash report shows that there is an issue loading extra planets. It did not crash before adding extra planets.
### Steps to Reproduce Issue
1. Get both mods
2. Change the config in extra planets to make it work with galaxy space, but it does not.

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
password: 2CxQa1hK5X
[](https://pastebin.com/9LLkjvCh )

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
It is the latest
1.8.9-1.6.8 I think.
**Where did this bug happen:** [Single Player or Server]
Single player
### Additional Information
[Any other information that may be able to help me with the problem]
None

**Comment by MJRLegends** [comment]
https://docs.mjrlegends.com/ExtraPlanets/1.12.2compact/

**Comment by MJRLegends** [comment]
https://docs.mjrlegends.com/ExtraPlanets/1.7.10compact/
