### ISSUE TITLE
[1.12.2] Insta-dying from pressure on Venus despite having proper equipment.

### ISSUE THREAD

**Issue by Mysteriaa** [MJRLegends/ExtraPlanets#611]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

### Description of Issue
Long story short, Venus is essentially unplayable despite me having proper equipment to actually go there (Tier 3 Thermal padding + Tier 2 Spacesuit). I've even tried giving myself a shield controller and a higher tiered space suit via cheats, but those didn't work. Even as I'm entering the atmosphere with the entry pod, I die within like 15 seconds due to the environmental pressure, even after disabling the pressure feature in config. If I'm missing something, I have no idea what that something is.

### Steps to Reproduce Issue
1. Fly to Venus in Survival w/ Tier 3 thermal padding + Tier 2 space suit.
2. Die before your landing pod can even touch the surface.

**Crash log/Log (if applicable):** N/A

**Screenshots (if applicable):** 
![image](https://user-images.githubusercontent.com/67705660/97770667-b4fcf900-1b0b-11eb-826b-8257e97d4225.png)

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** 0.7.0

**Where did this bug happen:** Singleplayer

### Additional Information
Other addons I have installed, if it helps: GalaxySpace, Zollern's Galaxy, Galacticraft Tweaker, More Planets, PlanetProgression.

**Comment by MJRLegends** [comment]
Probably Galaxyspace systems causing it you probably need to add ExtraPlanets space suit to Galaxyspace config

**Comment by MJRLegends** [comment]
https://docs.mjrlegends.com/ExtraPlanets/1.12.2compact/#step-5-allowing-extraplanets-space-suit-to-work-with-galaxyspace-pressure-solar-radiation-system

**Comment by Mysteriaa** [comment]
> 
> 
> https://docs.mjrlegends.com/ExtraPlanets/1.12.2compact/#step-5-allowing-extraplanets-space-suit-to-work-with-galaxyspace-pressure-solar-radiation-system

Copypasted everything into the config but now I keep getting a ticking player crash. https://paste.ee/p/MlTrw
![image](https://user-images.githubusercontent.com/67705660/97785302-98e47080-1b7a-11eb-9ee0-7da10c7786f3.png)

**EDIT:** Nvm, turns out removing the quantum armor from the list helped with the crash. Should probably report that.
