### ISSUE TITLE
Dungeon boss doesnt spawn

### ISSUE THREAD

**Issue by Slasher3000** [MJRLegends/ExtraPlanets#614]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

### Description of Issue
Dungeon boss doesnt spawn when i enter the boss room. This only happens with ExtraPlanets. Tried several versions. Also some corridors are not connected or there are dead ends and random items from chests are dropped on the ground. 

### Steps to Reproduce Issue
1. Fly to the moon
2. Go into a dungeon (no boss will spawn)

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/General%20Minecraft/crash-log/

**Screenshots (if applicable):**
![2020-11-30_10 04 46](https://user-images.githubusercontent.com/71720333/100589590-9731d800-32f3-11eb-9f81-b59f85f57ae2.png)
![2020-11-30_10 04 31](https://user-images.githubusercontent.com/71720333/100589643-a749b780-32f3-11eb-8e26-99e08b58d75a.png)

 **Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** 
1.12.2-0.7.0

**Where did this bug happen:** 
Singleplayer and Server

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
What Galacticraft version are you using?

**Comment by Slasher3000** [comment]
> What Galacticraft version are you using?

1.12.2-4.0.2.281 (newest)

**Comment by MJRLegends** [comment]
Check out https://github.com/TeamGalacticraft/Galacticraft/issues/3 it was a issue they were having
