### ISSUE TITLE
Cannot craft infinity battery

### ISSUE THREAD

**Issue by Grufoony** [MJRLegends/ExtraPlanets#615]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue
You can't craft the infinity battery if Thermal Foundation is installed because all Lead ingots are converted into Thermal Foundation Lead Ingot that cannot be used into this crafting.

### Steps to Reproduce Issue
1. Install CraftTweaker and ThermalFoundation
2. Try crafting an infinity battery

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/General%20Minecraft/crash-log/

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [1.12.2-0.7.0]

**Where did this bug happen:** [Single Player or Server]

### Additional Information
[Any other information that may be able to help me with the problem]
The solution could be make this crafing as the crafting of Tier 2 Battery (used for electric rocket) thet seems not have this problem.

**Comment by MJRLegends** [comment]
Infinity battery is a Galacticraft debug creative item
