### ISSUE TITLE
Is not compatible with galaxy space

### ISSUE THREAD

**Issue by onecrazybacon** [MJRLegends/ExtraPlanets#617]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue
When loading up both extra planets and galaxy space the game crashes, the crash reports says "caught exception from Extra Planets". Extra planets seems to work just fine with other mods and add-ons, it is just galaxy space that make it crash. I have MJRLegendslib, and asmodeuscore both installed on their most recent version. The mods/add-ons themselves are also on their most updated version. They're all on 1.12.2, and I am running them on forge 1.12.2.

### Steps to Reproduce Issue
1. Make sure both add-ons and their libs/cores are installed on 1.12.2 and in minecraft's 'mods' folder.
2. Launch up the game in forge 1.12.2, wait for it to load, then it will crash, returning you back to the launcher.

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> https://pastebin.com/ZN3t1m5T

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
extraplanets 1.12.2-0.7.0
MJRlegendslib 1.12.2-1.2.0
galaxyspace 1.12.2-2.0.14
asmodeusCore 1.12.2-0.0.23
**Where did this bug happen:** [Single Player or Server]
single player

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Extra Planets (extraplanets) 

Caused by: java.lang.RuntimeException: You have a double version of the same space station, station for planet ID: -31 You will most likely fix this by checking out compatibility guide over at https://docs.mjrlegends.com/ExtraPlanets/1.12.2compact/

**Comment by onecrazybacon** [comment]
thanks

**Comment by onecrazybacon** [comment]
I was able to make the mods compatible! Thank you so much!
