### ISSUE TITLE
Mo creatures conflict with this can someone help?(sorry if this is bad I’m new to this)

### ISSUE THREAD

**Issue by ghost** [MJRLegends/ExtraPlanets#620]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
yes

description of issue
When you play this with mo creatures Uranus doesn’t work like it’s all in red. I know 100% this is the mod that’s causing it

### Steps to Reproduce Issue
1. Download the latest version of mo creatures on 1.12.2
2. Use all the normal galacticraft mods with extra planets of course
3. Launch game
4. Go to map and you’ll see it’s gone 

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/General%20Minecraft/crash-log/

**Screenshots (if applicable):** 
![image](https://user-images.githubusercontent.com/77382669/104428721-a5e9ec80-5539-11eb-938b-58c3fda61ed9.jpg)

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** version 1.12.2-0.7.1

**Where did this bug happen:** [Single Player or Server]-Single player

### Additional Information
[Any other information that may be able to help me with the problem]
None but I’m really new to modding and this so sorry if some stuff here is kinda weird

**Comment by MJRLegends** [comment]
Yea please report to to their mod issue trackers its a issue on their side
