### ISSUE TITLE
Crashing when i open Galaxy map

### ISSUE THREAD

**Issue by SZCryo** [MJRLegends/ExtraPlanets#623]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes i have checked closed issues and none worked.
### Description of Issue
I crash everytime i open the galaxy map

### Steps to Reproduce Issue
1. We made basically added 4 mods to tekxit 3 LE but that isn't the issue in this case when people told me to go to the asmodeus to disable the create new galaxy map i can't find it in the config when i open the config its looks weird in the note pad and gives me no option to disabled or enable
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/General%20Minecraft/crash-log/
When i try to access the crash log it doesn't let me
**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
AsmodeusCore-1.12.2-0.0.23
**Where did this bug happen:** [Single Player or Server]
Server and Singleplayer
### Additional Information
[Any other information that may be able to help me with the problem]
This could probably easily be solved if someone was to send me a download of an edited version of asmodeus where the newgalaxymap thing is disabled

**Comment by MJRLegends** [comment]
I cant do much without a crash log sorry
