### ISSUE TITLE
Cant Seem to Have a correct launch pad

### ISSUE THREAD

**Issue by Xterrori** [MJRLegends/ExtraPlanets#624]
### ---Issue Report---
Cant Seem to Have a correct launch pad
**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes
### Description of Issue
[Description of the issue]
My launchpaud wont let me place a rocket ive checked the tiers and tried placing down a tier 4 one and did it in a 3x3 like usual and i tried it with other rockets on tier 1s and it worked why is this?
### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/General%20Minecraft/crash-log/

**Screenshots (if applicable):** 
![image](https://user-images.githubusercontent.com/77081400/106379355-539e2d80-6379-11eb-9ab7-4bf481b47773.png)

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
1.12.2
**Where did this bug happen:** [Single Player or Server]
Server
### Additional Information
[Any other information that may be able to help me with the problem]
quick thing this is my server not a public one just one with me and my friend

**Comment by MJRLegends** [comment]
It needs to be a 5x5 check the item tool tips
