### ISSUE TITLE
Crashes upon Start up

### ISSUE THREAD

**Issue by Healthboost213** [MJRLegends/ExtraPlanets#629]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [YES]

### Description of Issue
[Game Crashes upon startup]

### Steps to Reproduce Issue
1. [Click Launch]
2. [No Second Step]

**Crash log/Log (if applicable):** [https://pastebin.com/g8H85pjs]

**Screenshots (if applicable):** 

![Screenshot 2021-02-18 155617](https://user-images.githubusercontent.com/79184740/108343505-08519f00-7202-11eb-8855-f1195146c4c0.png)

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [1.12.2]

**Where did this bug happen:** [Single Player]

### Additional Information
[I use Tlauncher. I do not use the More Planets or Galaxy Space Mod. Galacticraft works perfectly fine on its own but once i add the extra planets mod as well as the MJRLegends lib, it crashes. Pls help asap]

**Comment by MJRLegends** [comment]
Because can you post your full log files, after crash has happened

**Comment by MJRLegends** [comment]
Also as well as the above please try without ExtraPlanets and MJRLegendsLib again and send the log from that too please

**Comment by Healthboost213** [comment]
Thanks for the quick response, I think this maybe the full log. I may have posted the wrong one yesterday but here you go

https://pastebin.com/FA37FzZs

**Comment by Healthboost213** [comment]
As for the second request, I can only access the "crash reports" but i cannot find the full log as i do not know where it is.

**Comment by Healthboost213** [comment]
I may have found the log, I pasted in on Pastebin. Please do take a look.

https://pastebin.com/dw3Whhbk

**Comment by Healthboost213** [comment]
I think i may have found the Culprit, Extra planets is not actually compatible with Flan's mod.  It works fine after i removed the mod.

**Comment by Healthboost213** [comment]
Thank you for the help man. Highly Appreciated
