### ISSUE TITLE
Space Suits causing FPS Lag when Wizardry mod installed

### ISSUE THREAD

**Issue by theismarius** [MJRLegends/ExtraPlanets#631]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

### Description of Issue
When reaching planets if im missing the armor game goes well. But when equipping any tier of space suit game starts lagging.

### Steps to Reproduce Issue
1. Reach the moon without knowing needed space suit and then equip it.
2. Start lagging until you take off the armor and restart the game.

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/General%20Minecraft/crash-log/

**Screenshots (if applicable):** No crash reports

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** 1.12.2-0.7.1

**Where did this bug happen:** Single player but playing on LAN

### Additional Information
Have all the mods listed below
![mods](https://user-images.githubusercontent.com/20540599/108619932-8f805c00-7428-11eb-80ef-73c83439e9a9.PNG)

**Comment by MJRLegends** [comment]
Please run this sampler on your world, during the lag your getting and export it once you have run it with the lag happening and post the .nps file here please https://docs.mjrlegends.com/General%20Minecraft/profiling/

**Comment by theismarius** [comment]
Done it as best as the client let me, Adding the file. Thanks for the help.

[theismarius.zip](https://github.com/MJRLegends/ExtraPlanets/files/6032039/theismarius.zip)

**Comment by MJRLegends** [comment]
What kinda lag are you getting, FPS or TPS?

**Comment by theismarius** [comment]
is on client, cpu gets to 100% of usage and FPS decrease

**Comment by MJRLegends** [comment]
Yea im not seeing any lag from this sample file from a space suit.

**Comment by MJRLegends** [comment]
Journey Map seems to be causing much more lag on the client if anything

**Comment by theismarius** [comment]
Is weird. when im without the space suit game runs fine. But after equipping it starts laggin.

**Comment by MJRLegends** [comment]
What CPU/GPU have you got any how much ram have you got assigned to minecraft?

**Comment by MJRLegends** [comment]
Also try without optifine please

**Comment by theismarius** [comment]
Intel core i5-9400F CPU 2.90GH and have 8GB of RAM assignated to the client.

**Comment by MJRLegends** [comment]
Ok try without optifine please, as i only see lag to do with optifine and Journey Map & Wizardry Player Animator

**Comment by theismarius** [comment]
ok im restarting my client

**Comment by MJRLegends** [comment]
optifine isnt supported by ExtraPlanets so if its the issue then i cant help you

**Comment by theismarius** [comment]
still happening without optifine. Is there anyway  to disable space suits?

**Comment by MJRLegends** [comment]
Please can you try without Wizardry mod also and make a new sampler without optifine & Wizardry mod

**Comment by MJRLegends** [comment]
Also do you have any modules installed on your space suit, if so which ones

**Comment by theismarius** [comment]
without wizardry mod client doesnt lag

**Comment by theismarius** [comment]
and no, no space modules installed in armor

**Comment by MJRLegends** [comment]
please can you make me two sample files 

1. with wizardry mod added but optfine removed
2. and then one with both wizardry mod and optfine removed.

Its good news we found that wizardry mod it doesnt happen thats progress and is consistent with what i saw in the file sample file

**Comment by theismarius** [comment]
This sampler is without optifine and optife. Must add that wizardry mod has multiples addon mods installed.
[nwo.zip](https://github.com/MJRLegends/ExtraPlanets/files/6032240/nwo.zip)

**Comment by theismarius** [comment]
restarting client with wizardry installed without addon mods.

**Comment by MJRLegends** [comment]
Ok yea it would be great if you could get me the name of the addon causing the issue or if its the base mod

**Comment by theismarius** [comment]
Seems like the main mod makes the game lag.
[wizardry.zip](https://github.com/MJRLegends/ExtraPlanets/files/6032269/wizardry.zip)

**Comment by MJRLegends** [comment]
ok yea thought so
![](https://i.gyazo.com/1b940ed28b173bb07341eac0c7a58383.png)

Ok please report it to them with two sample files, one with wizardry installed and one without wizardry (both with optfine removed too) and any screnshots, etc

You can link this issue also

**Comment by MJRLegends** [comment]
They can message me if they need anything from me :P Let me know what they say. I'll close this issue for now

**Comment by Electroblob77** [comment]
Hi there, finally got round to looking into this (it's been ages, I know 😅). Turns out it is kind of an issue with Extra Planets, but it's not obvious at all.

I've been seeing this issue with other mods too (namely Rats), it's to do with the method `ItemArmor#getArmorModel`, which gets called every tick. Both Rats and Extra Planets simply create a new model instance here, which is unnecessary since it doesn't change. The better way is to create a static instance at startup and return that instead.

Normally the difference is unnoticeable but because my animation system has to modify and cache the models, it ends up storing every new model that is created. I'm going to add a safeguard against this but I thought I'd comment here in case you want to fix it on your end.

Here's the code I'm talking about: https://github.com/MJRLegends/ExtraPlanets/blob/dev_1.12.2/src/main/java/com/mjr/extraplanets/items/armor/Tier0SpaceSuitArmor.java#L114

**Comment by MJRLegends** [comment]
@Electroblob77 
> Hi there, finally got round to looking into this (it's been ages, I know 😅). Turns out it is kind of an issue with Extra Planets, but it's not obvious at all.
> 
> I've been seeing this issue with other mods too (namely Rats), it's to do with the method `ItemArmor#getArmorModel`, which gets called every tick. Both Rats and Extra Planets simply create a new model instance here, which is unnecessary since it doesn't change. The better way is to create a static instance at startup and return that instead.
> 
> Normally the difference is unnoticeable but because my animation system has to modify and cache the models, it ends up storing every new model that is created. I'm going to add a safeguard against this but I thought I'd comment here in case you want to fix it on your end.
> 
> Here's the code I'm talking about: https://github.com/MJRLegends/ExtraPlanets/blob/dev_1.12.2/src/main/java/com/mjr/extraplanets/items/armor/Tier0SpaceSuitArmor.java#L114

Sorry for the delay for getting back to you too, thank you for your message i will get this fixed on my end
