### ISSUE TITLE
Basic Densifier output doesnt work

### ISSUE THREAD

**Issue by ToserBan** [MJRLegends/ExtraPlanets#632]
Hi,
I converted liquid glowstone into glowstone with the basic densifier and tried to output the glowstone from the bottom of the machine. I tried thermal expansion itemduct with servos, mekanisms logistical transporter and hoppers. None of them worked. 
Minecraft 1.12.2
forge 14.23.5.2854
ExtraPlanets-1.12.2-0.6.4
modpack Tosers Spacecraft

I love your mod
Toser

**Comment by MJRLegends** [comment]
Please use the provided issue template
