### ISSUE TITLE
Uranus biome generates in overworld

### ISSUE THREAD

**Issue by Squiddyboi501** [MJRLegends/ExtraPlanets#634]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues [Yes]

### Description of Issue
[extra planets generates Uranus biome in world]

### Steps to Reproduce Issue
just generate a world and find a Uranus biome

![Uploading 2021-02-24_12.52.22.png…]()
![2021-02-24_12 53 53](https://user-images.githubusercontent.com/79560342/108950954-17bd6600-76a2-11eb-997c-79a7b1e45ef2.png)

![Uploading 2021-02-24_12.53.53.png…]()

**Version of Mod using [ExtraPlanets-1.7.10-2.1.4]

**Where did this bug happen:** [Single Player]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by Squiddyboi501** [comment]
![2021-02-24_12 53 01](https://user-images.githubusercontent.com/79560342/108977084-29633580-76c3-11eb-82d6-f265ea0577b4.png)

**Comment by MJRLegends** [comment]
https://github.com/MJRLegends/ExtraPlanets/issues/589
