### ISSUE TITLE
This addon for the galacticraft mod adds a STUPID description of the planet/moon making it IMPOSSIBLE TO DO ANYTHING

### ISSUE THREAD

**Issue by Stepanek740d** [MJRLegends/ExtraPlanets#636]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue
The description of planets is cool i admit BUT IT IS IMPOSSiBLE TO CLoSE OR MOVE Out OF THE WAY MAKiNG it iMPOSSIBLE TO TRAVEL TO  ANY SPACE STATION OR MOON WITHOUT USING THE BUTTONS ON THE SIDE
### Steps to Reproduce Issue
1. Launch a rocket
2. Click on any planet

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/General%20Minecraft/crash-log/

**Screenshots (if applicable):** 
https://user-images.githubusercontent.com/80150714/110201623-59999980-7e64-11eb-9e07-b59c665245e7.PNG

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
1.12.2

**Where did this bug happen:** [Single Player or Server]
Single player (It can possibly also happen on a server)

### Additional Information
If i try to move the bar away nothing happens other than me unfocusing from the planet!

**Comment by MJRLegends** [comment]
You just gotta change your video settings gui scale. Also no need be rude with your caps

**Comment by Stepanek740d** [comment]
> You just gotta change your video settings gui scale. Also no need be rude with your caps

im not rude or anything its just incredibly annoying and all my attempts at getting rid of it just down quite work
