### ISSUE TITLE
Galacticraft server crash telepad.

### ISSUE THREAD

**Issue by Nepeskalle** [MJRLegends/ExtraPlanets#648]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes
### Description of Issue
[Description of the issue]
We don't really know anything of the issue, all we know is that there is galacticraft and the telepad that causes the issue. 
### Steps to Reproduce Issue
1. [Place telepad]
2. [Enter a netherportal next to it]
3. (I think that is how it happened according to my friend)

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
https://pastebin.com/SRVhQcnG
> *How do i locate a crash log* see https://docs.mjrlegends.com/General%20Minecraft/crash-log/

**Screenshots (if applicable):** 
No sorry
**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
Galacticraftmod and galactiraftplanets 4.0.2.220
**Where did this bug happen:** [Single Player or Server]
Server
### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
ExtraPlanets doesnt have a telepad, please report to Galacticraft instead
