### ISSUE TITLE
The color of the leaves

### ISSUE THREAD

**Issue by JrantKing** [MJRLegends/ExtraPlanets#65]
I found that something is not right

**Comment by MJRLegends** [comment]
Im going to need more information on this...

**Comment by MJRLegends** [comment]
@JrantKing Any more details on this issue, as they look fine for me

**Fancy Graphics**
![](https://i.gyazo.com/a36feb8746e229bb4f551bcaa3f5dcc6.png)

**Fast Graphics**
![](https://i.gyazo.com/00bb3bf8d68f198f515af2031545e87a.png)

**Comment by MJRLegends** [comment]
will reopen if and when more information is provided
