### ISSUE TITLE
Rocket related Crash (Using catserver for server software)

### ISSUE THREAD

**Issue by MossCG** [MJRLegends/ExtraPlanets#650]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue
launch a rocket
crash on enter Pluto

On mulitplayer server
proxy server use waterfall(lastest version)
mod server use catserver(lastest version)
(maybe crash because of the proxy?)

### Steps to Reproduce Issue
1. a rocket(tier 8) launch from anywhere
2. go to Ploto
3. boom~ a crash~

**Crash log/Log (if applicable):**
 https://pastebin.com/Qu48hpFx

**Screenshots (if applicable):** 
nope
(because client crash immediately)

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):**
happened on 0.7.0
also tried on 0.7.2
crashed either

**Where did this bug happen:**
As player playing our multiplayer server
crash on client
but server didnt report anything
(just display xxx lost connect : disconnect)

### Additional Information
nope

**Comment by MJRLegends** [comment]
Please can you test on just a forge server rather than catserver, as i think catserver is the possible issue here

**Comment by MJRLegends** [comment]
Im going to close this due to inactivity and lack of details to reproduce, if you still have the issue please open a new issue report
