### ISSUE TITLE
Unknown cause of lander spawning from Magma Cube (Using catserver for server software)

### ISSUE THREAD

**Issue by MossCG** [MJRLegends/ExtraPlanets#651]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue
as title
it display as a space lander......?

### Steps to Reproduce Issue
1. get a spawn egg
2. spawn a evolved magma cube

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
no crash log

**Screenshots (if applicable):**
![image](https://user-images.githubusercontent.com/77914339/113487595-9ef4c980-94eb-11eb-8f84-557a3e82e8bd.png)
![image](https://user-images.githubusercontent.com/77914339/113487601-ac11b880-94eb-11eb-9f26-6b51608d8d57.png)

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** 
0.7.2

**Where did this bug happen:** [Single Player or Server]
On mulitplayer server
proxy server use waterfall(lastest version)
mod server use catserver(lastest version)
(maybe crash because of the proxy?)

single player world will not happened

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MossCG** [comment]
but ......
it do not happened on 0.7.0

**Comment by MJRLegends** [comment]
Hello. I cant reproduce this with the level of testing with just forge itself, please provide any more details you can.

It looks like a issue with your proxy server setup, and plugins, etc

**Comment by MJRLegends** [comment]
P.S looking at your #650 issue, please also do the following as suggested there for this issue

> Please can you test on just a forge server rather than catserver, as i think catserver is the possible issue here?

**Comment by MJRLegends** [comment]
Im going to close this due to inactivity and lack of details to reproduce, if you still have the issue please open a new issue report
