### ISSUE TITLE
Mod doesnt work with galaxyspace

### ISSUE THREAD

**Issue by Daminecraftbro** [MJRLegends/ExtraPlanets#652]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** No

### Description of Issue
When I try to launch the game It crashes

### Steps to Reproduce Issue
1. Use galaxy space with extra planets
2. launch minecraft

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/General%20Minecraft/crash-log/

**Screenshots (if applicable):** 

**Version of Mod using 1.12.2:** [VERSION]

**Where did this bug happen:** None.

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Another Galacticraft addon Compatibility Support:
MC 1.7.10 - https://docs.mjrlegends.com/ExtraPlanets/1.7.10compact/
MC 1.12.2 - https://docs.mjrlegends.com/ExtraPlanets/1.12.2compact/
MC 1.8.9-1.11.2 - https://docs.mjrlegends.com/ExtraPlanets/1.8-1.11compact/
