### ISSUE TITLE
Crash on Start Up.

### ISSUE THREAD

**Issue by LePizzaRabbit** [MJRLegends/ExtraPlanets#655]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

### Description of Issue
[Crashing on startup, added these mods to RL craft modpack]

### Steps to Reproduce Issue
1. [Started up the game]
2. [Not applicable]

**Crash log/Log (if applicable):** [https://pastebin.com/JM21W6t3]
> *How do i locate a crash log* see https://docs.mjrlegends.com/General%20Minecraft/crash-log/

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION] ExtraPlanets-1.12.2-0.7.2.jar MJRLegendsLib-1.12.2-1.2.0.jar
 

**Where did this bug happen:** [Single Player]

### Additional Information
[Any other information that may be able to help me with the problem]
RL Craft, CurseForge Launcher, I added galactic craft, no problem, I decided I wanted this addon, and, now I crash on startup.

**Comment by MJRLegends** [comment]
Your forge/fml launcher files. or your modded instance is broken. This isnt anything related to ExtraPlanets so i cant do anything for you.
