### ISSUE TITLE
soft-crash when going to any of the planets added by extraplanets

### ISSUE THREAD

**Issue by ThiccBoy69** [MJRLegends/ExtraPlanets#656]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes
### Description of Issue
[Description of the issue]
Whenever going to any of the planets added by extraplanets, my game stops responding and a crash-log is created. For some reason the game still remains open and not responding.
### Steps to Reproduce Issue
1. [First step] Install extraplanets and travel to a planet
2. [Second step] Upon being sent to the planet my client stops responding and it needs a restart to get to the planet.

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
https://pastebin.com/fgxxuSvc
> *How do i locate a crash log* see https://docs.mjrlegends.com/General%20Minecraft/crash-log/

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION] 0.5.5

**Where did this bug happen:** [Single Player or Server] Singleplayer

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
You've download ExtraPlanets from a unofficial site. Download it from curseforge only.

**Comment by ThiccBoy69** [comment]
I have downloaded the mod from curseforge and its library and it seemed to fix a lot of things, but for some reason Jupiter Saturn Uranus Neptune Haumea and Makemake are disabled and I don't know how to fix that.

**Comment by MJRLegends** [comment]
Do you have mo creatures mod?

**Comment by ThiccBoy69** [comment]
Nevermind I figured it out, turns out they were disabled in the config. Thanks, downloading it from curseforge helped!

Have no clue where I got it from previously though.
