### ISSUE TITLE
It crashes when booting up

### ISSUE THREAD

**Issue by FIREBALL-Z42** [MJRLegends/ExtraPlanets#657]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No] Yes

### Description of Issue
[I boot up my game and it crashes and says that it was because of extra planets]

### Steps to Reproduce Issue
1. [Press play on Curseforge]
2. [Press play on MC launcher (and crash)

**Crash log/Log (if applicable):** [CrashForGitHubV2.txt](https://github.com/MJRLegends/ExtraPlanets/files/6423867/CrashForGitHubV2.txt)]
> *How do i locate a crash log* see https://docs.mjrlegends.com/General%20Minecraft/crash-log/

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [Version 0.7.2]

**Where did this bug happen:** [None]

### Additional Information
[None]

**Comment by FIREBALL-Z42** [comment]
I'm confused it may be the other addons for Galacticraft or just the mod

**Comment by MJRLegends** [comment]
Caused by: java.lang.RuntimeException: You have a double version of the same space station, station for planet ID: -31 You will most likely fix this by checking out compatibility guide over at https://docs.mjrlegends.com/ExtraPlanets/1.12.2compact/
