### ISSUE TITLE
Tier 1/2 batteries not taking ore dict lead

### ISSUE THREAD

**Issue by xJon** [MJRLegends/ExtraPlanets#662]
### ---Issue Report---

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

### Description of Issue
As the title says.

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [0.7.2]

**Where did this bug happen:** [Single Player]

**Comment by MJRLegends** [comment]
Update has been released
