### ISSUE TITLE
Error loading 

### ISSUE THREAD

**Issue by N1njakiw1** [MJRLegends/ExtraPlanets#664]
### ---Issue Report---

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

### Description of Issue
crashed when i to load

### Steps to Reproduce Issue
1. just starting up the game

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
im just using the norma mojang launcher sooo
![g](https://user-images.githubusercontent.com/85136353/120245052-4da75300-c26c-11eb-9398-fcd5e711deb0.PNG)

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
tried with both 0.7.0 and 0.6.3
**Where did this bug happen:** [Single Player or Server]
singleplayer
### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Please include that crash log

**Comment by N1njakiw1** [comment]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
  GSHooksLoader (GalaxySpace-1.12.2-2.0.16.jar)
  CreativePatchingLoader (CreativeCore_v1.10.61_mc1.12.2.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  midnight (themidnight-0.3.5.jar)
  MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.280.jar)
  WolfArmorCore (wolfarmor-1.12.2-3.7.5-universal-signed.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  ShetiPhian-ASM (ShetiPhian-ASM-1.12.0.jar)
  JustEnoughIDs Extension Plugin (JustEnoughIDs-1.0.3-55.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  SteveKunGLibPlugin (SteveKunG's-Lib-1.12.2-1.1.10.jar)
  LoadingPlugin (ChunkAnimator-MC1.12-1.2.jar)
Contact their authors BEFORE contacting forge

// Surprise! Haha. Well, this is awkward.

Time: 6/1/21 5:49 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Extra Planets (extraplanets)
Caused by: java.lang.RuntimeException: You have a double version of the same space station, station for planet ID: -31 You will most likely fix this by checking out compatibility guide over at https://docs.mjrlegends.com/ExtraPlanets/1.12.2compact/
	at com.mjr.extraplanets.util.GCRecipeUtilities.addSpaceStationRecipe(GCRecipeUtilities.java:20)
	at com.mjr.extraplanets.recipes.ExtraPlanets_Recipes.registerSatellitesRecipes(ExtraPlanets_Recipes.java:331)
	at com.mjr.extraplanets.recipes.ExtraPlanets_Recipes.initOther(ExtraPlanets_Recipes.java:33)
	at com.mjr.extraplanets.ExtraPlanets.init(ExtraPlanets.java:252)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2109531096 bytes (2011 MB) / 10938744832 bytes (10432 MB) up to 34359738368 bytes (32768 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx32G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2855 Optifine OptiFine_1.12.2_HD_U_G5 124 mods loaded, 124 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                      | Version                   | Source                                                    | Signature                                |
	|:----- |:----------------------- |:------------------------- |:--------------------------------------------------------- |:---------------------------------------- |
	| LCHI  | minecraft               | 1.12.2                    | minecraft.jar                                             | None                                     |
	| LCHI  | mcp                     | 9.42                      | minecraft.jar                                             | None                                     |
	| LCHI  | FML                     | 8.0.99.99                 | forge-1.12.2-14.23.5.2855.jar                             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHI  | forge                   | 14.23.5.2855              | forge-1.12.2-14.23.5.2855.jar                             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHI  | creativecoredummy       | 1.0.0                     | minecraft.jar                                             | None                                     |
	| LCHI  | ivtoolkit               | 1.3.3-1.12                | minecraft.jar                                             | None                                     |
	| LCHI  | micdoodlecore           |                           | minecraft.jar                                             | None                                     |
	| LCHI  | aiimprovements          | 0.0.1.3                   | AIImprovements-1.12-0.0.1b3.jar                           | None                                     |
	| LCHI  | creativecore            | 1.10.0                    | CreativeCore_v1.10.61_mc1.12.2.jar                        | None                                     |
	| LCHI  | ambientsounds           | 3.0                       | AmbientSounds_v3.1.5_mc1.12.2.jar                         | None                                     |
	| LCHI  | antiqueatlas            | 4.5.1                     | antiqueatlas-1.12.2-4.5.1.jar                             | e631d7254e451d0360d0148cb21407d5511d45e9 |
	| LCHI  | antiqueatlasoverlay     | 1.2                       | antiqueatlas-1.12.2-4.5.1.jar                             | e631d7254e451d0360d0148cb21407d5511d45e9 |
	| LCHI  | aoa3                    | 3.3.6                     | AoA3-3.3.6.jar                                            | 8bddeac148843f40e0b9f69201be2f4b3071700d |
	| LCHI  | appliedenergistics2     | rv6-stable-7              | appliedenergistics2-rv6-stable-7.jar                      | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| LCHI  | aquaculture             | 1.6.8                     | Aquaculture-1.12.2-1.6.8.jar                              | None                                     |
	| LCHI  | ic2                     | 2.8.170-ex112             | industrialcraft-2-2.8.170-ex112.jar                       | de041f9f6187debbc77034a344134053277aa3b0 |
	| LCHI  | mantle                  | 1.12-1.3.3.55             | Mantle-1.12-1.3.3.55.jar                                  | None                                     |
	| LCHI  | jei                     | 4.16.1.301                | jei_1.12.2-4.16.1.301.jar                                 | None                                     |
	| LCHI  | twilightforest          | 3.11.1021                 | twilightforest-1.12.2-3.11.1021-universal.jar             | None                                     |
	| LCHI  | tconstruct              | 1.12.2-2.13.0.183         | TConstruct-1.12.2-2.13.0.183.jar                          | None                                     |
	| LCHI  | galacticraftcore        | 4.0.2.280                 | GalacticraftCore-1.12.2-4.0.2.280.jar                     | None                                     |
	| LCHI  | galacticraftplanets     | 4.0.2.280                 | Galacticraft-Planets-1.12.2-4.0.2.280.jar                 | None                                     |
	| LCHI  | asmodeuscore            | 0.0.25                    | AsmodeusCore-1.12.2-0.0.25.jar                            | None                                     |
	| LCHI  | atum                    | 2.0.20                    | Atum-1.12.2-2.0.20.jar                                    | None                                     |
	| LCHI  | badmobs                 | 1.1.28                    | BadMobs-1.12.2-1.1.28.jar                                 | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHI  | bibliocraft             | 2.4.5                     | BiblioCraft[v2.4.5][MC1.12.2].jar                         | None                                     |
	| LCHI  | biomesoplenty           | 7.0.1.2441                | BiomesOPlenty-1.12.2-7.0.1.2441-universal.jar             | None                                     |
	| LCHI  | bonsaitrees             | 1.1.4                     | bonsaitrees-1.1.4-b170.jar                                | None                                     |
	| LCHI  | codechickenlib          | 3.2.3.358                 | CodeChickenLib-1.12.2-3.2.3.358-universal.jar             | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHI  | redstoneflux            | 2.1.1                     | RedstoneFlux-1.12-2.1.1.1-universal.jar                   | None                                     |
	| LCHI  | brandonscore            | 2.4.19                    | BrandonsCore-1.12.2-2.4.19.214-universal.jar              | None                                     |
	| LCHI  | buildcraftlib           | 7.99.24.8                 | buildcraft-all-7.99.24.8.jar                              | None                                     |
	| LCHI  | buildcraftcore          | 7.99.24.8                 | buildcraft-all-7.99.24.8.jar                              | None                                     |
	| LCHI  | buildcraftbuilders      | 7.99.24.8                 | buildcraft-all-7.99.24.8.jar                              | None                                     |
	| LCHI  | buildcrafttransport     | 7.99.24.8                 | buildcraft-all-7.99.24.8.jar                              | None                                     |
	| LCHI  | buildcraftsilicon       | 7.99.24.8                 | buildcraft-all-7.99.24.8.jar                              | None                                     |
	| LCHI  | crafttweaker            | 4.1.20                    | CraftTweaker2-1.12-4.1.20.646.jar                         | None                                     |
	| LCHI  | buildcraftcompat        | 7.99.24.8                 | buildcraft-all-7.99.24.8.jar                              | None                                     |
	| LCHI  | buildcraftenergy        | 7.99.24.8                 | buildcraft-all-7.99.24.8.jar                              | None                                     |
	| LCHI  | buildcraftfactory       | 7.99.24.8                 | buildcraft-all-7.99.24.8.jar                              | None                                     |
	| LCHI  | buildcraftrobotics      | 7.99.24.8                 | buildcraft-all-7.99.24.8.jar                              | None                                     |
	| LCHI  | buildinggadgets         | 2.8.4                     | BuildingGadgets-2.8.4.jar                                 | None                                     |
	| LCHI  | ceramics                | 1.12-1.3.7b               | Ceramics-1.12-1.3.7b.jar                                  | None                                     |
	| LCHI  | chameleon               | 1.12-4.1.3                | Chameleon-1.12-4.1.3.jar                                  | None                                     |
	| LCHI  | chunkpregenerator       | 2.5.0                     | Chunk+Pregenerator-V1.12-2.5.0.jar                        | None                                     |
	| LCHI  | chunkanimator           | 1.2                       | ChunkAnimator-MC1.12-1.2.jar                              | None                                     |
	| LCHI  | clumps                  | 3.1.2                     | Clumps-3.1.2.jar                                          | None                                     |
	| LCHI  | cofhcore                | 4.6.6                     | CoFHCore-1.12.2-4.6.6.1-universal.jar                     | None                                     |
	| LCHI  | cofhworld               | 1.4.0                     | CoFHWorld-1.12.2-1.4.0.1-universal.jar                    | None                                     |
	| LCHI  | ctgui                   | 1.0.0                     | CraftTweaker2-1.12-4.1.20.646.jar                         | None                                     |
	| LCHI  | crafttweakerjei         | 2.0.3                     | CraftTweaker2-1.12-4.1.20.646.jar                         | None                                     |
	| LCHI  | cucumber                | 1.1.3                     | Cucumber-1.12.2-1.1.3.jar                                 | None                                     |
	| LCHI  | customspawner           | 3.11.4                    | CustomMobSpawner-3.11.5.jar                               | None                                     |
	| LCHI  | thermalfoundation       | 2.6.7                     | ThermalFoundation-1.12.2-2.6.7.1-universal.jar            | None                                     |
	| LCHI  | draconicevolution       | 2.3.27                    | Draconic-Evolution-1.12.2-2.3.27.353-universal.jar        | None                                     |
	| LCHI  | elevatorid              | 1.3.14                    | ElevatorMod-1.12.2-1.3.14.jar                             | None                                     |
	| LCHI  | enderstorage            | 2.4.6.137                 | EnderStorage-1.12.2-2.4.6.137-universal.jar               | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHI  | erebus                  | 1.0.32                    | Erebus-1.0.32.jar                                         | None                                     |
	| LCHI  | mjrlegendslib           | 1.12.2-1.2.0              | MJRLegendsLib-1.12.2-1.2.0.jar                            | b02331787272ec3515ebe63ecdeea0d746653468 |
	| LCHI  | zollerngalaxy           | 2.0.28                    | ZollernGalaxy-1.12.2-v2.0.28.jar                          | None                                     |
	| LCHE  | extraplanets            | 1.12.2-0.7.0              | ExtraPlanets-1.12.2-0.7.0.jar                             | b02331787272ec3515ebe63ecdeea0d746653468 |
	| LCH   | fastbench               | 1.7.3                     | FastWorkbench-1.12.2-1.7.3.jar                            | None                                     |
	| LCH   | fluxnetworks            | 4.1.0                     | FluxNetworks-1.12.2-4.1.1.34.jar                          | None                                     |
	| LCH   | forgelin                | 1.8.4                     | Forgelin-1.8.4.jar                                        | None                                     |
	| LCH   | ftblib                  | 5.4.7.2                   | FTBLib-5.4.7.2.jar                                        | None                                     |
	| LCH   | itemfilters             | 1.0.4.2                   | ItemFilters-1.0.4.2.jar                                   | None                                     |
	| LCH   | ftbquests               | 1202.9.0.15               | FTBQuests-1202.9.0.15.jar                                 | None                                     |
	| LCH   | galaxyspace             | 2.0.16                    | GalaxySpace-1.12.2-2.0.16.jar                             | None                                     |
	| LCH   | gunpowderlib            | 1.12.2-1.1                | GunpowderLib-1.12.2-1.1.jar                               | 4ffa87db52cf086d00ecc4853a929367b1c39b5c |
	| LCH   | railcraft               | 12.0.0                    | railcraft-12.0.0.jar                                      | a0c255ac501b2749537d5824bb0f0588bf0320fa |
	| LCH   | immersiveengineering    | 0.12-98                   | ImmersiveEngineering-0.12-98.jar                          | None                                     |
	| LCH   | immersivepetroleum      | 1.1.9                     | immersivepetroleum-1.12.2-1.1.9.jar                       | None                                     |
	| LCH   | mekanism                | 1.12.2-9.8.3.390          | Mekanism-1.12.2-9.8.3.390.jar                             | None                                     |
	| LCH   | teslacorelib            | 1.0.17                    | tesla-core-lib-1.12.2-1.0.17.jar                          | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | industrialforegoing     | 1.12.2-1.12.2             | industrialforegoing-1.12.2-1.12.13-237.jar                | None                                     |
	| LCH   | mysticalagriculture     | 1.7.5                     | MysticalAgriculture-1.12.2-1.7.5.jar                      | None                                     |
	| LCH   | integrationforegoing    | 1.12.2-1.11               | IntegrationForegoing-1.12.2-1.11.jar                      | 4ffa87db52cf086d00ecc4853a929367b1c39b5c |
	| LCH   | inventorytweaks         | 1.63+release.109.220f184  | InventoryTweaks-1.63.jar                                  | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCH   | ironbackpacks           | 1.12.2-3.0.8-12           | IronBackpacks-1.12.2-3.0.8-12.jar                         | None                                     |
	| LCH   | journeymap              | 1.12.2-5.7.1              | journeymap-1.12.2-5.7.1.jar                               | None                                     |
	| LCH   | justenoughdimensions    | 1.6.0-dev.20200416.184714 | justenoughdimensions-1.12.2-1.6.0-dev.20200416.184714.jar | 2b03e1423915a189b8094816baa18f239d576dff |
	| LCH   | jeid                    | 1.0.3-55                  | JustEnoughIDs-1.0.3-55.jar                                | None                                     |
	| LCH   | libraryex               | 1.2.1                     | LibraryEx-1.12.2-1.2.1.jar                                | None                                     |
	| LCH   | mcjtylib_ng             | 3.5.4                     | mcjtylib-1.12-3.5.4.jar                                   | None                                     |
	| LCH   | mcwbridges              | 1.0.4                     | mcw-bridges-1.0.4-mc1.12.2.jar                            | None                                     |
	| LCH   | mcwdoors                | 1.0                       | mcw-doors-1.0.0-mc1.12.2.jar                              | None                                     |
	| LCH   | mcwfences               | 1.0.0                     | mcw-fences-1.0.0-mc1.12.2.jar                             | None                                     |
	| LCH   | mcwfurnitures           | 1.0.1                     | mcw-furniture-1.0.1-mc1.12.2beta.jar                      | None                                     |
	| LCH   | mcwroofs                | 1.0.2                     | mcw-roofs-1.0.2-mc1.12.2.jar                              | None                                     |
	| LCH   | mcwtrpdoors             | 1.0.2                     | mcw-trapdoors-1.0.2-mc1.12.2.jar                          | None                                     |
	| LCH   | mekanismgenerators      | 1.12.2-9.8.3.390          | MekanismGenerators-1.12.2-9.8.3.390.jar                   | None                                     |
	| LCH   | mekanismtools           | 1.12.2-9.8.3.390          | MekanismTools-1.12.2-9.8.3.390.jar                        | None                                     |
	| LCH   | millenaire              | Millénaire 7.2.1          | millenaire-1.12.2-7.2.1.jar                               | None                                     |
	| LCH   | stevekung's_lib         | 1.1.10                    | SteveKunG's-Lib-1.12.2-1.1.10.jar                         | None                                     |
	| LCH   | moreplanets             | 2.2.1                     | More-Planets-1.12.2-2.2.1-GC280.jar                       | None                                     |
	| LCH   | moreplanetsextras       | 1.12.2-1.0                | MorePlanetsExtras-1.12.2-1.0.jar                          | None                                     |
	| LCH   | neat                    | 1.4-17                    | Neat+1.4-17.jar                                           | None                                     |
	| LCH   | netherex                | 2.2.4                     | NetherEx-1.12.2-2.2.4.jar                                 | None                                     |
	| LCH   | netherportalfix         | 5.3.17                    | NetherPortalFix_1.12.1-5.3.17.jar                         | None                                     |
	| LCH   | shetiphiancore          | 3.5.9                     | shetiphiancore-1.12.0-3.5.9.jar                           | None                                     |
	| LCH   | platforms               | 1.4.6                     | platforms-1.12.0-1.4.6.jar                                | None                                     |
	| LCH   | reccomplex              | 1.4.8.2                   | RecurrentComplex-1.4.8.2.jar                              | None                                     |
	| LCH   | refinedstorage          | 1.6.16                    | refinedstorage-1.6.16.jar                                 | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
	| LCH   | refinedstorageaddons    | 0.4.4                     | refinedstorageaddons-0.4.4.jar                            | None                                     |
	| LCH   | additionalstructures    | 2.3.1                     | Rex's-Additional-Structures-1.12.x-(v.2.3.1).jar          | None                                     |
	| LCH   | roost                   | 2.0.10                    | roost-1.12.2-2.0.10.jar                                   | None                                     |
	| LCH   | valkyrielib             | 1.12.2-2.0.20.1           | valkyrielib-1.12.2-2.0.20.1.jar                           | None                                     |
	| LCH   | simplegenerators        | 1.12.2-2.0.20.2           | simplegenerators-1.12.2-2.0.20.2.jar                      | None                                     |
	| LCH   | storagedrawers          | 5.2.2                     | StorageDrawers-1.12.2-5.4.2.jar                           | None                                     |
	| LCH   | supermartijn642corelib  | 1.0.3                     | supermartijn642corelib-1.0.3-mc1.12.jar                   | None                                     |
	| LCH   | beneath                 | 1.7.0                     | The+Beneath-1.12.2-1.7.0.jar                              | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| LCH   | thermalexpansion        | 5.5.7                     | ThermalExpansion-1.12.2-5.5.7.1-universal.jar             | None                                     |
	| LCH   | thermalcultivation      | 0.3.6                     | ThermalCultivation-1.12.2-0.3.6.1-universal.jar           | None                                     |
	| LCH   | thermalinnovation       | 0.3.6                     | ThermalInnovation-1.12.2-0.3.6.1-universal.jar            | None                                     |
	| LCH   | universalmodifiers      | 1.12.2-1.0.16.1           | valkyrielib-1.12.2-2.0.20.1.jar                           | None                                     |
	| LCH   | wailaharvestability     | 1.1.12                    | WailaHarvestability-mc1.12-1.1.12.jar                     | None                                     |
	| LCH   | wawla                   | 2.6.275                   | Wawla-1.12.2-2.6.275.jar                                  | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | wolfarmor               | 3.7.5                     | wolfarmor-1.12.2-3.7.5-universal-signed.jar               | e94e38a605842477f3ec218e6fcf781f6b3f7f89 |
	| LCH   | xnet                    | 1.8.2                     | xnet-1.12-1.8.2.jar                                       | None                                     |
	| LCH   | gctweaks                | 1.6.0                     | GalacticTweaks-1.6.0.jar                                  | 20692d890dcfa0d9cf061915fc32d00d1f295cbc |
	| LCH   | structurize             | 1.12.2-0.10.277-RELEASE   | structurize-1.12.2-0.10.277-RELEASE.jar                   | None                                     |
	| LCH   | minecolonies            | 1.12.2-0.11.804-RELEASE   | minecolonies-1.12.2-0.11.804-RELEASE-universal.jar        | None                                     |
	| LCH   | midnight                | 0.3.5                     | themidnight-0.3.5.jar                                     | None                                     |
	| LCH   | teslacorelib_registries | 1.0.17                    | tesla-core-lib-1.12.2-1.0.17.jar                          | None                                     |

	Loaded coremods (and transformers): 
IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
GSHooksLoader (GalaxySpace-1.12.2-2.0.16.jar)
  galaxyspace.core.hooklib.minecraft.PrimaryClassTransformer
CreativePatchingLoader (CreativeCore_v1.10.61_mc1.12.2.jar)
  
ForgelinPlugin (Forgelin-1.8.4.jar)
  
midnight (themidnight-0.3.5.jar)
  com.mushroom.midnight.core.transformer.MidnightClassTransformer
MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  mekanism.coremod.KeybindingMigrationHelper
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.280.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
WolfArmorCore (wolfarmor-1.12.2-3.7.5-universal-signed.jar)
  
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
ShetiPhian-ASM (ShetiPhian-ASM-1.12.0.jar)
  shetiphian.asm.ClassTransformer
JustEnoughIDs Extension Plugin (JustEnoughIDs-1.0.3-55.jar)
  org.dimdev.jeid.JEIDTransformer
IvToolkit (IvToolkit-1.3.3-1.12.jar)
  
SteveKunGLibPlugin (SteveKunG's-Lib-1.12.2-1.1.10.jar)
  
LoadingPlugin (ChunkAnimator-MC1.12-1.2.jar)
  lumien.chunkanimator.asm.ClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 466.47' Renderer: 'NVIDIA GeForce RTX 3080/PCIe/SSE2'
	AE2 Version: stable rv6-stable-7 for Forge 14.23.5.2768
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 14
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: (internal)
	OpenGlVersion: 4.6.0 NVIDIA 466.47
	OpenGlRenderer: NVIDIA GeForce RTX 3080/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 16

**Comment by MJRLegends** [comment]
Caught exception from Extra Planets (extraplanets)
Caused by: java.lang.RuntimeException: You have a double version of the same space station, station for planet ID: -31 You will most likely fix this by checking out compatibility guide over at https://docs.mjrlegends.com/ExtraPlanets/1.12.2compact/
