### ISSUE TITLE
Every single mob, including player, is moving super fast after the addition of the mob

### ISSUE THREAD

**Issue by harishselvakumar05** [MJRLegends/ExtraPlanets#666]
I was playing on tekxit 3 and I wanted to add this mod, and after I did whenever I moved even slightly the player speed was very fast and I moved large distances, mobs are also moving very very fast and their animations are sped up by quite a bit. Not sure why this is

**Comment by MJRLegends** [comment]
Use issue template please when reporting bugs. Dont just delete it
