### ISSUE TITLE
Crash with Galaxyspace

### ISSUE THREAD

**Issue by MagmaSlime123** [MJRLegends/ExtraPlanets#667]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):**
Yes.

### Description of Issue
Title.

### Steps to Reproduce Issue
Use this mod with MorePlanets and any other Galacticraft addons/dependencies.

**Crash log/Log (if applicable):**
https://pastebin.com/P7RKFzB4

**Screenshots (if applicable):** 
N/A

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):**
ExtraPlanets-1.12.2-0.7.3

**Where did this bug happen:**
Singleplayer.

### Additional Information
N/A

**Comment by MJRLegends** [comment]
Crash is with Galaxyspace 

Caused by: java.lang.RuntimeException: You have a double version of the same space station, station for planet ID: -31 You will most likely fix this by checking out compatibility guide over at https://docs.mjrlegends.com/ExtraPlanets/1.12.2compact/

**Comment by MagmaSlime123** [comment]
Already disabled that Space Station. Still get a crash when entering the planet selection GUI.

**Comment by MJRLegends** [comment]
@MagmaBro123 probs need to follow all steps on the link provided via your crash log. theres more than one step. i know the crash your probs getting as i coded it to do that :P please follow all steps at https://docs.mjrlegends.com/ExtraPlanets/1.12.2compact/ for any of the addons you have which are listed there.
