### ISSUE TITLE
Uranus Thermal Effects Problem

### ISSUE THREAD

**Issue by bballboy2002** [MJRLegends/ExtraPlanets#67]
### ---Issue Report---

**Have you checked Closed Issues (if applicable):** [Yes or No]
### Description of Issue
On Uranus I burn to death not freeze. But the planet is literally made of ice!

### Steps to Reproduce Issue
1. Travel to Uranus
2. Enter Survival Mode without thermal padding
3. Observe temperature HUD in top-right

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Version of Mod using:** 1.0-Pre 5.0

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Yeah its something i need to fix but its only s visual thing

**Comment by MJRLegends** [comment]
v1.0-Pre 5.5 is out containing a fix for this
