### ISSUE TITLE
Galaxy Space compatibility and disabling planets

### ISSUE THREAD

**Issue by Creet1724** [MJRLegends/ExtraPlanets#670]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

### Description of Issue
When you enable compatibility with Galaxy Space and disable a planet, it will crash on start.

### Steps to Reproduce Issue
1. Enable compatibility with Galaxy Space
2. Disable a planet
3. Launch the game
4. Enter a world
5. Press M
6. Crash

**Crash log/Log (if applicable):** https://pastebin.com/re8VH9f6
> *How do i locate a crash log* see https://docs.mjrlegends.com/General%20Minecraft/crash-log/

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** ExtraPlanets-1.12.2-0.7.3

**Where did this bug happen:** Singleplayer

### Additional Information
I think the reason for this crash is:
- Renaming a planet that does not exist (disabled)

A (possible) way to prevent this crash (I think this is the problem):
- Is Galaxy Space compatibility setting enabled, if yes:
  - When renaming planets, check if the planet(s) have been disabled, if yes:
    - Don't rename the planet.

How it crashes (not really useful):
- *presses M*
- Shutting down internal server...
- *crash*

**Comment by MJRLegends** [comment]
Please report to Galaxyspace
