### ISSUE TITLE
Minecraft Galacticraft Crash with Asmodeus Core, Galaxy Map, Extra Planets With config disabled already

### ISSUE THREAD

**Issue by Frostiocean** [MJRLegends/ExtraPlanets#671]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes
[crash-2021-07-06_20.54.44-client.txt](https://github.com/MJRLegends/ExtraPlanets/files/6773554/crash-2021-07-06_20.54.44-client.txt)

### Description of Issue
[Description of the issue]

when i open the map it crashes, I DO have the asmodeus core map turned FALSE but it still crashes
### Steps to Reproduce Issue
1. Install Galacticraft, and Galaxy Space and Extra Planets amd MJRLegends
2. Open galaxy map

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/General%20Minecraft/crash-log/
https://paste.gg/p/anonymous/7dfec41c701646558dec7342975607b3
**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
1.12.2
**Where did this bug happen:** [Single Player or Server]
Single PLayer
### Additional Information
[Any other information that may be able to help me with the problem]

This is on the latest version of each galacticraft addons/mods

**Comment by MJRLegends** [comment]
I believe this is a already reported bug with Asmodeus core config not saving check out this discord or/and issue tracker for any solutions they have
