### ISSUE TITLE
More planets not working on my Aternos server, but does in singleplayer (their issue or this issue)

### ISSUE THREAD

**Issue by PotassiumMan** [MJRLegends/ExtraPlanets#672]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
yes
### Description of Issue
[Description of the issue]
On my aternos server, more planets is having some issues "mixin". It works perfectly fine singleplayer. I have a different Aternos server with more planets installed and it works with no issues, so I think I might of some something wrong?
### Steps to Reproduce Issue
1. install more planets and its dependencies.
2. launch the server

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/General%20Minecraft/crash-log/
https://pastebin.com/LZ2zGwQg
**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
More-Planets-1.12.2-2.1.14-GC261 and SteveKunG's-Lib-1.12.2-1.1.7
**Where did this bug happen:** [Single Player or Server]
server
### Additional Information
[Any other information that may be able to help me with the problem]
I'm not sure if this is an issue with installation or not, but uninstalling more planets allows the server to not crash upon startup. When I install it again, crashes upon startup. I have stevekung's Lib 1.1.7. The singleplayer worked with stevekung's lib 1.1.10, but the server still crashes with 1.1.10

**Comment by MJRLegends** [comment]
Sorry this isnt the issue tracker for More Planets, you have the wrong mod

**Comment by MJRLegends** [comment]
This is the one you want https://github.com/SteveKunG/MorePlanets/issues

**Comment by PotassiumMan** [comment]
oh sorry
