### ISSUE TITLE
Incompatibility with AsmodeusCore

### ISSUE THREAD

**Issue by Michele1303** [MJRLegends/ExtraPlanets#675]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

### Description of Issue
I searched for this problem and I found something similiar, but nothing couldn't solve the problem. So I started a world with a modpack with a lot galacticraft addons (10 addons) and I fixed all the configs to make the game work, but when I open the map the game crash. The problem can be solved removing AsmodeusCore (and GalaxySpace). The crash says to disable the 'enableNewGalaxyMap' option, but I already did, and I also tried to disable the same option on ExtraPlanets but nothing.

### Steps to Reproduce Issue
1. Open a world
2. Click 'm' to open map
3. Crash

**Crash log/Log (if applicable):** https://pastebin.com/vYqkQrrY

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** 1.12.2

**Where did this bug happen:** Single

### Additional Information
**I'll send you all the addons with versions and some configs (if you need more, ask me):**
BlankPlanet-1.12.2-0.3.jar
CraftTweaker2-1.12-4.1.20.655.jar
ExtraPlanets-1.12.2-0.7.3.jar (https://pastebin.com/1sPDYcBH)
Galacticraft-Planets-1.12.2-4.0.2.280.jar
GalacticraftCore-1.12.2-4.0.2.280.jar (https://pastebin.com/Nd0eHZP4)
GalacticraftTweaker-1.12.2-1.0.3.jar
GalacticTweaks-1.6.0.jar
MicdoodleCore-1.12.2-4.0.2.280.jar
MJRLegendsLib-1.12.2-1.2.1.jar
More-Planets-1.12.2-2.2.1-GC280.jar
MorePlanetsExtras-1.12.2-1.0.jar
PlanetProgression-1.12.2-0.4.5.jar
SpaceAmbient-1.12.2-0.0.1.jar
SteveKunG's-Lib-1.12.2-1.1.10.jar
AsmodeusCore-1.12.2-0.0.26.jar (https://pastebin.com/t2i2FxDJ)
GalaxySpace-1.12.2-2.0.16.jar
Interstellar-Exoplanets-1.12.2-0.1.1-compatfix.jar

**Comment by MJRLegends** [comment]
java.lang.RuntimeException: Please disable the following option: enableNewGalaxyMap in configs/AsmodeusCore/core.conf

**Comment by MJRLegends** [comment]
Also theres a bug in some Asmodeus core versions where config wasnt saving so contact them for details of thats the case for you

**Comment by Michele1303** [comment]
Ok, thanks
