### ISSUE TITLE
[1.12.2] Huge bugs on the moon (and other planets/moons)

### ISSUE THREAD

**Issue by Migmag789** [MJRLegends/ExtraPlanets#680]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO. | Required)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING | Required):** [Yes]

### Description of Issue(Required)
[When going on the moon, my computer (and any computer of any player in any GC/EP dimension) starts consuming everything, also there is earth gravity in all planets, chunks generate hardly, the server is lagging a lot, the TPS are greatly going down, oxygen/pressure/radiation bars don't even show up]

### Steps to Reproduce Issue(Required)
1. [Go on the moon or any dimension from GC/EP]
2. []

**Crash log/Log (if applicable):** [There is no crash log]
> *How do i locate a crash log* see https://docs.mjrlegends.com/General%20Minecraft/crash-log/

**Screenshots (if applicable):** 

**Mod List (Required):** https://pastebin.com/4VYqGp5f

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest' | Required):** [VERSION]
ExtraPlanets-1.12.2-0.7.3.jar
MJRLegendsLib-1.12.2-1.2.1.jar
GalacticraftCore-1.12.2-4.0.2.280.jar

**Where did this bug happen(Required):** [Server, Client-side+server-side]

### Additional Information
[Thanks for the mod and all the work you have put into! If it's not enough (I guess it's not enough) you can join the server or I can do additional tests if needed]

**Comment by MJRLegends** [comment]
Is it just the moon that has the issues, are any of the actual ExtraPlanets ones have the issues

**Comment by Migmag789** [comment]
I've tested with Saturn and Triton and it's the same, so it's all the planets I guess

**Comment by MJRLegends** [comment]
Ok please can you make a backup of your world, or try on a new single player world, and try removing ExtraPlanets and see if it still happens on the moon or mars, venus?

**Comment by Migmag789** [comment]
Hi, so I tried as you said, and I don't have any lags tho the gravity is still the same as earth's and there is no oxygen bar showing up. I'm very confused about this problem, and I don't know if I should also report this to Galacticraft (I initially tried but could not find where to put the issue)

**Comment by MJRLegends** [comment]
Since the issues happen without ExtraPlanets theres nothing i can do to fix any issues. Please report to Galacticraft

**Comment by Migmag789** [comment]
Hi, I'm sorry to bother you again, but I can't find where I'm supposed to report issues to Galacticraft, do you know a link ?

**Comment by MJRLegends** [comment]
https://github.com/TeamGalacticraft/Galacticraft-Legacy/issues

**Comment by Migmag789** [comment]
Thanks! I found the problem, it was the mod Universal Remote. That's weird but I guess that's how it is. Thank you for helping me, sorry for bothering you, thanks for your amazing mod and have a great day!

**Comment by MJRLegends** [comment]
Ahh yea looking at the mods code that mod is badly coded as it overrides dimensions causing major issues
