### ISSUE TITLE
Game crashing when opening the galaxymap

### ISSUE THREAD

**Issue by Lewyfcb9pro** [MJRLegends/ExtraPlanets#685]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO. | Required)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING | Required):** [Yes or No]
yes
### Description of Issue(Required)
When I open the galaxymap the game just crashes on both a server and a singleplayer world then the game just closes and I already checked the asmodeuscore core file if everything was right and the ExtraPlanets core it is fine too. This only happens when I try to make the Extra Planets Galaxy map open instead of the Asmodeuscore because the Galaxy Space one Works fine and yes the core files are setup as it is written in the Compatibility Support the enableNewGalaxyMap is set to false and it just crashes.

### Steps to Reproduce Issue(Required)
1. Set both files to use the Extra Planets Galaxy Map and save them.
2. Open the Galaxy Map and look at the game as it is crashing.

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/General%20Minecraft/crash-log/
https://pastebin.pl/view/83e5be10

**Screenshots (if applicable):** 

**Mod List (Required):** 
the entire Mod List is in the Pastebin (if you want then reply and I will just write them as a reply)

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest' | Required):** [VERSION]
ExtraPlanets-1.12.2-0.7.3
GalaxySpace-1.12.2-2.0.16
**Where did this bug happen(Required):** [Single Player or Server]
both (a copy of my Server not the original one because I don't want to break that original)
### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
java.lang.RuntimeException: Please disable the following option: enableNewGalaxyMap in configs/AsmodeusCore/core.conf

**Comment by MJRLegends** [comment]
If it still crashes contact Asmodeus core dev to how to fix their config saving issue they have with some versions

**Comment by Lewyfcb9pro** [comment]
Yeah I kinda did that 20 times now and it still doesn't work

**Comment by Lewyfcb9pro** [comment]
> If it still crashes contact Asmodeus core dev to how to fix their config saving issue they have with some versions

alright thanks didn't see this message
