### ISSUE TITLE
Minecraft Crashes at start

### ISSUE THREAD

**Issue by ghost** [MJRLegends/ExtraPlanets#686]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO. | Required)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING | Required):** [Yes or No]
Yes

### Description of Issue(Required)
[When I start minecraft my minecraft crashes]

### Steps to Reproduce Issue(Required)
1. [Install addons for GalactiCraft including Extra Planets]
2. [Launch Minecraft]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them] https://pastebin.com/LBiuA6P0
> *How do i locate a crash log* see https://docs.mjrlegends.com/General%20Minecraft/crash-log/

**Screenshots (if applicable):** 
![image](https://user-images.githubusercontent.com/90104389/132100472-c7c1fac0-f551-44e6-aacc-0867d9f03c8d.png)

**Mod List (Required):** 
![image](https://user-images.githubusercontent.com/90104389/132100488-b678ae9b-9191-427a-ab88-387636451d54.png)

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest' | Required):** [VERSION]
1.12.2-0.7.3

**Where did this bug happen(Required):** [Single Player or Server]
Single Player

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Caused by: java.lang.RuntimeException: You have a double version of the same space station, station for planet ID: -31 You will most likely fix this by checking out compatibility guide over at https://docs.mjrlegends.com/ExtraPlanets/1.12.2compact/

**Comment by Cyanide719** [comment]
I have the same problem

**Comment by MJRLegends** [comment]
How to fix is above
