### ISSUE TITLE
Only Mercury and Kepler 22b planets work

### ISSUE THREAD

**Issue by Pregothedog** [MJRLegends/ExtraPlanets#690]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO. | Required)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING | Required):**  Yes

### Description of Issue(Required)
When I use this mod normally there are planets like Jupiter, Saturn, Uranus...
However It shows me that:

1/Only Mercury and Kepler are accessible planets 
2/ A lot of Items from other planets are missing

### Steps to Reproduce Issue(Required)
1. Install latest version
2. And try going to other planets 

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/General%20Minecraft/crash-log/

**Screenshots (if applicable):** 

**Mod List (Required):** 
Optifine
MicdoodleCore
Galacticraft Planets
Galacticraft Core
Extra planets
MJRlegends Lib 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest' | Required):** [VERSION]
1.12.2
**Where did this bug happen(Required):** [Single Player or Server]
Singleplayer

### Additional Information
[Any other information that may be able to help me with the problem]
I'm Pretty sure I'm the only one with the problem but I can't figure it out
What caused it
![2021-09-21_18 33 20](https://user-images.githubusercontent.com/91146879/134211078-84530e4d-2250-40d1-92ad-dbd057453304.png)
.

**Comment by MJRLegends** [comment]
Please post a copy of your full log files

**Comment by MJRLegends** [comment]
@Pregothedog Hey just a follow up on this issue report, please can i have your log files so i can look in to this issue thank you.
