### ISSUE TITLE
ExtraPlanets Crashes on load 1.12.2 (included crash report please help)

### ISSUE THREAD

**Issue by Danielle11604** [MJRLegends/ExtraPlanets#691]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  AstralCore (astralsorcery-1.12.2-1.10.27.jar)
  GSHooksLoader (GalaxySpace-1.12.2-2.0.16.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.280.jar)
  CoreMod (Aroma1997Core-1.12.2-2.0.0.2.jar)
  SteveKunGLibPlugin (SteveKunG's-Lib-1.12.2-1.1.10.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
Contact their authors BEFORE contacting forge

// Don't be sad, have a hug! <3

Time: 10/1/21 12:55 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Extra Planets (extraplanets)
Caused by: java.lang.RuntimeException: You have a double version of the same space station, station for planet ID: -31 You will most likely fix this by checking out compatibility guide over at https://docs.mjrlegends.com/ExtraPlanets/1.12.2compact/
	at com.mjr.extraplanets.util.GCRecipeUtilities.addSpaceStationRecipe(GCRecipeUtilities.java:20)
	at com.mjr.extraplanets.recipes.ExtraPlanets_Recipes.registerSatellitesRecipes(ExtraPlanets_Recipes.java:331)
	at com.mjr.extraplanets.recipes.ExtraPlanets_Recipes.initOther(ExtraPlanets_Recipes.java:33)
	at com.mjr.extraplanets.ExtraPlanets.init(ExtraPlanets.java:257)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2848146232 bytes (2716 MB) / 5315756032 bytes (5069 MB) up to 7695499264 bytes (7339 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8256m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2855 114 mods loaded, 114 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                    | Version                  | Source                                          | Signature                                |
	|:----- |:--------------------- |:------------------------ |:----------------------------------------------- |:---------------------------------------- |
	| LCHI  | minecraft             | 1.12.2                   | minecraft.jar                                   | None                                     |
	| LCHI  | mcp                   | 9.42                     | minecraft.jar                                   | None                                     |
	| LCHI  | FML                   | 8.0.99.99                | forge-1.12.2-14.23.5.2855.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHI  | forge                 | 14.23.5.2855             | forge-1.12.2-14.23.5.2855.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHI  | micdoodlecore         |                          | minecraft.jar                                   | None                                     |
	| LCHI  | akashictome           | 1.2-12                   | AkashicTome-1.2-12.jar                          | None                                     |
	| LCHI  | crafttweaker          | 4.1.20                   | CraftTweaker2-1.12-4.1.20.661.jar               | None                                     |
	| LCHI  | jei                   | 4.16.1.301               | jei_1.12.2-4.16.1.301.jar                       | None                                     |
	| LCHI  | appleskin             | 1.0.14                   | AppleSkin-mc1.12-1.0.14.jar                     | None                                     |
	| LCHI  | aroma1997core         | 2.0.0.2                  | Aroma1997Core-1.12.2-2.0.0.2.jar                | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| LCHI  | aroma1997sdimension   | 2.0.0.2                  | Aroma1997s-Dimensional-World-1.12.2-2.0.0.2.jar | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| LCHI  | aromabackup           | 2.1.1.4                  | AromaBackup-1.12.2-2.1.1.4.jar                  | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| LCHI  | aromabackuprecovery   | 2.1.1.4                  | AromaBackup-1.12.2-2.1.1.4.jar                  | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| LCHI  | mantle                | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                        | None                                     |
	| LCHI  | ctm                   | MC1.12.2-1.0.2.31        | CTM-MC1.12.2-1.0.2.31.jar                       | None                                     |
	| LCHI  | chisel                | MC1.12.2-1.0.2.45        | Chisel-MC1.12.2-1.0.2.45.jar                    | None                                     |
	| LCHI  | tconstruct            | 1.12.2-2.13.0.183        | TConstruct-1.12.2-2.13.0.183.jar                | None                                     |
	| LCHI  | galacticraftcore      | 4.0.2.280                | GalacticraftCore-1.12.2-4.0.2.280.jar           | None                                     |
	| LCHI  | galacticraftplanets   | 4.0.2.280                | Galacticraft-Planets-1.12.2-4.0.2.280.jar       | None                                     |
	| LCHI  | asmodeuscore          | 0.0.27                   | AsmodeusCore-1.12.2-0.0.26.jar                  | None                                     |
	| LCHI  | baubles               | 1.5.2                    | Baubles-1.12-1.5.2.jar                          | None                                     |
	| LCHI  | astralsorcery         | 1.10.27                  | astralsorcery-1.12.2-1.10.27.jar                | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
	| LCHI  | autoreglib            | 1.3-32                   | AutoRegLib-1.3-32.jar                           | None                                     |
	| LCHI  | betterbuilderswands   | 0.11.1                   | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar | None                                     |
	| LCHI  | bibliocraft           | 2.4.5                    | BiblioCraft[v2.4.5][MC1.12.2].jar               | None                                     |
	| LCHI  | biomesoplenty         | 7.0.1.2441               | BiomesOPlenty-1.12.2-7.0.1.2441-universal.jar   | None                                     |
	| LCHI  | bonsaitrees           | 1.1.4                    | bonsaitrees-1.1.4-b170.jar                      | None                                     |
	| LCHI  | buildcraftlib         | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                    | None                                     |
	| LCHI  | buildcraftcore        | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                    | None                                     |
	| LCHI  | buildcraftbuilders    | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                    | None                                     |
	| LCHI  | buildcrafttransport   | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                    | None                                     |
	| LCHI  | buildcraftsilicon     | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                    | None                                     |
	| LCHI  | buildcraftcompat      | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                    | None                                     |
	| LCHI  | buildcraftenergy      | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                    | None                                     |
	| LCHI  | buildcraftfactory     | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                    | None                                     |
	| LCHI  | buildcraftrobotics    | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                    | None                                     |
	| LCHI  | buildinggadgets       | 2.8.4                    | BuildingGadgets-2.8.4.jar                       | None                                     |
	| LCHI  | carryon               | 1.12.3                   | carryon-1.12.2-1.12.4.16.jar                    | fd21553434f4905f2f73ea7838147ac4ea07bd88 |
	| LCHI  | chameleon             | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                        | None                                     |
	| LCHI  | chiselsandbits        | 14.33                    | chiselsandbits-14.33.jar                        | None                                     |
	| LCHI  | clumps                | 3.1.2                    | Clumps-3.1.2.jar                                | None                                     |
	| LCHI  | codechickenlib        | 3.2.3.358                | CodeChickenLib-1.12.2-3.2.3.358-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHI  | redstoneflux          | 2.1.1                    | RedstoneFlux-1.12-2.1.1.1-universal.jar         | None                                     |
	| LCHI  | cofhcore              | 4.6.6                    | CoFHCore-1.12.2-4.6.6.1-universal.jar           | None                                     |
	| LCHI  | cofhworld             | 1.4.0                    | CoFHWorld-1.12.2-1.4.0.1-universal.jar          | None                                     |
	| LCHI  | controlling           | 3.0.10                   | Controlling-3.0.10.jar                          | None                                     |
	| LCHI  | cosmeticarmorreworked | 1.12.2-v5a               | CosmeticArmorReworked-1.12.2-v5a.jar            | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
	| LCHI  | ctgui                 | 1.0.0                    | CraftTweaker2-1.12-4.1.20.661.jar               | None                                     |
	| LCHI  | crafttweakerjei       | 2.0.3                    | CraftTweaker2-1.12-4.1.20.661.jar               | None                                     |
	| LCHI  | cucumber              | 1.1.3                    | Cucumber-1.12.2-1.1.3.jar                       | None                                     |
	| LCHI  | elevatorid            | 1.3.14                   | ElevatorMod-1.12.2-1.3.14.jar                   | None                                     |
	| LCHI  | mjrlegendslib         | 1.12.2-1.2.1             | MJRLegendsLib-1.12.2-1.2.1.jar                  | b02331787272ec3515ebe63ecdeea0d746653468 |
	| LCHE  | extraplanets          | 1.12.2-0.7.3             | ExtraPlanets-1.12.2-0.7.3.jar                   | b02331787272ec3515ebe63ecdeea0d746653468 |
	| LCH   | fastleafdecay         | v14                      | FastLeafDecay-v14.jar                           | None                                     |
	| LCH   | ftbbackups            | 1.1.0.1                  | FTBBackups-1.1.0.1.jar                          | None                                     |
	| LCH   | cfm                   | 6.3.1                    | furniture-6.3.1-1.12.2.jar                      | None                                     |
	| LCH   | gc-rpc                | 2.2.0                    | galacticraft-rpc-2.2.0.jar                      | None                                     |
	| LCH   | galacticrafttweaker   | 1.12.2-1.0.3             | GalacticraftTweaker-1.12.2-1.0.3.jar            | b02331787272ec3515ebe63ecdeea0d746653468 |
	| LCH   | galaxyspace           | 2.0.16                   | GalaxySpace-1.12.2-2.0.16.jar                   | None                                     |
	| LCH   | ichunutil             | 7.2.2                    | iChunUtil-1.12.2-7.2.2.jar                      | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCH   | hats                  | 7.1.1                    | Hats-1.12.2-7.1.1.jar                           | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCH   | waila                 | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                     | None                                     |
	| LCH   | inventorytweaks       | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                        | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCH   | ironbackpacks         | 1.12.2-3.0.8-12          | IronBackpacks-1.12.2-3.0.8-12.jar               | None                                     |
	| LCH   | ironchest             | 1.12.2-7.0.67.844        | ironchest-1.12.2-7.0.72.847.jar                 | None                                     |
	| LCH   | journeymap            | 1.12.2-5.7.1             | journeymap-1.12.2-5.7.1.jar                     | None                                     |
	| LCH   | mcjtylib_ng           | 3.5.4                    | mcjtylib-1.12-3.5.4.jar                         | None                                     |
	| LCH   | mcwbridges            | 1.0.6                    | mcw-bridges-1.0.6b-mc1.12.2.jar                 | None                                     |
	| LCH   | mcwdoors              | 1.3                      | mcw-doors-1.0.3-mc1.12.2.jar                    | None                                     |
	| LCH   | mcwfences             | 1.0.0                    | mcw-fences-1.0.0-mc1.12.2.jar                   | None                                     |
	| LCH   | mcwfurnitures         | 1.0.1                    | mcw-furniture-1.0.1-mc1.12.2beta.jar            | None                                     |
	| LCH   | mcwroofs              | 1.0.2                    | mcw-roofs-1.0.2-mc1.12.2.jar                    | None                                     |
	| LCH   | mcwtrpdoors           | 1.0.2                    | mcw-trapdoors-1.0.2-mc1.12.2.jar                | None                                     |
	| LCH   | mcwwindows            | 1.0                      | mcw-windows-1.0.0-mc1.12.2.jar                  | None                                     |
	| LCH   | mekanism              | 1.12.2-9.8.3.390         | Mekanism-1.12.2-9.8.3.390.jar                   | None                                     |
	| LCH   | mekanismgenerators    | 1.12.2-9.8.3.390         | MekanismGenerators-1.12.2-9.8.3.390.jar         | None                                     |
	| LCH   | mekanismtools         | 1.12.2-9.8.3.390         | MekanismTools-1.12.2-9.8.3.390.jar              | None                                     |
	| LCH   | refinedstorage        | 1.6.16                   | refinedstorage-1.6.16.jar                       | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
	| LCH   | moartinkers           | 0.6.0                    | moartinkers-0.6.0.jar                           | None                                     |
	| LCH   | stevekung's_lib       | 1.1.10                   | SteveKunG's-Lib-1.12.2-1.1.10.jar               | None                                     |
	| LCH   | moreplanets           | 2.2.1                    | More-Planets-1.12.2-2.2.1-GC280.jar             | None                                     |
	| LCH   | moreplanetsextras     | 1.12.2-1.0               | MorePlanetsExtras-1.12.2-1.0.jar                | None                                     |
	| LCH   | morph                 | 7.2.0                    | Morph-1.12.2-7.2.1.jar                          | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCH   | mousetweaks           | 2.10                     | MouseTweaks-2.10-mc1.12.2.jar                   | None                                     |
	| LCH   | mysticalagriculture   | 1.7.5                    | MysticalAgriculture-1.12.2-1.7.5.jar            | None                                     |
	| LCH   | mysticalagradditions  | 1.3.2                    | MysticalAgradditions-1.12.2-1.3.2.jar           | None                                     |
	| LCH   | naturescompass        | 1.8.5                    | NaturesCompass-1.12.2-1.8.5.jar                 | None                                     |
	| LCH   | oreexcavation         | 1.4.150                  | OreExcavation-1.4.150.jar                       | None                                     |
	| LCH   | harvestcraft          | 1.12.2zb                 | Pam's HarvestCraft 1.12.2zg.jar                 | None                                     |
	| LCH   | patchouli             | 1.0-23.6                 | Patchouli-1.0-23.6.jar                          | None                                     |
	| LCH   | thermalfoundation     | 2.6.7                    | ThermalFoundation-1.12.2-2.6.7.1-universal.jar  | None                                     |
	| LCH   | thermalexpansion      | 5.5.7                    | ThermalExpansion-1.12.2-5.5.7.1-universal.jar   | None                                     |
	| LCH   | redstonearsenal       | 2.6.6                    | RedstoneArsenal-1.12.2-2.6.6.1-universal.jar    | None                                     |
	| LCH   | refinedstorageaddons  | 0.4.5                    | refinedstorageaddons-0.4.5.jar                  | None                                     |
	| LCH   | rftools               | 7.73                     | rftools-1.12-7.73.jar                           | None                                     |
	| LCH   | spaceambient          | 0.0.1                    | SpaceAmbient-1.12.2-0.0.1.jar                   | None                                     |
	| LCH   | thaumcraft            | 6.1.BETA26               | Thaumcraft-1.12.2-6.1.BETA26.jar                | None                                     |
	| LCH   | spartanshields        | 1.5.4                    | SpartanShields-1.12.2-1.5.4.jar                 | None                                     |
	| LCH   | storagedrawers        | 5.2.2                    | StorageDrawers-1.12.2-5.4.2.jar                 | None                                     |
	| LCH   | thermalcultivation    | 0.3.6                    | ThermalCultivation-1.12.2-0.3.6.1-universal.jar | None                                     |
	| LCH   | thermaldynamics       | 2.5.6                    | ThermalDynamics-1.12.2-2.5.6.1-universal.jar    | None                                     |
	| LCH   | thermalinnovation     | 0.3.6                    | ThermalInnovation-1.12.2-0.3.6.1-universal.jar  | None                                     |
	| LCH   | thermaltinkering      | 1.0                      | ThermalTinkering-1.12.2-2.0.1.jar               | None                                     |
	| LCH   | tcomplement           | 1.12.2-0.4.3             | TinkersComplement-1.12.2-0.4.3.jar              | None                                     |
	| LCH   | tinkertoolleveling    | 1.12.2-1.1.0.DEV.b23e769 | TinkerToolLeveling-1.12.2-1.1.0.jar             | None                                     |
	| LCH   | travelersbackpack     | 1.0.35                   | TravelersBackpack-1.12.2-1.0.35.jar             | None                                     |
	| LCH   | tbintegration         | 1.0.1                    | TravelersBackpackIntegration-1.12.2-1.0.1.jar   | None                                     |
	| LCH   | vanillasatchels       | 1.0.2                    | VanillaSatchels-1.12.2-1.0.2.4-universal.jar    | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCH   | vanillatools          | 1.1.0                    | VanillaTools-1.12.2-1.1.0.2-universal.jar       | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCH   | wawla                 | 2.6.275                  | Wawla-1.12.2-2.6.275.jar                        | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | waystones             | 4.1.0                    | Waystones_1.12.2-4.1.0.jar                      | None                                     |
	| LCH   | wbpickup              | 1.0                      | wearabackpackspickup1.0.jar                     | None                                     |
	| LCH   | wearablebackpacks     | 3.1.4                    | WearableBackpacks-1.12.2-3.1.4.jar              | None                                     |
	| LCH   | galactictweaks        | 1.7.0                    | GalacticTweaks-1.7.0.jar                        | fdf52b4949f62c459bc7c8b88b3fc626710d49ff |

	Loaded coremods (and transformers): 
AstralCore (astralsorcery-1.12.2-1.10.27.jar)
  
GSHooksLoader (GalaxySpace-1.12.2-2.0.16.jar)
  galaxyspace.core.hooklib.minecraft.PrimaryClassTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  mekanism.coremod.KeybindingMigrationHelper
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.280.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
CoreMod (Aroma1997Core-1.12.2-2.0.0.2.jar)
  
SteveKunGLibPlugin (SteveKunG's-Lib-1.12.2-1.1.10.jar)
  
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 471.35' Renderer: 'NVIDIA GeForce RTX 2080 Super with Max-Q Design/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- wailaIntegration (Enabled/Not Forced)

	Pulsar/tcomplement loaded Pulses: 
		- ModuleCommons (Enabled/Forced)
		- ModuleMelter (Enabled/Not Forced)
		- ModuleArmor (Enabled/Not Forced)
		- ModuleSteelworks (Enabled/Not Forced)
		- ChiselPlugin (Enabled/Not Forced)
		- ToolLevelingPlugin (Enabled/Not Forced)
		- Oredict (Enabled/Forced)

	Patchouli open book context: n/a
	 

	################ [GALACTICTWEAKS DATA START] ################: 
	|	---------------------------------------------
	|	| GalaxySpace                        2.0.16 
	|	| --> AsmodeusCore                   0.0.27 
	|	| Extra Planets                1.12.2-0.7.3 
	|	| --> MJRLegendsLib            1.12.2-1.2.1 
	|	| SpaceAmbient                        0.0.1 
	|	| AsmodeusCore                       0.0.27 
	|	| MorePlanetsExtras              1.12.2-1.0 
	|	| galacticrafttweaker          1.12.2-1.0.3 
	|	| Galacticraft Rich Presence                2.2.0 
	|	| More Planets                        2.2.1 
	|	| Galacticraft Planets            4.0.2.280 
	|	| Galacticraft Core               4.0.2.280 
	|	---------------------------------------------
	|	
	################# [GALACTICTWEAKS DATA END] #################

**Comment by MJRLegends** [comment]
Caused by: java.lang.RuntimeException: You have a double version of the same space station, station for planet ID: -31 You will most likely fix this by checking out compatibility guide over at https://docs.mjrlegends.com/ExtraPlanets/1.12.2compact/
