### ISSUE TITLE
The "general info" wont go away if i click on a planet

### ISSUE THREAD

**Issue by Canina-X** [MJRLegends/ExtraPlanets#693]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO. | Required)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING | Required):** [Yes]

### Description of Issue(Required)
So if i launch a rocket i go to space. But then i get the interface as normal, but if i double click a planet the general info wont go away, and it's very hard to see my space station.

### Steps to Reproduce Issue(Required)
1. Create a rocket
2. Launch it
3. Interface will pop up => double click any planet then the general info will be stuck and non-dissapearing

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
Not applicable

**Screenshots (if applicable):**
![image](https://user-images.githubusercontent.com/78931214/138617759-d0d7e3dc-cfc8-4be9-9f12-4f88398a5878.png)
 

**Mod List (Required):** 
BetterFps-1.4.8
cfm-6.3.0-mc1.12.2
cgm-0.15.3-mc1.12.2
ExtraPlanets-1.12.2-0.7.0
foamfix-0.10.14-1.12.2
forgemod_VoxelMap-1.9.27_for_1.12.2
Galacticraft-Mod-1.12.2
Galacticraft-Planets-1.12.2-4.0.2.280
Helicopter_Pack-2.7.0 
Immersive+Vehicles-1.12.2-20.2.0
jei_1.12.2-4.16.1.301
MicdoodleCore-1.12.2-4.0.2.280 
MJRLegendsLib-1.12.2-1.2.1 
MTS_Official_Pack_V22
obfuscate-0.2.6-1.12.2
OptiFine-OptiFine-1.12.2_HD_U_G5
TexFix+V-1.12-4.0
tlskincape_1.12.2-1.4
UNU+Parts+Pack+[MTS]+1.12.2-20.1.0-4.4.2
VanillaFix-1.0.10-150
vehicle-0.44.1-mc1.12.2
WorldEdit+CUI+Forge+Edition+2-2.2.0-mf-1.12.2-14.23.5.2768
worldedit-bukkit-6.1.9
worldedit-forge-mc1.12.2-6.1.10-dist

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest' | Required):** [1.12.2-0.7.0]

**Where did this bug happen(Required):** [Single Player]

### Additional Information
[none]

**Comment by MJRLegends** [comment]
Yea its not meant to but you can change your `Change your gui scale in your video settings to normal or small `to see things better
