### ISSUE TITLE
Incompatibility with ExtraPlanets and Galaxy Space

### ISSUE THREAD

**Issue by leocorrea75** [MJRLegends/ExtraPlanets#696]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO. | Required)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING | Required):** [Yes or No]
Yes

### Description of Issue(Required)
[Haumea from Galaxy Space not showing when  ExtraPlanets is on
### Steps to Reproduce Issue(Required)

1. [First step]
Install the following mods: ExtraPlanets And Galaxy Space.
2. [Second step]
Run the game, go to the galaxy map and done.

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/General%20Minecraft/crash-log/

**Screenshots (if applicable):** 

**Mod List (Required):**
ExtraPlanets, Galaxy Space, More Planets, More Planets Extras, Zollern Galaxy, Blank Planet, StarMaker And Interestellar Exoplanets.

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest' | Required):** [VERSION] 
ExtraPlanets-1.12.2-0.7.3.jar
**Where did this bug happen(Required):** [Single Player or Server]
Single Player

### Additional Information
[Any other information that may be able to help me with the problem]
This can be fixed if you remove haumea from extraplanets, but can't be fixed if you only add it to the list of other planets for other addons on the config.

**Comment by leocorrea75** [comment]
sorry for bad english, I will post a screenshot of it tomorrow, because this bug happened on my brother's computer and he is going to play all the night.

**Comment by leozzaunn** [comment]
screenshot:
![2021-11-12_11 53 23](https://user-images.githubusercontent.com/94063023/141478512-fd94ef67-0e4f-4b1d-bdf0-ebdf765b9263.png)
 other screenshot:
![2021-11-12_11 53 20](https://user-images.githubusercontent.com/94063023/141478716-bc67ef2b-ca50-4ccf-af07-68efdfc9f6d3.png)
where haumea from galaxy space should be:
![2021-11-12_12 01 12](https://user-images.githubusercontent.com/94063023/141479068-b23e92ab-7786-4b78-9494-e17c7a0a01c0.png)

**Comment by MJRLegends** [comment]
Hey sorry for the delay getting back to you, Thank you yea i can fix this, i was not informed by the GalaxySpace, StarMaker of any compact breaking changes....

This is what needs to be fixed:

-Haumea - Only in ExtraPlanets for Galaxy Map Visuals, so im not to worried here
-MakeMake - Only in ExtraPlanets for Galaxy Map Visuals, so im not to worried here
-Eris - Needs fixing
-BlackHole - Needs fixing to work with Star Maker in the Blank Planet mod, which is a different addon to this.

**Comment by leocorrea75** [comment]
thanks! but it's not the extraplanets haumea, makemake and eris, it's galaxy space's ones that are not showing when extraplanets is on, they added their own haumea, makemake and eris, and sorry by not replying again you too.

**Comment by leocorrea75** [comment]
It's like issue #492, but now with haumea, and I found out that makemake and eris from galaxy space are only for a older version, and that I was using version 1.8.9 for blank planet, sorry I will change here

**Comment by leocorrea75** [comment]
I forgot I had 1 more addon on, and they also added charon for their pluto, but it's not reachable

**Comment by MJRLegends** [comment]
Haumea was the only planet that can be visited and is not correctly being disabled when GalaxySpace compact config options are enabled. This will be fixed in the next update, as for the black hole thing please report to https://github.com/MJRLegends/BlankPlanet/issues as thats my other addons issue not ExtraPlanets

**Comment by MJRLegends** [comment]
Update has been released https://www.curseforge.com/minecraft/mc-mods/extraplanets/files/3614752
