### ISSUE TITLE
Minecraft Crashes when i open  Space map

### ISSUE THREAD

**Issue by Not0xAstral** [MJRLegends/ExtraPlanets#698]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO. | Required)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING | Required):** [Yes or No]
No
### Description of Issue(Required)
[Description of the issue]
Minecraft Crashes when i open the map to go to other planets
### Steps to Reproduce Issue(Required)
1. [First step] Launch minecraft with Extra Planets and StarMaker (or Galaxy Space and Interstellar Exoplanets)
2. [Second step] open/create a world then place a rocket (any tier) click on rocket and click m (opens map)

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/General%20Minecraft/crash-log/

**Screenshots (if applicable):** 

**Mod List (Required):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest' | Required):** [VERSION]
ExtraPlanets-1.12.2-0.7.3 
**Where did this bug happen(Required):** [Single Player or Server]
Single Player
### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Please disable the following option: enableNewGalaxyMap in configs/AsmodeusCore/core.conf
