### ISSUE TITLE
Dim 0 Missing

### ISSUE THREAD

**Issue by vagaprime** [MJRLegends/ExtraPlanets#7]
Just added extra planets to my mod pack last night and went to create a new world this morning only to have the game crash cause Dim 0 does not exist. You are able to create a supper flat world, but not a stranded survival world.

Here is a copy of the crash log.

http://pastebin.com/zrx0Ha6G

**Comment by MJRLegends** [comment]
This shouldn't be anything to do with my addon

**Comment by vagaprime** [comment]
It only started up after I removed More planets, and added in Extra Planets. I have tried a couple other GC addon mods and none have given me the a problem. When I am in a super flat world it is loading a different dim cause the oxygen tank gauges are shown. The survival world that I tried to load was a BoP type.

**Comment by MJRLegends** [comment]
There is no way this can be my addon as the overworld is dimension 0 and my addon doesn't touch that dimension

**Comment by vagaprime** [comment]
Well your addon is the only that has caused that issue. So I don't know what to say. I gave you the crash log, told you what i did, what mod I removed and replaced with yours. I have run my pack with with other GC addon mods with out this problem which leaves only thing that could could cause the problem.

**Comment by MJRLegends** [comment]
Has the crash happened more than once

**Comment by vagaprime** [comment]
It has just happened again, and digging into the FML log has shown that the problem maybe getting caused my GC.
