### ISSUE TITLE
Compatibility problem with the Custom NPC's mod since the 0.7.4 update of the ExtraPlanets mod.

### ISSUE THREAD

**Issue by HDL34** [MJRLegends/ExtraPlanets#701]
Since the 0.7.4 update of the mod, there are quite a few items of the Custom NPC's mod that don't work anymore or work very partially. 
I asked the developer of the custom NPC mod to make an update but he told me to ask you because it's not his job to solve the problem.

**Comment by MJRLegends** [comment]
Please fill out the issue template which gets pre added when making an issue report

**Comment by HDL34** [comment]
Which issue model?
