### ISSUE TITLE
Server crash when player join

### ISSUE THREAD

**Issue by deathsovushka** [MJRLegends/ExtraPlanets#704]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO. | Required)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING | Required):** Yes

### Description of Issue(Required)
Crash server when player join

### Steps to Reproduce Issue(Required)
1. start server
2. join

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/General%20Minecraft/crash-log/
https://pastebin.com/7baVe7a6

**Screenshots (if applicable):** 

**Mod List (Required):** 
In crashlog

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest' | Required):** [VERSION]
1.12.2 - 0.7.4
**Where did this bug happen(Required):** [Single Player or Server]
Server

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Looks like you've got a tampered jar file somehow for ExtraPlanets please redownload from curseforge only and let me know if it still does it. Thank you

**Comment by MJRLegends** [comment]
Im going to close this due to inactivity and lack of details to reproduce, if you still have the issue please open a new issue report
