### ISSUE TITLE
Space Suit addition in config not working on Space Astronomy 2

### ISSUE THREAD

**Issue by misterblusky985** [MJRLegends/ExtraPlanets#706]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO. | Required)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING | Required):**
Yes, there was one that was closed as the person found a workaround, I have linked the closed issue below. The fix they found is not applicable to my game.
https://github.com/MJRLegends/ExtraPlanets/issues/516

### Description of Issue(Required)
When I tried to add items to the Space Suit list, they fail to protect me from pressure on the Moon. Specifically, I attempted to add the Modular Powersuit set to the list, but this failed. I attempted to just add the Vanilla Iron Armor Set, but this failed as well.

### Steps to Reproduce Issue(Required)
1. Before loading up the game, goto the ExtraPlanets config and add the sets. This is a copy-paste from my config:
   S:"List of armour items to be considered as a space suit" <
        minecraft:iron_helmet:4
        minecraft:iron_chestplate:4
        minecraft:iron_leggings:4
        minecraft:iron_boots:4
        powersuits:powerArmorHead:4
        powersuits:powerArmorTorso:4
        powersuits:powerArmorLegs:4
        powersuits:powerArmorFeet:4
     >
2. Head to a celestial body such as the Moon which I used, and step out with oxygen and see if the pressure makes the player take damage. In all instances this occurred. I must add that the normal added Pressure Suit Tier 1 does work fine.

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/General%20Minecraft/crash-log/
n/a

**Screenshots (if applicable):** 
n/a

**Mod List (Required):** 
Space Astronomy 2 v1.5.7 (Current Release)
no changes to the default modlist

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest' | Required):** [VERSION]
ExtraPlanets-1.10.2-1.2.8

**Where did this bug happen(Required):** [Single Player or Server]
Singleplayer

### Additional Information
I also tried editing the config to say "powersuits:powerArmorHelmet - Chestplate - Leggings - Boots" but that also did not work.
Thank you in advance :)

**Comment by MJRLegends** [comment]
Thank you for the report, Yea sorry it was fixed in a few versions of mod after what the latest pack version has, as im that mod packs dev also just to let you know im unable to update the pack without removing some building blocks mods from the pack so i will probs not. But you should be able to manually update ExtraPlanets and it will work ok.
