### ISSUE TITLE
Space Suit Jetpack Reduces Durability

### ISSUE THREAD

**Issue by Khepricus** [MJRLegends/ExtraPlanets#711]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO. | Required)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING | Required):**
Yes

### Description of Issue(Required)
Possible regression of #493 . Using the jetpack on the space suit jetpack will reduce durability to the point where getting hit even once will delete the suit, with potentially catastrophic results.

### Steps to Reproduce Issue(Required)
1. Start a new creative world
2. Temporarily set difficulty to peaceful
3. Equip a fully charged Tier 1 space suit jetpack
4. Change game mode to survival
5. Hover around until jetpack no longer functions, being careful not to go high enough / fall hard enough to take damage
6. Set difficulty to normal
7. Spawn or find a mob, allow it to hit you a single time
8. Note that the suit is no longer present, despite only being hit once

**Crash log/Log (if applicable):**
N/A

**Screenshots (if applicable):**
N/A

**Mod List (Required):** 
Modpack Sevtech Ages release 3.2.3

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest' | Required):**
1.12.2-0.7.0

**Where did this bug happen(Required):** [Single Player or Server]
Confirmed in both single player and multiplayer server

### Additional Information
N/A

**Comment by MJRLegends** [comment]
Thanks for the report, I believe this has already been fixed to latest version of ExtraPlanets, please update or ask the mod pack dev to update in their new pack update.
