### ISSUE TITLE
Basic Solar Evaporation chamber doesnt output products

### ISSUE THREAD

**Issue by ToserBan** [MJRLegends/ExtraPlanets#712]
Hi,
i make Potassium out of Potash shards with the basic solar evaporation chamber. This works. But when i try to get the potassium out of the bottom side of the machine, nothing happens. I tried the vanilla hopper, thermal expansion itemducts, mekanisms logistic transport pipe, ender io´s pipe and the item extraction cable from cyclic. None of the above worked. I remember it worked in an older release of the mod.
minecraft version: 1.12.2
extraplanets version: ExtraPlanets-1.12.2-0.7.4.jar
Forge: 14.23.5.2854
Modpack: Tosers Spacecraft
regards
Toser

**Comment by MJRLegends** [comment]
Please use the template to submit bugs
