### ISSUE TITLE
Compatability issues with MorePlanets

### ISSUE THREAD

**Issue by imadethisaccounttoreportbugs** [MJRLegends/ExtraPlanets#713]
**Sorry if you have done this before, I just couldn't find the issue.**

### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO. | Required)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING | Required):** [Yes or No]

Yes, I have

### Description of Issue(Required)

Can't find the thing that the config files tell me to do for compatibility

### Steps to Reproduce Issue(Required)

No steps, pretty self-explanatory (config files)

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do I locate a crash log* see https://docs.mjrlegends.com/General%20Minecraft/crash-log/

**Screenshots (if applicable):** 

Not needed.

**Mod List (Required):** 

Mixinbooter,
Galacticraft (and the 2 other required mods),
BlankPlanet,
AsmodeusCore,
Extraplanets,
Moreplanets (and extras),
MJRLegendslib,
Galaxyspace,
SteveKunG's Lib.

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest' | Required):** [VERSION]

1.12.2-2.2.2-GC280

**Where did this bug happen(Required):** [Single Player or Server]

On boot-up

### Additional Information
[Any other information that may be able to help me with the problem]

It says to disable features under something in the config file for More Planets even though it is nowhere to be seen

**Comment by MJRLegends** [comment]
If you cant find it dont worry about it, as it means you are on a different version
