### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by zyxkad** [MJRLegends/ExtraPlanets#718]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO. | Required)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING | Required):** [Yes or No]

### Description of Issue(Required)

I got a mystery bug:
<https://pastebin.com/1Nb9KqtJ>
As you see, when you joined the game, you will be kicked quickly, and you got no more tip.  
This bug happens when I drive the rocket up to y > 1200

**It's actually happens in the singleplayer server**
<https://pastebin.com/ytMLKVGf>

### Steps to Reproduce Issue(Required)
1. Join a world
2. Prepare fire a rocket
3. Fire the rocket
4. Wait the rocket up to 1200 blocks height
5. The game will crash _(client bound)_

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
<https://pastebin.com/1Nb9KqtJ>
<https://pastebin.com/ytMLKVGf>

**Screenshots (if applicable):** 
No typical screenshots

**Mod List (Required):** 
```
Advanced+Solar+Panels-4.3.0.jar
advsolarpatch-1.1.jar
AsmodeusCore-1.12.2-0.0.30.jar
buildcraft-all-7.99.24.8.jar
cc-tweaked-1.12.2-1.83.0.jar
CodeChickenLib-1.12.2-3.2.3.358-universal.jar
ExtraPlanets-1.12.2-0.7.4.jar
Galacticraft-1.12.2-4.0.2.284.jar
Gravitation Suite-3.1.1.jar
Hwyla-1.8.26-B41_1.12.2.jar
industrialcraft-2-2.8.221-ex112.jar
InventoryTweaks-1.64+dev.146.jar
jei_1.12.2-4.16.1.301.jar
Mantle-1.12-1.3.3.55.jar
MJRLegendsLib-1.12.2-1.2.1.jar
NotEnoughItems-1.12.2-2.4.3.245-universal.jar
plustic-8.0.0.1.jar
ReactorStuff-[1.12.2]-1.10.2.jar
TConstruct-1.12.2-2.13.0.183.jar
WarpDrive-1.12.2-1.5.26.jar
Xaeros_Minimap_22.5.0_Forge_1.12.jar.disable
XaerosWorldMap_1.20.6_Forge_1.12.jar
```

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest' | Required):** [VERSION]
*See above*

**Where did this bug happen(Required):** [Single Player or Server]
Both of them

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
: Exception caught during firing event net.minecraftforge.client.event.GuiOpenEvent@21e412e9: 

java.lang.RuntimeException: Please disable the following option: enableNewGalaxyMap in configs/AsmodeusCore/core.conf
