### ISSUE TITLE
Crash.

### ISSUE THREAD

**Issue by MagmaSlime123** [MJRLegends/ExtraPlanets#719]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO. | Required)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING | Required):**
Yes.

### Description of Issue(Required)
Game is crashing.

### Steps to Reproduce Issue(Required)
Launch a rocket of any kind.

**Crash log/Log (if applicable):**
No report is made. All I'm given is some 'fatal error' message. A log file is all I can provide.
https://pastebin.com/d0iXQTht
The log does mention the map screen, but I have disabled this mod's version of it. I've also enabled GalaxySpace support and edited the config files respectfully. I may be stupid and missed something. GitHub does not support .cfg files, so I can't do much.

**Screenshots (if applicable):** 
![2022-05-18_13 31 05](https://user-images.githubusercontent.com/51277766/169141419-9ac6b29b-c980-4719-944c-8ff6b8050066.png)

**Mod List (Required):** 
![image](https://user-images.githubusercontent.com/51277766/169141393-fce92240-2d3c-4501-b0a0-537a2c5f7706.png)

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest' | Required):**
See screenshot above.

**Where did this bug happen(Required):** [Single Player or Server]
Singleplayer.

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Looks like a bunch of issues for Galaxyspace with galaxy map screen and some image files

**Comment by MJRLegends** [comment]
Please report to them if they havent fixed it already
