### ISSUE TITLE
Double space station after following compatibility guide

### ISSUE THREAD

**Issue by ashyashton** [MJRLegends/ExtraPlanets#720]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO. | Required)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING | Required):** Yes

### Description of Issue(Required)
I can't figure out what space station to disable

### Steps to Reproduce Issue(Required)
1. Start Minecraft via CurseForge with mods list detailed below
2. (Extra step: Cry upon seeing the pig with the crown in the launcher)
3. Hit "Play"
4. Game crashes
5. Realize I need to enable compatibility options
6. Follow all instructions at https://docs.mjrlegends.com/ExtraPlanets/1.12.2compact/ to the best of my abilities (disabled Venus space station as the website told me, added items to the compatibility lists, enabled MorePlanets compatibility)
7. Try to start up again
8. Game still crashes and says planet ID: -29 has a double version
9. I don't know which planet has the ID of -29 as this is my first time using Galacticraft and such, so I don't know which to disable, and come here instead!

**Crash log/Log (if applicable):** https://mclo.gs/XfyujR9

**Screenshots (if applicable):**  N/A

**Mod List (Required):** 
[SteveKunG's Lib (by SteveKunG)](https://www.curseforge.com/minecraft/mc-mods/stevekungs-lib)
    [Galacticraft Legacy (by teamgalacticraft)](https://www.curseforge.com/minecraft/mc-mods/galacticraft-legacy)
    [Galaxy Space [Addon for GalactiCraft] (by BlesseNtumble)](https://www.curseforge.com/minecraft/mc-mods/galaxy-space-addon-for-galacticraft)
    [More Planets - Galacticraft Add-on (by SteveKunG)](https://www.curseforge.com/minecraft/mc-mods/more-planets-gc-addon)
    [MixinBooter (by Rongmario)](https://www.curseforge.com/minecraft/mc-mods/mixin-booter)
    [Galacticraft Rich Presence (by JustPyrrha)](https://www.curseforge.com/minecraft/mc-mods/galacticraft-rpc)
    [AsmodeusCore (by BlesseNtumble)](https://www.curseforge.com/minecraft/mc-mods/asmodeuscore)
    [ExtraPlanets (by MJRLegends)](https://www.curseforge.com/minecraft/mc-mods/extraplanets)
    [MJRLegends Lib (by MJRLegends)](https://www.curseforge.com/minecraft/mc-mods/mjrlegendslib)

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest' | Required):** ExtraPlanets-1.12.2-0.7.4.jar along with whatever CurseForge automatically downloads for 1.12.2 for the other mods

**Where did this bug happen(Required):** On start-up

### Additional Information
It works when I disable GalaxySpace even though I disabled the Venus station as the guide told me to do. So I have to guess that either there's another planet that both mods use, or for some reason my config is being ignored; I've seen others in closed issues have the latter problem, so it could be that, but I'm hoping it's the first one as that sounds easier to fix.

**Comment by ashyashton** [comment]
**UPDATE:** I went to the Discord and asked which planet has ID -29 to see if I could figure it out and was told it was Mars from Galacticraft itself. I disabled Mars in the config of this mod, which seems to have worked!

**Comment by DeVviL** [comment]
Hello!
I was able to find a causal relationship in the melting of the error. The error itself says "Two space station types registered with the same home planet ID: -29". Keywords - "Two space station". That is, for one planet - two stations.
Steps to solve
1) Find a planet with this id. We have Mars from GalactiCraft.
  - config\Galacticraft\planets.conf -> parameter "I:dimensionIDMars=-29"
2) Turn off the station for this planet in one of the mods. We have GalaxySpace
  - config\GalaxySpace\dimensions.conf -> change parameter "B:enableMarsSpaceStation=true" to "false"

**Comment by MJRLegends** [comment]
Has been added to docs file unded step 6 

https://docs.mjrlegends.com/ExtraPlanets/1.12.2compact/
