### ISSUE TITLE
Extra Planet Tier Space Suits Frame Drop

### ISSUE THREAD

**Issue by Noodle1243** [MJRLegends/ExtraPlanets#729]
I'm playing the 1.12.2 modpack with my friends on a server, and we're trying to go to space but every time I see the space suit(even when im wearing it in my inventory) my fps drop from 95-120 down to 10-15 and is preventing us from continuing. I have a ryzen 5 1600x and a rx 580 with 16Gb of ram. My friend has the same exact specs and is running fine even while looking at the suits.
![low frames](https://user-images.githubusercontent.com/114773416/193342212-6c068a7a-aaab-47b1-9d61-c02001da996a.png)
![high frames](https://user-images.githubusercontent.com/114773416/193342214-6d67b03d-59fe-4d7d-9137-8a3913d80e76.png)

**Comment by MJRLegends** [comment]
Please fill out the issue template
