### ISSUE TITLE
1.12.2 Unknown issue with space suits causing frame drops

### ISSUE THREAD

**Issue by Noodle1243** [MJRLegends/ExtraPlanets#730]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO. | Required)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING | Required):** [Yes or No]

### Description of Issue(Required)
I'm playing the 1.12.2 modpack with my friends on a server, and we're trying to go to space but every time I see the space suit(even when im wearing it in my inventory) my fps drop from 95-120 down to 10-15 and is preventing us from continuing. I have a ryzen 5 1600x and a rx 580 with 16Gb of ram. My friend has the same exact specs and is running fine even while looking at the suits.

### Steps to Reproduce Issue(Required)
1. Have someone wear space suit or wear it yourself
2. If wearing it yourself go into third person 

**Crash log/Log (if applicable):** None

**Screenshots (if applicable):** 
![high frames](https://user-images.githubusercontent.com/114773416/193375529-f51aa5b2-ef3a-4f03-bf19-ead17e6909d4.png)
![low frames](https://user-images.githubusercontent.com/114773416/193375530-23ecb090-6606-4059-8369-bf2c2fd05bd9.png)

**Mod List (Required):** 
![mods](https://user-images.githubusercontent.com/114773416/193375625-fb45908e-5a66-46f2-adf7-629be467205c.png)
![mods 2](https://user-images.githubusercontent.com/114773416/193375630-4e1eed0b-bd05-43f5-840d-ff9baee4fb15.png)

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest' | Required):**  1.12.2-0.7.4

**Where did this bug happen(Required):** It happens in both. It happened at first in a server with my friends so i went into a singleplayer creative to see if it was that and it continued to happen.

### Additional Information
[Any other information that may be able to help me with the problem] none

**Comment by janojano5** [comment]
What i can recommend and how did i solve this issue is mod for removing players armour. So basically you will download mod which will disable render of armours whenever you will go somewhere with suit, it disable yours and others players so you wont have this issue. Based on title i assume that you are running 1.12.2 mc version so this is mod that i download myself https://www.curseforge.com/minecraft/mc-mods/hidden-armor/download. Its clientside, so everybody needs to have this installed. Hope this help.

**Comment by MJRLegends** [comment]
@Noodle1243 Hey sorry for the delayed reply, please can you run this sampler on your client, during the lag your getting and export it once you have run it with the lag happening and post the .nps file here please https://docs.mjrlegends.com/General%20Minecraft/profiling/

**Comment by MJRLegends** [comment]
Hey, thank you for your bug report.

I've fixed some issues with lag for the space suit in #705 issue, i think this might be related so please try these new versions.

1.12.2 Download Link:  https://www.curseforge.com/minecraft/mc-mods/extraplanets/files/4366814
1.11.2 Download Link:  https://www.curseforge.com/minecraft/mc-mods/extraplanets/files/4366784
1.10.2 Download Link:  https://www.curseforge.com/minecraft/mc-mods/extraplanets/files/4366790

If issue still happens please open a new issue report
