### ISSUE TITLE
Venus rover wheels crash

### ISSUE THREAD

**Issue by eraseded** [MJRLegends/ExtraPlanets#731]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO. | Required)**

**Have you checked Closed Issues** [Yes]

### Description of Issue(Required)
[I accidently acquired some of the wheels for the Venus Rover whilst in 1.7.10 through a pet and now my game instantly crashes when trying to join the server. The wheels turned out to be called unnamed and had missing texture texture so Im guessing its a null block.]

### Steps to Reproduce Issue(Required)
1. [Create a world]
2. [Get the wheels used in Venus Rover]
3. [Your game should crash and you wont be able to re-join the world]

**Crash log/Log (if applicable)**
https://pastebin.com/5JrTPAhT

**Screenshots (if applicable):**
These are the wheels
![image](https://user-images.githubusercontent.com/116728165/198056931-07b22273-48c7-4118-b409-114d5e706e39.png)

**Mod List (Required):** 
![image](https://user-images.githubusercontent.com/116728165/198057103-2bacd503-86d2-4f0e-9a29-faa1ab0607d8.png)

**Version of Mod using (Required)** 
[Im unsure as this is all it shows]
![image](https://user-images.githubusercontent.com/116728165/198057345-4943a4b8-d6f7-4e6a-83ab-34ae2a76f223.png)

**Where did this bug happen(Required):**
[Server]

### Additional Information
Things I have tried
1. [/kill from the console as soon as I joined however it did not register me as fully in before I crashed]

**Comment by MJRLegends** [comment]
Ok so yea that file name you are showing me, shows you downloaded this mod from an illegal site that isnt safe and gives people false and viruses and older versions.

Please download from curseforge only as my mods are only from here.

https://www.curseforge.com/

FYI this issue was fixed years ago so you should be good once you got correct version

**Comment by eraseded** [comment]
Thanks, will do. I got the mod from a friend a year or so ago so that would be why.

**Comment by eraseded** [comment]
Hey, sorry to bother you again,
but the wheels are still unnamed with the missing texture, the mod version is now 'ExtraPlanets-1.7.10-2.1.4.jar'.
Thanks

**Comment by MJRLegends** [comment]
Yea this report and solution i gave was just to solve your crash issue, the other issues are still issues and will be fixed at a later date. But you now should be able to play without crashing
