### ISSUE TITLE
Extra Planets crashing on game launch after updating Launcher to version "Windows 10.0 2.3.481"

### ISSUE THREAD

**Issue by SparJar** [MJRLegends/ExtraPlanets#732]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO. | Required)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING | Required):** [Yes or No]
Yes

### Description of Issue(Required)
Extra Planets crashing game on load. This only started happening after the Minecraft Launcher updated to version "Windows 10.0 2.3.481"  

### Steps to Reproduce Issue(Required)
1. Let Minecraft Launcher update
2. Launch Project Ozone 3

**Crash log/Log (if applicable):** 

(https://pastebin.com/U77AFnBW)

> *How do i locate a crash log* see https://docs.mjrlegends.com/General%20Minecraft/crash-log/

**Screenshots (if applicable):** 

**Mod List (Required):** 
Project Ozone 3 modpack

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest' | Required):** [VERSION]
ExtraPlanets-1.12.2-0.7.4

**Where did this bug happen(Required):** [Single Player or Server]
Happens when launching the modpack. Game never fully loads. 

### Additional Information
Found a similar bug report from last year with Venus causing the same message in the crash log.  Went through those steps and Venus is already disabled in the config for Extra Planets. Also the planet ID in the crash log in -13 not -31.  I tried looking for -13 and could not find a planet that correlates with that ID.  The only -13 in the config looks like it might be Mercury but it is already disable from the modpack as well.

**Comment by MJRLegends** [comment]
Solution can be found in the crash log

Caused by: java.lang.RuntimeException: You have a double version of the same space station, station for planet ID: -13 You will most likely fix this by checking out compatibility guide over at https://docs.mjrlegends.com/ExtraPlanets/1.12.2compact/

**Comment by SparJar** [comment]
I did check that from a previous issue before submitting my own.  Venus is already disabled as it Mercury.  I do not see a planet directly correlating with ID -13 in the config to be able to disable it directly. 
![image](https://user-images.githubusercontent.com/1742901/200464617-254ede5e-dfa7-46cd-b262-52fa98e32f4c.png)
That screenshot is the only time -13 appears in the config file.

**Comment by MJRLegends** [comment]
Please contact your mod pack devs support team as something is broken with your mod packs setup.

**Comment by MJRLegends** [comment]
ExtraPlanets is crashing because configs are messed up. As this isnt ExtraPlanets bug, the crash it forced to make the user away of a unhappy configuration
