### ISSUE TITLE
[1.12.2] Duplicate Planets on Galaxy Map

### ISSUE THREAD

**Issue by MishaBlinsky** [MJRLegends/ExtraPlanets#733]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO. | Required)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING | Required):** Yes (by keywords "duplicate" and "map" to be precise)

### Description of Issue(Required)
GalactiCraft's unaccessable planet (like Mercury, Jupiter, Uranus) buttons persist with ExtraPlanets' planet buttons. Tested with just GalactiCraft, MJRLegendsLib and ExtraPlanets.
Mods downloaded from CurseForge. Configs untouched.
forge:1.12.2-14.23.5.2860
OptiFine:1.12.2_HD_U_G5

### Steps to Reproduce Issue(Required)
1. Open Galaxy Map
2. Profit

**Crash log/Log (if applicable):**
https://pastebin.com/96B5f92g

**Screenshots (if applicable):** 
![2022-12-01_23 02 52](https://user-images.githubusercontent.com/99417065/205154458-c770047a-c558-43f8-aa74-ecfccad6c751.png)

**Mod List (Required):** 
GalactiCraft, MJRLegendsLib, ExtraPlanets

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest' | Required):** 
Galacticraft-1.12.2-4.0.4
MJRLegendsLib-1.12.2-1.2.1
ExtraPlanets-1.12.2-0.7.4

**Where did this bug happen(Required):** Single Player

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
This is a Galacticraft bug, as the red ones are being incorrectly added by their new version

**Comment by MJRLegends** [comment]
https://github.com/TeamGalacticraft/Galacticraft-Legacy/commit/b1ae3d8e30f7144d28bdff9111100b46bef4f115
