### ISSUE TITLE
(1.10.2) java.lang.NullPointerException: Unexpected error every time I teleport to asteroids with a mekanism teleporter

### ISSUE THREAD

**Issue by LittleTimmy52** [MJRLegends/ExtraPlanets#734]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO. | Required)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING | Required):** [Yes or No]
yes
### Description of Issue(Required)
[Description of the issue]
I made a mekanism teleporter, used it to teleport to over world, when I teleport back I get the error seen in the title.
### Steps to Reproduce Issue(Required)
1. [First step]
make mekanism teleporter and teleport to over world
2. [Second step]
teleport back to asteroids

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/General%20Minecraft/crash-log/
[crash-2022-12-01_20.06.38-client.txt](https://github.com/MJRLegends/ExtraPlanets/files/10137332/crash-2022-12-01_20.06.38-client.txt)

**Screenshots (if applicable):** 

**Mod List (Required):** 
Space astronomy 2 modpack (yes I know its not supported, but this about the mod not pack)
**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest' | Required):** [VERSION]
the one for 1.10.2
**Where did this bug happen(Required):** [Single Player or Server]
server, I was the only one online
### Additional Information
[Any other information that may be able to help me with the problem]
using a rocket got me there just fine

**Comment by MJRLegends** [comment]
heyy, this is a Galacticraft issue. Please report to them

**Comment by LittleTimmy52** [comment]
Oh my bad l sorry.
