### ISSUE TITLE
Game Crashes During Forge Load

### ISSUE THREAD

**Issue by StrawberryLesbian** [MJRLegends/ExtraPlanets#735]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO. | Required)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING | Required):** Yes

### Description of Issue(Required)
Upon attempting to load the game, it crashes as soon as it starts trying to load ExtraPlanets. I tried removing Xaero's Minimap because I thought it might be causing the issue, but it did not work.

### Steps to Reproduce Issue(Required)
1. Install the mods listed below and place them into the mods folder.
2. Run 1.12.2 Forge 14.23.5.2859 and wait.

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/General%20Minecraft/crash-log/
[crash-2022-12-11_05.10.43-client.txt](https://github.com/MJRLegends/ExtraPlanets/files/10201883/crash-2022-12-11_05.10.43-client.txt)

**Screenshots (if applicable):** 
![image](https://user-images.githubusercontent.com/120307274/206897736-4a74e6c0-bbbd-494f-96f6-4409fc2e5903.png)

**Mod List (Required):** 
AsmodeusCore - 1.12.2-0.0.030
ExtraPlanets - 1.12.2-0.7.4
GalacticraftCore - 1.12.2-4.0.2.280
GalacticraftPlanets - [SEE ABOVE VERSION]
GalaxySpace - 1.12.2-2.0.18
jei - 1.12.2-4.16.1.301
MicdoodleCore - [SEE GALACTICRAFT VERSIONS]
MJRLegendsLib - 1.12.2-1.2.1
Xaero's Minimap - 22.3.1_Forge_1.12

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest' | Required):** 1.12.2-0.7.4

**Where did this bug happen(Required):** Single Player

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Extra Planets (extraplanets)
Caused by: java.lang.RuntimeException: You have a double version of the same space station, station for planet ID: -31 You will most likely fix this by checking out compatibility guide over at https://docs.mjrlegends.com/ExtraPlanets/1.12.2compact/
