### ISSUE TITLE
Spacesuits causing abnormally high RAM usage

### ISSUE THREAD

**Issue by Arceus3251** [MJRLegends/ExtraPlanets#739]
Took me a while to figure this one out, but after narrowing it down, I've notice when I have a spacesuit on, and look in my inventory, or someone around me has a spacesuit on and I'm looking at them (Basically, whenever I see a spacesuit), it causes my RAM usage to spike up until eventually crashing everything entirely, Minecraft, a couple applications.

Despite setting my max RAM usage to 4 GB, it goes WAY past. Up to like. 28 GB. 

Issue only occurred after upgrading my machine to 32 GB of RAM

**Comment by MJRLegends** [comment]
Please use the provided issue template, thank you
