### ISSUE TITLE
RAM Ussage Abnormally High with space suits

### ISSUE THREAD

**Issue by Arceus3251** [MJRLegends/ExtraPlanets#740]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO. | Required)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING | Required):** [Yes or No]
Yes

### Description of Issue(Required)
When wearing space suit or looking at another player wearing a space suit, RAM usage goes abnormally high, far higher than max set by launcher.

### Steps to Reproduce Issue(Required)
1. Acquire and Equip space suit
2. Open inventory or look in 3rd person while wearing space suit
3. Observe RAM usage in task manager spiking

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/General%20Minecraft/crash-log/
No crash log containing useful information as the crash is treated as a system out of memory error. (Aka: Many applications on my machine force close due to no RAM)

**Screenshots (if applicable):** 

**Mod List (Required):** 
BuildCraft
CodeChickenLib
COFHCore
COFHWorld
CTM-MC
ExtraPlanets
ExtremeReactors
FoamFix
GalacticCraftCore
Galacticraft-Planets
Hwyla
jei
Mantle
MicdoodleCore
MJRLegendsLib
OptiFine
ProjectE
RestoneFlux
ThermalExpansion
Xaeros_Minimap
zerocore

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest' | Required):** [VERSION]
1.2.2-0.7.4

**Where did this bug happen(Required):** [Single Player or Server]
Server

### Additional Information
[Any other information that may be able to help me with the problem]
To identify this issue, I had to narrow down the root cause of the issue, by selectively removing mods. I eventually got down to just the essential mods needed for Extra Planets to run. So I can confirm it is not a compatibility issue.

And I ran tests with a timer to test my theory of spacesuits whilst monitoring RAM usage in task manager.

And for whatever reason, my partner playing the game does NOT have the issue, however, the issue only started for me after upgrading my machine to 32 GB of RAM.

**Comment by MJRLegends** [comment]
Hey, thank you for your bug report.

I've fixed some issues with lag for the space suit in #705 issue, i think this might be related so please try these new versions.

1.12.2 Download Link:  https://www.curseforge.com/minecraft/mc-mods/extraplanets/files/4366814
1.11.2 Download Link:  https://www.curseforge.com/minecraft/mc-mods/extraplanets/files/4366784
1.10.2 Download Link:  https://www.curseforge.com/minecraft/mc-mods/extraplanets/files/4366790

If issue still happens please open a new issue report
