### ISSUE TITLE
[Suggestion] Remove Gas Giants

### ISSUE THREAD

**Issue by weeJman** [MJRLegends/ExtraPlanets#743]
Jupiter, Saturn, Uranus & Neptune shouldn't be visitable because they're gas giants. My idea would be to improve the moons in the mod. Put palladium & the tier 5 rocket dungeon on Io, magnesium & the tier 6 rocket dungeon on Titan, crystal & the tier 7 rocket dungeon on Oberon, & zinc & the tier 8 rocket dungeon on Triton.

**Comment by MJRLegends** [comment]
Thanks for the suggestions but in view of this being a minecraft mod i did decide to make some fun planets for them just so more content was possible. And so i could do some fun ideas like Jupiter has

**Comment by weeJman** [comment]
Thanks for the information.
