### ISSUE TITLE
[1.12.2] Launch pads LV2 and LV3 not working with launch controller

### ISSUE THREAD

**Issue by DarkRiot98** [MJRLegends/ExtraPlanets#748]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO. | Required)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING | Required):**  Yes

### Description of Issue(Required)
I built two tier 2 launch pads on Earth and Mercury, put launch controllers to both of them, assigned IDs, and still, after every launch the pad gets broken and rocket just travels to another planet, not to the other pad. Tested with tier 2 pad and tier 4 rocket on SMP, as well as tier 3 pad and tier 10 rocket in singleplayer. Both have the same thing.

### Steps to Reproduce Issue(Required)
1. Place launch pad tier 2/3 in 5x5 structure.
2. Place launch controller right to the pad and power it with energy.
3. Assign ID for controller and destination.
4. Travel to another planet, repeat steps 1-3, assigning IDs vice versa.
5. Try to launch the rocket via controller.

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/General%20Minecraft/crash-log/

**Screenshots (if applicable):** 

**Mod List (Required):
![image](https://user-images.githubusercontent.com/124073597/219947960-8264a7d7-710c-4e5e-a19f-dcc417751f56.png)
![image](https://user-images.githubusercontent.com/124073597/219947988-e750875a-d67e-4ecc-9611-0d0deff744f7.png)
** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest' | Required):** ExtraPlanets 0.7.4

**Where did this bug happen(Required):** Both SMP and singleplayer.

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Please report to Galacticraft its their machine that is hard coded, btw this is a known issue i believe for them too

**Comment by DarkRiot98** [comment]
If so, maybe you can make something like tier 2 and tier 3 launch controllers for respective launch pads?
