### ISSUE TITLE
Game crashes when rocket launch

### ISSUE THREAD

**Issue by emsar69** [MJRLegends/ExtraPlanets#758]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO. | Required)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING | Required):** Yes but couldn't solve

### Description of Issue(Required)
whenever i try to launch a rocket in singleplayer, it crashes in countdown or in air. the situation is diffirent in server actually. it doesnt crash until the planet selection menu. but when i select the moon and click launch on moon on server minecraft stucks on dirt screen and shuts down itself.

### Steps to Reproduce Issue(Required)
1. Removing extraplanets absolutely works but isn't there a way to make it work while extraplanets installed?
2. Removing all mods except galacticraft also works

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> https://pastebin.com/jgHYWwEm

**Screenshots (if applicable):** 

**Mod List (Required):** 

[1.12.2]+SecurityCraft+v1.9.4
any_dimension_mod_v1.3.4
BattleTowers-1.12.2
buildcraft-all-7.99.24.8
ExtraPlanets-1.12.2-0.7.6
Flan's+Mod-1.12.2-5.10.0
furniture-6.3.2-1.12.2
Galacticraft-1.12.2-4.0.5
ironchest-1.12.2-7.0.72.847
ironfurnaces-1.3.5
jei_1.12.2-4.16.1.1000
mcef-1.12.2-0.9
MJRLegendsLib-1.12.2-1.2.1
stg-1.12.2-1.2.3
techguns-1.12.2-2.0.2.0_pre3.2
TravelersBackpack-1.12.2-1.0.35
TreeChopper-1.12.2-1.2.4
webdisplays-1.12.2-1.0
Xaeros_Minimap_23.4.4_Forge_1.12

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest' | Required):** 1.12.2-forge-14.23.5.2859 

**Where did this bug happen(Required):** Both. singeplayer and server

### Additional Information
i am not only the one person who experiencing this all of my friends tested and everyone has the same issue

**Comment by MJRLegends** [comment]
Please report to Galacticraft, provided crash log only mentions their rocket and asteroids code.
