### ISSUE TITLE
When I Use ExtraPlanets For Glacticraft, when I go to space It just crashes. then it says Shutting Down internal Server (On 1.12.2)

### ISSUE THREAD

**Issue by ArouraNightSky** [MJRLegends/ExtraPlanets#759]
When I Use ExtraPlanets For Glacticraft, when I go to space It just crashes.
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO. | Required)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING | Required):** [Yes or No]

### Steps to Reproduce Issue(Required)
1. [First step]
2. [Second step]

**Crash log/Shutting Down internal Server (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/General%20Minecraft/crash-log/

**If you type this --> (Screen Shot 2023-06-18 at 2.05.43 PM):** 

**Mod List (ExtraPlanets):** 

**Version of Mod using [ExtraPlanets-1.12.2-0.7.6.jar]

**(When I Went Into Space):** [Single Player]

**Comment by MJRLegends** [comment]
Your bug report isnt acceptable you have barely filled any of it out so im unable to help you.

Please resubmit a bug report with more effort.

**Comment by ArouraNightSky** [comment]
ok
