### ISSUE TITLE
[1.7.10] Pluto unreachable

### ISSUE THREAD

**Issue by rockbanddude** [MJRLegends/ExtraPlanets#76]
I cannot reach pluto with a tier 8 rocket, and cannot obtain tungsten.

Version: 1.5.7

**Comment by MJRLegends** [comment]
Why cant you reach it? And what config options have you changed? What other mods are you using??

**Comment by rockbanddude** [comment]
I have 200 mods in my pack. I'll try with just a few (like IC2, botania, CoFH mods, and just tech mods)

**Comment by rockbanddude** [comment]
I started to build a new pack, but now I'm testing the original without chicken chunks.

**Comment by rockbanddude** [comment]
It'll take a day or two for me to test, as I need to add back each mod 1 at a time.

**Comment by rockbanddude** [comment]
Are there any magic mods you know of that might break your mod?

**Comment by MJRLegends** [comment]
Nope but does it work with just galacticraft and my mod, if so you might be getting dimension id conflicts

**Comment by MJRLegends** [comment]
If not its a bug on my end

**Comment by rockbanddude** [comment]
hmmm... maybe twilight forest or witchery is the culprit.

**Comment by rockbanddude** [comment]
They both add dimensions. RFtools isn't causing it, i'm pretty sure.

**Comment by rockbanddude** [comment]
By the way, i added most of my tech mods back and they all work

**Comment by rockbanddude** [comment]
Does MFR add new dimensions?

**Comment by rockbanddude** [comment]
I changed the dimension ID to 200, testing now

**Comment by rockbanddude** [comment]
Ok, it was indeed a dimension id problem. changed it to -82.

**Comment by rockbanddude** [comment]
Thank you for the help.
