### ISSUE TITLE
Game crashes when Power Armor from Modular Powersuits is set as a space suit

### ISSUE THREAD

**Issue by Varaxia** [MJRLegends/ExtraPlanets#762]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO. | Required)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING | Required):** [Yes or No]
Yeah

### Description of Issue(Required)
The game crashes when I set the Power Armor from the Modular Powersuits mod as a spaces suit. I might've switched to survival for it to crash? It was a long time ago
### Steps to Reproduce Issue(Required)
1. Set the Power Armor from Modular Powersuits as a space suit in config
2. Go to survival? (I don't remember)

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/General%20Minecraft/crash-log/
https://pastebin.com/dPMwZATf

**Screenshots (if applicable):** 

**Mod List (Required):** 
From the log
	micdoodlecore       | 4.0.5    
	ivtoolkit           | 1.3.3-1.12
	galacticraftcore    | 4.0.5         
	galacticraftplanets | 4.0.5        
	crafttweaker        | 4.1.20        
	mjrlegendslib       | 1.12.2-1.2.1  
	numina              | 1.0      
	powersuits          | 1.1.048       
	extraplanets        | 1.12.2-0.7.6  
	planetprogression   | 1.12.2-0.4.8  
	asmodeuscore        | 0.0.30      
	jei                 | 4.16.1.301  
	base                | 3.14.0       
	contenttweaker      | 1.12.2-4.10.0 
	ctgui               | 1.0.0        
	crafttweakerjei     | 2.0.3         
	galacticrafttweaker | 1.12.2-1.0.3  
	reccomplex          | 1.4.8.4       
	resourceloader      | 1.5.3        
	restrictedportals   | 1.12-0.6.3   
	worldedit           | 6.1.10     

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest' | Required):** [VERSION]
1.12.2-0.7.6

**Where did this bug happen(Required):** [Single Player or Server]
Single Player

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Due to duplicated issue reports for the same thing, we are now tracking this issue over on https://github.com/MJRLegends/ExtraPlanets/issues/765

Thanks for reporting
