### ISSUE TITLE
Vanilla gravity and sky on Moon with ExtraPlanets installed (GC gravity and sky without)

### ISSUE THREAD

**Issue by MrFuzzihead** [MJRLegends/ExtraPlanets#764]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO. | Required)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING | Required):** Yes

### Description of Issue(Required)
When ExtraPlanets is installed, I have overworld gravity and overworld sky issues on the Moon, etc. in Galacticraft. This does not occur with ExtraPlanets removed

### Steps to Reproduce Issue(Required)
1. Enable ExtraPlanets
2. Visit the moon

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/General%20Minecraft/crash-log/
https://gist.github.com/MrFuzzihead/72cf03b47bb7d60766cd877cfab98822

**Screenshots (if applicable):** 

**Mod List (Required):** 
https://gist.github.com/MrFuzzihead/e1b6cdacdb4171964d2ba9311391917b

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest' | Required):** 0.7.6

**Where did this bug happen(Required):** Server

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Please can you try without MoCreatures mod installed

**Comment by MrFuzzihead** [comment]
Tested without MoCreatures, everything is now working as intended. Thanks for finding the issue, guess that mod just has a ton of incompatibilities

**Comment by MJRLegends** [comment]
Yea for some reason it causes major issues some how even tho it shouldnt be.

Please report to them, i dont know if the developer is still around for that mod though but worth a try.
