### ISSUE TITLE
ModularPowersuits integration issue (1.12.2)

### ISSUE THREAD

**Issue by Kuzibaba** [MJRLegends/ExtraPlanets#765]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO. | Required)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING | Required):** [Yes or No]
Yes

### Description of Issue(Required)
When I try to add radiation and heat plating to my modularpowersuit set the options dont show up

### Steps to Reproduce Issue(Required)
1. Install latest versions of the both mods
2. Open power armor tinker table
3. No radiation or heat platibg

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/General%20Minecraft/crash-log/
Not a crash

**Screenshots (if applicable):** 
Cant access screenshots

**Mod List (Required):** 
ModularPowersuits-1.12.2-1.1.048
Numina-1.12.2-1.1.049
Galacticraft-1.12.2-4.0.6
MJRLegendsLib-1.12.2-1.2.1
ExtraPlanets-1.12.2-0.7.6
RoughlyEnoughIDs-2.0.6

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest' | Required):** [VERSION]
1.12.2-0.7.6
**Where did this bug happen(Required):** [Single Player or Server]
Single player

### Additional Information
Only the latest version of modularpowersuits cause the issue and ExtraPlanets' modular powersuits integration log message doesnt show up on the log at all

**Comment by MJRLegends** [comment]
Please include the full log file, Thank you 


Issue dev note: Issue same powersuits mod verison as https://github.com/MJRLegends/ExtraPlanets/issues/762

**Comment by Kuzibaba** [comment]
[Log file](https://github.com/lehjr/MachineMusePowersuits/files/12264625/debug.log)
I dida little bit of digging thru the code and found ExtraPlanets is supposed to give a feedback if the modularpowersuits integration worked or not, and in the log file it seems that the modularpowetsuits integration wasnt detected at all

**Comment by xJon** [comment]
@MJRLegends I assume it's due to the new Modular Powersuits update?

**Comment by MJRLegends** [comment]
@xJon 

> @MJRLegends I assume it's due to the new Modular Powersuits update?

Correct yea MachineMusePowersuits did some code refactoring in their v1.12.2-1.1.048 which broke the compact due to unable to find the code needed.

So yea a update from ExtraPlanets Side is needed

**Comment by MJRLegends** [comment]
Issue has been fixed in https://legacy.curseforge.com/minecraft/mc-mods/extraplanets/files/4756976

Thanks for the report
