### ISSUE TITLE
[1.12.2] Crash on startup

### ISSUE THREAD

**Issue by DP413710** [MJRLegends/ExtraPlanets#766]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO. | Required)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING | Required):** Yes

### Description of Issue(Required)
Minecraft crashed when load is complete.

### Steps to Reproduce Issue(Required)
1. Launch minecraft
2. Wait for minecaft to fully load

**Crash log/Log (if applicable):** https://pastebin.com/sm8ijWFX
> *How do i locate a crash log* see https://docs.mjrlegends.com/General%20Minecraft/crash-log/

**Screenshots (if applicable):** 

**Mod List (Required):**
!mixinbooter-8.4.jar
AncientSpellcraft-1.12.2-1.5.10.jar
apatheticmobs-1.4.1.jar
arcane_essentials-1.0.1.jar
AsmodeusCore-1.12.2-1.0.0.jar
AutoRegLib-1.3-32.jar
BiblioCraft[v2.4.6][MC1.12.2].jar
carryon-1.12.2-1.12.7.23.jar
clearlag-1.0.jar
Clumps-3.1.2.jar
collective-1.12.2-3.0.jar
comforts-1.12.2-1.4.1.3.jar
conarm-1.12.2-1.2.5.10.jar
Controlling-3.0.12.2.jar
CraftTweaker2-1.12-4.1.20.691.jar
CTM-MC1.12.2-1.0.2.31.jar
CustomNPCs_1.12.2-(05Jul20).jar
CyclopsCore-1.12.2-1.6.7.jar
ElectroblobsWizardry-4.3.11.jar
EvilCraft-1.12.2-0.10.78.jar
ExtraGolems-1.12-7.1.9.jar
ExtraPlanets-1.12.2-0.7.6.jar
ExtraSpells-1.12.2-1.2.0.jar
Fish's Undead Rising-1.3.3.jar
Forgelin-1.8.4.jar
FpsReducer-mc1.12.2-1.20.jar
GalacticComputers-1.0.0.jar
Galacticraft-1.12.2-4.0.6.jar
galacticraft-rpc-2.2.0.jar
GalacticraftTweaker-1.12.2-1.0.3.jar
GalaxySpace-1.12.2-2.1.0.jar
HeroesExpansion-1.12.2-1.3.5.jar
ICBM-classic-1.12.2-5.3.0.jar
infinity-1.12.jar
IronMan-1.12.2-Beta-1.12.2-1.2.6.jar
jei_1.12.2-4.16.1.301.jar
LagGoggles-1.12.2-5.9-140.jar
llibrary-1.7.20-1.12.2.jar
LucraftCore-1.12.2-2.4.17.jar
Mantle-1.12-1.3.3.55.jar
MJRLegendsLib-1.12.2-1.2.1.jar
moartinkers-0.6.0.jar
More-Planets-1.12.2-2.3.2-GC4.0.5.jar
MoSpells-1.12.2-1.0.4.jar
MouseTweaks-2.10-mc1.12.2.jar
movingelevators-1.4.3-forge-mc1.12.jar
movingworld-1.12-6.353-full.jar
mowziesmobs-1.5.8.jar
OpenComputers-MC1.12.2-1.8.3+274990f.jar
OpenComputersICBMAddon-1.3.jar
OpenDisks-MC1.12.2-0.1.0.3.jar
OpenPrinter-1.12.2-0.1.0.16.jar
OpenPython-MC1.12.2-OC1.7-1.0.1.jar
openscreens-1.12.2-1.0.1.jar
OpenSecurity-1.12.2-1.0-93.jar
PlanetProgression-1.12.2-0.4.8.jar
PymTech-1.12.2-1.0.2.jar
Quark-r1.6-179.jar
SpaceAmbient-1.12.2-0.0.1.jar
SpeedsterHeroes-1.12.2-2.2.1.jar
SpellBundle-1.12.2-1.1.4.jar
StarMaker-1.12.2-1.0.1.jar
SteveKunG's-Lib-mc1.12.2-v1.3.0.jar
supermartijn642configlib-1.1.7-forge-mc1.12.jar
taiga-1.12.2-1.3.4.jar
TConstruct-1.12.2-2.13.0.183.jar
TickCentral-3.2.jar
TinkersComplement-1.12.2-0.4.3.jar
tinkersoc-0.6.jar
TinkerToolLeveling-1.12.2-1.1.0.jar
villagernames_1.12.2-3.4.jar
WizardryGolems-1.12.2-1.2.0.jar
WizardryNecromancersDelight-1.12.2-1.0.5.jar
WizardryUtils-1.12.2-1.1.4.jar
WolfArmorAndStorage-1.12.2-3.8.0-universal-signed.jar
worldedit-forge-mc1.12.2-6.1.10-dist.jar
Xaeros_Minimap_20.0.0_Forge_1.12.jar
ZollernGalaxy-1.12.2-2.0.45.jar
[\_\_\_MixinCompat-1.1-1.12.2\_\_\_].jar
_supermartijn642corelib-1.1.12b-forge-mc1.12.jar

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest' | Required):** 0.7.6

**Where did this bug happen(Required):** Neither singleplayer nor multplayer

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Issue and way to fix is provided in the crash log already for you to see

`net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Extra Planets (extraplanets)
Caused by: java.lang.RuntimeException: You have a double version of the same space station, station for planet ID: -31 You will most likely fix this by checking out compatibility guide over at https://docs.mjrlegends.com/ExtraPlanets/1.12.2compact/`
