### ISSUE TITLE
Numia / All armor conflict

### ISSUE THREAD

**Issue by AceSardonyx** [MJRLegends/ExtraPlanets#768]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE. ok. | Required)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING | Required):** [Yes or No]
Yes and this may-?- be a duplicate but I am using many mods so I suggest taking a look
### Description of Issue(Required)
you can't be in survival or wear any armor on any other planets.
I tried disabling the pressure/rad system as well but no results

### Steps to Reproduce Issue(Required)
1. go to any other planet except earth
2. just be there / put on armor (must be in survival)

**Crash log/Log (if applicable):** (no, gist 😡)
here -> https://gist.github.com/AceSardonyx/d39e14e46eadb1ff759d28c9f0a1d70e
**Screenshots (if applicable):** 
too simple, screenshot not needed
**Mod List (Required):** 
in the log
**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest' | Required):** [VERSION]
in the log, it's  1.12.2-0.7.6   
**Where did this bug happen(Required):** [Single Player or Server]
i was going to use this on a server. I like to test stuff in single player first but I'm 90% sure this would happen on a server since it's a ticking player error (I think)
### Additional Information
sorry if this is a duplicate, the error log I have just seems different so I though I might as well post

**Comment by MJRLegends** [comment]
Duplicate issue of https://github.com/MJRLegends/ExtraPlanets/issues/765
