### ISSUE TITLE
Crash when trying to place lava bucket in nether

### ISSUE THREAD

**Issue by BrisingrAerowing** [MJRLegends/ExtraPlanets#77]
### ---Issue Report---

**Have you checked Closed Issues (if applicable):** Yes
### Description of Issue
I tried to use a lava bucket in the nether to place down some lava and got a major crash.

This was in creative mode.

### Steps to Reproduce Issue
1. Go to nether
2. Get a lava bucket
3. Try to use it

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

[Crash Log](https://gist.github.com/BrisingrAerowing/103cd0a9f96eccea860d62f2f4669ac5)

**Version of Mod using:** 1.10.2-0.2.0-Beta

### Additional Information
This might happen with other buckets as well.

**Comment by MJRLegends** [comment]
There will be a updated version out for 1.8.9 and 1.10.2 soon with this fix :D

**Comment by MJRLegends** [comment]
There will be a updated version out for 1.10.2 soon with this fix :D

**Comment by MJRLegends** [comment]
v0.3.0-Beta-Build is released fixing this bug :P
