### ISSUE TITLE
How can I fix this error?

### ISSUE THREAD

**Issue by JackLR7392** [MJRLegends/ExtraPlanets#774]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO. | Required)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING | Required):** [Yes or No]

### Description of Issue(Required)
My error number is -1.

### Steps to Reproduce Issue(Required)
1. I opened minecraft
2. loading screen
3. crashed
4. there said The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Extra Planets (extraplanets)

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]

https://pastebin.com/9zfMqMY0

**Screenshots (if applicable):** 
[Screenshot 2024-02-22 134750](https://github.com/MJRLegends/ExtraPlanets/assets/156823085/62a50c24-4eaf-4e57-a3c7-35344637219e)

**Mod List (Required):** 
![Screenshot 2024-02-22 135420](https://github.com/MJRLegends/ExtraPlanets/assets/156823085/882face6-5872-49a2-bb8d-4e3719444455)
**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest' | Required):** [1.12.2]

**Where did this bug happen(Required):** [Single Player or Server]
Single Player
### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
```
java.lang.RuntimeException: Please disable the following option: enableNewGalaxyMap in configs/AsmodeusCore/core.conf
```
