### ISSUE TITLE
Crash with Flans Mod

### ISSUE THREAD

**Issue by VladSog** [MJRLegends/ExtraPlanets#775]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO. | Required)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING | Required):** [Yes or No]
No

### Description of Issue(Required)
This mod crash if you use it with Flans Mod

### Steps to Reproduce Issue(Required)
1. Install Extra Planets and Flans mod
2. Launch Minecraft

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/General%20Minecraft/crash-log/
https://pastebin.com/Xfqumru5

**Screenshots (if applicable):** 

**Mod List (Required):** 
Extra Planets
Flans mod

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest' | Required):** [VERSION]

**Where did this bug happen(Required):** [Single Player or Server]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Please report to flans mod its a issue between Galacticraft and flans mod
