### ISSUE TITLE
can't launch Minecraft with GalaxySpace and ExtraPlanets in it

### ISSUE THREAD

**Issue by Nonbron** [MJRLegends/ExtraPlanets#776]
### ---Issue Report---
it launches only if there's one addon (galaxyspace or extra planets)
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO. | Required)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING | Required):** [Yes or No] 
Yes

### Description of Issue(Required)
[Description of the issue]
i really wanna play with two of these addons but game crashes every time i try

### Steps to Reproduce Issue(Required)
1. [First step] found the reason of the conflict
2. [Second step] launch the game successfully

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/General%20Minecraft/crash-log/
https://pastebin.com/5HVR8aDM

**Screenshots (if applicable):** 

**Mod List (Required):** 
ZollernGalaxy-1.12.2-2.0.45.jar
stevekung's-lib-mc1.12.2-v1.3.1.jar
StarMaker-1.12.2-1.0.2.jar
SpaceCraftX-1.2.1.jar
Space Tech and Dungeons.jar
PlanetProgression-1.12.2-0.4.8.jar
MorePlanetsExtras-1.12.2-1.0.jar
More-Planets-1.12.2-2.3.3-GC4.0.6.jar
MJRLegendsLib-1.12.2-1.2.1.jar
!mixinbooter-8.8.jar
Interstellar-Exoplanets-0.1.4.jar
GalaxySpace-1.12.2-2.1.3.jar
GalacticTweaks-1.8.0.jar
GalacticraftTweaker-1.12.2-1.0.3.jar
galacticraft-rpc-2.2.0.jar
Galacticraft-1.12.2-4.0.6.jar
GalacticraftAutomaticResources 1.12.2 0.4.jar
GalacticResearch-1.0.9.jar
ExtraPlanets-1.12.2-0.7.7.jar
gcepcheaperrecipes-1.0.jar
CraftTweaker2-1.12-4.1.20.698.jar
BlankPlanet-1.12.2-0.3.jar
AutomaticResourcesRemastered 1.12.2 0.5.jar
AsmodeusCore-1.12.2-1.0.1.jar

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest' | Required):** [VERSION]

**Where did this bug happen(Required):** [Single Player or Server]
singleplayer

### Additional Information
[Any other information that may be able to help me with the problem]
downloaded every mode from curseforge launcher

**Comment by MJRLegends** [comment]
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Extra Planets (extraplanets) 

Caused by: java.lang.RuntimeException: You have a double version of the same space station, station for planet ID: -31 You will most likely fix this by checking out compatibility guide over at https://docs.mjrlegends.com/ExtraPlanets/1.12.2compact/
