### ISSUE TITLE
Crash on dedicated server with Unlock & Remove Schematic Commands due to client code not found

### ISSUE THREAD

**Issue by AtomizerEmerald** [MJRLegends/ExtraPlanets#777]
---Issue Report---

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING | Required):** Yes

### Description of Issue(Required)
Tried setting up a server for my modpack as of recently and this crash keeps popping up everytime I try to start it, something about a toolflag or something?

### Steps to Reproduce Issue(Required)
1. Create Server With Extraplanets
2. Try to Start it
3. Wait 5 minutes for it to start
4. Crash

https://mclo.gs/JMI5r6h
Had to use MClo.gs because pastebin doesn't appreciate LoliASM

**Mod List (Required):** https://pastebin.com/374TnB2u

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest' | Required):** 0.7.8

**Where did this bug happen(Required):** Server

**Comment by MJRLegends** [comment]
Thanks, i will release a fix later today

**Comment by AtomizerEmerald** [comment]
Thanks mate!

**Comment by MJRLegends** [comment]
Updates are being pushed to curseforge as we speak.

Will close issue when all files are pushed and approved

**Comment by MJRLegends** [comment]
MC 1.12.2 Version: https://www.curseforge.com/minecraft/mc-mods/extraplanets/files/5323107
MC 1.11.2 Version: https://www.curseforge.com/minecraft/mc-mods/extraplanets/files/5323124
MC 1.10.2 Version: https://www.curseforge.com/minecraft/mc-mods/extraplanets/files/5323174
