### ISSUE TITLE
[Server Crash from Blue Gem helmet registering as null (v 1.5.7 for 1.7.10)]

### ISSUE THREAD

**Issue by Dulciphi** [MJRLegends/ExtraPlanets#78]
### [Server Crash from Blue Gem helmet registering as null (v 1.5.7 for 1.7.10)]

I'd expect this issue to already be reported if there wasn't something different I'm doing. 
1. I have an existing instance. I've removed [an inferior Galacticraft addon] and replaced it with the Extra Planets 1.5.7. Everything loaded fine in SSP. Then I've edited the [config](https://pastebin.com/b4mpYbKg) to remove soft and toxic metal tools and armour. I did NOT remove blue gem tools and armour. 
2. I uploaded the edited config and the mod .jar to my dedicated server, started it up and got the below crash. Reloading my SSP instance results in the same crash. 
3. I then edited the config to disable Blue Gem tools and armour (reluctantly) and everything works without issue.
4. Then I attempted to report the issue on this repo> accidentally submitted it to the Open Modular Turrets repo instead> bothered them for no reason> concluded I'm an idiot.

Description: Exception in server tick loop

java.lang.NullPointerException: Can't add null-object to the registry, name ExtraPlanets:blueGemHelmet.
	at cpw.mods.fml.common.registry.FMLControlledNamespacedRegistry.add(FMLControlledNamespacedRegistry.java:363)

**[crash report](https://paste.ee/p/xKvNP)**

**Version:**  1.5.7 for 1.7.10

### Additional Information
I'm loading an edited version of the en_US.lang file from my resources folder. I just changed the name of "Frozen Water" to "Supercooled Water" (because science). I've checked to ensure that there's no issue with that file, and particularly with the Blue Gem Helmet, 

I'd really like to get those Blue Gem tools and armour working.

**Comment by MJRLegends** [comment]
v1.6.0 is released with this issue fixed

**Comment by Dulciphi** [comment]
thank you
