### ISSUE TITLE
Having Issues With Communications Dish Keycard disappearing when either I close and reopen the game or the game crashes

### ISSUE THREAD

**Issue by CreeperAwMan176** [MJRLegends/ExtraPlanets#782]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO. | Required)**
Having Issues With Communications Dish Keycard disappearing when either mining the satellite controller and placing it down then putting in a new Keycard in or the game crashes
**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING | Required):** [Yes or No]
Yes
### Description of Issue(Required)
[Description of the issue]
so this happened like 3 times now and I'm done with having to deal with it, it commonly happens when mining the satellite controller and placing it down then putting in a new Keycard in, it also refuses to recognize any satellites ive previously sent and this has happened since I have installed the PlanetProgression Mod
### Steps to Reproduce Issue(Required)
1. [First step] closing and reopening the game
2. [Second step] wait for the game to crash or make the game crash

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/General%20Minecraft/crash-log/

**Screenshots (if applicable):** 
![2024-05-09_21 20 49](https://github.com/MJRLegends/ExtraPlanets/assets/125536883/a3041f40-a193-4c2d-8b8d-1b047002674e)

**Mod List (Required):** 
![image](https://github.com/MJRLegends/ExtraPlanets/assets/125536883/cae28453-6e04-4caa-b567-fa5869be26a4)

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest' | Required):** [VERSION]
PlanetProgression-1.12.2-0.4.8
**Where did this bug happen(Required):** [Single Player or Server]
LAN is enabled but its mostly singleplayer as im always the only one playing in that world
### Additional Information
[Any other information that may be able to help me with the problem]
When the satellite controller gets powered if I stay in the GUI for a little bit it closes automatically and erases the keycard inside from what ive just learned, Heres a YT video of the showcase:

https://youtu.be/0oa_GKPC0FE

**Comment by MJRLegends** [comment]
Thx for the report but you've put it on the wrong mods issue tracker. Please move to the correct one
