### ISSUE TITLE
Space suit memory leak bug

### ISSUE THREAD

**Issue by Belucipacito** [MJRLegends/ExtraPlanets#783]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO. | Required)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING | Required):** [Yes or No]
Yes

### Description of Issue(Required)
My friends played with me in the compilation with your mod and when we are going to build a rocket and craft a spacesuit to fly to another planet they started to lag the game is so much
It turned out to be a memory leak. Later it turned out that both friends have AMD graphics cards, me and one other friend have Nvidia graphics cards and we don't have any memory leak. The leak happens if the friend with the AMD card has a spacesuit in range.

### Steps to Reproduce Issue(Required)
1.Put on a spacesuit
2.Call a friend with an AMD card

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/General%20Minecraft/crash-log/
There is nothing in the logs and will not be as the problem is caused by amd drivers.
**Screenshots (if applicable):** 
![image](https://github.com/MJRLegends/ExtraPlanets/assets/123774274/352e45de-c64d-425c-b63b-bbec668a4e1f)

**Mod List (Required):** 
OPTIFINE
PHOSPHOR
BETTERFPS
VANILLAFIX
JEI
JOURNEY MAP
IRON CHESTS
TRAVELER'S BACKPACK
FALLING TREE
NEAT
MEKANISM
ENCHANTING PLUS
SCAPE AND RUN PARASITES
ZOMBIE AWARENESS
LYCANITES MOBS
THE LOST CITIES
BIBLIOCRAFT
BLOODMOON
CRAFTTWEAKER
ATOMIC STRYKER'S 
INFERNAL MOBS
LEVEL UP HP
CRIOGONAL'S ZOMBIES MOD
HUNTER ZOMBIE
TECHGUNS
MUTANT BEASTS
ROUGH MOBS 2
HARDCORE DARKNESS
DYNAMIC LIGHTS
ANIMALIUM
FTB QUESTS
THE EREBUS
THE AURORIAN
GLACIDUS
BETTER HUD
CUSTOM STARTER GEAR
NETHER ORES PLUS+
GALACTICRAFT
EXTRA PLANETS
MORE PLANETS
INVENTORY TWEAKS
PATCHOULI
SRP VACCINE
BUILDING GADGETS
AFTER THE DEATH: SUNSET
**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest' | Required):** [VERSION]
ExtraPlanets-1.12.2-0.7.3
**Where did this bug happen(Required):** [Single Player or Server]
Server forge-1.12.2-14.23.5.2860
### Additional Information
I use the translator DeepL as I live in Ukraine.

**Comment by MJRLegends** [comment]
Update your ExtraPlanets version, it's very old

**Comment by MJRLegends** [comment]
Guessing the latest version fixed the issue, yea?
