### ISSUE TITLE
Crash after few seconds in world Dimension -17

### ISSUE THREAD

**Issue by Karnatour** [MJRLegends/ExtraPlanets#784]
### ---Issue Report---

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING | Required):** [Yes or No]
Yes

### Description of Issue(Dimesion -17 crash)
Crash after joining/creating world

### Steps to Reproduce Issue(Required)
1. Create world
2. Wait 30s for crash

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
https://pastebin.com/DK7ZQuLA

**Screenshots (if applicable):** 

**Mod List (Required):** 
https://pastebin.com/kdguBc4J

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest' | Required):** [VERSION]
Extra planets 1.7.10-2.1.4

**Where did this bug happen(Required):** [Single Player or Server]
SinglePlayer

**Comment by MJRLegends** [comment]
Remove MoCreatures and all your issues will be fixed

**Comment by Karnatour** [comment]
Still same crash even after removing MoCreatures. Installed BetterCrashes and it says that the cause is codechickenchunks.
Even in the error seems something with codechickenchunks
```
at RFB-Launch//codechicken.chunkloader.ChunkLoaderManager.cleanChunks(ChunkLoaderManager.java:745) ~[ChunkLoaderManager.class:?]
	at RFB-Launch//codechicken.chunkloader.ChunkLoaderManager.tickEnd(ChunkLoaderManager.java:755) ~[ChunkLoaderManager.class:?]
	at RFB-Launch//codechicken.chunkloader.ChunkLoaderEventHandler.worldTick(ChunkLoaderEventHandler.java:32) ~[ChunkLoaderEventHandler.class:?]
```

**Comment by MJRLegends** [comment]
Please include full crash logs

**Comment by Karnatour** [comment]
Would provide latest.log but deleted codechickenchunks and it seemed to worked for now (restarted mc = old latest.log lost). There is atleast the crash-report
https://pastebin.com/uqfRKYrS

**Comment by Karnatour** [comment]
Ok so the error is in galacticcraft not extraplanets
