### ISSUE TITLE
Why is Makemake a config option? No blocks/content related to it exists.

### ISSUE THREAD

**Issue by MagmaSlime123** [MJRLegends/ExtraPlanets#786]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO. | Required)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING | Required):** [Yes or No] Yes.

### Description of Issue(Required)
Title. (Since you have 0 channels on your Discord that can be talked in, then I'm forced to ask here.)

### Steps to Reproduce Issue(Required)
Use the mod.

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/General%20Minecraft/crash-log/

N/A.

**Screenshots (if applicable):** 
N/A.

**Mod List (Required):** 
Happens with or without other mods.

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest' | Required):** [VERSION]
ExtraPlanets-1.12.2-0.8.0

**Where did this bug happen(Required):** [Single Player or Server] Happens on both.

### Additional Information
N/A.

**Comment by MagmaSlime123** [comment]
I followed your template... Not responding isn't helpful.

**Comment by MJRLegends** [comment]
You made a ticket complaining about a config option existing, I dont think that needs a reply as anyone normally will be happy to see configuration options

**Comment by MagmaSlime123** [comment]
Since you have 0 channels on your Discord that can be talked in, then I'm forced to ask here.
