### ISSUE TITLE
Getting provider type of dimensions from Extra Planets mod causes game to crash

### ISSUE THREAD

**Issue by gengyunmaster** [MJRLegends/ExtraPlanets#788]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO. | Required)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING | Required):** [Yes or No]
yes
### Description of Issue(Required)
[Description of the issue]
Exception in server tick loop
java.lang.IllegalArgumentException: Could not get provider type for dimension -13, does not exist
### Steps to Reproduce Issue(Required)
1. create a world
2. save and go back to main menu
3. enter the world again

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/General%20Minecraft/crash-log/
attach files
[crash-2024-08-16_23.27.03-server.txt](https://github.com/user-attachments/files/16639729/crash-2024-08-16_23.27.03-server.txt)
[crash-2024-08-17_00.22.48-server.txt](https://github.com/user-attachments/files/16639743/crash-2024-08-17_00.22.48-server.txt)
[2024-08-16-1.log.gz](https://github.com/user-attachments/files/16639751/2024-08-16-1.log.gz)
[2024-08-17-2.log.gz](https://github.com/user-attachments/files/16639755/2024-08-17-2.log.gz)

**Screenshots (if applicable):** 

**Mod List (Required):** 
 1.7.10/Baubles-1.7.10-1.0.1.10.jar
 1.7.10/CodeChickenLib-1.7.10-1.1.3.141-universal.jar
 1.7.10/ForgeMultipart-1.7.10-1.2.0.347-universal.jar
 1.7.10/ForgeRelocation-1.7.10-0.0.1.4-universal.jar
 1.7.10/ForgeRelocationFMP-1.7.10-0.0.1.2-universal.jar
 1.7.10/MrTJPCore-1.1.0.33-universal.jar
 ic2/EJML-core-0.26.jar
 1.7.10_AM2-1.4.0.009.jar
 AM2PlayGround-Beta-0.11.3.jar
 AOBD-2.9.2.jar
 AOBDBB-1.0.6.jar
 AOBDsingularities-1.0.4.jar
 AgriCraft-1.7.10-1.5.0.jar
 AnimationAPI-1.7.10-1.2.4.jar
 AppleCore-mc1.7.10-3.1.1.jar
 Aroma1997Core-1.7.10-1.0.2.16.jar
 Aroma1997s-Dimensional-World-1.7.10-1.1.0.1.jar
 AromaBackup-1.7.10-0.1.0.0.jar
 Automagy-1.7.10-0.28.2.jar
 Avaritia-1.13.jar
 Avaritiaddons-1.4b.jar
 BetterFps-1.0.1.jar
 BigReactors-0.4.3A.jar
 BloodArsenal-1.7.10-1.2-5.jar
 BloodMagic-1.7.10-1.3.3-17.jar
'Botania r1.8-249.jar'
 BotanicEnergistics-0.2.7.jar
 BrandonsCore-1.0.0.12.jar
 ChickenChunks-1.7.10-1.3.4.19-universal.jar
'CoFHCore-[1.7.10]3.1.4-329.jar'
 CodeChickenCore-1.7.10-1.0.7.48-universal.jar
 CustomTrees-2.0.jar
 Draconic-Evolution-1.7.10-1.0.2h.jar
 Enchiridion2-2.0.3.jar
 EnderCore-1.7.10-0.2.0.39_beta.jar
 EnderIO-1.7.10-2.3.0.429_beta.jar
 EnderIOAddons-1.7.10-2.3.0.427_beta-0.10.13.56_beta.jar
 EnderStorage-1.7.10-1.4.7.37-universal.jar
 EternalSingularity-1.7.10-1.0.4b.jar
 Ex-Astris-MC1.7.10-1.16-36.jar
 Ex-Nihilo-1.38-53.jar
 ExtraCells-1.7.10-2.3.14b200.jar
 ExtraE-1.7.10-1.2.jar
 ExtraPlanets-1.7.10-2.1.4.jar
 ExtraTiC-1.7.10-1.4.6.jar
 Factorization-1.7.10-0.8.109.jar
 FastLeafDecay-1.7.10-1.0.jar
 FoamFix-1.7.10-universal-1.0.4.jar
 Forbidden+Magic-1.7.10-0.575.jar
 Galacticraft-Planets-1.7-3.0.12.504.jar
 GalacticraftCore-1.7-3.0.12.504.jar
 HBM-NTM-.1.0.27_X5036.jar
'INpureCore-[1.7.10]1.0.0B9-62.jar'
 IndustrialUpgrade-2.5.21.jar
 InputFix-1.7.10-v5.jar
 InventoryTweaks-1.59-dev-152.jar
 Mantle-1.7.10-0.3.2b.jar
 Mekanism-1.7.10-9.1.1.1031.jar
 MekanismGenerators-1.7.10-9.1.1.1031.jar
 MekanismTools-1.7.10-9.1.1.1031.jar
 Metallurgy-1.7.10-4.0.9.148.jar
 MetallurgyCore-1.7.10-4.0.5.30.jar
 MicdoodleCore-1.7-3.0.12.504.jar
'MineFactoryReloaded-[1.7.10]2.8.1-174.jar'
 Minechem-1.7.10-5.0.5.406.jar
 MouseTweaks-2.4.4-mc1.7.10.jar
 NEIIntegration-MC1.7.10-1.1.2.jar
'NoMoreRecipeConflict-0.3(1.7.10).jar'
 NotEnoughCharacters-1.7.10-1.5.0.jar
 NotEnoughIDs-1.4.3.4.jar
 NotEnoughItems-1.7.10-1.0.5.120-universal.jar
 NotEnoughResources-1.7.10-0.1.0-122.jar
 NotEnoughThaumcraftTabs-1.0.2.jar
 OmniOcular-1.7.10-1.0build107.jar
 OpenComputers-MC1.7.10-1.8.5+ad76e2a-universal.jar
 OreExcavation-1.1.134.jar
 PlayerAPI-1.7.10-1.4.jar
 PneumaticCraft-1.7.10-1.12.7-152-universal.jar
 Practical-Logistics-1.7.10-0.2.4.jar
 ProjectBlue-1.1.6-mc1.7.10.jar
 ProjectE-1.7.10-PE1.10.1.jar
 ProjectRed-1.7.10-4.7.0pre12.95-Base.jar
 ProjectRed-1.7.10-4.7.0pre12.95-Compat.jar
 ProjectRed-1.7.10-4.7.0pre12.95-Fabrication.jar
 ProjectRed-1.7.10-4.7.0pre12.95-Integration.jar
 ProjectRed-1.7.10-4.7.0pre12.95-Lighting.jar
 ProjectRed-1.7.10-4.7.0pre12.95-Mechanical.jar
 ProjectRed-1.7.10-4.7.0pre12.95-World.jar
 Railcraft-9.15.11.jar
 RedstoneArmory-1.7.10-1.2.0-41.jar
'RedstoneArsenal-[1.7.10]1.1.2-92.jar'
 SonarCore-1.7.10-1.1.3.jar
 StevesAddons-1.7.10-0.10.16.jar
 StevesCarts2.0.0.b18.jar
 StevesFactoryManagerA93.jar
 TCBotaniaExoflame-1.7.10-1.4.jar
 TConstruct-1.7.10-1.8.8.jar
 Technomancy+-+0.12.5+-+1.7.10.jar
 Thaumcraft-1.7.10-4.2.3.5.jar
 ThaumcraftMobAspects-1.7.2-2A.jar
 ThaumicTinkerer-2.5-1.7.10-512.jar
'ThermalDynamics-[1.7.10]1.2.1-172.jar'
'ThermalExpansion-[1.7.10]4.1.5-248.jar'
'ThermalFoundation-[1.7.10]1.2.6-118.jar'
 ThermalSingularities-1.7.10-1.2.jar
 TorchLevers-V1.4.2-MC1.7.10.jar
 Torcherino-1.7.10-2.2s.jar
 TwilightForest-2.4.3.jar
 UncraftingGrinder-1.7.10-1.0.1.jar
 UnicodeFontFixer-1.1.12-mc1.7.10.jar
'Universal+Singularities+[Version+8]-1.7.10.jar'
 WR-CBE-1.7.10-1.4.1.9-universal.jar
 Waila-1.5.10_1.7.10.jar
 WailaHarvestability-mc1.7.10-1.1.6.jar
 WanionLib-1.7.10-1.8.jar
 Wawla-1.0.5.120.jar
 WirelessCraftingTerminal-1.7.10-rv2-1.8.7b.jar
 ae2stuff-0.5.1.61-mc1.7.10.jar
 appliedenergistics2-rv2-stable-10.jar
 bdlib-1.9.4.109-mc1.7.10.jar
 binnie-mods-1.7.10-2.0.22.7.jar
 buildcraft-7.1.26.jar
 buildcraft-compat-7.1.8.jar
 clayium-0.4.6.36.hotfix2.jar
 enderlicious-1.1.2.jar
 excompressum-mc1.7.10-1.2.0.jar
 extrautilities-1.2.12.jar
 fastcraft-1.25.jar
 forestry_1.7.10-4.2.16.64.jar
 fossilsarcheology-7.3.2.jar
 funky-locomotion-1.7.10-beta-6a.jar
 gregtech_1.7.10-6.17.01.jar
 gtweapons-0.3.0.jar
 industrialcraft-2-2.2.828-experimental.jar
 instantblocks-1.7.10-1.5.5.jar
 journeymap-1.7.10-5.1.4p2-unlimited.jar
 llibrary-1.5.1-1.7.10.jar
 logisticspipes-0.9.3.132.jar
 magicbees-1.7.10-2.4.4.jar
 mariculture-1.3.0-6fork6.jar
 mcjtylib-1.8.1.jar
 neiaddons-1.12.14.40-mc1.7.10.jar
 netherlicious-3.2.8.jar
 netherportalfix-mc1.7.10-1.1.1.jar
 orespawn-20.3.zip
 p455w0rdslib-1.7.10-1.0.4.jar
 rftools-4.23.jar
 tcinventoryscan-mc1.7.10-1.0.11.jar
 tcnodetracker-1.7.10-1.1.2.jar
 thaumcraftneiplugin-1.7.10-1.7a.jar
 thaumicenergistics-1.1.2.0-RV2.jar
'tinker_io-1.7.10-release 1.5.0.jar'
 witchery-1.7.10-0.24.1.jar
 worldedit-forge-mc1.7.10-6.1.1-dist.jar
**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest' | Required):** [VERSION]
1.7.10-2.1.4
**Where did this bug happen(Required):** [Single Player or Server]
single player
### Additional Information
[Any other information that may be able to help me with the problem]
When I create a world, everything goes correctly. But I can't enter the world after saving it and going back to the main menu. Once I enter the save, the game will crash. As the crash log suggests, the problem is related to dimensions from extra planets mod (dimension id -13 and -19). I'm not in those dimensions, I'm in the overworld. I don't know why does the game try to get provider type of those dimensions. I can enter the save after removing extra planets mod. Is there a bug or mod conflict?

**Comment by gengyunmaster** [comment]
Is there a conflict between extra planets and chicken chunks ( https://www.curseforge.com/minecraft/mc-mods/chickenchunks )? The causation might be improper registrations of extra planets' dimensions. When I try to enter a save, chicken chunks will perform a method named "codechicken.chunkloader.ChunkLoaderManager.cleanChunks" to initiate chunks loaded, which indirectly reads the provider type of dimensions. However, dim -19 from extra planets mod has not been registered correctly, so the game will crash. I would appreciate it if you can give me some help. Thank you!

**Comment by MJRLegends** [comment]
Im seeing 

```
[00:14:26] [Client thread/ERROR]: Could not register dimension -19 - does it clash with another mod?  Change the ID in config.
[00:14:26] [Client thread/ERROR]: Could not register dimension -37 - does it clash with another mod?  Change the ID in config.
[00:14:26] [Client thread/ERROR]: Could not register dimension -38 - does it clash with another mod?  Change the ID in config.
[00:14:26] [Client thread/ERROR]: Could not register dimension -39 - does it clash with another mod?  Change the ID in config.
[00:14:26] [Client thread/ERROR]: Could not register dimension -42 - does it clash with another mod?  Change the ID in config.
```

What happens if you remove everything except, Galacticraft & ExtraPlanets?

**Comment by MJRLegends** [comment]
Personally im pretty sure you just have dimension id conflicts with another mod or mods, so you need to change 

dimension -19
dimension -37 
dimension -38 
dimension -39
dimension -42

in the ExtraPlanets to another number for each, in till you get no conflicts

**Comment by gengyunmaster** [comment]
Sorry! After changing those dimension ids, I can enter the world. Sure, there are id conflicts with Thaumcraft, ThaumicTinkerer and Witchery. Generally, dimension id conflicts will cause game to crash during startup process, but it doesn't. Thank you very much!
