### ISSUE TITLE
[1.10.2] [0.3.0-BETA] Server-sided crash whilst loading client-sided classes.

### ISSUE THREAD

**Issue by Axiom1999** [MJRLegends/ExtraPlanets#79]
### ---Issue Report---

**Have you checked Closed Issues (if applicable):** Yes.
### Description of Issue
Server-sided crash trying to load client-side classes (*EntityPlayerSP*).
https://github.com/MJRLegends/ExtraPlanets/blob/dev_1.10.2/src/main/java/com/mjr/extraplanets/handlers/MainHandlerServer.java#L128-135

### Steps to Reproduce Issue
1. Install Extra Planets and all dependencies (possibly IC2 as well).
2. Crash.

**Crash log/Log (if applicable):** https://pastebin.com/SvK5uga4

**Version of Mod using:** 0.3.0-BETA.

### Additional Information
Our modpack is located at https://minecraft.curseforge.com/projects/the-tinderbox/files/2407592.
Obviously, we removed client sided mods from the server, before launching.

**Comment by MJRLegends** [comment]
Thanks will fix

**Comment by MJRLegends** [comment]
Sorry for the delay on the version containing the fix, im working on some extra features for the update :D

**Comment by AndrewGraber** [comment]
Hello, I couldn't help but notice that you've just pushed an update for the 1.7.10 version of the mod. I'm just wondering if you know when the version containing this fix will be released. If not, is the git stable enough for me to compile?

**Comment by MJRLegends** [comment]
v0.3.1-Beta-Build is out containing this fix and a few others :D Please give it a few mins to sync and get approved on curse :D

**Comment by AndrewGraber** [comment]
Thank you!

**Comment by MJRLegends** [comment]
No problem sorry for the delay :D

**Comment by Axiom1999** [comment]
Glad you got it fixed, simple errors haha!
