### ISSUE TITLE
[1.7.10] Server crashes on startup

### ISSUE THREAD

**Issue by SirWindfield** [MJRLegends/ExtraPlanets#81]
### ---Issue Report---

**Have you checked Closed Issues (if applicable):** [Yes or No]
### Description of Issue
The server fails to start properly if the newest version has been added.

### Steps to Reproduce Issue
1. Just added ExtraPlanets to my server and started it.

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
https://pastebin.com/f3cBkUQ8
**Version of Mod using:** [VERSION]
1.6.3/1.6.4
### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
seems to be due to extrautils and my addon

**Comment by MJRLegends** [comment]
Will fix later :P

**Comment by SirWindfield** [comment]
Will fix later ^^
Btw, just a general question, you seem really chilled overall. How is the modding community doing nowadays? Looks like a lot of mods are still only for 1.7.10. 
Microsoft rewrote the game in C# and, as far as I read, there is no good way to mod it.

**Comment by MJRLegends** [comment]
Right after looking at the issue, i dont think there anything i can do, It seems your mining the pads with a ender quarry which isn't a normal thing to do so i dont think its a issue that will cause the game to break often :D

**Comment by MJRLegends** [comment]
Might be something i can do for it though

**Comment by McyD** [comment]
or the reference to you calling client side rendering?  And why post an update you know is broken...

**Comment by SirWindfield** [comment]
I don't use any quarries in my world. That's strange o.O

**Comment by McyD** [comment]
That's alright I will just post the issue on extra utils, so they can tell you to fix your mod.

**Comment by MJRLegends** [comment]
v1.6.5 is out containing this fix and a few others :D Please give it a few mins to sync and get approved on curse :D

**Comment by MJRLegends** [comment]
@McyD Try being less rude to people. I will give respect to people who respect me!

**Comment by McyD** [comment]
I tried that and you deleted my posts...

**Comment by SirWindfield** [comment]
nice :D Thank you sir (or ma'am)!
