### ISSUE TITLE
1.7.10 Client/server crash.

### ISSUE THREAD

**Issue by kolbka96** [MJRLegends/ExtraPlanets#83]
### ---Issue Report---

**Have you checked Closed Issues (if applicable)**: No

### Description of Issue

04/30/17. Testing Tier 10 Rocket to Kepler 22b.
Comeback to Overworld(via Rocket Pad) cause client/server crash,
 
On Kepler 22b when rocket start after countdown to 0 game freeze and crashed. 

**Crash log/Log (if applicable):**

https://pastebin.com/i8X6qxQ9

**Version of Mod using:**
Minecraft 1.7.10(LiteLoader + Forge 10.13.4.1614 )
ExtraPlanets-1.6.6
GalacticraftCore-1.7-3.0.12.465
Galacticraft-Planets-1.7-3.0.12.465
MicdoodleCore-1.7-3.0.12.465

**Comment by MJRLegends** [comment]
Update your 

GalacticraftCore
Galacticraft-Planets
MicdoodleCore to latest

**Comment by kolbka96** [comment]
Updated Galacticraft to .490 - problem is solved, all work correctly.
Thank for help.
