### ISSUE TITLE
[1.10.2] Game crash when disable planets in config

### ISSUE THREAD

**Issue by bortooo** [MJRLegends/ExtraPlanets#85]
When I disable Kepler 22b or Kepler SolarSystems the game crash.

[Crash report](https://pastebin.com/jwWAB6R2)

[Config](https://pastebin.com/Qk2k00ZT)

Edit: I set Kepler 22b and Kepler SolarSystems on true and the game still crash [Crash report](https://pastebin.com/LNischmE), then I regenerate the config and now it doesnt crash

**Comment by MJRLegends** [comment]
Thanks i can fix this :D

**Comment by bortooo** [comment]
That's great!

**Comment by MJRLegends** [comment]
I've fixed this issue and Update v0.3.3-Beta-Build has been released fixing it
