### ISSUE TITLE
[1.10.2] Recipes with titanium

### ISSUE THREAD

**Issue by bortooo** [MJRLegends/ExtraPlanets#86]
Recipes of titanium waffle and tier 2 armor layer use heavy-duty plate tier 3 instead titanium ingot.

![2017-05-07_10 38 55](https://cloud.githubusercontent.com/assets/28114042/25779154/d6a10b36-3311-11e7-81e3-cc239cf2f6bf.png)

**Comment by MJRLegends** [comment]
Thanks will fix

**Comment by MJRLegends** [comment]
I've fixed this issue and Update v0.3.3-Beta-Build has been released fixing it
