### ISSUE TITLE
[1.10.2] Solar panel rendering

### ISSUE THREAD

**Issue by bortooo** [MJRLegends/ExtraPlanets#87]
Bug with rendering of hybrid and ultimate solar panel.

![2017-05-07_10 54 26](https://cloud.githubusercontent.com/assets/28114042/25779234/c3224a14-3313-11e7-8d74-c2a2ce5bfa59.png)

**Comment by MJRLegends** [comment]
Thanks will fix

**Comment by MJRLegends** [comment]
I've fixed this issue and Update v0.3.3-Beta-Build has been released fixing it
