### ISSUE TITLE
[1.10.2] Texture missing

### ISSUE THREAD

**Issue by bortooo** [MJRLegends/ExtraPlanets#88]
Front texture of Basic Crystallizer, Basic Decrystallizer, Basic Block Smasher, Basic Chemical Injector, Basic Solar Evaporation Chamber is missing

![2017-05-07_12 23 50](https://cloud.githubusercontent.com/assets/28114042/25779850/12ff0e80-3320-11e7-8de4-15fd35c719aa.png)

**Comment by MJRLegends** [comment]
Thanks Yeah this isn't a bug they just isn't added yet but will be very soon

**Comment by bortooo** [comment]
Great!
