### ISSUE TITLE
[1.10.2] Useless tooltips

### ISSUE THREAD

**Issue by bortooo** [MJRLegends/ExtraPlanets#89]
Tooltips of wafers are useless since GC had JEI support.

![2017-05-11_20 46 00](https://cloud.githubusercontent.com/assets/28114042/25966326/fb00ee20-368a-11e7-925a-abbb4fdc146e.png)

Question: will you add jei support for 4-10 tier rocket?

**Comment by MJRLegends** [comment]
Yeah they were added before JEI support for GC and yeah I will be adding JEI support too

**Comment by bortooo** [comment]
Thanks again!
