### ISSUE TITLE
[1.10.2] Missing Texture Tier 4 Rocket

### ISSUE THREAD

**Issue by Zonk1987** [MJRLegends/ExtraPlanets#92]
### ---Issue Report---

**Have you checked Closed Issues (if applicable):** Yes
### Description of Issue

Texture missing  in NASA Workbench

### Steps to Reproduce Issue
1. Get the NASA Workbench Schematic Tier 4 Rocket from from Mercury.
2. Lern the Schematic in the NASA Workbench 

Screenshot:
![070ee0c14a844ec38f20a14fae2d09b9](https://cloud.githubusercontent.com/assets/25836879/26019753/3a65dd4e-3778-11e7-8853-6348679e3bd5.png)

**Version of Mod using:** 1.10.2-0.3.3-BETA

### Additional Information
I play on the FTB Beyond 1.5.3 pack with a few other Mods installt.
Screenshot of the other Mods : 
![2d3e38dce925460585e4102037cb45c9](https://cloud.githubusercontent.com/assets/25836879/26019761/4fc3a3ce-3778-11e7-9e73-4e0229a7e6fe.png)

**Comment by MJRLegends** [comment]
Will be fixed in the next update coming out in a few hours

**Comment by MJRLegends** [comment]
Please try out v0.3.4-Beta-Build
