### ISSUE TITLE
[1.7.10] ExtraPlanets-1.7.0, Server crashes during start (postInit)

### ISSUE THREAD

**Issue by zetti68** [MJRLegends/ExtraPlanets#95]
### ---Issue Report---

**Have you checked Closed Issues (if applicable):** Yes
### Description of Issue
Server crashes during startup
Reason: call of client code in `AdvancedOxygenCompressor` -> 
`function public void func_149651_a(IIconRegister par1IconRegister)` -> missing annotation `@SideOnly(Side.CLIENT)`

### Steps to Reproduce Issue
1. Add mod extrautilities to mod directory
2. Start server

**Crash log/Log (if applicable):** [https://pastebin.com/X8zkKxg7]

**Version of Mod using:** 1.7.0

### Additional Information
-

**Comment by MJRLegends** [comment]
Use v1.7.1
