### ISSUE TITLE
1.7.10. Server crash.

### ISSUE THREAD

**Issue by kolbka96** [MJRLegends/ExtraPlanets#97]
### ---Issue Report---

**Have you checked Closed Issues (if applicable):** [No]

### Description of Issue
Crashing dedicated server on load, client works ok.

**Crash log/Log (if applicable):** 

https://pastebin.com/raw/wbYW2uaY

**Version of Mod using:** 
Minecraft 1.7.10(LiteLoader + Forge 10.13.4.1614 )
ExtraPlanets-1.7.1
GalacticraftCore-1.7-3.0.12.495
Galacticraft-Planets-1.7-3.0.12.495
MicdoodleCore-1.7-3.0.12.495

**Comment by MJRLegends** [comment]
There will be a update out soon with the fix, im waiting on files.minecraftforget.net to come back up so i can compile the updated version

**Comment by MJRLegends** [comment]
v1.7.2 is out :D. Please give it 10 mins to get approved on curse
