### ISSUE TITLE
Higher tier refineries not automatable with fluid pipes

### ISSUE THREAD

**Issue by BrisingrAerowing** [MJRLegends/ExtraPlanets#98]
### ---Issue Report---

**Have you checked Closed Issues (if applicable):** Yes
### Description of Issue
Fluid pipes do not interact with the refineries added by this mod, and likely don't interact with other machines added as well.

### Steps to Reproduce Issue
1. Get fluid pipes, tanks, oil, and a refinery
2. Try to connect a tank with oil to the black input and a tank for fuel to the yellow output
3. Nothing gets transfered, and some pipes don't connect at all.

**Version of Mod using:** 1.10.2-0.4.0-beta

### Additional Information
I tried Ender IO fluid conduits, Galacticraft pipes and Mekanism pipes (those are the only pipes I have in my setup)

**Comment by MJRLegends** [comment]
Thanks will be fixed in the next update for MC1.10.2

**Comment by MJRLegends** [comment]
v0.4.1-Beta-Build is out and should fix this issue, any more problems let me know :D
