### ISSUE TITLE
[1.7.10]crash with manu-ra mod (could not get provider dimension -19)

### ISSUE THREAD

**Issue by tonimark** [MJRLegends/ExtraPlanets#99]
java.lang.IllegalArgumentException: Could not get provider type for dimension -29, does not exist

**Have you checked Closed Issues (if applicable): yes
the problem maybe be in the config with the manu-ra mod wich cannot get the dimension detailed:
dimension -19 doesn't exist

### Steps to Reproduce Issue
1. travel with a shuttle and create a mothership
2. place the thrusters, after travelling to mars with the mothership, the game will crash

link:https://pastebin.com/8HDNw5Ld

**Version 1.7.2

### Additional Information
link for manu-ra mod:http://files.katzenpapst.de/files/AmunRa-GC-0.4.5.jar

**Comment by MJRLegends** [comment]
Change dimension id -19 in the ExtraPlanets config

**Comment by tonimark** [comment]
OOOOOOOOOOOOOOHHHHHHHH LIER STUPID PROGRAMMER YOU HAD SET THE PLUTO DIMENSION ID TO -19 and this is why the mars error happening (error dimension registry already was taken)
make sure to not add more planets with dimension id -19 or this crash may be happen again

**Comment by tonimark** [comment]
what do you mean?

**Comment by MJRLegends** [comment]
@tonimark Your message that you deleted was very rude! But im still prepared to help you, Open up the ExtraPlanets config file located at /config/ExtraPlanets.cfg

and change this 
I:"Pluto Dimension ID"=-19

to this 
I:"Pluto Dimension ID"=-190
